/**
 * 花常 本文 第一章 睦月「初売り」
 * 原稿から転記した実行時シナリオデータ。
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️解放スロットの対応:
 *   「ステージ1-1の前」   → month-open 1
 *   「ステージ1-1クリア後」「ステージ1-2の前」 → stage-clear m1-1
 *   「ステージ1-2クリア後」「ステージ1-3の前」 → stage-clear m1-2
 *   「ステージ1-3クリア後」 → stage-clear m1-3
 *   「一月の全ステージクリア後」 → month-close 1
 */

import type { Vignette } from "./types.js";

const chomen0106: Vignette = {
	id: "m1-chomen-0106",
	kind: "chomen",
	month: 1,
	title: "一月六日",
	trigger: { at: "month-open", month: 1 },
	synopsis: "初売りの朝の帳面。開店前の支度と、店の音を書き並べる。",
	lines: [
		{ kind: "diary", text: "一月六日。雪、のち晴れ。積雪三センチ。" },
		{ kind: "diary", text: "初売り。" },
		{ kind: "diary", text: "五時に目が覚めた。目覚ましは六時に掛けてあった。二階の窓が白かったので、それで起きた。" },
		{ kind: "diary", text: "開店一時間前に店に着いた。準備は昨日のうちに終わっていた。終わっていたのに着いてしまったのだから、仕方がない。" },
		{ kind: "diary", text: "表のシャッターの鍵が固い。上げるとき、途中で一度引っかかる。油を差すこと。" },
		{ kind: "diary", text: "雪かき。店の前と、まるはちの前と、霜月堂の角まで。スコップはまるはちの借り物。返すときに礼を言うこと。" },
		{ kind: "diary", text: "水道は出た。外の蛇口は凍っていた。バケツの水に一センチの氷。割って捨てた。" },
		{ kind: "diary", text: "桶の水は、前の晩に汲んで店の中に置いておくこと。冷たすぎる水は、花が飲まない。" },
		{ kind: "diary", text: "釣り銭よし。五百円玉二十、百円玉五十、十円玉百、五円と一円は箱ごと。千円札は三十枚。多い気もする。少ないよりいい。" },
		{ kind: "diary", text: "レジの引き出しは、右の角を押さえながら閉めると鳴らない。二日目で覚えた。" },
		{ kind: "diary", text: "ケースよし。松三十、千両二十、水仙四十九。値札よし。" },
		{ kind: "diary", text: "値札は全部書き直した。前の店の書体が手に染みついていて、三枚目でようやく抜けた。" },
		{ kind: "diary", text: "千両の値付けを一度下げて、戻した。下げる理由が「不安」しかなかったので、それは理由ではないと思った。" },
		{ kind: "diary", text: "引き出しの奥に、祖母の書いた値札が一枚だけ残っていた。松、六百。同じ値にした。" },
		{ kind: "diary", text: "ストーブ、点火。灯油、今日買い足す。ポリタンクは二つとも空。" },
		{ kind: "diary", text: "作業場の棚に、朱塗りの盆と、大ぶりの魔法瓶があるのを見つけてしまった。祖母の甘酒の道具だ。どうするかは、店を開けてから決める。" },
		{ kind: "diary", text: "祖母の帳面の、去年の初売りの頁を開きかけて、やめた。数字を見ると、比べる。比べると、手が止まる。今日は手を止めない日だ。" },
		{ kind: "diary", text: "前の店の初売りは、六時集合、八時開店、十時までに一日の三割を売り切る決まりだった。ここには決まりがない。決まりは、これから私が作るらしい。" },
		{ kind: "diary", text: "松は上、中、下に分けて出す。上を先に出すか、下を先に出すかで、一日の売れ方が変わるはずだが、まだ分からない。今日は上から出す。" },
		{ kind: "diary", text: "水仙は桶を二つに分けた。店先と、ケースの中。店先のほうが早く咲く。咲いた順に売る。" },
		{ kind: "diary", text: "千両は実の落ちやすいものを手前に。落ちる前に出す。" },
		{ kind: "diary", text: "店の音を書いておく。ストーブが、こん、と鳴る音。ケースの機械が低く唸る音。表の雪をどける音。全部で三つ。開店前の店は、この三つでできている。" },
		{ kind: "diary", text: "八時五十分。表に人影なし。鳥の足跡だけ。" },
		{ kind: "diary", text: "九時、開店。" },
		{ kind: "diary", text: "甘酒の道具のことを、まだ書いていない。書くと決めたことになる。" },
		{ kind: "diary", text: "祖母がこの盆を何年出していたのかは、帳面の数字からは分からない。分からないことは、書かない。" },
		{ kind: "diary", text: "一年目の初売り。数字は、夜に書く。" },
	],
};

const hatsuuri: Vignette = {
	id: "m1-hatsuuri",
	kind: "scene",
	month: 1,
	title: "初売り",
	trigger: { at: "stage-clear", stageId: "m1-1" },
	synopsis: "花常の初売りの一日。雪かきから始まり、千両を買う親子、仏花の常連、急ぎの髪飾り、松を一束選んで帰る熊の獣人が店を訪れる。",
	choices: [
		{
			id: "B-01",
			label: "甘酒",
			axis: "縁",
			options: [
				{ key: "A", label: "出してみる", note: "縁+1" },
				{ key: "B", label: "今年は、出さない" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "front_winter", text: "雪の朝の商店街は、音が近い。" },
		{ kind: "narration", text: "シャッターの上がる音がひとつ、四軒先で鳴る。それが誰の店かまで分かってしまう。看板の上に三センチの雪が乗り、電線がいつもより太い。米屋の前だけ塩がまかれて、そこの舗装が黒く濡れている。空は、雪を降らせ終えたばかりの薄い明るさだった。" },
		{ kind: "narration", text: "スコップの先が舗装に当たる音が、通りの端から端まで届く。若菜が店の前を掻き終えて、まるはちの前に移ったところで、店の中から八重さんが出てきた。前掛けの上に半纏を着ている。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "うちの前はいいって言ってるのに" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "スコップをお借りしているので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "理屈だねえ" },
		{ kind: "narration", text: "八重さんは笑って、それから若菜の手元を見た。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんは雪かき下手だったよ。腰が入ってなくて。あんたのほうがうまい" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "そう、なんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "なんでも上手だったわけじゃないの、あの人も" },
		{ kind: "narration", text: "雪の山が歩道の際にひとつ積み上がって、若菜はスコップを立てて息をついた。八重さんが店先のみかんの箱を日の当たるほうへずらしている。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "今日、初売りだろ。花屋の初売りってのは、何を売るんだい" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "松と、千両と、水仙です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃ知ってるよ。何を売るんだいって聞いたの" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "同じことでは" },
		{ kind: "say", speaker: "sub", name: "八重", text: "ぜんぜん違うよ。うちだって今日はみかん売ってるつもりはないんだから。景気を売ってんの" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "景気" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そう。だから声出しな。花屋は黙ってると、閉まってるように見えるんだよ" },
		{ kind: "narration", text: "八重さんはみかんの箱の角を叩いて位置を決め、それから思い出したように付け足した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんは声だけは大きかったねえ。雪かきは下手だったけど" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "両方は、難しいので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃそうだ" },
		{ kind: "narration", text: "八重さんは店に引っ込んだ。若菜はスコップを返して、店に戻った。" },
		{ kind: "narration", text: "作業場の棚の上で、朱塗りの盆が、こちらを見ている。祖母の甘酒の道具。八重さんは「やらなくていい」と言った。道楽だから、と。" },
		// ◆選択 B-01「甘酒」(軸: 縁)
		{ kind: "narration", when: { choice: "B-01", is: "A" }, text: "米麹を朝から仕込む時間は、ない。若菜は酒粕を——まるはちに走って、八重さんに事情を言って、分けてもらった。" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "sub", name: "八重", text: "あんた、やるのかい。やらなくていいって言ったのに" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "wakana", emo: 16, text: "道楽を、してみたくなりました" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "sub", name: "八重", text: "ふん。鍋はうちの貸してあげる。焦がすからね、酒粕は" },
		{ kind: "narration", when: { choice: "B-01", is: "A" }, text: "魔法瓶に移した甘酒は、開店の三十分後に間に合った。朱塗りの盆に、湯呑みを五つ。見様見真似の初売りが、湯気を立てた。" },
		{ kind: "narration", when: { choice: "B-01", is: "B" }, text: "若菜は盆を、棚の奥へ、静かに押し戻した。" },
		{ kind: "narration", when: { choice: "B-01", is: "B" }, text: "道楽は、まだ早い。今年の初売りは、花だけで立つ。花だけで立てるかどうかを、まず知りたい。" },
		{ kind: "narration", when: { choice: "B-01", is: "B" }, text: "盆は、来年も同じ場所にある。そう思うと、押し戻す手が、少しだけ軽くなった。" },
		// 【合流】 [背景=shop_day]
		{ kind: "narration", bg: "shop_day", text: "九時、開店。" },
		{ kind: "narration", text: "——誰も来ない。" },
		{ kind: "narration", text: "九時二十分。誰も来ない。ガラス戸の内側から見る商店街は白く、人の足跡より、鳥の足跡のほうが多かった。若菜は水仙の桶の位置を三センチ直し、松の束をひとつ結び直し、それ以上直すところを探して、やめた。雪のせいだ。雪のせいにして、いい朝だと思うことにした。" },
		{ kind: "narration", text: "九時四十分、戸が開いた。" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "すみません、お正月の、赤い実のやつ、まだあります?" },
		{ kind: "narration", text: "小さな子どもを連れた母親だった。千両、と言いかけて、若菜は籠ごと勘定台の前へ持ってきた。子どもの目の高さに、赤い実が来る。子どもの手がすっと伸びて、母親が「見るだけ」と言うと、手は伸びたままの形で止まった。えらい、と若菜は思った。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "——お待たせしました。六百円です" },
		{ kind: "narration", text: "会計を済ませてから、若菜は千両の短い一枝を切って、実の付きのいいところを子どもに持たせた。" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "見るだけ、できたので" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "あら、すみません、ほら、ありがとうは?" },
		{ kind: "narration", text: "子どもは何も言わずに、実をじっと見ていた。それでよかった。" },
		{ kind: "narration", text: "昼を過ぎて、客がぽつぽつと続いた。松の追加、仏壇の花、正月用品の買い足し。" },
		{ kind: "narration", text: "一時前に、古いショールを巻いた女性が、戸を半分だけ開けて中をうかがった。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "開けたんだねえ、ここ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい。今日から" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "白と、黄色。仏さんの。うるさくないやつでね" },
		{ kind: "narration", text: "若菜は白菊と小菊、それに水仙を二本添えて束にした。女性は水仙のところで手を止めた。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "これ、入れるのかい" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "香りが強いので、外します" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "いや、入れとくれ。うちの人、匂いのするやつが好きだったから。うるさいのは色の話" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "——承知しました" },
		{ kind: "narration", text: "包み終えると、女性は千円札を出して、釣りを受け取る手のところで一度だけ若菜の顔を見た。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "毎月来るからね。八日と、二十三日" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "八日と、二十三日" },
		{ kind: "narration", text: "若菜は復唱してから、勘定台の隅の紙にそれを書いた。名前は聞かなかった。聞くのは、次でいいと思った。" },
		{ kind: "narration", text: "二時前に、着物の袋を提げた母娘が入ってきた。" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "あの——生花で髪飾りって、できますか。前撮り、今日の午後からで" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "今日の、午後" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "急ですよね、ごめんなさい。造花のやつを忘れてきちゃって、家まで戻ると間に合わなくて" },
		{ kind: "narration", text: "若菜は時計を見た。二時間。ケースを見た。頭の中で、手が先に動き始めるのが分かった。ワイヤー、テープ、白い小菊、松葉を少し、千両の実を三粒。前の職場で、成人式のたびに何十個と巻いた。" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "三十分ください。振袖のお色は" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "え、あ、青です。濃い青" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "白と、赤い実でいきます" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "あの、お代は。急にお願いして、それで普通の値段というのも" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "髪飾りは千二百円です。急ぎの分は、いただきません" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "そんな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "今日は初売りなので" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "初売りって、そういうものでしたっけ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "そういうことに、しました" },
		{ kind: "narration", text: "作業台の上で、小菊の茎を短く落とし、ワイヤーを添わせ、テープを巻く。指が勝手に順番を知っている。娘は勘定台に肘をついて、その手元をじっと見ていた。" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "速い。なんか、手品みたい" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "三年やると、こうなります" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "三年。わたし、三年後なにしてるかな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "分かりませんが、髪は伸びていると思います" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "そこですか" },
		{ kind: "narration", text: "仕上げに松葉を一本だけ挿して、鏡を出した。娘が髪に当てる。" },
		{ kind: "say", speaker: "sub", name: "娘の声", text: "わ" },
		{ kind: "narration", text: "それだけだった。それで足りた。母親が深く会釈をして、二人は雪の道を駅のほうへ帰っていった。ガラス戸の向こうで、娘が二度、髪に手をやるのが見えた。" },
		{ kind: "narration", text: "四時を回ると、通りの雪が青くなり始めた。霜月堂が先に灯りを入れ、それから米屋が入れた。花常の店先も、ケースの中だけが白く光っている。" },
		{ kind: "narration", text: "夕方、戸がゆっくり開いて、大きな影が入ってきた。" },
		{ kind: "narration", text: "熊の獣人だった。焦げ茶の毛並みに、灰色の交じった年配の男性で、黒いコートの肩に雪が残っている。戸口の高さが足りず、男性は入るときに少しだけ首を下げた。" },
		{ kind: "narration", text: "男性は何も言わずにケースの前へ立った。松の束を、上から順に見ていく。二本目を持ち上げて、葉の張りを見て、戻す。四本目を持ち上げて、そのまま手に残した。選ぶのに、十秒もかからなかった。" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "……六百円です" },
		{ kind: "narration", text: "男性は硬貨をきっちり数えて置いた。指が太いので、十円玉を一枚ずつ、爪の先でずらすようにして数えた。それから、コートの内側に手を入れて、小さな紙袋を出しかけた。" },
		{ kind: "narration", text: "出しかけて、止まった。" },
		{ kind: "narration", text: "紙袋はコートの中へ戻り、男性は会釈だけして、戸を押して出ていった。閉まりかけた戸を、外から一度、押さえ直していく。乱暴に閉めない人の手つきだった。" },
		{ kind: "narration", text: "窓越しに見ると、大きな背中は通りの先の、喫茶くろまつの灯りのほうへ帰っていった。松の束が、脇に抱えられて揺れていた。" },
		{ kind: "narration", text: "閉店前に、腰の曲がった老人がひとり、戸から顔だけ入れた。" },
		{ kind: "say", speaker: "sub", name: "老人の声", text: "今年は、甘酒は" },
		// 【B-01=A】
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "wakana", emo: 11, text: "あります。見様見真似ですが" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "sub", name: "老人の声", text: "おっ" },
		{ kind: "narration", when: { choice: "B-01", is: "A" }, text: "老人は顔だけでなく全身で入ってきて、湯呑みを両手で受け取った。ひと口すすって、しばらく黙った。" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "sub", name: "老人の声", text: "……常さんのと、違う味だね" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "wakana", emo: 5, text: "すみません" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "sub", name: "老人の声", text: "謝るこたない。違うだけだよ。悪かない。……来年も、この味かい?" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "wakana", emo: 16, text: "来年は、もう少し、うまくなってます" },
		{ kind: "say", when: { choice: "B-01", is: "A" }, speaker: "sub", name: "老人の声", text: "そうかい。じゃ、来年も来なきゃな" },
		// 【B-01=B】
		{ kind: "say", when: { choice: "B-01", is: "B" }, speaker: "wakana", emo: 5, text: "……今年は、ないんです" },
		{ kind: "say", when: { choice: "B-01", is: "B" }, speaker: "sub", name: "老人の声", text: "そうかい" },
		{ kind: "narration", when: { choice: "B-01", is: "B" }, text: "老人は少しだけ間を置いて、それから顔のままの姿勢で言った。" },
		{ kind: "say", when: { choice: "B-01", is: "B" }, speaker: "sub", name: "老人の声", text: "まあ、寒いから気をつけてな。ばあさんによろしく——" },
		{ kind: "narration", when: { choice: "B-01", is: "B" }, text: "言ってから、老人は自分で気づいて、口をつぐんだ。" },
		{ kind: "say", when: { choice: "B-01", is: "B" }, speaker: "wakana", emo: 17, text: "……はい。伝わると思います" },
		// 【合流】
		{ kind: "narration", text: "戸が閉まった。六時、シャッターを半分下ろす。レジを開けて、初日の売上を勘定台に並べる。硬貨を十ずつの山にしていく手元だけが、しばらく店の音のすべてだった。" },
		{ kind: "narration", text: "外は、雪がやんでいた。" },
	],
};

const kyouNoUchi: Vignette = {
	id: "m1-kyou-no-uchi",
	kind: "scene",
	month: 1,
	title: "今日のうちに飾る花",
	trigger: { at: "stage-clear", stageId: "m1-1" },
	synopsis: "水を張りすぎて傷めた水仙十二本の始末を決める。丈を詰めて籠に立て、貼る言葉を選び直す。",
	lines: [
		{ kind: "narration", bg: "workroom", text: "作業場の裸電球は、点けてから十秒ほど、じじ、と鳴いてから明るくなる。" },
		{ kind: "narration", text: "二日目の閉店後、水場の隅の桶が、若菜を待っていた。" },
		{ kind: "narration", text: "開店前に仕入れて、水を深く張ってしまったほうの水仙だ。球根の花は深い水に弱い。分かっていたのに、あの日は手が先に動いて、頭が後から来た。茎の下のほうが半透明になって、指で押すと、頼りなく凹む。" },
		{ kind: "narration", text: "若菜は桶を作業台の下に引き出して、水を全部捨てた。桶の内側を手で拭うと、ぬめりがあった。水を替え、今度は指の第一関節までの深さで張り直す。水仙は、それくらいでいい。" },
		{ kind: "narration", text: "一本ずつ抜き出して、茎を並べていく。丈夫なもの、まだ持ち直しそうなもの、駄目なもの。三つに分ける。分ける手つきだけは、迷いがなかった。" },
		{ kind: "narration", text: "まだ持ち直しそうなものは、新聞紙できつく巻いて、首を立てたまま、浅い水に戻した。これで朝までに立てば、売り物に戻る。立たなければ、戻らない。" },
		{ kind: "narration", text: "五十本のうち、駄目になりかけているのが十二本。" },
		{ kind: "narration", text: "若菜は十二本を作業台に並べた。捨てる、と一度口の中で言ってみた。チェーンの店なら迷わない。廃棄は廃棄で、数字がそう言えば手もそう動く。でもここでは、仕入れたのも、水を張ったのも、間違えたのも、全部同じ手だった。" },
		{ kind: "narration", text: "裏口の戸を、こつこつ、と鳴らす音がした。開けると、まるはちのゴミを出しに来た八重さんが立っていた。両手が塞がっているので、肘で戸を叩いたらしい。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "灯りが点いてるから。まだやってんのかい" },
		{ kind: "say", speaker: "wakana", emo: 5, text: "水仙を、駄目にしました" },
		{ kind: "say", speaker: "sub", name: "八重", text: "見せてごらん" },
		{ kind: "narration", text: "八重さんは長靴のまま土間に一歩入って、桶を覗き込んだ。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "ああ、腰が抜けてるね。これはうちの葉物と一緒だ。水を張りすぎたんだろ" },
		{ kind: "say", speaker: "wakana", emo: 12, text: "張りすぎました" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そうかい" },
		{ kind: "narration", text: "八重さんはそれ以上言わなかった。若菜が十二本を作業台に並べるのを、腕を組んで眺めていた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "捨てるのかい" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "決めかねています" },
		{ kind: "say", speaker: "sub", name: "八重", text: "うちはね、傷んだみかんは半分に割って、割った面を上にして並べるの。そうすると売れる。傷を隠すと売れないんだよ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "割るんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "割るの。中は甘いんだから" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "花は、割れません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "割れないねえ。花は難しいよ、ほんとに。うちは腐りかけを安くすりゃいいけど、あんたとこは、安くすると花が可哀想みたいな顔になるもんね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "顔にはしていません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "してるよ、今" },
		{ kind: "narration", text: "若菜は作業台のほうを向いた。八重さんが、後ろで笑ったのが分かった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "安くするならね、言い方を決めときな。うちは『訳あり』で通してる。二十年おんなじ札" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "訳あり" },
		{ kind: "say", speaker: "sub", name: "八重", text: "訳があるのは客のほうもだからね。安いのを買う訳があって、みんな来るんだから。花屋のとこは、あんたが決めな" },
		{ kind: "narration", text: "八重さんはゴミ袋を持ち直して、外の暗がりへ出ていった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんは花を捨てるとき、いっぺん外に持って出てたよ。店の中じゃ捨てないの。理由は聞いたことないけどね" },
		{ kind: "narration", text: "戸が閉まって、また裸電球の音だけになった。" },
		{ kind: "narration", text: "茎の駄目なところを切り詰めると、丈が半分になった。短い水仙が十二本。売り物の顔ではない。花の顔はしている。" },
		{ kind: "narration", text: "籠は、店の裏に重ねてあったもののうち、いちばん浅いものを選んだ。深い籠に短い花を入れると、花が隠れる。隠れた花は、無いのと同じだった。" },
		{ kind: "narration", text: "若菜は空いた籠をひとつ持ってきて、短い水仙を立てた。値札の裏紙に「おつとめ品」と書きかけて、ペンが止まった。" },
		{ kind: "narration", text: "前の職場の言葉だ。間違ってはいない。間違ってはいないが、この籠に貼る言葉ではない気がした。" },
		{ kind: "narration", text: "しばらく考えて、裏紙を新しくした。" },
		{ kind: "narration", text: "——今日のうちに飾る花。一本五十円。" },
		{ kind: "narration", text: "書いてから、声に出して読んでみた。店の中には誰もいなかった。ストーブが、こん、と鳴った。" },
		{ kind: "narration", text: "裏紙をもう一枚出して、同じ言葉を書き直した。一枚目より字が寝ていたので、二枚目を使うことにした。一枚目は丸めて、ポケットに入れた。" },
		{ kind: "narration", text: "値段のところだけ、少し迷った。四十円にすれば早く出る。八十円にすれば、丈が短いだけの花として売れる。五十円は、その真ん中ではなかった。ただ、勘定がしやすかった。花屋の値段には、そういう理由の値段もあっていいはずだった。" },
		{ kind: "narration", text: "籠は戸口のいちばん近くに置いた。置いてみて、三十センチ内側に寄せた。外に出しすぎると、雪をかぶる。" },
		{ kind: "narration", text: "明日、雪でなければ、誰かが持って帰るかもしれない。" },
		{ kind: "narration", text: "戸締りをして、電気を落とす前に、若菜は新聞紙で巻いた水仙のほうをもう一度見た。首は、まだ垂れていた。朝までに立つかどうかは、朝にならないと分からない。分からないものを見て立っていても仕方がないので、電気を消した。" },
		{ kind: "narration", bg: "shop_day", text: "翌朝、十時過ぎ。籠の前に、リュックを背負った学生が立ち止まった。手袋を外して、値札の裏紙を指でつまんで読んでいる。" },
		{ kind: "say", speaker: "sub", name: "学生の声", text: "これ、五十円って、一本ですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "一本です。丈が短いので" },
		{ kind: "say", speaker: "sub", name: "学生の声", text: "短いの、逆に置きやすいんですよね。うち、置くとこがコップしかなくて" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "でしたら、二本のほうが持ちます。一本だと倒れるので" },
		{ kind: "say", speaker: "sub", name: "学生の声", text: "あー、倒れる。倒れました、前に" },
		{ kind: "narration", text: "学生は三本抜いて、百五十円を勘定台に置いた。若菜が新聞紙を出そうとすると、学生は首を横に振って、リュックの脇のポケットに、穂先を上にして三本を挿した。" },
		{ kind: "say", speaker: "sub", name: "学生の声", text: "これで大丈夫です。じゃ、失礼します" },
		{ kind: "narration", text: "戸が閉まる。ガラス越しに、リュックの脇から白い花が三本、坂のほうへ歩いていくのが見えた。" },
		{ kind: "narration", text: "若菜は籠を見た。九本。値札の裏紙の字が、少しだけ雑になっているのが自分でも分かった。書き直すのはやめて、そのままにした。" },
	],
};

const chomen0107: Vignette = {
	id: "m1-chomen-0107",
	kind: "chomen",
	month: 1,
	title: "一月七日",
	trigger: { at: "stage-clear", stageId: "m1-2" },
	synopsis: "七日の帳面。七草で賑わう隣の八百屋の列と、灯油や包材の在庫を書く。",
	lines: [
		{ kind: "diary", text: "一月七日。晴れ。最低気温マイナス一度。" },
		{ kind: "diary", text: "七草。まるはちの店先に七草の籠が出て、朝から列ができていた。八百屋の初売りは七日なのだと八重さんが言った。うちより商売がうまい。" },
		{ kind: "diary", text: "列が長いので、うちの前まで伸びていた。並んでいる人が退屈して、花を見る。三人が入ってきて、二人が買った。列は借りるものらしい。" },
		{ kind: "diary", text: "八重さんに礼を言ったら、「うちは客を貸した覚えはないよ」と言われた。貸してもらった、と言い直したら、それならいい、と言われた。" },
		{ kind: "diary", text: "灯油を買った。十八リットル、二缶。台車を借りた。これも、まるはち。" },
		{ kind: "diary", text: "私の名前は、この日から取られたらしい。若菜摘みの、若菜。祖母が付けたと聞いている。理由は聞いたことがない。聞ける人は、もういない。" },
		{ kind: "diary", text: "見切りの籠、朝いちばんに三本出た。「今日のうちに飾る花」は、我ながら少し長い。でも直さない。" },
		{ kind: "diary", text: "短くすると、意味が減る。「見切り」も「おつとめ」も、花のほうを向いていない言葉だった。" },
		{ kind: "diary", text: "仏花の人。八日と二十三日に来ると言っていた。明日だ。白と黄色、水仙は入れる。忘れないように書いておく。" },
		{ kind: "diary", text: "名前を聞いていない。次に聞く。値札より先に、というほどのことでもないが。" },
		{ kind: "diary", text: "今日が誕生日だと、この町ではまだ誰も知らない。言う機会がないまま、二十七になった。" },
		{ kind: "diary", text: "大阪の母から電話。店のことは半分、体のことが半分。花のことは訊かれなかった。それはいつものことだ。" },
		{ kind: "diary", text: "誕生日おめでとう、は言われた。七草粥は食べたか、も訊かれた。名前の由来は、母も知らないらしい。" },
		{ kind: "diary", text: "電話の最後に「無理はせんとってね」。無理をしているつもりはないので、していない、と答えた。" },
		{ kind: "diary", text: "夜、七草粥を作った。まるはちの籠の売れ残りをもらった。売れ残りをもらう側になったのが、なんとなく可笑しい。" },
		{ kind: "diary", text: "新聞紙が足りない。まるはちに古紙を分けてもらう。八百屋は紙が余るらしい。" },
		{ kind: "diary", text: "包材の在庫。セロハン、あと二巻き。リボン、白と赤は十分。紙は足りない。紙がいちばん減る。" },
		{ kind: "diary", text: "前の店では、七日は「松納めの日」だった。松を下げて、春の色に替える日。ここでは、まだ松が八本ある。下げるのは、売れてからでいい。" },
		{ kind: "diary", text: "松、残り八。千両、残り四。水仙は、まだある。" },
		{ kind: "diary", text: "明日の仕入れなし。九日、市場。四時起き。目覚ましは二つ掛ける。" },
	],
};

const ookami: Vignette = {
	id: "m1-ookami",
	kind: "scene",
	month: 1,
	title: "狼の来客",
	trigger: { at: "stage-clear", stageId: "m1-2" },
	synopsis: "雪もよいの夕方、狼の獣人の青年が店に入ってきて、水仙を一輪だけ買っていく。二人の最初の出会い。",
	choices: [
		{
			id: "B-02",
			label: "去り際",
			options: [
				{ key: "A", label: "「お待ちしています」" },
				{ key: "B", label: "水仙の長持ちのコツを、伝える" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "八日の夕方は、雪もよいだった。" },
		{ kind: "narration", text: "降るとも降らないともつかない空の下で、商店街は早じまいの気配になり、花常の客足も三時を最後に途切れていた。ガラス戸の内側が白く曇って、指で拭くと、そこだけ通りの色が戻る。" },
		{ kind: "narration", text: "その日の午前に、仏花の女性が言ったとおりに来た。白と黄色、水仙は二本。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "言ったとおりだろ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "はい。用意してありました" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "用意しなさんな。売れ残ったら困るじゃないの" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "困りません。水仙は自分で飾ります" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "そりゃいい商売だ" },
		{ kind: "narration", text: "客の束を渡したあと、若菜は白菊を一本だけ抜き、自分の分として勘定台の内側へ置いた。" },
		{ kind: "narration", text: "若菜は勘定台の紙の「八日と二十三日」の下に、白と黄。水仙は入れる、と書き足した。二行になると、それは急に予定表の顔をした。" },
		{ kind: "narration", text: "一時に松の追加が一件。二時半に、包装紙だけを分けてほしいという人が一人。それきり、通りから足音が消えた。" },
		{ kind: "narration", text: "若菜は作業台で明日の分の水揚げをした。茎を水の中で斜めに落とす。落とすたびに、桶の底で細い音がする。三十本を終えて、手拭いで手を拭き、ときどきガラス戸の白い明るさを見た。" },
		{ kind: "narration", text: "ストーブの上で、やかんが少しずつ喉を鳴らし始めていた。" },
		{ kind: "narration", text: "四時半、戸が開いた。" },
		{ kind: "narration", text: "冷気と一緒に入ってきたのは、大柄な青年だった。狼の獣人で、灰色の毛並みに黒いジャケット、首にヘッドホンを掛けている。肩幅のわりに、戸を開ける手つきが静かだった。青年は戸を後ろ手に閉めて——そこで、止まった。" },
		{ kind: "narration", text: "店の中を、ゆっくり見回した。" },
		{ kind: "narration", text: "棚。花桶。冷蔵ケース。天井から下がった裸電球と、その脇の、日に焼けた竹箒。ストーブの上のやかん。壁に貼られた手書きの品書き。値札。勘定台。それから、勘定台の奥の丸椅子。視線はそこで一拍だけ止まって、下りた。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……" },
		{ kind: "say", speaker: "ren", emo: 18, text: "営業してるんですね。よかった" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "いらっしゃいませ。今年から、また開けています" },
		{ kind: "narration", text: "——また、のところで、青年の耳が小さく動いた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "先月、何回か前を通ったんですけど、いつも閉まってて。年末も、正月も" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "閉めていました" },
		{ kind: "say", speaker: "ren", emo: 20, text: "あー、ですよね" },
		{ kind: "narration", text: "青年はそれ以上訊かなかった。訊かない人だ、と分かるまでに、二秒もかからなかった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ……水仙、一輪ください" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "一輪、ですか" },
		{ kind: "say", speaker: "ren", emo: 5, text: "はい。一輪で" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "贈り物でしたら、三本のほうが形になります。奇数で束ねると据わりがいいので" },
		{ kind: "say", speaker: "ren", emo: 6, text: "いや、贈り物じゃないんですよ。一輪で足りるんです。一輪が、いいんです" },
		{ kind: "narration", text: "言い方に押しがなかったので、若菜はそれ以上勧めなかった。" },
		{ kind: "narration", text: "青年はケースではなく、土間の桶の前にしゃがんで、水仙を選び始めた。上からではなく、花と同じ高さまで頭を下げて、一本ずつ見ていく。選び方に迷いがなかった。長さでも、蕾の数でもなく、何かべつの基準で三本まで絞り、最後の一本を引き抜いて立ち上がった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "これで" },
		{ kind: "narration", text: "差し出し方が、根元を上にしていた。花のほうを自分の側に抱えて、茎を先に渡す持ち方だった。" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "——それを" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんか、まずかったですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "いえ。いちばん開きの遅いのを取ったので" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、分かります?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "分かります。仕事なので" },
		{ kind: "narration", text: "青年は水仙を目の高さに持ち上げて、蕾のところを見た。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、名前あるんですか。品種っていうか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "日本水仙です。房咲きの、白と黄色のもの。桶の右側は別のもので、そちらは真っ白です" },
		{ kind: "say", speaker: "ren", emo: 4, text: "二種類あるんですね。ぜんぜん気づかなかった" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "香りが違います。右のほうが強い" },
		{ kind: "narration", text: "青年は右の桶に一歩寄って、しゃがんだ。鼻先を近づけるのではなく、少し離れたところで止めて、それから立ち上がった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "こっちだと、部屋には強すぎるかもしれないですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "六畳なら、強すぎます" },
		{ kind: "say", speaker: "ren", emo: 5, text: "六畳です" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、そちらで正解です" },
		{ kind: "narration", text: "それから、店の中をもう一度、今度は短く見回した。" },
		{ kind: "narration", text: "立ち上がるとき、青年の肘が松の束をかすめて、束がひとつ、桶の縁で傾いた。倒れる前に、太い手が下から支えた。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "すいません。俺、狭いとこだと、だいたいこれやるんですよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "支えたので、問題ありません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "支える前提で言われると、それはそれで" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "鉢は、倒れるものとして置きます" },
		{ kind: "narration", text: "青年は松の束をまっすぐ立て直して、位置を指一本ぶん直した。直し方が几帳面だった。" },
		{ kind: "narration", text: "勘定台まで来る途中で、青年は戸口の脇の籠に気づいて、足を止めた。丈の短い水仙が九本、立ててある。裏紙の字を、少しかがんで読んだ。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "今日のうちに飾る花" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "傷んだ分です。丈を詰めてあります" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、名前がいいですね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "名前ではありません。ただの説明です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "説明が名前になるやつ、いちばん強いんですよ。うちの界隈だとそうなんです。ちゃんと何をするものか書いてある名前が、いちばん長生きする" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "界隈" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あ、いや。俺、坂の上の大学で、そういうのを触ってて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "工科大の方ですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "情報工学科の二回生です" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "では、花のほうはご専門外ですね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "そうですね。花のほうは、まるっきり素人で" },
		{ kind: "narration", text: "素人が、いちばん開きの遅い一本を引き当てるものだろうか、と若菜は思った。思ったが、口には出さなかった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "ここ、暖かいですね。ストーブ、灯油のやつだ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花には少し暑いくらいです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "うち、暖房ないんですよ。エアコンはあるけど電気代が怖くて。でも機械を回してると部屋があったかいんです。デスクトップとサーバー一台、置きっぱなしなんで。ファンが四つ回ってるから、冬はほぼ暖房です。夏は逆に地獄なんですけど、扇風機を機械のほうに向けて、人間は諦めるっていうか、そもそも人間が涼しくなる必要ないんで、優先度としては——" },
		{ kind: "narration", text: "青年はそこで、自分の話す速さに気づいたらしく、口を閉じた。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "すみません。花、買いに来たんでした" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "聞いていました。四つ、回っているんですよね" },
		{ kind: "say", speaker: "ren", emo: 3, text: "四つです" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花も、風は嫌います。当てると乾くので" },
		{ kind: "say", speaker: "ren", emo: 4, text: "花って、風邪ひくんですか" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "そういう言い方も、できます" },
		{ kind: "narration", text: "若菜は作業台でセロハンを広げ、リボンの棚に手を伸ばした。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あ——そのままで。新聞紙の、くるっとしたやつで、いいです" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "くるっとした" },
		{ kind: "say", speaker: "ren", emo: 1, text: "はい。斜めに、こう、一巻きの" },
		{ kind: "narration", text: "若菜はセロハンを置いた。新聞紙の束を引き寄せ、一枚を抜く。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "角を落として、斜めに、でしたか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "そうです。まさにそんな感じで" },
		{ kind: "narration", text: "一枚を斜めに置き、水仙を乗せて、巻いた。手が覚えていない包み方だった。チェーンの店では新聞紙を客に見せることすらない。指が正しい角度を探して、二度やり直した。仕上がりは少し不格好で、穂先が右に傾いた。" },
		{ kind: "say", speaker: "ren", emo: 18, text: "それです、それ" },
		{ kind: "narration", text: "何がそれなのか、若菜には分からなかった。" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "傾いています" },
		{ kind: "say", speaker: "ren", emo: 5, text: "傾いてるのがいいんですよ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "理屈が通っていません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "花屋が言うと説得力ありますね、それ" },
		{ kind: "narration", text: "青年は包みを両手で受け取って、新聞の面をちらりと見た。テレビ欄の裏の、去年の暮れの紙面だった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "古い新聞、取ってあるんですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "この店では紙を捨てません。使うので" },
		{ kind: "say", speaker: "ren", emo: 20, text: "なるほど。理にかなってますね" },
		{ kind: "narration", text: "百五十円は、五十円玉が三枚だった。青年は硬貨を勘定台の上に一枚ずつ、間を置いて並べた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "ここ、何時までですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "六時です。冬は、暗くなったら閉めます" },
		{ kind: "say", speaker: "ren", emo: 5, text: "休みは" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "今は、水曜だけ。市場のある日は、朝が遅くなります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "市場、行くんですね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "二駅先です。五時半に競りが始まるので、四時に出ます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "四時。それ、俺が寝る時間です" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "生活が、逆です" },
		{ kind: "say", speaker: "ren", emo: 5, text: "真逆ですね" },
		{ kind: "narration", text: "青年は首に掛けたヘッドホンの位置を直して、包みを軽く持ち直した。それから戸口で、一度だけ振り返った。" },
		{ kind: "say", speaker: "ren", emo: 18, text: "また来ます" },
		// ◆選択 B-02「去り際」(軸: なし)
		{ kind: "say", when: { choice: "B-02", is: "A" }, speaker: "wakana", emo: 2, text: "お待ちしています" },
		{ kind: "narration", when: { choice: "B-02", is: "A" }, text: "青年は、にっと笑って、戸を押した。" },
		{ kind: "say", when: { choice: "B-02", is: "B" }, speaker: "wakana", emo: 4, text: "あの——水は、浅めにしてください。水仙は、深いと弱るので。毎日、替えて" },
		{ kind: "say", when: { choice: "B-02", is: "B" }, speaker: "ren", emo: 5, text: "浅め。毎日" },
		{ kind: "narration", when: { choice: "B-02", is: "B" }, text: "青年は、ジャケットからスマホを出して、その場でメモを打った。" },
		{ kind: "say", when: { choice: "B-02", is: "B" }, speaker: "ren", emo: 3, text: "……メモしました。ありがとうございます" },
		{ kind: "narration", when: { choice: "B-02", is: "B" }, text: "律儀な客だ、と思った。" },
		// 【合流】
		{ kind: "narration", text: "戸が閉まる。ガラスの向こうで、白いものがちらつき始めていた。青年の耳がぴるっと震えて、それから足早に、坂のほうへ遠ざかっていった。包みを胸の側に寄せて、風の当たらないほうへ持ち替えたのが、曇りガラス越しにも分かった。" },
		{ kind: "narration", text: "店の中に、ストーブの音とやかんの音だけが戻ってきた。" },
		{ kind: "narration", text: "若菜は桶を見た。水仙、四十八本。" },
		{ kind: "narration", text: "勘定台の上には、五十円玉が三枚、間を空けたまま並んでいた。三枚を一枚ずつ拾って、レジの引き出しに落とす。右の角を押さえて閉めると、やはり鳴らなかった。" },
		{ kind: "narration", text: "籠を見た。九本。丈の短い水仙は、明日の朝にはもう少し減っているだろう。" },
		{ kind: "narration", text: "シャッターを下ろす前に、若菜は勘定台の奥をひとまわり片づけた。丸椅子の座面に、細かい枝の屑が落ちている。手のひらで払って、椅子の向きを元に戻した。元というのが、どの向きなのかは、知らないままだった。" },
		{ kind: "narration", text: "それから新聞紙の束を見た。斜めに一巻き。見覚えのある包み方だったが、誰の手だったか、すぐには出てこなかった。" },
	],
};

const hamaichiba: Vignette = {
	id: "m1-hamaichiba",
	kind: "scene",
	month: 1,
	title: "浜市場",
	trigger: { at: "stage-clear", stageId: "m1-3" },
	synopsis: "夜明け前の浜市場へ、初めて自分の名前の木札で仕入れに行く。競りで二度出遅れ、三度目に競り人の声の息継ぎで落札する。",
	lines: [
		{ kind: "narration", bg: "market", text: "朝の四時に目覚ましを止めると、店の二階は真っ暗で、窓の外も真っ暗だった。" },
		{ kind: "narration", text: "台所の蛇口の水は、指が痛くなるほど冷たい。顔を洗って、湯を沸かす間に着替える。厚手の靴下を二枚。長靴は玄関の三和土に、洗ったまま逆さに立ててある。" },
		{ kind: "narration", text: "白い軽トラは、祖母の代からのものだ。エンジンは一度で掛からない。二度目で掛かる。掛かってから三十秒、そのまま置くこと——これは誰に教わったのでもなく、掛からなかった朝に自分で覚えた。荷台に空の桶を積み、幌のゴム紐を二か所留めて、商店街を出る。" },
		{ kind: "narration", text: "信号はどれも点滅で、フロントガラスの端に、昨日の雪が細く残っていた。国道に出ると、前を走るのはトラックばかりになる。花を積んだ車、魚を積んだ車、何を積んでいるのか分からない車。同じ方向へ、同じ速さで走っていく。ラジオはつけなかった。" },
		{ kind: "narration", text: "浜市場は、町より先に朝が来る場所だった。" },
		{ kind: "narration", text: "駐車場はもう半分埋まっていて、白い息が、荷台の陰のあちこちで立っている。建物の入口の手前で長靴に履き替え、若菜は首から木札を提げた。祖母の名前の入った古い札ではなく、去年の暮れに書き換えてもらった、新しい札だ。角がまだ尖っている。" },
		{ kind: "narration", text: "天井の高い建物の中に、白い照明がずらりと並び、フォークリフトが箱を運び、長靴が濡れた床を鳴らす。床は一日じゅう濡れているので、乾く暇がない。" },
		{ kind: "narration", text: "五時十分。競りまでの二十分は、下見の時間だった。" },
		{ kind: "narration", text: "若菜は台車の間を歩いて、並んだ箱を上から覗いていく。松、千両、葉牡丹。年明けの色がまだ幅を利かせている。その隣に、一列だけ、淡い色の箱があった。桃色と、白と、薄紫。真冬の照明の下で、そこだけ温度が違って見えた。" },
		{ kind: "narration", text: "箱の脇に書かれた産地を読んで、若菜はしゃがんだ。指で花びらに触れずに、顔だけ近づけて、蕾の数を数えた。それから立ち上がって、もう一度、松の列を見に戻った。松の値は、初売り前より落ちていた。" },
		{ kind: "narration", text: "競り場の電光掲示に数字が流れ、符丁が飛び交って、若菜には半分も聞き取れない。段には五十人ほどが立っていて、前のほうの背中は、みな同じ角度で少しだけ前に傾いている。若菜はいちばん後ろの段に立った。" },
		{ kind: "narration", text: "五時半、始まった。" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "はい松! 三十把、上がってます、いくら、いくら、いくら——はい前! 二番!" },
		{ kind: "narration", text: "速い。数字が読み上げられているというより、数字が転がり落ちていく。若菜の三つ前に立った男が、指を軽く曲げただけで一箱を取った。挙げたようにも見えない挙げ方だった。" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "千両いきます! はい、はい、はい——奥!" },
		{ kind: "say", speaker: "sub", name: "買参人の声", text: "もう一声" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "もう一声出ました、はい決まり!" },
		{ kind: "narration", text: "若菜は自分の手のひらが汗ばんでいるのを、木札の紐を握り直したときに知った。" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "はい次スイートピー、宮の内藤——じゃない、宮の内田! 百本口!" },
		{ kind: "narration", text: "スイートピーだった。淡い色の箱が台に上がった瞬間、若菜は指を挙げようとして、遅れた。数字はもう次の段に動いていた。" },
		{ kind: "narration", text: "二口目。また遅れた。挙げた指の先で、値が決まった。" },
		{ kind: "narration", text: "前に立っていた男が、振り返りもせずに笑った。笑われたことより、笑い方が親切だったことのほうが、耳に残った。" },
		{ kind: "narration", text: "三口目、若菜は数字を見るのをやめた。掲示板から目を外して、競り人の声だけを聞いた。声には、上がりきる前に必ず短く落ちる場所がある。息を継ぐ場所だ。花の鋏を入れる位置を決めるのと、同じ種類の見つけ方だった。" },
		{ kind: "narration", text: "そこで指を挙げた。" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "——はい! 後ろ、三隅!" },
		{ kind: "narration", text: "取れた。" },
		{ kind: "narration", text: "名前を呼ばれた。それが自分の名前だと分かるまでに、半拍かかった。" },
		{ kind: "narration", text: "隣に立っていた年配の女性が、掲示板を見たまま言った。" },
		{ kind: "say", speaker: "sub", name: "隣の買参人の声", text: "あんた、高いよ、今の" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "高い、ですか" },
		{ kind: "say", speaker: "sub", name: "隣の買参人の声", text: "二声ぶんね。まあ、取れなきゃゼロだから。取れたぶんは高くない" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "取れなきゃ、ゼロ" },
		{ kind: "say", speaker: "sub", name: "隣の買参人の声", text: "そう。うちなんか三年、それが分からなくてね。安く買えた日に喜んで、売る花がなくて泣いた" },
		{ kind: "narration", text: "女性はそれきり口をきかず、次の品目で二度、指を挙げた。二度とも取れなかった。取れなかったときの顔も、取れたときの顔と同じだった。" },
		{ kind: "narration", text: "水仙は、二品目あとに立った。" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "日本水仙いきます、地物! 五十本口、いくらいくら——はい、後ろ! 三隅!" },
		{ kind: "narration", text: "今度は遅れなかった。声の落ちるところが、耳のほうで先に分かるようになっていた。二度目は、一度目より安く取れた。" },
		{ kind: "say", speaker: "sub", name: "競り人の声", text: "三隅、いい耳しとる!" },
		{ kind: "narration", text: "段の前のほうで、誰かが小さく笑った。悪い笑い方ではなかった。" },
		{ kind: "narration", text: "その後の松は、見送った。値が初売り前より下がっていたが、店にはまだ八本残っている。八本を売り切ってから買う。今日の残りは、水仙を少しと、それだけでいい。" },
		{ kind: "narration", text: "指を挙げないでいるのは、挙げるより難しかった。" },
		{ kind: "narration", text: "競りの波が次の品目に移ってから、法被の男が段の下を通りかかって、若菜の木札を見上げた。日に焼けた顔に、白いものの交じった眉。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "常サンとこの!" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "はいっ" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "声で分かったかい、今の。三度目でよう取った" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "……声の、息継ぎで" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "ほう" },
		{ kind: "narration", text: "辰巳と名乗った競り人は、法被の袖をまくり直して、段の下から若菜を見上げたままでいた。近くで聞くと、あの声と同じ喉から出ているとは思えないほど、話し声は普通だった。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "三隅の札、去年の暮れに書き換えたな。字がまだ黒い" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "分かるものですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "札は日に焼けるからよ。十年提げてる連中の札は、飴色だ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "十年" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そのうちなるさ。焼けるのは待ってりゃいい" },
		{ kind: "narration", text: "辰巳は若菜の伝票に目を落として、スイートピー、と読んだ。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "一月にスイートピーか。常サンは松の人だったがな" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "春を、少し早く置きたくて" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "早いのは売れねえぞ。正月疲れで、町はまだ財布が閉まっとる" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "閉まっている財布の前を、毎日通ります" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "ほう" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そりゃ、屁理屈だな" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "理屈のつもりでした" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "屁理屈は、こっちのほうが好きだ" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "あんた、水仙も取ったな。二度目は安かったろ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "安かったです" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そりゃな、一度目で覚えたぶんだ。授業料は先に払っとる" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "……ま、目ぇ肥やしてけ。あんたのばあさんは、セリ場のどこにいても声だけで値が分かった。五十年かかっとるがな" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "五十年" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "気にすんなってことよ" },
		{ kind: "narration", text: "辰巳は笑って、法被の背中を向けた。それから、三歩ほど行ったところで足を止めて、振り返らずに言った。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "二月は梅だ。枝は難しいぞ。早めに来い" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "早めに、来ます" },
		{ kind: "narration", text: "競り場の向こう、仲卸の区画に「犬飼生花」の看板が見えた。看板の下で、若い衆が台車を三台つないで押していく。" },
		{ kind: "narration", text: "精算所の窓口は、番号を呼ばれる順に並ぶ。若菜の前の男が、伝票を三十枚ほど束にして出していた。若菜の伝票は、二枚だった。" },
		{ kind: "narration", text: "荷受けの場所は、精算所よりも混んでいた。名前を呼ばれて、箱を受け取る。呼ぶほうも受け取るほうも、余計な言葉を一つも使わない。" },
		{ kind: "say", speaker: "sub", name: "荷受けの声", text: "三隅さん、二口。台車、そこの返してね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お借りします" },
		{ kind: "say", speaker: "sub", name: "荷受けの声", text: "初めてでしょ。台車、返さない人が多いのよ。返す人は覚えるから" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "覚えていただけるように、返します" },
		{ kind: "say", speaker: "sub", name: "荷受けの声", text: "そういうこと言う人も、覚える" },
		{ kind: "narration", text: "スイートピーの箱を受け取ると、思っていたより軽かった。花は、いつも思っているより軽い。箱を二つ抱えて駐車場まで歩き、幌の下に押し込んで、ゴム紐を留め直した。水仙を一箱。それで今日の仕入れは終わりだった。松は買わなかった。" },
		{ kind: "narration", text: "軽トラに戻ると、空が藍色になりかけていた。助手席のスイートピーの箱が、暗がりの中でそこだけ春の色をしている。運転席に座って、手袋を外すと、指がまだ冷たいままだった。" },
		{ kind: "narration", text: "駐車場を出るとき、市場の建物のほうを一度だけ振り返った。まだ照明が全部点いていて、入口から白い息が絶え間なく出入りしている。あの中では、これからもう一巡、競りが立つ。若菜の一日は終わって、彼らの一日はまだ半分だった。" },
		{ kind: "narration", text: "帰りの国道で、対向車のライトが増え始めた。町のほうへ帰る車と、町から出ていく車が、ちょうど同じ数になる時間だった。海のほうの空だけが先に白んで、その白さが、山の側へゆっくり広がっていく。信号がひとつ、点滅から赤に切り替わった。町が起きる。" },
		{ kind: "narration", text: "若菜は一度だけ声に出して言ってみた。" },
		{ kind: "narration", text: "「息継ぎで」" },
		{ kind: "narration", text: "誰も聞いていない車内で言うぶんには、ちゃんと自慢に聞こえた。" },
		{ kind: "narration", text: "商店街に着いたのは七時前で、まるはちのシャッターがちょうど半分上がったところだった。八重さんが下から顔だけ出して、白い軽トラを見た。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "その車、まだ動くんだねえ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "二度目で掛かります" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんと同じこと言うんだね" },
	],
};

const kuromatsu: Vignette = {
	id: "m1-kuromatsu",
	kind: "scene",
	month: 1,
	title: "くろまつ",
	trigger: { at: "month-close", month: 1 },
	synopsis: "配達の帰り、雪宿りに喫茶くろまつへ入る。ほとんど口をきかないマスターの淹れた珈琲を一杯飲んで帰る。",
	lines: [
		{ kind: "narration", bg: "street", text: "一月の終わりの午後、駅向こうの配達の帰りに、また雪が降り始めた。" },
		{ kind: "narration", text: "空の箱を抱えて商店街の入口まで戻ると、通りの奥まで灯りが点いていた。降り始めの雪は、舗装に落ちた端から消えていく。米屋の軒下で、猫が一匹、丸くなって動かない。" },
		{ kind: "narration", text: "傘のない若菜は、くろまつの灯りの前で足を止めた。飴色のガラス戸に、白い文字で「珈琲」。硝子の内側は湯気で曇っていて、中の様子はほとんど見えない。戸の脇に、木の札が下がっている。表は「営業中」、裏は何も書いていない。" },
		{ kind: "narration", text: "初売りの日の、大きな背中を思い出した。" },
		{ kind: "narration", text: "戸を押すと、鈴がひとつ鳴った。" },
		{ kind: "narration", bg: "indoor_other", text: "狭い店だった。カウンターに止まり木が六つ、奥に小さなテーブルがひとつ。天井も壁も、長い年月ぶんの色をしている。左の壁際に、碁盤が一面、蓋をされて置いてある。蓋の上に埃はなかった。" },
		{ kind: "narration", text: "カウンターの奥の棚に、口を紐で縛った紙袋がいくつも並んでいた。中身の名前が、それぞれ手書きで書いてある。字は太く、まっすぐで、書き慣れた人の字だった。" },
		{ kind: "narration", text: "カウンターの中に、あの熊の獣人がいた。松の束が、レジの脇の一輪挿しに——挿すには太すぎるので、水を張った一升瓶に、無造作に立ててあった。初売りの日の松だった。" },
		{ kind: "narration", text: "客はいなかった。ストーブの上で、鉄瓶が湯気を細く立てている。有線もラジオも点いていない。" },
		{ kind: "narration", text: "若菜は肩の雪を払って、コートを腕に掛けた。マスターは顔を上げて、それから何も言わずに、カウンターの内側で布巾を置いた。" },
		{ kind: "narration", text: "若菜が手前の止まり木に腰を下ろしかけると、マスターの目がわずかに動いた。視線は若菜を通り越して、その隣の席に落ち、また戻った。" },
		{ kind: "narration", text: "若菜は理由の分からないまま、ひとつ隣にずれて座った。マスターは何も言わなかった。手前の席には、擦り切れた座面の丸い跡が、ひとつぶん残っていた。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "何に、します" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ブレンドを" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……" },
		{ kind: "narration", text: "湯の音と、豆を挽く音と、ストーブの音。店の中の音はそれで全部で、それ以上要らなかった。厚い白のカップが目の前に置かれ、湯気がまっすぐ立った。" },
		{ kind: "narration", text: "一杯を飲み終わるまで、マスターは一度も喋らなかった。若菜も喋らなかった。窓の外を雪が斜めに通り、ときどき商店街の誰かが、灯りの前を会釈だけして過ぎた。" },
		{ kind: "narration", text: "途中で戸の鈴が鳴って、作業着の男が首だけ入れた。" },
		{ kind: "say", speaker: "sub", name: "男の声", text: "マスター、いつもの二百" },
		{ kind: "say", speaker: "sub", name: "玄", text: "深いのと、浅いの" },
		{ kind: "say", speaker: "sub", name: "男の声", text: "深いの" },
		{ kind: "narration", text: "紙袋がひとつ、カウンターの端に置かれた。男は千円札を置いて、釣りを待たずに出ていった。マスターは釣りを小皿に入れて、カウンターの端に残した。次に来るときに渡すのだろう、と思った。" },
		{ kind: "narration", text: "碁盤の蓋の縁が、そこだけ手垢で光っている。若菜はカップを両手で持ち直した。厚い陶器は、冷めるのが遅い。" },
		{ kind: "narration", text: "雪が少し強くなって、通りの音が遠のいた。マスターはカウンターの中で布巾を絞り、同じ場所を二度拭いて、それから水切り籠のカップの向きを揃えた。動きに無駄がない。狭い場所で長く働いてきた人の体の使い方だった。" },
		{ kind: "narration", text: "若菜は一升瓶の松に目をやった。切り口から下が、水に浸かりすぎている。言おうかと思って、やめた。松は丈夫だ。それに、ここはこの人の店だった。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "言いたいことが、ありそうだ" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "いえ" },
		{ kind: "say", speaker: "sub", name: "玄", text: "花屋の顔だな。それは" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "水が、深いです。松は少しでいいので" },
		{ kind: "narration", text: "マスターは一升瓶を持ち上げて、流しで半分ほど水を捨てた。それだけのことに、たっぷり十秒かかった。それから、瓶を元の場所に、ほとんど同じ位置に戻した。" },
		{ kind: "narration", text: "会計のとき、マスターは釣り銭を渡してから、初めて若菜の顔を見た。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……花屋の" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "はい" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……よく、来た" },
		{ kind: "say", speaker: "wakana", emo: 9, text: "また来ます" },
		{ kind: "narration", text: "マスターは答えなかった。代わりに、カウンターの下から紙袋をひとつ出して、口の紐を確かめ、また下に戻した。出しかけて戻す、という動きを、この人は二度見せたことになる。" },
		{ kind: "narration", text: "若菜はコートを着て、戸口で一度、店の中を振り返った。碁盤、止まり木六つ、一升瓶の松。隣の席は、空いたままだった。" },
		{ kind: "narration", text: "それだけだった。戸の鈴が鳴って、外の雪は、もう止みかけていた。" },
		{ kind: "narration", bg: "street", text: "商店街に戻ると、花常のガラス戸に、自分の店の灯りが映っていた。消し忘れではなく、閉店まではまだ一時間ある。" },
	],
};

const chomen0131: Vignette = {
	id: "m1-chomen-0131",
	kind: "chomen",
	month: 1,
	title: "一月三十一日",
	trigger: { at: "month-close", month: 1 },
	synopsis: "一月の締めの帳面。営業日数と仕入れ、売上、二月の予定を書き出す。",
	lines: [
		{ kind: "diary", text: "一月三十一日。曇り。" },
		{ kind: "diary", text: "一月の集計。初売り、客十七人。祖母の正月は、もっと多かった気がする。数えたことはなかったけれど。" },
		{ kind: "diary", text: "営業二十四日。休み二日。雪の日六日。雪の日は、客が半分になる。半分にはなるが、ゼロにはならない。" },
		{ kind: "diary", text: "仕入れ、市場二回。松、千両、水仙、小菊、スイートピー、葉牡丹少々。" },
		{ kind: "diary", text: "灯油、四缶。思っていたより減りが早い。二月は六缶で見ておく。" },
		{ kind: "diary", text: "髪飾り一件。急ぎの分を取らなかったのは、初売りだったから。二月は取る。取れるかどうかは、そのとき考える。" },
		{ kind: "diary", text: "八日と二十三日の人。二回とも来た。白と黄色、水仙は入れる。二月は、梅を一枝すすめてみる。" },
		{ kind: "diary", text: "見切りの籠から三本買った学生。リュックに挿して坂を上っていった。あの持ち方は、うちの包装より強い。" },
		{ kind: "diary", when: { choice: "B-01", is: "A" }, text: "甘酒は、七杯出た。「違う味だね」と言われた。違っていいらしい。来年は、もう少しうまく作る。八重さんに鍋を返すとき、酒粕の追加を黙って持たされた。" },
		{ kind: "diary", when: { choice: "B-01", is: "B" }, text: "甘酒の盆は、棚の奥に仕舞ったままだ。花だけで立てたか、というと、立てた、と思う。盆は逃げない。来年の私が決めればいい。" },
		{ kind: "diary", text: "月の売上は、書くのに少し勇気の要る数字だった。でも書いた。数字だけは、嘘をつかないでおく。" },
		{ kind: "diary", text: "仕入れ、光熱、灯油、包材。引くと、残りは月の家賃には足りない。家賃がないのが、この店の唯一の強みだ。" },
		{ kind: "diary", text: "前の店の一日の売上が、ここの一週間だった。それは比べても仕方がない。比べても仕方がないことを、月末に一度だけ書いて、あとは忘れる。" },
		{ kind: "diary", text: "スイートピー、完売。仕入れを倍にするか、二月も同じにするか、まだ決めていない。競りは、息継ぎで取る。これは私が自分で見つけた。" },
		{ kind: "diary", text: "見切りの籠は、名前を変えてから、ほとんど残らない。値段は五十円のまま。二月も変えない。" },
		{ kind: "diary", text: "籠に入れる本数は、日によって決める。多く入れると、そちらばかり売れる。売れればいいというものでもない。" },
		{ kind: "diary", text: "水仙の水は、指の第一関節まで。これは忘れない。忘れたら十二本になる。" },
		{ kind: "diary", text: "サービス、二回。千両の一枝と、髪飾りの松葉。祖母の帳面に同じ項目があるのかは、まだ見ていない。" },
		{ kind: "diary", text: "市場で言われたこと。取れなきゃゼロ。安く買えた日に喜ぶな。札は焼けるまで待て。二月に一つでも身につけばいい。" },
		{ kind: "diary", text: "松を見送ったのは、たぶん正しかった。残り八本は、二十六日に全部出た。正しかったかどうかは、月末にしか分からない。それが商いというものらしい。" },
		{ kind: "diary", text: "八日と二十三日の人の名前を、まだ聞いていない。三度目で聞く。" },
		{ kind: "diary", text: "一輪の客の名前も、聞いていない。名前を聞かない客ばかり増えていく。" },
		{ kind: "diary", text: "くろまつの珈琲は、濃かった。隣の席には、誰か座るはずだった気がする。" },
		{ kind: "diary", text: "松が一升瓶に立ててあった。花瓶を買う気はないらしい。あれはあれで、悪くなかった。" },
		{ kind: "diary", text: "二月の予定。節分、梅市。梅は枝。枝は難しいと言われた。早めに行く。" },
		{ kind: "diary", text: "レジの引き出しの右角。まだ油を差していない。" },
		{ kind: "diary", text: "帳面は数字だけつけると決めたのに、今月はずいぶん数字でないことを書いた。来月は減らす。" },
		{ kind: "diary", text: "一輪の客は、あれから来ない。" },
		{ kind: "diary", text: "あの包み——新聞紙の、斜めの一巻き。思い出した。祖母のやり方だ。祖母は急ぎの客には、いつもあれで渡していた。" },
		{ kind: "diary", text: "あの人は、どこであれを覚えたのだろう。" },
		{ kind: "diary", text: "二月の仕入れは、梅と、フリージアを少し。梅市は十日前後。辰巳さんに早めに、と言われている。" },
		{ kind: "diary", text: "「よかった」って、何がだろう。" },
	],
};

/** 第一章 睦月。⚠️並び順が再生順。 */
export const M01: readonly Vignette[] = [
	chomen0106,
	hatsuuri,
	kyouNoUchi,
	chomen0107,
	ookami,
	hamaichiba,
	kuromatsu,
	chomen0131,
];
