/**
 * 花常 本文 第二章 如月「梅市」
 * 正本: packages/frontend/hanaawase/HANATSUNE-STORY-02.md
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️解放スロットの対応:
 *   「二月開始時」「ステージ2-1の前」   → month-open 2
 *   「ステージ2-1クリア後」「ステージ2-2の前」 → stage-clear m2-1
 *   「ステージ2-2クリア後」 → stage-clear m2-2
 *   「ステージ2-3クリア後」 → stage-clear m2-3
 *   「全ステージクリア後」「二月の全ステージクリア後」 → month-close 2
 */

import type { Vignette } from "./types.js";

// 解放: 解放: 二月開始時
const hiiragi: Vignette = {
	id: "m2-hiiragi",
	kind: "scene",
	month: 2,
	title: "柊は置いていない",
	trigger: { at: "month-open", month: 2 },
	synopsis: "節分の朝、隣の八百屋に柊はあるかと聞かれる。店に柊はなく、買いに来た子どもを手ぶらで帰した。",
	lines: [
		{ kind: "narration", bg: "street", text: "二月三日の入舟銀座は、朝から豆の袋だらけだった。" },
		{ kind: "narration", text: "まるはちの店先には枡入りの大豆が段になって積まれ、向かいの霜月堂は硝子戸に「福ハ内」と書いた半紙を貼っている。米屋の前に子どもの自転車が三台倒れていて、誰も起こさない。風は真冬のままで、坂の上から川のほうへ吹き下ろしていく。花常の店先の桶では、フリージアの黄色だけが季節を一つ先に走っていた。" },
		{ kind: "narration", text: "若菜が縁台の水を替えていると、道の向こうから声が飛んできた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、柊ある?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "柊、ですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "柊。鰯の頭を刺すやつ。うちに聞きに来た子がいてね、それは花屋さんだよって回したんだけど" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "うちに、ですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花屋以外のどこで買うんだい、枝を" },
		{ kind: "narration", text: "言われてみればそうだった。若菜は店先の桶をひととおり見た。フリージア、チューリップ、スイートピー、菜の花、水仙の名残。梅の空箱。柊は、ない。仕入れ表にも書かなかった。書き忘れたのではない。思いつきもしなかった。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ありません。今年は、置いていません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "今年は、ときたね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "言葉の綾です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんは毎年出してたよ。二日にね、店先に束にして立ててさ。柊はこっち、鰯の頭は魚屋さん。あすこは商売が上手いんだ、隣と組んでやるんだから" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "二日、ですか。三日ではなく" },
		{ kind: "say", speaker: "sub", name: "八重", text: "三日は休みさ。豆撒いて、うちで甘酒飲んで、くろまつで碁を打って帰る。毎年おんなじ順番。時計より正確だったよ" },
		{ kind: "narration", text: "若菜は店の奥から古帳面を持ってきて、二月の頭を開いた。三日の欄は、知っているとおり「休み。豆」。その一行上、二日の欄に、几帳面な数字が並んでいる。" },
		{ kind: "narration", text: "柊 二十" },
		{ kind: "narration", text: "数字は、はじめから読めていた。読めていて、何も分かっていなかった。若菜は指で行をなぞり、それから閉じた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あった?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ありました。二十本" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃそうさ。売り切ってたもの" },
		{ kind: "narration", text: "自転車のベルが鳴った。ランドセルの子どもが二人、店の前で足を止めた。" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "花屋さん、ひいらぎ、ある?" },
		{ kind: "say", speaker: "wakana", emo: 5, text: "ごめんなさい。今年は、ないんです" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "ふーん" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "かえろ" },
		{ kind: "narration", text: "ふーん、の三文字だけが、店先に残った。子どもたちは坂のほうへ漕いでいって、途中で一人が振り返り、もう一度ベルを鳴らしていった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "気にすんじゃないよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "気にはしていません。書き留めるだけです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そういうとこ、似てるねえ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "どこがですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "顔じゃないよ。手つきだよ、手つき" },
		{ kind: "narration", text: "八重さんは店先まで来て、桶のフリージアを一本つまみ上げ、匂いを嗅ぎ、元に戻した。それから思い出したように白い袋を勘定台に置いた。中で林檎が二つ、鈍い音を立てた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "これ、傷ものだけど味は同じ。店に飾ってもいいよ、赤くて可愛いだろ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "果物は、花の隣に置けません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "なんだいそりゃ。喧嘩でもすんのかい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "エチレンが出ます。花が早く終わってしまうので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "エチレン" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "果物から出る気体です。蕾が開かなくなったり、花びらが落ちたり" },
		{ kind: "say", speaker: "sub", name: "八重", text: "六十年生きて初めて聞いたよ、そんな敵" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "奥の台所でいただきます。ありがとうございます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そうしな。夜は鍋にしなよ、あんた痩せたよ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "同じ体重です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "顔が細いんだよ。花屋の顔だね、あれは。冷たい水ばっかり触ってるから" },
		{ kind: "narration", text: "八重さんは自分の店へ戻りかけて、途中で振り返った。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "甘酒、うちで作るからさ。夕方おいで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "店が七時までなので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "七時に持ってくよ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "持ってくるんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "持ってくよ。常ちゃんにも毎年持ってったんだから、順番が下に降りただけだよ" },
		{ kind: "narration", text: "日が傾くころ、商店街の子ども会の豆まきが米屋の前で始まった。掛け声が三度あって、そのたびに笑いが起きる。若菜は店先に立って、それを最後まで見た。桶の水の面が、風で細かく震えていた。" },
		{ kind: "narration", text: "戻って値札を書いた。フリージア、一本百八十円。書いてから、束の値も要ると気づいて、五本七百円と書き足した。一本ずつ買う客のほうが多い店で、束の値札を書くのは、少し先の話だった。" },
		{ kind: "narration", text: "夕方、路地に鰯を焼く煙が流れてきた。店じゅうの花が、その煙を一度くぐった。若菜は勘定台に戻り、三月の仕入れ表の下に、新しい行を足した。" },
		{ kind: "narration", text: "二月二日　柊　二十" },
		{ kind: "narration", text: "一年先の予定を書いたのは、店を開けてから初めてだった。書いてしまうと、来年の二月というものが、急に日付として存在しはじめた。若菜はガラス戸を閉め、桶の水を落として、店の灯りを一つ落とした。" },
	],
};

// 解放: 解放: ステージ2-1の前
const chomen0203: Vignette = {
	id: "m2-chomen-0203",
	kind: "chomen",
	month: 2,
	title: "二月三日",
	trigger: { at: "month-open", month: 2 },
	synopsis: "節分の日の帳面。売り逃した柊のことと、翌朝の梅市の段取りを書く。",
	lines: [
		{ kind: "diary", text: "二月三日。晴れ。風は真冬。" },
		{ kind: "diary", text: "節分。まるはちの店先に豆の袋が山と積まれて、夕方には鰯を焼く煙が路地を流れていった。花屋に、節分の花はない。" },
		{ kind: "diary", text: "訂正。あった。柊。二日の欄に二十本。売り切り。" },
		{ kind: "diary", text: "子どもが二人、買いに来て、手ぶらで帰った。売り逃した二十本より、あの「ふーん」のほうが高くついた気がする。仕入れ表の来年の欄に書いた。来年の欄というものを、今日初めて作った。" },
		{ kind: "diary", text: "祖母の帳面の二月三日の欄には「休み。豆」とだけある。何度読んでも「休み。豆」である。" },
		{ kind: "diary", text: "笑ってしまった。この帳面を開いて笑ったのは、初めてかもしれない。" },
		{ kind: "diary", text: "八重さんによれば、三日の順番は豆・甘酒・碁と決まっていたらしい。時計より正確だった、とのこと。帳面には順番までは書いていない。書かなかったのか、書くまでもなかったのか。" },
		{ kind: "diary", text: "明日から梅市。憂鬱、と書きたくないので、書かない。" },
		{ kind: "diary", text: "枝物は、分からない。切り花は型で覚えた。前の会社では、束ねる本数も、リボンの落とし丈も、水の高さまで決まっていた。決まっていれば、迷わない。迷わないので、上手いとも思われない代わりに、下手にもならない。" },
		{ kind: "diary", text: "枝には型がない。太さも曲がりもひと枝ずつ違って、同じ値段で箱に寝ている。あれをどう選ぶのか、誰も教科書にしていない。" },
		{ kind: "diary", text: "祖母は枝を選ぶとき根元しか見なかった——これは、私自身の記憶にある。花のついているほうを一度も見なかった。数える私と、見る祖母。" },
		{ kind: "diary", text: "三時起き。軽トラのバッテリーが弱っているので、明日の朝で駄目なら修理に出す。この軽トラは私より長く、あの道を通っている。" },
		{ kind: "diary", text: "フリージア三十、入荷。黄色は、それだけで春の顔をしている。桶に立てると、店の暗いところが一段明るくなった。値札は書いた。一本百八十円。束の値も書いたが、たぶん今月は使わない。" },
		{ kind: "diary", text: "八重さんが甘酒を持ってくるらしい。祖母のところへ毎年持っていったものが、そのまま下に降りてきた。順番、と言われた。順番という言い方をされたのは初めてで、うまく返事ができなかった。" },
		{ kind: "diary", text: "商店街の豆まきを最後まで見た。子ども会の掛け声が三度。三度目がいちばん揃っていた。" },
		{ kind: "diary", text: "明日の段取り。三時起き、四時出、四時四十分着。木札、長靴、毛布、麻紐。現金。梅は毛布をかけて縛る。穂先を荷台の外に出さない。" },
		{ kind: "diary", text: "買う本数を決めてから行く。決めずに行くと、迷った顔をして、迷った値で買う。前の会社ではそれを「予算」と呼んでいた。ひとりでやると、予算はただの決心になる。" },
		{ kind: "diary", text: "決めた。ひと箱。多くても、ひと箱。" },
		{ kind: "diary", text: "祖母の帳面の二月四日は、去年も一昨年も、朝の欄が空白で、昼から数字が始まっている。市場の日は帳面をつける時間がなかったのだと思う。私も明日は空白になるだろう。空白の日があってもいいことを、祖母の帳面から教わっている。" },
		{ kind: "diary", text: "教わっている、と書いた。相手はいないのに、教わっているという言い方になる。" },
	],
};

// 解放: 解放: ステージ2-1クリア後
const umeichi: Vignette = {
	id: "m2-umeichi",
	kind: "scene",
	month: 2,
	title: "梅市",
	trigger: { at: "stage-clear", stageId: "m2-1" },
	synopsis: "夜明け前の浜市場で、初めて梅の枝を競り落とす。競り人に枝の見方を教わる。",
	lines: [
		{ kind: "narration", bg: "market", text: "浜市場の駐車場に着いたのは、四時四十分だった。" },
		{ kind: "narration", text: "外はまだ完全な夜で、建物の窓だけが白く光っている。荷受けの扉が開くたび、中の照明が四角く地面に落ちて、そこをフォークリフトの影が横切っていく。若菜は軽トラの荷台に毛布を敷き直し、首に木札を提げて、コンクリートの坂を上がった。長靴の底が、水を含んだ床でわずかに滑る。" },
		{ kind: "narration", text: "場内は、二駅ぶんの距離を隔てて別の国だった。台車の車輪、荷札を破る音、値を読み上げる声、それに笑い声。誰も急いでいないように歩いていて、誰も止まっていない。若菜が最初にここへ来た一月は、この速度についていけずに壁際を歩いた。二度目の今日は、真ん中を歩いた。歩けたが、肩は少し内側に入っていた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "おう、常サンとこの! 早いな、今日は" },
		{ kind: "narration", text: "法被の背中が振り向いて、大きな声が飛んできた。競り台の上から、辰巳はもう若菜を見つけていた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "おはようございます。梅を、見に来ました" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "見に来た、ときたか。買いに来た、じゃなくてな" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "買いに来ました。見てから" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そら結構。隅だ、隅。奥から二番目の島" },
		{ kind: "narration", text: "梅の区画は、競り場の隅にあった。" },
		{ kind: "narration", text: "天井の照明の下に、切り枝の箱がずらりと寝かされて、そこだけ空気が違った。冷たいままなのに、春の匂いがする。市場じゅうの魚箱と長靴の間で、梅の区画の周りだけ、人の歩く速さが少し落ちる。買参人が三人、四人と屈み込んでは、箱の中に手を入れ、また立ち上がって次の島へ移っていく。誰も長くはいない。長くいるのは、若菜だけだった。" },
		{ kind: "narration", text: "箱の札には産地と等級と本数が書かれている。読める。読めるのに、箱と箱の違いが、値段のぶんだけ見えてこない。" },
		{ kind: "narration", text: "隣の島では、仲卸の若い衆が段ボールを崩しながら大声で数を通していた。奥の壁ぎわに「犬飼生花」と書かれた札が下がっていて、その下を台車が二台、続けて抜けていく。誰も梅の区画には長く留まらない。屈む、触る、立つ、行く。その三拍子が、若菜には楽譜のように見えた。" },
		{ kind: "narration", text: "先に来ていた白髪の買参人が、若菜の斜め前で屈んだ。手が箱の奥へまっすぐ入り、二本抜いて、一本を戻した。三秒だった。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "(三秒)" },
		{ kind: "narration", text: "同じことを自分がやろうとすると、手が箱の手前で止まる。手前の枝は、みんなが触ったあとの枝だった。若菜は袖をまくって、奥まで腕を入れた。冷たい。箱の底のほうが、外より冷たかった。" },
		{ kind: "narration", text: "若菜は箱の前にしゃがんで、枝を見た。見た、つもりだった。気づけば、花芽を数えていた。ひと枝に十二、隣は十五、その隣は——" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "数えとるな" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "……はい" },
		{ kind: "narration", text: "いつの間にか、法被の辰巳が隣に立っていた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "数えるな、とは言わん。数えたあとに、こうだ" },
		{ kind: "narration", text: "辰巳は屈んで、一本の枝の根元を、指の節で、こん、と叩いた。隣の枝も。その隣も。三つの音は、若菜の耳には同じに聞こえた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "詰まっとる音と、空いとる音がある。水の上がる枝は、根元が詰まっとる" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "……もう一度、いいですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "ほう" },
		{ kind: "narration", text: "辰巳は面白そうに、同じ三本を叩き直した。若菜は目を閉じた。一本目。二本目。三本目。——二本目だけ、わずかに低い。骨まで届く音がする。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "二本目" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "当たりだ。常サンの孫だな、耳は" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "(耳、は)" },
		{ kind: "narration", text: "耳は、の「は」が少し引っかかったが、聞かないことにした。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "花芽を数えるなとは言わんが、数は嘘をつくぞ。芽ばっかり付いて根元の細い枝は、店で三日ももたん。開かんまま茶色くなる" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "開かないまま" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "客は怒らんよ。二度と買わんだけだ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "いちばん困ります、それが" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "だろ。あとは曲がりだ。真っ直ぐな枝を選びたがるのは素人だ。花屋は、曲がりで生ける" },
		{ kind: "narration", text: "辰巳は箱から一本抜き出して、床と平行に持ち上げた。枝は途中でゆるく折れて、先で持ち直している。若菜の目の高さで、その曲がりが一度止まった。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "それは、売れ残りの側では" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "言うねえ。この曲がりが玄関で効くんだ。真っ直ぐは束にしたとき喧嘩する" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "うちは、束で出しません。一枝ずつ売ります" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "なら余計に曲がりだ。一枝で立つ枝ってのは、曲がってる枝のことだ" },
		{ kind: "narration", text: "若菜は手帳を出そうとして、やめた。書いたら、書いたところで止まる気がした。代わりに、箱の端から端まで、根元だけを順に叩いていった。こん。こん。こん。二十本ほど叩いたところで、辰巳が短く笑った。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "一日でやろうとするな。一年で二回しか来ん相場だぞ、梅は" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "二回、ですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "正月前と、今。それだけだ。だから、みんな下手なままなんだよ" },
		{ kind: "narration", text: "若菜は、叩いて音のよかった枝の入った箱を三つに絞った。三つのうち、一つは値が高くつきそうな産地だった。手帳を出さずに、番号だけ三つ、口の中で繰り返す。繰り返しているうちに、ひとつ目の番号が曖昧になった。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "三つも覚えるな。二つだ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "見えるんですか、それも" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "口が動いとる。三つ覚える人は、三つとも逃す" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、二つで" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "本命と、次点な。次点は、本命が高こなったときの逃げ場だ。逃げ場のない買い方をすると、店が痩せる" },
		{ kind: "narration", text: "競りが始まった。" },
		{ kind: "narration", text: "前の島の声がこちらへ寄ってきて、辰巳が台に上がると、場の音が一段変わった。掛け声は、若菜の耳には最後まで日本語に聞こえない。数字だけが、その中に硬く混じって落ちてくる。手が上がる。指の形が値になる。木札が読み上げられ、荷札が飛ぶ。速い。速いのに、誰も間違えない。" },
		{ kind: "narration", text: "梅の口が回ってきた。若菜は、根元の詰まっていた口の番号を頭で押さえていた。値が上がる。二つ上がって、止まって、もう一つ上がる。息を吸って、吸ったまま、手を上げた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "はい花常さん!" },
		{ kind: "narration", text: "自分の屋号が、あの声で場内に飛ぶのを、若菜は初めて聞いた。ひと箱。息継ぎで、一度で。" },
		{ kind: "narration", text: "隣の買参人が、若菜のほうを見もせずに言った。" },
		{ kind: "say", speaker: "sub", name: "買参人", text: "いい口、取ったね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ありがとうございます" },
		{ kind: "narration", text: "木札を返しに行くと、辰巳は台の上から降りてきて、法被の袖で額を拭った。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "常サンはな、ここで一回も手ぇ挙げ直したことがない。取れんときは、すっと引く。あれが上手いんだ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "引くのが、ですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "今日のあんたは、二度手が浮いとった。浮いた手は、店の帳簿に出るぞ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "見ていたんですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "台の上は、よう見えるんだ。誰が今日買えん人か、誰が今日は無理して買う人か、顔で分かる" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "私は、どちらでしたか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "今日は買う顔だ。無理はしとらん。悪くない" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "祖母は、どんな顔でしたか" },
		{ kind: "narration", text: "辰巳は木札の束を揃えながら、少し考えた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "顔がなかったな、あの人は。買っても買えんでも同じ顔で帰る。あれは真似せんでいい。真似できるもんでもない" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "真似はしません" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そのほうがいい。うちの若い衆も、みんな最初は誰かの真似をしよる。三年で剥がれる" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "三年" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "早い者で三年だ。あんたは、まだ二月だ" },
		{ kind: "narration", text: "若菜は木札を渡し、荷受けの伝票を受け取った。二月、という言葉が、思っていたより短い長さで返ってきた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "梅はな、店で開かせて売るもんだ。仕入れた日がいちばん値打ちが低い。あれだけは、待ったぶんが金になる" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "待ちます" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "待て待て。あと、水は毎日替えろ。枝は横着すると、根元から匂いが出る" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "匂いが出たら、どうすれば" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "切り戻して、桶を洗え。花屋の桶がぬめっとる店は、客が黙って減る。あんたのばあさんは桶洗いだけは人にやらせんかった" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "その話は、聞いていません" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "聞いとらんことばっかりだろ、あんたは" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "まあ、そんなもんだ。聞いとらんことを、これから拾いに来い。ここは毎週開いとる" },
		{ kind: "narration", text: "若菜は頭を下げた。下げてから、市場の音が、来たときより少しだけ聞き分けられるようになっていることに気づいた。台車の音、荷札、値、笑い声。四つに分かれて聞こえる。" },
		{ kind: "narration", text: "軽トラの荷台に箱を積むころには、駐車場の空が濃い青になっていた。毛布をかけ、口を縛る。梅の穂先が毛布の端から少し出て、走り出しても折れないように、若菜はもう一度縛り直した。" },
		{ kind: "narration", text: "帰りの軽トラの信号待ちで、若菜はハンドルを指の節で、こん、と叩いてみた。ハンドルは詰まった音がした。当たり前だった。" },
		{ kind: "narration", text: "川沿いの道に出たところで空が白みはじめ、町へ下る坂の途中で、荷台の梅が一度だけ、かたん、と鳴った。" },
	],
};

// 解放: 解放: ステージ2-2の前
const chomen0210: Vignette = {
	id: "m2-chomen-0210",
	kind: "chomen",
	month: 2,
	title: "二月十日",
	trigger: { at: "stage-clear", stageId: "m2-1" },
	synopsis: "梅の売れ行きと、市場で教わったことの帳面。祖母の帳面に、見覚えのない一行を見つける。",
	lines: [
		{ kind: "diary", text: "二月十日。曇り。夕方から雨。" },
		{ kind: "diary", text: "去年の梅の仕入れ値を確かめたくて、祖母の帳面の二月を開いた。「読む」と決めて開いたのは、初めてだった。数字を照らし合わせるために開いたことは何度もある。読むために開くのは、別の動作だと分かった。" },
		{ kind: "diary", text: "数字は几帳面で、ひと月ぶんめくっても崩れない。私の帳面は、三日目でもう傾きはじめている。" },
		{ kind: "diary", text: "去年の梅の値は、今年より二割安い。安いのに本数は少ない。少なく買って売り切る人だったのだと思う。私は多く買って、余らせている。" },
		{ kind: "diary", text: "その途中に一箇所、筆圧の乱れた行があって、その脇に、例の小さな字があった。" },
		{ kind: "diary", text: "" },
		{ kind: "diary", text: "「狼の子、また来た。水切りを教えた。筋がいい」" },
		{ kind: "diary", text: "" },
		{ kind: "diary", text: "狼の子。" },
		{ kind: "diary", text: "うちに、そんな客がいたのか。日付はない。「また」とある。一度ではない。教えた、とある。花屋に、水切りを教わりに来たのだろうか。" },
		{ kind: "diary", text: "前後の頁も見た。数字ばかりで、その字はもうない。ひと月に一行、多くて二行。祖母は言葉を、こういう置き方でしか使わない人だった。" },
		{ kind: "diary", text: "分からないことは、分からないままにしておく。この帳面は、そういう読み方をするものな気がする。急いで意味にしてしまうと、たぶん、間違ったものを掴む。" },
		{ kind: "diary", text: "仕入れの筆頭に「宮・内藤」。これは毎年、二月の頭にある。二月に入れるものが思いつかない相手なのに、毎年ある。名前だけ、覚えておく。" },
		{ kind: "diary", text: "梅、売れ行きは中の下。開いた枝から先に出ていく。蕾のうちに買っていく人は、家で開かせるつもりの人だ。そういう人は、たいてい二度来る。" },
		{ kind: "diary", text: "枝物は、待つ商売だと思うことにする。待つのは、性に合っている。" },
		{ kind: "diary", text: "辰巳さんに言われたこと。仕入れた日がいちばん値打ちが低い。待ったぶんが金になる。切り花では一度も聞かなかった話で、書いておかないと忘れる種類の話だと思った。" },
		{ kind: "diary", text: "水は毎日替える。枝は横着すると根元から匂いが出る。これも書いておく。" },
		{ kind: "diary", text: "三年で剥がれる、とも言われた。誰かの真似は三年で剥がれるらしい。私はまだ二月なので、剥がれる前の何かを、今やっているところなのだと思う。" },
		{ kind: "diary", text: "桶洗いは人にやらせなかった、という話も出た。私は今のところ、やらせる人がいない。" },
		{ kind: "diary", text: "本命と次点。逃げ場のない買い方をすると店が痩せる。これは前の会社でも同じことを言われた気がするが、言い方がぜんぜん違う。同じ内容でも、言い方の違うほうだけが手に残る。" },
		{ kind: "diary", text: "梅、開き具合ごとに三つに分けて桶を変えた。開いたもの、半分、蕾。値は同じにする。選ぶのはお客さんの都合であって、私の都合ではない。" },
		{ kind: "diary", text: "明日、レジのロール紙を注文すること。最近、印字が薄い。" },
	],
};

// 解放: 解放: ステージ2-2クリア後
const regi: Vignette = {
	id: "m2-regi",
	kind: "scene",
	month: 2,
	title: "レジと、コンデンサ",
	trigger: { at: "stage-clear", stageId: "m2-2" },
	synopsis: "店のレジが止まり、居合わせた常連の青年が部品を替えて直す。修理の礼をどう返すかを決める。",
	choices: [
		{
			id: "B-03",
			label: "修理の礼",
			axis: "縁",
			options: [
				{ key: "A", label: "梅を一枝、渡す" },
				{ key: "B", label: "くろまつの珈琲に誘う", note: "縁+1" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_day", text: "二月半ばの昼下がりは、店のなかでいちばん光の入る時間だった。" },
		{ kind: "narration", text: "ガラス戸の桟の影が床に伸びて、桶の縁で折れている。ストーブの上のやかんが弱く鳴り、その音の下に、通りを行く自転車と、まるはちの店先の声が混じる。若菜は作業台で梅の手入れをしていた。箱から出したまま二日置いた枝の、根元を切り直していく作業だった。" },
		{ kind: "narration", text: "切り花には自分の鋏を使う。それが枝に替わる時、手はいつのまにか、飴色の柄のほうへ伸びている。持ち替えたことに、若菜自身は気づいていない。祖母の鋏は、枝を切るとき、いい音がした。刃の分厚いぶん、切り口が潰れず、断面に細かい水の粒が浮く。" },
		{ kind: "narration", text: "昼過ぎに客がひとり入って、フリージアを五本と、梅を一枝買っていった。" },
		{ kind: "say", speaker: "sub", name: "女性客", text: "これ、家で咲くのよね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "暖かい部屋なら、四、五日で開きます。お風呂場の近くには置かないでください" },
		{ kind: "say", speaker: "sub", name: "女性客", text: "湿気が駄目なの?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "急に開いて、急に終わります" },
		{ kind: "say", speaker: "sub", name: "女性客", text: "せっかちなのねえ" },
		{ kind: "narration", text: "会計をして、包んで、送り出した。ガラス戸が閉まって、店が静かになった。その静けさの中で、若菜がもう一度キーを押したとき、レジが沈黙した。" },
		{ kind: "say", speaker: "wakana", emo: 5, text: "嘘でしょう、今日" },
		{ kind: "narration", text: "ボタンを押しても、うんともすんとも言わない。電源を抜いて挿し直しても、表示窓は黒いままだった。裏に回してコードを辿り、コンセントを変え、叩いてみる。叩くのは祖母がやっていた直し方で、祖母のときは直っていた。今日は直らなかった。" },
		{ kind: "narration", text: "若菜が電卓と領収書の束を出したところで、ガラス戸が開いた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "こんにちはー。あれ。手書きですか" },
		{ kind: "say", speaker: "wakana", emo: 5, text: "レジが。朝は動いていたんですけど" },
		{ kind: "say", speaker: "ren", emo: 1, text: "見せてもらっていいですか。俺、こういうの専門なんで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "花屋のレジがですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "レジも中身はただの計算機っす。表示が出ないってことは、計算より手前で止まってるんで、たぶん電源です" },
		{ kind: "narration", text: "大神漣——まだ名前は知らない、水仙と梅の青年——は、自転車の前かごから布の工具袋を出してきた。持ち歩いているらしい。勘定台の内側に回り、断ってから、レジの裏蓋を外して覗き込む。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー。コンデンサが妊娠してますね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "妊娠" },
		{ kind: "say", speaker: "ren", emo: 6, text: "膨らんでるんです、ここ。頭のとこ、こう、ぷくっと。中の電解液が悪くなると圧が上がって、逃がすために天面に十字の溝が切ってあって、そこが最初に開くんですけど、この個体はまだ耐えてます。破裂する前でよかった。液が漏れると基板ごと駄目になるんで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今、何割くらい分かればいいですか" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あ。すいません、早口になりました。要は部品ひとつ替えれば直ります" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "それは、分かります" },
		{ kind: "say", speaker: "ren", emo: 1, text: "駅前のパーツ屋にあるんで、三十分ください。容量と耐圧が合えばいいんで、たぶん百円しないっす" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "百円" },
		{ kind: "say", speaker: "ren", emo: 2, text: "百円で治る病気なんすよ、これ" },
		{ kind: "narration", text: "言うなり自転車で消えていった。" },
		{ kind: "narration", text: "若菜は勘定台に電卓を置いたまま、店に残った。ロール紙の予備の箱を出し、伝票の綴りを開いて、二月の売上を鉛筆で写しはじめる。指先が冷えて、字が硬くなった。途中で客がふたり入り、どちらも手書きの領収書を待ってくれた。ひとりは待つあいだ、桶の梅を覗き込んで、これは家で咲くのかと聞いた。同じことを、今日二度聞かれた。" },
		{ kind: "narration", text: "三十分きっかりに、ガラス戸が開いた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "ありました! 二本買ってきたっす、失敗したとき用に" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "失敗、するんですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "しないっす。しないっすけど、二本目があると手が落ち着くんで" },
		{ kind: "narration", text: "工具袋から、鉛筆ほどの太さの半田ごてが出てきた。青年は勘定台の隅を借り、レジの基板を裏返し、古い部品の脚を溶かして抜いた。半田の細い煙が一筋立って、若菜は換気のためにガラス戸を少し開けた。冷たい風が足元を通り、桶の梅の穂先が揺れた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "寒くないですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "今、いいっす" },
		{ kind: "narration", text: "そこから、青年は何も喋らなくなった。手だけが動いていた。新しい部品を挿し、向きを二度確かめ、脚を切る。ぱちん、という小さな音が、店の中では意外なほど響いた。若菜が使う鋏の音とは、違う切り方の音だった。" },
		{ kind: "narration", text: "やがてレジは、チン、と生き返った。" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "直った" },
		{ kind: "say", speaker: "ren", emo: 2, text: "直りました! いや、頑丈ですよこのレジ。まだ現役だったんだな、おまえ" },
		{ kind: "narration", text: "レジに向かって言った。言ってから、青年は半拍おいて付け足した。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あ、いや。年代物だなって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "よく分かるんですね、こういう機械が" },
		{ kind: "say", speaker: "ren", emo: 1, text: "古いやつは中が読めるんすよ。今のは基板見ても何も分からないっす。全部一枚になってて、壊れたら丸ごと交換" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花も、そうです。長く持たせようとすると、古いやり方に戻ります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "花もっすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "水切りとか。結局あれがいちばん効きます" },
		{ kind: "narration", text: "青年は裏蓋を締め直しながら、ドライバーを持つ手を一度止めた。それから、何でもない声で締め終えた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お代を" },
		{ kind: "say", speaker: "ren", emo: 6, text: "いらないっす、いらないっす。通りがかりなんで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "通りがかりで工具は持ち歩きません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "サークルの部室が坂の上なんで、いつも持ってるんすよ。同好会のサーバーがしょっちゅう落ちるんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "サーバー" },
		{ kind: "say", speaker: "ren", emo: 2, text: "機械です。部屋の隅で唸ってるやつ。うるさいし熱いし、金は食うし" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "褒めているんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "褒めてます" },
		{ kind: "narration", text: "若菜は勘定台に戻り、レジを開けて閉めた。もう一度開けて、閉めた。二十年ぶんの音がした。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "この音、久しぶりに聞きました" },
		{ kind: "say", speaker: "ren", emo: 4, text: "半日っすよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "半日でも、店の音が一つ減ると、店が静かになります" },
		{ kind: "narration", text: "青年は工具を袋に戻しながら、店をひととおり見た。桶、冷蔵ケース、勘定台、その奥の丸椅子。視線が、丸椅子のところで一拍だけ止まった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "いい店っすね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "古いだけです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "古いのがいいんすよ。中が読めるんで" },
		{ kind: "narration", text: "若菜は、それはさっきも聞きました、と言おうとしてやめた。二度言う人は、たいてい本気で言っている。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あ、そうだ。これ、電源のとこなんで、また同じ壊れ方します。三年か、四年か" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "また膨らむんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "膨らみます。ほかの部品も同い年なんで、順番に来ます" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "では、まとめて替えたほうが" },
		{ kind: "say", speaker: "ren", emo: 1, text: "替えられます。けど、壊れてから替えたほうが安いっす。壊れる前に替えると、まだ元気なやつまで捨てることになるんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花と、逆です" },
		{ kind: "say", speaker: "ren", emo: 4, text: "逆っすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花は、傷む前に手を打たないと戻りません。水が下がってからでは遅い" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー。それは、そうっすね" },
		{ kind: "narration", text: "青年は工具袋の口を締めながら、少しのあいだ黙って、それから言った。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ、俺のほうが楽っすね。壊れてから行けばいいんで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "壊れてからでも来てくれるんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "呼ばれたら来ます。呼ばれなくても、まあ、買いに来ますけど" },
		{ kind: "narration", text: "レジの表示窓の数字が、律儀にゼロを並べていた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "一つ、聞いてもいいですか" },
		{ kind: "say", speaker: "ren", emo: 4, text: "はい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "先月の水仙は、どうなりましたか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "一週間もちました。最後、ちょっと首が曲がって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "水が多かったんだと思います。水仙は浅く張ってください。球根のものは、深いと傷みます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "浅くていいんすか。すぐ乾きそうっすけど" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "乾く前に足せばいいので。毎日見ることになります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "なるほど。毎日見るのが仕事っすね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "仕事ではありません。ただの水やりです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "うちのサーバーと一緒っすね。毎日見てるやつは、落ちないんすよ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "落ちる" },
		{ kind: "say", speaker: "ren", emo: 2, text: "止まることっす。放っとくと、いちばん寒い日に止まります" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花も、いちばん寒い日に傷みます" },
		{ kind: "say", speaker: "ren", emo: 2, text: "一緒じゃないっすか" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "一緒にされると、少し困ります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "道理で持つと思った、あれ。うち、暖房ガンガンなのに" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "暖房の効いた部屋は、花には向きません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "じゃあ、寒くしとけばいいっすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "あなたが風邪をひきます" },
		{ kind: "narration", text: "青年は笑って、自転車の鍵を出しながら戸口へ向かった。ガラス戸の桟の影は、来たときより一段、床の奥へ伸びていた。" },
		// 【B-03=A】
		{ kind: "narration", when: { choice: "B-03", is: "A" }, text: "若菜は少し考えて、店先の梅から、いちばん根元の詰まった一枝を選んだ。市場で叩いた二十本のうちの、一本だった。新聞紙を斜めに置いて、一巻き。二度目は、一度目より上手く巻けた。" },
		{ kind: "say", when: { choice: "B-03", is: "A" }, speaker: "wakana", emo: 1, text: "では、これを" },
		{ kind: "say", when: { choice: "B-03", is: "A" }, speaker: "ren", emo: 4, text: "え、それ、売り物じゃ" },
		{ kind: "say", when: { choice: "B-03", is: "A" }, speaker: "wakana", emo: 1, text: "売り物です。修理代のほうが高いので、こちらが損をしています" },
		{ kind: "say", when: { choice: "B-03", is: "A" }, speaker: "ren", emo: 6, text: "損て" },
		{ kind: "say", when: { choice: "B-03", is: "A" }, speaker: "wakana", emo: 1, text: "損得の話にしておいたほうが、受け取りやすいでしょう" },
		// 【B-03=B】
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "wakana", emo: 1, text: "では、お茶を。この先の、くろまつというお店で" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 4, text: "え、いいんですか" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "wakana", emo: 1, text: "珈琲だけの店です。二十分ほど" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 2, text: "行くっす。腹減ってるんで何か食えたら最高っす" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "wakana", emo: 1, text: "食べ物は、豆しかありません" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 4, text: "豆" },
		{ kind: "narration", bg: "indoor_other", when: { choice: "B-03", is: "B" }, text: "くろまつのカウンターに、若菜とレンが並んだ。" },
		{ kind: "narration", when: { choice: "B-03", is: "B" }, text: "昼を過ぎた店には客がひとりもおらず、窓から入る光が、カウンターの木目を端から順に舐めていた。奥でミルが回り、回り終わってから、湯の落ちる音だけが長く続いた。マスターはレンを一瞥して、豆の缶を三つ——今日は四つ、並べた。" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 1, text: "あの、これ、何が違うんすか" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "sub", name: "玄", text: "……豆" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 4, text: "豆っすか" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "sub", name: "玄", text: "……" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "wakana", emo: 1, text: "左から、浅いほうです" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 1, text: "じゃあ、真ん中で" },
		{ kind: "narration", when: { choice: "B-03", is: "B" }, text: "出てきた一杯を、レンは両手で包んで、ひと口で目を丸くした。" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 4, text: "うっま。何これ、うっま" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "sub", name: "玄", text: "……" },
		{ kind: "narration", when: { choice: "B-03", is: "B" }, text: "マスターの口の端が、ほんのわずか動いた。それから、カウンターの下から小皿を出して、豆菓子をいくつか置いた。頼んでいないものだった。" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 2, text: "え、いいんすか。いただきます" },
		{ kind: "narration", when: { choice: "B-03", is: "B" }, text: "若菜は自分のカップを見た。カウンターの、隣の席。座るようになったのは先月からで、今日は自分の左に一人ぶん、席が空いている。" },
		{ kind: "narration", when: { choice: "B-03", is: "B" }, text: "店を出て花常の前まで戻ったところで、若菜は思い出したように、店先の梅から一枝を選んだ。根元の詰まった、いい音のする枝。" },
		{ kind: "say", bg: "front_winter", when: { choice: "B-03", is: "B" }, speaker: "wakana", emo: 1, text: "こちらは、今月のぶんです。買っていくのでしょう、どうせ" },
		{ kind: "say", when: { choice: "B-03", is: "B" }, speaker: "ren", emo: 2, text: "どうせ、買います" },
		// 【合流】
		{ kind: "say", speaker: "ren", emo: 5, text: "……" },
		{ kind: "narration", text: "青年は、両手で受け取った。" },
		{ kind: "narration", text: "片手で足りる細い枝を、わざわざ両手で。梅の穂先が、彼の胸の高さで小さく揺れた。" },
		{ kind: "say", speaker: "ren", emo: 3, text: "じゃあ、これで" },
		{ kind: "narration", text: "戸口で、青年は思い出したように振り返った。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "今月のぶん、ってことで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "今月の……?" },
		{ kind: "narration", text: "戸は閉まった。今月のぶん。先月は水仙で、今月は梅。彼の中には、何か決まりがあるらしい。" },
	],
};

// 解放: 解放: ステージ2-3クリア後
const tanjoubi: Vignette = {
	id: "m2-tanjoubi",
	kind: "scene",
	month: 2,
	title: "誕生日は過ぎている",
	trigger: { at: "stage-clear", stageId: "m2-3" },
	synopsis: "夕方の店先で、過ぎたばかりの誕生日を隣の八百屋に言い当てられる。名前の由来の話になる。",
	choices: [
		{
			id: "B-04",
			label: "誕生日",
			options: [
				{ key: "A", label: "正直に答える" },
				{ key: "B", label: "流そうとする" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "二月の終わりの夕方は、日の落ちる位置が先月より少しだけ川寄りになっていた。" },
		{ kind: "narration", text: "五時を過ぎても店先はまだ薄青く、通りの向かいで霜月堂が暖簾を下ろしはじめる。ストーブを弱め、桶の水を足し、若菜が値札を書き直していると、ガラス戸が勢いよく開いて、八重さんが白菜を一玉抱えて入ってきた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "余りもん。鍋にしな。ひとり鍋でも鍋は鍋だよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "いつもすみません。あの、お代を" },
		{ kind: "say", speaker: "sub", name: "八重", text: "白菜に代取ったら、罰が当たるよ、今の時期" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、帰りに何か持っていってください" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花はいらないよ。うちは店じゅう青いんだから" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "青物と花は違います" },
		{ kind: "say", speaker: "sub", name: "八重", text: "同じだよ。水につけときゃ長持ちする" },
		{ kind: "narration", text: "ちょうど、水仙——ではなく今日はフリージアを選んでいたレンが、桶の前から会釈した。八重さんはレンをじろりと見て、それから若菜を見た。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常連さんかい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい。月に一度の" },
		{ kind: "say", speaker: "ren", emo: 2, text: "どうも。月に一度の者です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "変な挨拶だね。——そういえば若菜ちゃん、あんた誕生日いつだい" },
		// 【B-04=A】
		{ kind: "say", when: { choice: "B-04", is: "A" }, speaker: "wakana", emo: 4, text: "……一月七日、ですけど" },
		{ kind: "say", when: { choice: "B-04", is: "A" }, speaker: "sub", name: "八重", text: "過ぎてるじゃないの!" },
		{ kind: "say", when: { choice: "B-04", is: "A" }, speaker: "wakana", emo: 3, text: "過ぎてから聞かれたので" },
		// 【B-04=B】
		{ kind: "say", when: { choice: "B-04", is: "B" }, speaker: "wakana", emo: 1, text: "……もう、過ぎたので。いいんです" },
		{ kind: "say", when: { choice: "B-04", is: "B" }, speaker: "sub", name: "八重", text: "過ぎたってことは一月かい。一月の何日" },
		{ kind: "say", when: { choice: "B-04", is: "B" }, speaker: "wakana", emo: 3, text: "……七日です" },
		{ kind: "say", when: { choice: "B-04", is: "B" }, speaker: "sub", name: "八重", text: "ほら言えるじゃないの! 過ぎてるじゃないの!" },
		{ kind: "narration", when: { choice: "B-04", is: "B" }, text: "流せる相手ではなかった。" },
		// 【合流】
		{ kind: "say", speaker: "ren", emo: 4, text: "一月七日って、七草の日っすか。若菜の日じゃないですか。名前まんまじゃないですか" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "まんま、って" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんが付けたんだよ、その名前。『いい名だろう』って、そりゃあ自慢してた" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "……自慢、ですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "してたよぉ。仕入れ先にまで言ってた。孫の名前はあたしが付けた、七日の生まれで若菜だ、って。聞かされたこっちが覚えちまうくらい" },
		{ kind: "narration", text: "若菜は、フリージアの黄色に目を落とした。祖母が名前を自慢して回る姿は、記憶のどこを探しても、ない。知らない祖母が、また一人増えた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "本人からは、一度も聞いていません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "言うわけないだろ、本人には。ああいう人は、いないとこでしか自慢しないの" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "厄介です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "厄介だよ。碁も強かったしね" },
		{ kind: "say", speaker: "ren", emo: 4, text: "碁、打つんすか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "打ったよ。くろまつのマスターと、毎週。負けると三日は不機嫌でさ、そういう日は花に当たるんだ。水の替え方が乱暴でね、見てりゃ分かるんだよ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花に、ですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんたのばあちゃんはね、聖人じゃないよ。よく怒鳴ってたし、値切りは町でいちばん厳しかった。うちの父さんが泣かされてる" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "それは、少し安心します" },
		{ kind: "say", speaker: "sub", name: "八重", text: "変な孫だねえ" },
		{ kind: "say", speaker: "ren", emo: 4, text: "若菜って、七草の若菜っすよね。春の七草の" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そうそう。若菜摘みってのがあるんだよ、昔の。正月の七日に、野に出て若い菜を摘むの。それの日に生まれたから若菜" },
		{ kind: "say", speaker: "ren", emo: 2, text: "めちゃくちゃ花屋の孫じゃないっすか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花屋の孫だから付けたんじゃないよ。生まれた日が先。日にちが名前になっただけ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "順番の話が、今日は多いです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "歳を取るとね、何でも順番の話になるんだよ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、店は続けんの" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "続けます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "即答だね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "即答できる質問だったので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そうかい。じゃあ、いいんだ" },
		{ kind: "narration", text: "八重さんは、それ以上は聞かなかった。聞かないまま、桶の梅を一枝抜いて、勘定台に置いた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "これ、もらってく。うちの店に一本立てとくよ。青物のとこに赤い枝があるとね、目が留まるんだ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "エチレンの話をしたばかりです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "一日で売り切るからいいの" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、お代はいただきます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "取るのかい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "白菜と違って、これは仕入れているので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そういうとこも似てるよ、ほんとに" },
		{ kind: "narration", text: "八重さんは白菜を勘定台に置き直して、それから、店の奥の作業場をひととおり見た。水場、冷蔵ケース、壁に掛かった鋏。目が止まったのか止まらなかったのか、若菜には分からなかった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "置き方、変わってないね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "動かす理由が、まだないので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そのうち動かしな。あんたの店なんだから" },
		{ kind: "say", speaker: "ren", emo: 2, text: "来年は祝うっす。覚えました、一月七日" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "別に、いいです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "メモしました" },
		{ kind: "narration", text: "スマホが、ことり、と鳴った。本当にメモをしたらしい。" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "何と書いたんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "一月七日、って" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "それだけですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それだけっす。ほかに要ります?" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "要りません" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ、来年" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "気の長い予定です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "一年なんて、水仙から水仙までっすよ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "そういう数え方をするんですね" },
		{ kind: "say", speaker: "ren", emo: 2, text: "花屋で覚えました" },
		{ kind: "narration", text: "若菜は、その言い方を頭の中で一度なぞって、それから値札の束を揃え直した。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "来年の話をしましたね、今" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え。しました?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "しました" },
		{ kind: "say", speaker: "ren", emo: 6, text: "まあ、来年もいるんで" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんた、学生だろ。卒業は" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あと二年半っす" },
		{ kind: "say", speaker: "sub", name: "八重", text: "二年半。ちょうどいいね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "何がですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "何がだろうね" },
		{ kind: "narration", text: "八重さんは笑って、来たときと同じ勢いでガラス戸を開け、白菜の話だけ念を押して帰っていった。通りはもう暗く、まるはちの店先の裸電球が、道の半分を黄色くしていた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ、俺も。これください" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "今月のぶんは、もう渡しました" },
		{ kind: "say", speaker: "ren", emo: 2, text: "これは別っす。ちゃんと買うぶん" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "区別があるんですね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あるんすよ、俺の中では" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "フリージアですね。一本で" },
		{ kind: "say", speaker: "ren", emo: 2, text: "一本で" },
	],
};

// 解放: 解放: 全ステージクリア後
const miyaNaitou: Vignette = {
	id: "m2-miya-naitou",
	kind: "scene",
	month: 2,
	title: "宮・内藤",
	trigger: { at: "month-close", month: 2 },
	synopsis: "祖母の帳面にある取引先の名前を市場に問い合わせる。作業場で梅を切り直し、鋏を並べて見る。",
	lines: [
		{ kind: "narration", bg: "workroom", text: "作業場は、店より三度ほど寒い。" },
		{ kind: "narration", text: "北側の窓が高い位置に一つだけあって、そこから落ちる光が、水場のタイルを白く照らしている。冷蔵ケースの音が低く続き、蛇口の水滴が、間を置いて桶に落ちる。棚には新聞の束と麻紐、明礬の瓶。壁の釘に、鋏が二挺。若菜のものと、飴色の柄のもの。" },
		{ kind: "narration", text: "若菜は電話を耳と肩で挟んで、梅の残りを数えていた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "二月の頭に、毎年入っている名前がありまして。宮の、内藤さん" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "内藤? 内藤は菊屋だ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "菊、ですか。二月に" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "出さんよ。あすこは秋しか出さん。十月の頭から十一月まで、それきりだ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "では、二月の頭に何を仕入れるんですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "知らん。常サンが何か書いとったんなら、仕入れじゃないんじゃないか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "仕入れの頁の、いちばん上に書いてあります" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そりゃ、忘れんためだろ。あの人は忘れそうなことを一番上に書く" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "二月の頭に、菊農家に、忘れてはいけない用がある" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "あんた、それを俺に聞いてどうする" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "聞ける相手が、そう多くないので" },
		{ kind: "narration", text: "電話の向こうで、荷を降ろす音と、誰かの笑い声がした。辰巳は少し黙って、それから声を張った。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "内藤の畑は、山んほうだ。近くはない。今から行く話じゃない" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "行くとは言っていません" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "言っとらんが、あんたは行く顔で喋る" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "電話です" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "電話でも分かるわ! 秋になったら連れてってやる。それまで、名前だけ覚えとけ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "名前だけ、ですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "名前だけでいい。値札より先に名前を覚えろ" },
		{ kind: "narration", text: "若菜の手が止まった。同じ言い回しが耳に残った。いつ聞いたのかは、思い出せなかった。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "内藤は無愛想だぞ。うちの若い衆が三人ばかり泣かされとる" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "泣かされる要素が、菊に" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "菊にはない。あの爺さんにある" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "祖母とは、どうだったんでしょう" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "常サンには喋っとったな。あの二人、話すときだけ声が小さかった" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "小さく" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "商売の話じゃなかったんだろ。俺は聞いとらん。聞かんもんだ、ああいうのは" },
		{ kind: "narration", text: "若菜は受話器を持ち替えた。冷蔵ケースの音が、電話の向こうの市場の音と、しばらく重なっていた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "秋に、お願いします" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "おう。十月だ。忘れるなよ、こっちは忘れるから" },
		{ kind: "narration", text: "電話を切って、若菜は帳面の二月の頁に「宮・内藤=菊農家(秋のみ)」と書き足した。分からないことが、少しだけ形になって、そのぶん、分からなさが濃くなった。" },
		{ kind: "narration", text: "店先から声がした。" },
		{ kind: "say", speaker: "sub", name: "男性客", text: "すみませーん、花あります?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい、ただいま" },
		{ kind: "narration", text: "若菜は前掛けで手を拭いて、店へ出た。作業着の男が桶を覗き込んでいて、何を買うとも決めていない顔をしていた。" },
		{ kind: "say", speaker: "sub", name: "男性客", text: "開店祝いなんだけど、堅苦しくないやつ。相手が同い年でさ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "開店は、いつですか" },
		{ kind: "say", speaker: "sub", name: "男性客", text: "あさって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、今日は開きすぎていないものを。あさってがいちばんいい顔になります" },
		{ kind: "say", speaker: "sub", name: "男性客", text: "そんな計算できんの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花は、その計算しかできません" },
		{ kind: "narration", text: "若菜はフリージアを主にして、菜の花を少し混ぜた。黄色ばかりになったところへ、梅を一枝、後ろに立てた。男は、それがいい、と言った。理由は言わなかった。" },
		{ kind: "narration", text: "送り出してから、作業場へ戻った。梅を切り直す作業の途中だった。" },
		{ kind: "narration", text: "桶から一本抜いて、長さを決め、壁の釘へ手を伸ばす。飴色の柄。切る。断面に水の粒が浮く。もう一本。切る。フリージアの束を整えるところで、若菜は鋏を置き、自分の鋏を取った。細い刃が、茎を薄く滑らせる。" },
		{ kind: "narration", text: "置いて、取って、また置いて、取る。" },
		{ kind: "narration", text: "その往復を、若菜は何度も繰り返した。梅のときは祖母の鋏。切り花のときは自分の鋏。手が勝手に選び分けていて、選び分けていること自体は、頭のどこにも上がってこない。作業場の窓の光が少しずつ低くなり、水滴の音だけが同じ間隔で続いていた。" },
		{ kind: "narration", text: "最後の一枝を切り終えて、若菜は飴色の柄を釘に戻した。刃を拭く布は、祖母の鋏のときだけ、丁寧に二度動いた。" },
		{ kind: "narration", text: "前の会社では、鋏は支給品だった。名前のシールを貼って、退職の日に返した。返すとき、何も思わなかった。思わないように作られた道具だった。" },
		{ kind: "narration", text: "若菜は自分の鋏を作業台に置き、飴色の柄を釘に掛けたまま、二挺を並べて見た。刃渡りはほとんど同じで、柄の太さだけが違う。祖母の手のほうが、自分より大きかったのだと分かる。" },
		{ kind: "narration", text: "水場の蛇口を締めて、桶を伏せた。窓の光はもう届かず、蛍光灯の白さだけが残っている。冷蔵ケースの音が、また一段低くなった。" },
		{ kind: "narration", text: "釘に掛かった飴色の柄を、若菜はもう一度見た。柄の端に、細い傷が三本ある。数えたのは初めてだった。" },
		{ kind: "narration", text: "若菜は帳面を作業台に開き、今日の欄に書いた。" },
		{ kind: "narration", text: "梅　切り直し　二十二" },
		{ kind: "narration", text: "フリージア　束　一" },
		{ kind: "narration", text: "開店祝い一束(あさって開店・同い年の方)" },
		{ kind: "narration", text: "書いてから、最後の行を見た。名前は聞いていない。聞いていないのに、行にした。以前の若菜なら、この行は数字だけで済ませていた。" },
		{ kind: "narration", text: "作業場を出るとき、若菜は電気を消し、消してから、もう一度つけた。切り屑をまとめ忘れていた。それを新聞にくるんで、通りの隅のごみ箱へ持っていく。表に出ると、風が坂を下ってきて、庇のトタンが一度だけ鳴った。" },
	],
};

// 解放: 解放: 二月の全ステージクリア後
const chomen0228: Vignette = {
	id: "m2-chomen-0228",
	kind: "chomen",
	month: 2,
	title: "二月二十八日",
	trigger: { at: "month-close", month: 2 },
	synopsis: "二月の締めの帳面。梅の残りと売上を数え、三月の仕入れの支度を書く。",
	lines: [
		{ kind: "diary", text: "二月二十八日。晴れ。夕方から風。" },
		{ kind: "diary", text: "梅、残り三枝。待つ商売は、待てば勝つ。来年は口数を増やす。増やして、二割高く買う。安い口は安いなりの音がしていた、と今なら書ける。" },
		{ kind: "diary", text: "市場では二度、手が浮いた。辰巳さんに見られていた。台の上からは、よく見えるらしい。次は、引く練習をする。取れない日を作らないと、取る日が下手になる。" },
		{ kind: "diary", text: "根元を叩く癖がついた。梅を叩き、物差しを叩き、ハンドルを叩き、白菜まで叩いた。白菜は、詰まった音がした。おいしかった。" },
		{ kind: "diary", text: "レジ、復活。修理代は梅一枝。安すぎる気がするが、彼はあれで満足したらしい。「今月のぶん」と言っていた。先月は水仙、今月は梅。彼の中には決まりがある。" },
		{ kind: "diary", text: "誕生日が、八重さん経由で知れた。「来年は祝うっす」だそうだ。来年、という言葉を、ためらいなく使う人だ。" },
		{ kind: "diary", text: "祖母は私の名前を自慢していたらしい。本人からは一度も聞いていない。そういうことが、この町にはまだ埋まっている気がする。掘るのが、少し怖くて、少し楽しみだ。" },
		{ kind: "diary", text: "碁に負けると花に当たっていた、とも聞いた。値切りは町でいちばん厳しかった、とも。祖母の話は、いい話ばかり出てくると思っていた。出てこないだけだった。" },
		{ kind: "diary", text: "宮の内藤さんは菊農家。秋しか出さない。二月の頭に、菊農家に用のある花屋。秋になったら市場から連れていってもらう約束を取り付けた。約束を、自分から取り付けた。" },
		{ kind: "diary", text: "作業場の道具の置き方を、変えなかった。変える理由がまだない、と八重さんには言った。理由ができるまでは、このままにしておく。" },
		{ kind: "diary", text: "筋がいい、って、誰のことだろう。狼の子。狼の——" },
		{ kind: "diary", text: "……考えるのをやめて、三月の仕入れ表を作った。桃と、啓翁桜。卒業式の日取りを商店街の掲示板で確かめて、前後三日に丸をつけた。束の値札は、来月こそ使う。" },
		{ kind: "diary", text: "春が数字になっていくのは、悪くない。" },
		{ kind: "diary", text: "今月の売上は、先月より少し良い。良くなった理由の半分は梅で、半分は分からない。分からないほうを、来月は減らしたい。" },
		{ kind: "diary", text: "レジは、あと三、四年でまた同じ壊れ方をするらしい。壊れてから替えるほうが安い、とのこと。花は逆で、傷む前でないと戻らない。同じ「古いものを使い続ける」でも、機械と花では手の打ち方が逆になる。逆になるのに、どちらも「よく見る」ところから始まるのは同じだった。" },
		{ kind: "diary", text: "八重さんに梅を一枝売った。青物の隣に赤い枝。一日で売り切るから平気だそうだ。売り切る自信のある人の言うことは、だいたい正しい。" },
		{ kind: "diary", text: "開店祝いの束を作った。あさって開店の、同い年の方。名前は聞いていない。名前を聞くのは、まだ少し図々しい気がして、聞けなかった。来月からは聞くことにする。" },
		{ kind: "diary", text: "二月の帳面を読み返した。数字のほかに、名前が四つ書いてある。一月は、二つだった。" },
		{ kind: "diary", text: "増えている。増やそうとした覚えは、ない。" },
		{ kind: "diary", text: "三月は、卒業式がある。人の門出に立ち会う商売だと、前の会社では研修で教わった。教わったときは、うまい言い方だと思っただけだった。今年は、うちの店の前を通る子が何人か、袴で通る。" },
		{ kind: "diary", text: "梅は、まだ三枝残っている。残りは店に立てておく。売れなければ、自分の部屋に持って上がろうと思う。" },
	],
};

/** 第二章 如月。⚠️並び順が再生順。 */
export const M02: readonly Vignette[] = [
	hiiragi,
	chomen0203,
	umeichi,
	chomen0210,
	regi,
	tanjoubi,
	miyaNaitou,
	chomen0228,
];
