/**
 * 花常 本文 第五章 皐月「母の日」
 * 原稿から転記した実行時シナリオデータ。
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ5-1の前」   → month-open 5
 *   「ステージ5-1クリア後」 → stage-clear m5-1
 *   「ステージ5-2クリア後」 → stage-clear m5-2
 *   「ステージ5-3クリア後」 → stage-clear m5-3
 *   「五月の全ステージクリア後・前半/中盤/後半」 → month-close 5
 */

import type { Vignette } from "./types.js";

// 解放: ステージ5-1の前
const chomen0501: Vignette = {
	id: "m5-chomen-0501",
	kind: "chomen",
	month: 5,
	title: "五月一日",
	trigger: { at: "month-open", month: 5 },
	synopsis: "連休明けの帳面。母の日に向けた仕入れと値札、予約の受け方の段取りを書き出す。",
	lines: [
		{ kind: "diary", text: "五月一日。晴れ。連休の商店街は、静かだ。" },
		{ kind: "diary", text: "朝の八時に表を掃いたら、通りに人が三人しかいなかった。まるはちの八重さんと、犬を連れた誰かと、私。旗の出ていない店が四軒。四月の終わりから、この通りは半分眠っている。" },
		{ kind: "diary", text: "静かなのは今のうちで、第二日曜に向けて、母の日の陣を立てる。カーネーション、赤六十、桃四十、白は仏用と分けて十。芍薬二十。リボン、発注済み。" },
		{ kind: "diary", text: "追加でバケツを六つ買った。前の職場では、母の日の三日前から店の床が桶で埋まって、通路が一本になった。ここは通路がもともと一本しかない。桶は縦に並べる。" },
		{ kind: "diary", text: "軽トラは、二日と六日と、十日の朝。十日は二度行く。荷台に立てる仕切りの板が一枚割れていたので、麻紐で縛って足した。棚は縛れ、と祖母は書いた。板も縛れるだろう。" },
		{ kind: "diary", text: "値札は、赤・桃・白でそれぞれ書き分ける。去年の値札は一枚も残っていない。祖母は毎年、その年の紙に書いていたらしい。使い回しの札が抽斗から出てこない。" },
		{ kind: "diary", text: "予約は、去年までの紙の帳面をそのまま使う。名前、電話番号、受け取りの日と時刻、色、予算。欄は五つで足りる。足りるはずだ。" },
		{ kind: "diary", text: "前の職場では、母の日の三週間前に本部から手引きが届いた。何時に何束を作り置きするか、包装紙の型番、リボンの結び方の写真まで載っていた。あれを一度も見ないで済む五月は、これが初めてになる。" },
		{ kind: "diary", text: "見ないで済む、というのは、誰も教えてくれないということでもある。" },
		{ kind: "diary", text: "白の置き場所は、赤の隣にしない。隣り合っていると、いつか誰かが取り違える。取り違えたほうを責める話ではなく、置いたほうの落ち度だ。棚を一段ぶん、奥にずらす。" },
		{ kind: "diary", text: "冷蔵ケースの温度を一度下げた。下げすぎると花が眠って、日曜の朝に起きない。去年の設定はどこにも書き残されていない。祖母は、たぶん指で確かめていた。" },
		{ kind: "diary", text: "白は仏用と分けて置く。同じカーネーションでも、置き場所が違うと客の手の伸び方が変わる。これは前の職場で覚えたことなので、素直に使う。" },
		{ kind: "diary", text: "蕾の固さは、市場で聞いた。第二日曜に合わせるなら、五日の入荷は固すぎるくらいでいいそうだ。あとは店で開かせる。開かせる、という言い方を、この仕事に来てから覚えた。" },
		{ kind: "diary", text: "五百円の束の作り方だけ、先に決めておく。三本と緑一枚、紙は薄いほうを縦に。母の日に五百円で来る人は、たいてい若い。若い人に小さい束を渡すときの手つきを、雑にしない。" },
		{ kind: "diary", text: "芍薬は温度で開く。夜のうちに作業場の戸を閉めるか開けるかで、日曜の朝の顔が変わる。天気予報を毎晩見る月になる。" },
		{ kind: "diary", text: "立て看板は、去年のものが物置にあった。「母の日 ご予約承ります」。字は祖母の字だ。書き直すか迷って、そのまま出すことにした。私の字で書き足すのは、下の余白の一行だけにする。" },
		{ kind: "diary", text: "祖母の帳面の五月は、頁が黒い。客の名前がびっしりで、数字より名前のほうが多い。こんな頁は、ほかの月にはない。" },
		{ kind: "diary", text: "「木下さんの奥さん 赤 大きめ」「三丁目の郵便屋さん 母上へ 桃」「霜月堂 二束 ひとつは義母」——数の隣に、必ず誰かがいる。" },
		{ kind: "diary", text: "名前の下に、小さく線が引いてある人が何人かいる。線の意味はどこにも書いていない。二年つづけて来た人か、はじめて来た人か。どちらだろう。" },
		{ kind: "diary", text: "余白にひとつ。「爪で弾いて、音のいい蕾を」" },
		{ kind: "diary", text: "芍薬の蕾を、爪で弾いてみた。こん。こん。こん。二十個、全部同じ音がする。" },
		{ kind: "diary", text: "まだ、私の耳は蕾に届かない。" },
		{ kind: "diary", text: "届かないことを、今年の分として書いておく。" },
	],
};

// 解放: ステージ5-1クリア後
const denwa: Vignette = {
	id: "m5-denwa",
	kind: "scene",
	month: 5,
	title: "電話が鳴りやまない",
	trigger: { at: "stage-clear", stageId: "m5-1" },
	synopsis: "母の日の一週間前。予約の電話が次々にかかり、手と受話器の数が足りなくなる。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "連休が明けて三日、通りに旗が戻った。まるはちの店先には筍が積まれ、霜月堂の硝子には柏餅の札が出て、花常の桶は床の端まで一列に伸びた。赤のカーネーションが六十本、桃が四十本、水を吸って、朝の光の向きに首を揃えている。" },
		{ kind: "narration", text: "母の日の一週間前から、店の電話が別の生き物になった。" },
		{ kind: "say", speaker: "sub", name: "電話の声", text: "もしもし、日曜に受け取りって、まだ間に合います?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "はい、お名前を——" },
		{ kind: "narration", text: "言っている途中で、店先には花束を待つ客が二人。作業台には巻きかけの束。電話を肩で挟んで、リボンを結びながらメモを取ると、字が自分でも読めない角度に曲がった。" },
		{ kind: "narration", text: "受話器を置いて、五秒。" },
		{ kind: "say", speaker: "sub", name: "電話の声(男)", text: "あの、母がですね、赤が嫌いなんですよ。カーネーションって赤しかないんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "桃色と、白と、今年は薄い黄も少し入ります" },
		{ kind: "say", speaker: "sub", name: "電話の声(男)", text: "黄色って、なんか、意味ありませんでしたっけ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "花言葉のことでしたら、気にされる方もいます。気にされない方のほうが多いです" },
		{ kind: "say", speaker: "sub", name: "電話の声(男)", text: "気にされる方もいる、か。じゃあ桃で" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "桃で承ります。お名前を——" },
		{ kind: "narration", text: "切って、置いて、三秒。" },
		{ kind: "say", speaker: "sub", name: "電話の声(女)", text: "配達って、坂の上まで行きます?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "大学の坂の上まででしたら、伺えます" },
		{ kind: "say", speaker: "sub", name: "電話の声(女)", text: "じゃあ、坂の途中の、青い屋根の" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "青い屋根" },
		{ kind: "say", speaker: "sub", name: "電話の声(女)", text: "行けば分かりますよ。うち以外、みんな灰色だから" },
		{ kind: "narration", text: "町の住所は、こういう形で伝わってくる。若菜はメモに「坂・青屋根」と書いた。書きながら、自分の字がまた曲がるのを見ていた。" },
		{ kind: "narration", text: "九時、二本目。" },
		{ kind: "say", speaker: "sub", name: "電話の声(若い女)", text: "予算って、いくらから頼めますか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "五百円からお作りします" },
		{ kind: "say", speaker: "sub", name: "電話の声(若い女)", text: "五百円で、束になります?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "三本と、緑を一枚。束と呼んでいいと思います" },
		{ kind: "say", speaker: "sub", name: "電話の声(若い女)", text: "そういうの、頼んでいいのか分からなくて" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "いいです。いちばん多いのは三千円ですが、いちばん少ないのは毎年五百円です" },
		{ kind: "say", speaker: "sub", name: "電話の声(若い女)", text: "毎年あるんですね、五百円" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "あります" },
		{ kind: "narration", text: "十時半、店先の客に緑を足しているところで、また鳴った。" },
		{ kind: "say", speaker: "sub", name: "電話の声(年配の女)", text: "白いのを、五本ほど" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "白のカーネーションでよろしいですか" },
		{ kind: "say", speaker: "sub", name: "電話の声(年配の女)", text: "それが、母の日のでは、ないんですよ。仏さんのほうで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "承知しました。仏花のご用意は、別にしております" },
		{ kind: "say", speaker: "sub", name: "電話の声(年配の女)", text: "同じ日に頼むと、変に思われやしないかと思って" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "思いません。日曜は、両方いちばん出る日です" },
		{ kind: "say", speaker: "sub", name: "電話の声(年配の女)", text: "両方" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "両方です。母上に持っていく方が、いちばん多い日ですから" },
		{ kind: "narration", text: "受話器の向こうで、しばらく間があった。" },
		{ kind: "say", speaker: "sub", name: "電話の声(年配の女)", text: "じゃあ、白を五本。それと、赤も一本、足してもらえます? 私の母は、赤が好きだったので" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "白五本と、赤を一本。承ります" },
		{ kind: "narration", text: "書いてから、色の欄に、線を一本引いて分けた。同じ束の中で、二つの用がある。祖母の帳面にも、そういう行がいくつかあった。" },
		{ kind: "narration", text: "昼前、八重さんが筍を抱えたまま顔を出した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、電話。鳴ってるよ、電話" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "聞こえてます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "聞こえてるのに出ないのかい" },
		{ kind: "say", speaker: "wakana", emo: 12, text: "手が二本しかないんです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんはねえ、肩と耳で挟んで、包丁みたいにリボン切ってたよ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "今それを聞くと、少し、恨みます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あははは。恨みな恨みな" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そういや若菜ちゃん、今年、白は分けたのかい" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "分けました。仏用は、奥の棚に" },
		{ kind: "say", speaker: "sub", name: "八重", text: "えらい。去年の霜月堂んとこの嫁が、間違えて赤の隣から白を取ってったのよ。それでうちのばあさんが、あれは何のつもりだって、三日言ってた" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "三日" },
		{ kind: "say", speaker: "sub", name: "八重", text: "町ってのは、そういうとこだよ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "でもさ、常ちゃんだって最初からできたわけじゃないよ。あたしが見てた頃はね、注文の紙、腕に貼ってた" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "腕に" },
		{ kind: "say", speaker: "sub", name: "八重", text: "テープでね。ここからここまで、って。両腕。あれ見て、ああこの人は本気だと思ったもんだ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "私も貼りましょうか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "やめときな。あれは常ちゃんだから許された恰好だよ" },
		{ kind: "narration", text: "八重さんは筍を抱え直して、自分の店へ帰っていった。若菜は自分の左腕を、一度だけ見た。" },
		{ kind: "narration", text: "午後、店先に立て看板を出しに行った十秒のあいだに、二度鳴った。二度目は、外に出たまま聞いた。硝子の向こうで、勘定台の黒い電話が震えているのが見えた。看板の脚を立て終えてから戻ったが、間に合わなかった。" },
		{ kind: "narration", text: "三時、四本まとめて包む客の前で、また鳴った。" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "失礼します、少しだけ" },
		{ kind: "say", speaker: "sub", name: "客", text: "どうぞどうぞ、こっちはいいから" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花常です" },
		{ kind: "say", speaker: "sub", name: "電話の声", text: "あ、切れちゃったかと思った。日曜の三時って、まだ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "三時、承れます" },
		{ kind: "narration", text: "そのやりとりのあいだ、四本は作業台の上で開きかけていた。包み直しになった。" },
		{ kind: "narration", text: "切ったそばから、また鳴る。三度目の呼び出し音の途中で、先客の会計と重なって、出られなかった。四度目も、出られなかった。" },
		{ kind: "narration", bg: "shop_evening", text: "夕方、電話の横のメモ用紙は、矢印と訂正線だらけになっていた。六時の光が勘定台の角まで届いて、その訂正線を一本ずつ照らしていた。若菜はそれを見つめた。前の職場なら、予約はレジの端末が受けた。ここでは、私が端末だ。そして私は、今日、三回も呼び出し音を取り損ねた端末だった。" },
		{ kind: "narration", text: "閉店間際に、月に一度の客が来た。芍薬はまだ売らない。蕾が固い。レンは店の様子を——電話のメモ用紙の惨状を——入り口から一瞥して、しばらく黙っていた。" },
		{ kind: "say", speaker: "ren", emo: 20, text: "……三隅さん。この電話、日曜まで、あと何回鳴ると思います?" },
		{ kind: "say", speaker: "wakana", emo: 14, text: "……考えたくないです" },
		{ kind: "say", speaker: "ren", emo: 16, text: "ですよね。……ちょっと、考えてみます" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "考えるとは" },
		{ kind: "say", speaker: "ren", emo: 15, text: "まだ言えないです。言うと、できなかったとき恥ずかしいんで" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "できなかったときは、私が三回取り損ねるだけです" },
		{ kind: "say", speaker: "ren", emo: 6, text: "それ、けっこう痛いこと言いますね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "芍薬、今日も固いですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "固いです。今月のぶんは、もう少し待ってください" },
		{ kind: "say", speaker: "ren", emo: 18, text: "待ちます。待つのは得意なんで" },
		{ kind: "narration", text: "戸を閉める音がして、通りの向こうで自転車の錠が鳴った。電話は、それから閉店までに、あと二回鳴った。" },
	],
};

// 解放: ステージ5-2クリア後
const hitoban: Vignette = {
	id: "m5-hitoban",
	kind: "scene",
	month: 5,
	title: "一晩",
	trigger: { at: "stage-clear", stageId: "m5-2" },
	synopsis: "レンが一晩で作ってきたものを前に、母の日の注文の受け方を二人で詰める。",
	choices: [
		{
			id: "B-09",
			label: "注文の受け方",
			axis: "縁",
			options: [
				{ key: "A", label: "全面的に任せる", note: "縁+1" },
				{ key: "B", label: "電話も残す" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "作業場の水音を止めて表に出ると、店の硝子が橙に灼けていた。桶の水面に同じ色が乗って、カーネーションの赤だけが、その色に負けずに赤かった。電話は、この日は八回鳴って、六回出られた。六回は昨日より多い。" },
		{ kind: "narration", text: "翌日の夕方、レンはノートパソコンを抱えて現れた。両手が塞がっていたので、店の戸を肘で開けた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "できました。注文フォーム" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "……できました、とは" },
		{ kind: "narration", text: "勘定台に広げられた画面には、花常の名前と、母の日の受け取り日時を選ぶ欄と、束の予算を選ぶ欄が並んでいた。いちばん下に「おまかせ」の丸いボタンがある。" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "その前に、椅子を出します。立ったままで説明されると、こちらが急かしている形になるので" },
		{ kind: "say", speaker: "ren", emo: 19, text: "そんなん気にします?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "気にします" },
		{ kind: "narration", text: "丸椅子を勘定台の脇から引き出した。祖母が座っていた椅子だ。レンはそれを見て、一拍置いてから、そこには座らず、床に置いたパソコンの前にしゃがんだ。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "俺、しゃがんだほうが打ちやすいんで" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "打ちにくくないですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "打ちにくいです。でも早いんですよ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "上から説明していいですか。まず日にち。十日から十二日まで、一時間ごとの枠にしてあります。枠ごとに受けられる数を入れられるんで、たとえば日曜の午前を二十で止めたかったら、ここに二十って打つと、二十一人目には最初から出ません" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "出ない" },
		{ kind: "say", speaker: "ren", emo: 1, text: "出ないです。埋まった枠は灰色になります。だから『すみません、その時間はもう』って言わなくて済みます" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "それは、いちばん言いたくない台詞です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "でしょ。そこ、いちばん先に作りました" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "枠の数は、私が決めるんですね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "決めてください。俺、一時間に何束作れるか知らないんで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "八束です。包みまで入れて" },
		{ kind: "say", speaker: "ren", emo: 4, text: "即答" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "三年、数えていたので" },
		{ kind: "say", speaker: "ren", emo: 16, text: "じゃあ十時の枠、八にします。いや、六にしましょう。店に来る人が入る余地がないと、まずいですよね" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "まずいです。よく分かりましたね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "昨日、客がずっと待ってたんで" },
		{ kind: "say", speaker: "ren", emo: 1, text: "次、予算。三千、五千、八千、それ以上は自由入力。色は赤・桃・白・おまかせ。備考欄は百文字まで。長いと三隅さんが読むの大変なんで" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "百文字で足りますか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "足りない人は電話してくると思うんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "なるほど" },
		{ kind: "say", speaker: "ren", emo: 16, text: "名前と電話番号は必須。ここが空だと送信できません。送ると、相手にも控えのお知らせが届きます" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "うちの名前で" },
		{ kind: "say", speaker: "ren", emo: 3, text: "あ、文面、勝手に書いちゃったんで、直してください。俺が書くと軽いんで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "読みます" },
		{ kind: "narration", text: "画面をのぞきこむ。四行だけの短い文だった。花常です。ご注文ありがとうございます。当日、店先でお名前をおっしゃってください。花はこちらで用意して待っています。" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "軽くないです。これでいきます" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "昨日、帰ってから作ったんですか" },
		{ kind: "say", speaker: "ren", emo: 17, text: "作りました。二時くらいまで。途中で先輩から通話きて、『大神、お前また花屋いんの』って言われました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花屋にいたわけでは" },
		{ kind: "say", speaker: "ren", emo: 6, text: "いなかったんですけど、画面が花屋だったんで、まあ、いた扱いです" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "ひとつ、伺います" },
		{ kind: "say", speaker: "ren", emo: 5, text: "どうぞ" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "これが動かなくなったとき、注文はどうなりますか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "消えないです。入った注文は、別のところに二重に書き置きされてます。画面が出なくなっても、中身は残る" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "では、いちばん困るのは" },
		{ kind: "say", speaker: "ren", emo: 16, text: "日曜の朝に、新しく入れられなくなることです。もう入ってるぶんは紙にして渡してあるんで、店は回ります。回るように作りました" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "そこまで" },
		{ kind: "say", speaker: "ren", emo: 5, text: "そこまでです。花、腐らせたくないんで" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "腐りません。売れ残っても、飾ります" },
		{ kind: "say", speaker: "ren", emo: 13, text: "あ、そっか。そうか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "電話だと、三隅さんの手が止まるんで。これなら寝てるあいだに注文が入ります。二次元コードも刷ってきました。店先に貼っといてください" },
		// 【B-09=A】
		{ kind: "say", speaker: "wakana", emo: 18, when: { choice: "B-09", is: "A" }, text: "……分かりました。母の日の予約は、これに一本化します。任せます" },
		{ kind: "say", speaker: "ren", emo: 4, when: { choice: "B-09", is: "A" }, text: "え、いいんですか。そんなあっさり" },
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-09", is: "A" }, text: "作った人が『寝てるあいだに』と言うなら、寝てるあいだに入るんでしょう。私は花のほうを見ます" },
		{ kind: "say", speaker: "ren", emo: 1, when: { choice: "B-09", is: "A" }, text: "じゃあ、電話は留守番にして、フォームに案内する音声を入れときます。俺の声だと客が引くんで、三隅さんが吹き込んでください" },
		{ kind: "say", speaker: "wakana", emo: 11, when: { choice: "B-09", is: "A" }, text: "私の声も、たいがい硬いですが" },
		{ kind: "say", speaker: "ren", emo: 2, when: { choice: "B-09", is: "A" }, text: "硬いのがいいんです。花屋っぽくないけど、花常っぽい" },
		{ kind: "say", speaker: "wakana", emo: 19, when: { choice: "B-09", is: "A" }, text: "褒められているのか、判断がつきません" },
		{ kind: "say", speaker: "ren", emo: 16, when: { choice: "B-09", is: "A" }, text: "あと、これ。日曜の朝、注文の一覧を一枚に印刷して持ってきます。三隅さんが画面を見る時間、たぶんゼロにしたほうがいいんで" },
		{ kind: "say", speaker: "wakana", emo: 3, when: { choice: "B-09", is: "A" }, text: "せっかく作ったのに、見ないんですか" },
		{ kind: "say", speaker: "ren", emo: 18, when: { choice: "B-09", is: "A" }, text: "作ったやつを見なくて済むのが、いちばんいい出来なんですよ" },
		{ kind: "say", speaker: "ren", emo: 16, when: { choice: "B-09", is: "A" }, text: "責任重大だ。落ちたら走ってくるんで、ほんとに" },
		// 【B-09=B】
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-09", is: "B" }, text: "……使います。ただ、電話も残します。声で頼みたい人が、この町にはまだ多いので" },
		{ kind: "say", speaker: "ren", emo: 1, when: { choice: "B-09", is: "B" }, text: "あー、たしかに。じゃあ、フォームの注文一覧に、電話受けのぶんも手で足せる欄、作っときます。一枚の紙に全部並ぶように" },
		{ kind: "say", speaker: "wakana", emo: 9, when: { choice: "B-09", is: "B" }, text: "それは、助かります" },
		{ kind: "say", speaker: "ren", emo: 1, when: { choice: "B-09", is: "B" }, text: "あと、電話受けの紙、これ使ってください。名前、番号、時間、色、予算。フォームと並び順を同じにしときました" },
		{ kind: "say", speaker: "wakana", emo: 8, when: { choice: "B-09", is: "B" }, text: "同じ並び" },
		{ kind: "say", speaker: "ren", emo: 1, when: { choice: "B-09", is: "B" }, text: "そうです。人間って、書式が二種類あると必ず片方を見落とすんで" },
		{ kind: "say", speaker: "wakana", emo: 15, when: { choice: "B-09", is: "B" }, text: "経験談ですか" },
		{ kind: "say", speaker: "ren", emo: 6, when: { choice: "B-09", is: "B" }, text: "サークルの当番表で、一回やらかしました。三人ぶん飛ばしました" },
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-09", is: "B" }, text: "その紙、電話のすぐ横に置きます。取りに行く距離があると、私は書きません" },
		{ kind: "say", speaker: "ren", emo: 2, when: { choice: "B-09", is: "B" }, text: "分かってるじゃないですか" },
		{ kind: "say", speaker: "wakana", emo: 12, when: { choice: "B-09", is: "B" }, text: "三日で分かりました" },
		{ kind: "say", speaker: "ren", emo: 18, when: { choice: "B-09", is: "B" }, text: "ハイブリッド運用ってやつです。かっこいいでしょ" },
		// 【合流】
		{ kind: "say", speaker: "wakana", emo: 6, text: "一晩で、これを" },
		{ kind: "say", speaker: "ren", emo: 6, text: "サーバーは——同好会のを使うと先輩に怒られるんで、俺の自宅のやつです。タダです。落ちたら俺のせいです" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "落ちたら、うちはどうすれば" },
		{ kind: "say", speaker: "ren", emo: 5, text: "俺が走ってきます" },
		{ kind: "narration", text: "冗談の顔ではなかった。若菜は二次元コードの紙を受け取って、店先のガラスに、曲がらないように貼った。貼ってから、一歩下がって眺めた。祖母の店に、四角い模様がひとつ増えた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あ、その紙、雨降ると滲みます。透明のテープ、上から貼っといてください。四辺全部" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "テープなら、あります" },
		{ kind: "narration", text: "勘定台の抽斗から出したテープは、祖母が使っていたものだった。端が黄ばんで、切り口が斜めに歪んでいる。若菜はそれを引き出して、四角い紙の上を、四辺、順に塞いだ。" },
		{ kind: "narration", text: "貼り終えた頃、通りを歩いていた誰かが足を止めて、硝子の紙を覗きこんだ。携帯を構えて、また歩いていった。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "入りました。今の人、たぶん入りました" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "見て分かるんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "分かるんですよ。ここ、今、一件って出てるんで" },
		{ kind: "narration", text: "画面の隅に、小さな数字が「1」と出ていた。押しても消えなかった。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "どなたですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "木下さん。日曜の十時、赤、大きめ" },
		{ kind: "narration", text: "若菜は勘定台の帳面を開いて、その名前を書いた。祖母の五月の頁のいちばん上にも、同じ名字があった。書いてから、少しのあいだ、二つの頁を並べて置いていた。" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "……お代を" },
		{ kind: "say", speaker: "ren", emo: 15, text: "今月のぶんの芍薬、いちばんいい蕾のやつ。それでチャラです" },
		{ kind: "say", speaker: "wakana", emo: 12, text: "蕾の良し悪しは、まだ私には分からないんですけど" },
		{ kind: "say", speaker: "ren", emo: 18, text: "じゃあ、分かるようになった頃に、いちばんいいやつで" },
		{ kind: "narration", text: "ツケにしては、気の長い話だった。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "もう一つ。これは、母の日が終わったら消えますか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "消しません。日にちの設定変えるだけで、来月も使えます。父の日でも、お盆でも" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "盆の仏花を、この画面で頼む人がいますか" },
		{ kind: "say", speaker: "ren", emo: 19, text: "あー、それはちょっと違いますね。仏花は電話のほうが合ってる気がするんで。なんとなくですけど" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "私も、そう思います" },
		{ kind: "say", speaker: "ren", emo: 16, text: "じゃあ、そこは電話で。全部を機械にしなくていいんです。手が止まるところだけでいいんで" },
		{ kind: "say", speaker: "wakana", emo: 6, text: "そういう作り方を、なんと言うんですか" },
		{ kind: "say", speaker: "ren", emo: 15, text: "特に名前ないです。ふつうです" },
		{ kind: "narration", text: "その晩、店を閉めてから、若菜は自分の携帯でフォームを開いてみた。自分の店の名前が、画面のいちばん上に黒い字で出ていた。日にちの欄を押すと、十日から十二日までの枠が並んで、どれもまだ白かった。" },
		{ kind: "narration", text: "試しに、いちばん端の枠を押してみた。灰色になった。慌てて戻した。白に戻った。" },
		{ kind: "narration", text: "戻ることは、確かめておいたほうがいい。" },
		{ kind: "narration", text: "十一時を過ぎて、画面の数字が「2」になった。名前は知らない人だった。日曜の午後二時、桃、五千円、備考欄に一行。「母が去年入院したので、今年は行きます」。" },
		{ kind: "narration", text: "若菜は帳面を開いて、その名前と、その一行をそのまま写した。備考は数字ではないので、本当は写さなくていい。写した。" },
		{ kind: "narration", text: "祖母の頁の、名前の下の線。あれが何なのか、まだ分からない。分からないまま、自分の頁の下にも、一本引いてみた。" },
	],
};

// 解放: ステージ5-3クリア後
const hahaNoHi: Vignette = {
	id: "m5-haha-no-hi",
	kind: "scene",
	month: 5,
	title: "母の日",
	trigger: { at: "stage-clear", stageId: "m5-3" },
	synopsis: "母の日の当日。開店前から人が並び、八重さんが売り子に入り、レンが配達に走る。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "夜のうちに雨が降って、朝には上がっていた。通りの敷石がまだ濡れていて、そこに店の灯りが四角く落ちている。作業場の戸を開けると、昨夜のうちに開かせた芍薬が、白い頭を揃えて待っていた。" },
		{ kind: "narration", text: "芍薬の茎を落とすとき、若菜は壁の釘のほうを見なかった。" },
		{ kind: "narration", text: "第二日曜の朝は、開店前から人が立っていた。" },
		{ kind: "narration", text: "六時四十分。札を出すのは七時と決めている。硝子越しに、傘を畳んだままの男性と、自転車を押した女子高生と、犬を連れた誰かが見えた。若菜は戸を開けた。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "どうぞ。まだ札が出ていませんが、やっています" },
		{ kind: "say", speaker: "sub", name: "男性客", text: "助かった。九時の新幹線なんです" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、九時に間に合う包み方にします。膝の上で立てて持てるように" },
		{ kind: "narration", text: "七時十分、八重さんが前掛けのまま入ってきた。まるはちの札はまだ出ていない。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "開けたのかい、もう" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "立っていたので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃ開けるわ。で、あたしはどこに立てばいい" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "八重さん、お店は" },
		{ kind: "say", speaker: "sub", name: "八重", text: "筍は逃げないよ。花は逃げるだろ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、勘定台をお願いします。私が包みます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "金だけ数えろって?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "いちばん間違えてはいけないところです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "上手いこと言うね。常ちゃんもそれ言ったよ" },
		{ kind: "narration", text: "フォームの注文が三十一件。店頭が、たぶんその倍。作業台の上をリボンが飛び、冷蔵ケースは昼前に一度空になりかけた。八重さんが前掛けのまま乗り込んできて、勝手に売り子を始めた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "はい、赤いの三本ね! 若菜ちゃん、こっち桃色あと二本!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "二本、出します" },
		{ kind: "say", speaker: "sub", name: "八重", text: "この人、うちで筍買ったついでにこっち来たんだよ。ついでで悪いって言うから、ついでで上等だって言っといた" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "ついでで上等です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "ほらね" },
		{ kind: "say", speaker: "sub", name: "客", text: "じゃあ、桃色を" },
		{ kind: "narration", text: "八時を回ると、店の中で人が向きを変えられなくなった。八重さんが「並んで、並んで」と通りに列を作り、その列がまるはちの前まで伸びた。まるはちの筍は、列の人が勝手に見ていった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、これ、うちの筍が売れてくよ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "よかったです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "よかないよ。あたし、今こっちにいるんだから、誰も金を取ってないんだよ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "取りに行ってください" },
		{ kind: "say", speaker: "sub", name: "八重", text: "行ってくる!" },
		{ kind: "narration", text: "八重さんは十分で戻ってきた。前掛けの物入れが、少し重そうになっていた。" },
		{ kind: "narration", text: "カーネーションの箱を開けるたび、胡椒に似た青い匂いが立った。それを束ね、包み、渡す。渡した先の客の顔を見る余裕は、昼までなかった。" },
		{ kind: "narration", text: "九時半、若い夫婦が二人で入ってきて、桶の前で三分ほど動かなかった。" },
		{ kind: "say", speaker: "sub", name: "妻", text: "大きいほうがいいって、絶対" },
		{ kind: "say", speaker: "sub", name: "夫", text: "うちの母、大きいと『こんなに』って言うんだよ" },
		{ kind: "say", speaker: "sub", name: "妻", text: "褒めてるんじゃないの、それ" },
		{ kind: "say", speaker: "sub", name: "夫", text: "怒られてるんだよ、あれは" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、本数は控えて、丈を長くしましょう" },
		{ kind: "say", speaker: "sub", name: "夫", text: "丈" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "同じ値段でも、丈が長いと、玄関に置いたとき大きく見えます。花瓶に挿すと、そこまで大げさにはなりません" },
		{ kind: "say", speaker: "sub", name: "妻", text: "……それ、すごい技じゃないですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "毎年この日に、同じ相談を受けます" },
		{ kind: "narration", text: "包み終えた束を、夫のほうが受け取った。妻が横から一度だけ、リボンの位置を直した。" },
		{ kind: "narration", text: "配達は、自転車のレンだった。" },
		{ kind: "say", speaker: "ren", emo: 8, text: "三件目、行ってきます! 坂の上の二件は任せてください、地元なんで!" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "地元って、坂の上はあなたの家では" },
		{ kind: "say", speaker: "ren", emo: 2, text: "だから道に詳しいんです!" },
		{ kind: "narration", text: "十一時、レンが一度戻ってきて、水を一杯飲んで、また出ていこうとした。" },
		{ kind: "say", speaker: "ren", emo: 8, text: "坂の上、二件終わりました! 次、三丁目です!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "保冷剤、入れましたか" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "入れてください" },
		{ kind: "say", speaker: "ren", emo: 16, text: "入れます!" },
		{ kind: "narration", text: "籠に保冷剤が二つ落ちる音がして、錠の音がして、車輪の音が遠ざかった。" },
		{ kind: "narration", text: "昼前に、小学生くらいの男の子が、握った小銭を勘定台に置いた。" },
		{ kind: "say", speaker: "sub", name: "少年", text: "三百円で、買えるやつ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "あります" },
		{ kind: "narration", text: "カーネーションを一本、緑を一枚添えて、紙で細く巻いた。リボンは赤にした。" },
		{ kind: "say", speaker: "sub", name: "少年", text: "リボンって、お金かかる?" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "今日はかかりません" },
		{ kind: "say", speaker: "sub", name: "少年", text: "なんで" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "今日だからです" },
		{ kind: "narration", text: "男の子は花を垂直に持って、走らずに帰っていった。走ると折れる、と横から教えたのは八重さんだった。" },
		{ kind: "narration", text: "十二時半、白髪の紳士が、列の切れ目に入ってきた。" },
		{ kind: "say", speaker: "sub", name: "老紳士", text: "家内が毎年、自分の母親に送っとったんですがね。今年は入院しとるもんで、私が" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、奥様がいつも選ばれていた色を" },
		{ kind: "say", speaker: "sub", name: "老紳士", text: "それが、分からんのです。勝手が分からんので、いちばん普通のをください" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "いちばん普通のを、少しだけ多めにします" },
		{ kind: "say", speaker: "sub", name: "老紳士", text: "多めに" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "二人ぶんですので" },
		{ kind: "narration", text: "紳士は札を出しながら、しばらく束のほうを見ていた。それから、花を胸の前で抱えて出ていった。" },
		{ kind: "narration", text: "一時過ぎ、三度目に戻ってきたレンは、前髪が全部後ろに流れていた。" },
		{ kind: "say", speaker: "ren", emo: 17, text: "坂、下るとき速いんですよ。上るときが人生です" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "水を飲んでください" },
		{ kind: "say", speaker: "ren", emo: 1, text: "飲みます。あと、三丁目の奥さんが、これ持ってけって" },
		{ kind: "narration", text: "勘定台に、包装紙のままの柏餅が二つ置かれた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "霜月堂のじゃないか。あそこ、今日は行列だったよ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "行列、抜かしてないです。もらっただけです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "誰も疑ってないよ" },
		{ kind: "say", speaker: "ren", emo: 19, text: "あと、フォームの十四番の人、留守でした。置いてきていいか分かんなかったんで、持って帰ってきました" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "正解です。花は置いてきません。傷むのと、濡れるのと、持っていかれるのと、三つあるので" },
		{ kind: "say", speaker: "ren", emo: 4, text: "三つもあるんですか" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "三つ目がいちばん多いです" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……人間って" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "夕方、もう一度行ってください。それでも留守なら、明日の朝の水に立て直して、また行きます" },
		{ kind: "say", speaker: "ren", emo: 16, text: "了解です。二度目は速いんで、坂も覚えたし" },
		{ kind: "narration", text: "昼過ぎ、列が一度短くなって、また伸びた。その後ろのほうに、春先に卒業したばかりの顔があった。四月に初任給の花を買っていった青年だ。順番が来ると、彼は少し照れながら言った。" },
		{ kind: "say", speaker: "sub", name: "春野", text: "母には、先月あげたんで……今日は、祖母に。先月の、母のやつを、ばあちゃんが横で、じーっと見てたらしくて" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、お祖母様には、少し明るすぎるくらいの色にしましょう" },
		{ kind: "say", speaker: "sub", name: "春野", text: "明るすぎるくらい" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "じーっと見てた方には、それくらいでちょうどです" },
		{ kind: "say", speaker: "sub", name: "春野", text: "あの、これ、ばあちゃん、名前で呼んでくれますかね。花の名前" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "カーネーションは、たぶん" },
		{ kind: "say", speaker: "sub", name: "春野", text: "ですよね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花の名前を書いた札を、一枚挿しておきます。読める大きさで" },
		{ kind: "say", speaker: "sub", name: "春野", text: "それ、助かります。ばあちゃん、老眼なんで" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、大きく書きます" },
		{ kind: "say", speaker: "sub", name: "春野", text: "あの、去年までは、花屋って入りにくかったんですよ。何を言えばいいか分かんなくて" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "今も、分からないですか" },
		{ kind: "say", speaker: "sub", name: "春野", text: "今は、ばあちゃんに、って言えば済むって分かったんで" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "それだけで足ります。あとはこちらで考えます" },
		{ kind: "say", speaker: "sub", name: "春野", text: "考えてくれるんですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "それが仕事です" },
		{ kind: "narration", text: "札に太い字で書いて、束の中央に、正面を向けて挿した。青年は札のほうを何度か確かめてから、両手で受け取った。" },
		{ kind: "narration", text: "二時の枠の客が来た。桃、五千円。備考の一行を書いた人だ。若菜は名前を呼んだ。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "お待ちしていました。二時のご予約で" },
		{ kind: "say", speaker: "sub", name: "客", text: "あ、名前で来るんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "書いてありましたので" },
		{ kind: "narration", text: "束は、朝のうちに作って冷やしておいた。渡すとき、客は両手を出した。" },
		{ kind: "say", speaker: "sub", name: "客", text: "これ、病室に持ってっていいのかな。だめなとこもあるって聞いて" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "先に伺ってください。だめでしたら、ご自宅に。退院の日に玄関へ、という方も多いです" },
		{ kind: "say", speaker: "sub", name: "客", text: "それでも、いいんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "日付が過ぎても、花は花です。今日でなくてもいい花のほうが、うちは多いくらいです" },
		{ kind: "narration", text: "客は束を胸の高さで抱えて、通りを駅のほうへ歩いていった。" },
		{ kind: "narration", text: "三時、制服の女子が三人で入ってきて、桶の前で相談を始めた。相談は長く、結論は早かった。" },
		{ kind: "say", speaker: "sub", name: "女子A", text: "三人で一個にしよ。同じ家じゃないけど" },
		{ kind: "say", speaker: "sub", name: "女子B", text: "同じ家じゃないのに一個?" },
		{ kind: "say", speaker: "sub", name: "女子A", text: "バラして持って帰ればいいじゃん" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "それでしたら、三本ずつ別に包みます。同じ紙で" },
		{ kind: "say", speaker: "sub", name: "女子C", text: "別々にできるんですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "同じ束を三つに分けるのと、同じ紙で三つ作るのは、値段がほとんど変わりません" },
		{ kind: "say", speaker: "sub", name: "女子A", text: "じゃあそれで。同じ紙がいい" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "同じ紙にします" },
		{ kind: "narration", text: "三つ並べて包んで、リボンだけ、三本とも色を変えた。誰も色の話はしなかったが、三人とも自分のぶんを間違えずに取った。" },
		{ kind: "narration", text: "四時を過ぎて、赤が尽きた。桃と白と、市場で保険に買っておいた薄黄が残った。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "赤がないって言うとさ、みんな一回、がっかりした顔するね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "します" },
		{ kind: "say", speaker: "sub", name: "八重", text: "でも、桃色持って帰る顔は、赤持って帰る顔と同じだよ。あたし今日、二百回見たから分かる" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "八重さんが数えていたのは、そこですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そこだよ。花の数は若菜ちゃんが数えるだろ" },
		{ kind: "narration", text: "五時、レンが十四番の束を持って戻ってきた。籠は空だった。" },
		{ kind: "say", speaker: "ren", emo: 13, text: "渡しました。おばあちゃん、昼寝してたらしいです。すみませんすみませんって、三回言われました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "三回" },
		{ kind: "say", speaker: "ren", emo: 6, text: "四回かも。数えてないです" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "数えなくていいです" },
		{ kind: "narration", text: "夕方六時、最後の予約の束が出て、店は急に静かになった。八重さんは「上がり!」と言って自分の店に帰り、レンは自転車ごと、角をひとつ曲がって夕日に溶けた。" },
		{ kind: "narration", text: "ケースの中には、カーネーションが四本だけ残っていた。" },
		{ kind: "narration", text: "八重さんが一度戻ってきて、勘定台の釣り銭を数え直してから帰った。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "四本、残ったね" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "四本です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんの年は、いっつも一本も残さなかったよ。あの人、六時過ぎたら通りに出てって、歩いてる人に押しつけてたから" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "押しつけて" },
		{ kind: "say", speaker: "sub", name: "八重", text: "『持ってきな』ってさ。金も取らないんだよ。あれで年に何回か、あたし本気で叱ったね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "怒られる側の気持ちが、少し分かります" },
		{ kind: "say", speaker: "sub", name: "八重", text: "今ので分かるのかい" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "今、少し、外に出たくなりました" },
		{ kind: "say", speaker: "sub", name: "八重", text: "ほらね。血だよ、血" },
		{ kind: "narration", text: "八重さんは笑って、まるはちの明かりを消しに行った。" },
		{ kind: "narration", text: "若菜は四本を抜いて、見切り籠に移した。籠の札には「今日のうちに飾る花」と書いてある。母の日の夜に、この籠に赤が入るとは思っていなかった。" },
		{ kind: "narration", text: "戸締まりの前に、電話の横のメモ用紙を見た。訂正線が、一本もなかった。" },
		{ kind: "narration", text: "作業台を拭き、床の切れ端を掃き集めた。葉と茎の屑で、竹箒の先が青く染まっている。桶を六つとも洗い、逆さに立てて並べたところで、店の灯りを落とした。" },
		{ kind: "narration", text: "硝子の外の四角い紙が、通りの街灯を受けて、白く光っていた。" },
		{ kind: "narration", text: "戸に錠を下ろしてから、若菜はもう一度、中を覗いた。籠の赤が四本、暗がりで色を失わずにいた。" },
	],
};

// 解放: 五月の全ステージクリア後・前半
const denpyou: Vignette = {
	id: "m5-denpyou",
	kind: "scene",
	month: 5,
	title: "伝票",
	trigger: { at: "month-close", month: 5 },
	synopsis: "翌日、レンが宅配の伝票を持ってくる。冷蔵便で花を送るための箱詰めを教える。",
	choices: [
		{
			id: "B-10",
			label: "伝票の宛先",
			axis: "問い",
			options: [
				{ key: "A", label: "尋ねる", note: "問い+1" },
				{ key: "B", label: "何も言わずに包む" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_day", text: "翌日の昼、通りは元の速度に戻っていた。桶は三つに減って、床が広い。硝子に貼った四角い紙が、テープの下で少しだけ反っていた。" },
		{ kind: "narration", text: "レンが宅配の伝票を持って現れた。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "すみません、これ、書き方これで合ってます? 冷蔵便のやつ" },
		{ kind: "narration", text: "伝票は店のものではなく、折り目が一つついていた。" },
		{ kind: "narration", text: "伝票の品名欄には「カーネーション(花束)」、お届け先には、長野県の住所と——大神志乃、の字。丁寧に書こうとして、途中から急いだ字だった。" },
		// 【B-10=A】
		{ kind: "say", speaker: "wakana", emo: 10, when: { choice: "B-10", is: "A" }, text: "……合ってます。お母様に?" },
		{ kind: "say", speaker: "ren", emo: 6, when: { choice: "B-10", is: "A" }, text: "まあ、はい。母の日、過ぎちゃいましたけど。当日は配達で走り回ってたんで、自分のは後回しっていうか" },
		{ kind: "say", speaker: "wakana", emo: 21, when: { choice: "B-10", is: "A" }, text: "お母様、待ってたと思いますよ。今も" },
		{ kind: "say", speaker: "ren", emo: 15, when: { choice: "B-10", is: "A" }, text: "いや、どうかな。……どうかな" },
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-10", is: "A" }, text: "日付が過ぎた花を、日付のせいで受け取らない人はいません" },
		{ kind: "say", speaker: "ren", emo: 19, when: { choice: "B-10", is: "A" }, text: "そういうもんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-10", is: "A" }, text: "そういうものです。うちは十三日にも十四日にも束を作ります" },
		// 【B-10=B】
		{ kind: "say", speaker: "wakana", emo: 4, when: { choice: "B-10", is: "B" }, text: "……合ってます。冷蔵便はこの欄に丸を" },
		{ kind: "narration", when: { choice: "B-10", is: "B" }, text: "宛先の字は、目に入ってしまった。長野県。大神志乃様。見なかったことにするには、少し遅かったが、口には出さないことにした。聞けば答えてくれるのだろう。聞かないでいる方を、今日は選んだ。" },
		{ kind: "say", speaker: "ren", emo: 19, when: { choice: "B-10", is: "B" }, text: "助かります。これ、ちゃんと届きますよね? 花って、崩れたりとか" },
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-10", is: "B" }, text: "崩れないように包むのが、うちの仕事です" },
		{ kind: "say", speaker: "ren", emo: 4, when: { choice: "B-10", is: "B" }, text: "言い切りましたね" },
		{ kind: "say", speaker: "wakana", emo: 16, when: { choice: "B-10", is: "B" }, text: "ここは言い切るところです" },
		// 【合流】
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、いくらかかります? 箱代とか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "箱は市場のを使い回します。中の綿と紙で、三十円ほど" },
		{ kind: "say", speaker: "ren", emo: 4, text: "三十円" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "取りません。包むところまでが花代です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "そういうの、ちゃんと取ったほうがいいですよ。俺、フォームに『梱包代』の欄、足しときますけど" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "足さなくていいです" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんでですか" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "祖母の帳面に、その欄がないので" },
		{ kind: "say", speaker: "ren", emo: 19, text: "それ、理由になってます?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "今年は、なっています" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "箱を出します。冷蔵便なら、これで足ります" },
		{ kind: "narration", text: "奥から出した箱は、市場から花が来るときの箱と同じ形をしている。底に新聞紙を敷き、湿らせた綿を茎の先に巻いて、その上から薄い袋で留める。花の首が箱の中で動かないように、細く切った紙で三か所、渡しをかける。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "花って、そんなに縛るんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "揺れると、こすれます。こすれた花びらは、着いた先で茶色くなります" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー。輸送中の振動、ってことですね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "そういう言い方をされると、急に機械の話みたいですね" },
		{ kind: "say", speaker: "ren", emo: 2, text: "機械の話です。壊れないように運ぶ話は、だいたい全部おんなじなんで" },
		{ kind: "say", speaker: "ren", emo: 19, text: "あの、聞いていいですか。この綿のやつ、なんで湿らせるんですか。濡れてたら腐りません?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "切り口は、水の中にいると思っていたいんです。空気に触れた瞬間から、吸う口が塞がりはじめます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "塞がる" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "塞がります。だから水中で切ります。水切り、と言います" },
		{ kind: "say", speaker: "ren", emo: 20, text: "水切り" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "覚えなくていいです。送る側の仕事なので" },
		{ kind: "say", speaker: "ren", emo: 16, text: "覚えます。名前がついてるものは覚えとくと得なんで" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "得な場面が、あるといいですね" },
		{ kind: "say", speaker: "ren", emo: 18, text: "ありますよ。今" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "これで、長野まで一日半" },
		{ kind: "say", speaker: "ren", emo: 20, text: "一日半" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "着いたら、すぐ水に。切り口を一センチ、水の中で切り直してくださいと、紙に書いて入れます" },
		{ kind: "say", speaker: "ren", emo: 15, text: "それ、俺が書くより、三隅さんの字のほうがいいですよ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "なぜ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "花屋の字だから、言うこと聞くと思うんで" },
		{ kind: "narration", text: "若菜は短冊ほどの紙に、一行書いた。書いてから、下に「花常」と足した。足してから、少し迷って、消さなかった。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "店の名前、入れるんですね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "入れます。困ったときに、どこに聞けばいいか分かるので" },
		{ kind: "say", speaker: "ren", emo: 6, text: "長野から電話くるかもしれないですよ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "かかってきたら、出ます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "うちの母、かけますよ、ほんとに" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "では、出ます" },
		{ kind: "narration", text: "箱には、昨日の売れ残りではない、今朝の市場で若菜が選び直した赤が詰められた。レンは伝票を三回読み直してから、箱に貼った。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "三回、読みました" },
		{ kind: "say", speaker: "ren", emo: 6, text: "番地、一個間違えると山に行くんで" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "山に" },
		{ kind: "say", speaker: "ren", emo: 1, text: "うち、番地の隣が全部山なんですよ。郵便屋さんが強いんで、たいてい着くんですけど" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "送り状の控えは、こちらで預かります。番号を控えておけば、途中で止まっても追えます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "止まるんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "年に一度か二度。雪と、盆と、正月です" },
		{ kind: "say", speaker: "ren", emo: 13, text: "五月は安全ですね" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "五月は安全です" },
		{ kind: "narration", text: "それから、いつものように店の桶を一周して、芍薬の前で止まった。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、これ、開きはじめてる" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今朝からです。今月のぶん、持っていきますか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "持っていきます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、開くとどのくらいになるんですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "手のひらを広げたくらいです。人によっては、顔くらいと言います" },
		{ kind: "say", speaker: "ren", emo: 4, text: "顔" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "大きい人が、そう言います" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、何日もちます?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "一週間。水を毎日替えて、切り直せば、もう少し" },
		{ kind: "say", speaker: "ren", emo: 19, text: "毎日ですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "毎日です" },
		{ kind: "say", speaker: "ren", emo: 6, text: "俺、たぶん、三日に一回です" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "三日に一回でも、替えない人よりは長くもちます" },
		{ kind: "say", speaker: "ren", emo: 19, text: "そこ、怒らないんですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "怒る場面ではないです。替えないまま捨てる人には、言います" },
		{ kind: "say", speaker: "ren", emo: 5, text: "捨てないですよ、俺" },
		{ kind: "narration", text: "若菜は手を止めた。止めてから、何も聞かずに、新聞紙を一枚引き寄せた。" },
		{ kind: "narration", text: "芍薬のいちばん固い蕾を、若菜は選んだ。分からないなりに、二十個の中でいちばん重い音がした気がする蕾だった。新聞紙を斜めに、一巻き。" },
		{ kind: "narration", text: "カーネーションの箱と、芍薬の一輪。レンは両方を自転車の籠に立てて、坂を上っていった。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "箱は横にしないでください" },
		{ kind: "say", speaker: "ren", emo: 15, text: "立てます。坂も立てて上ります" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "押して上ってください" },
		{ kind: "say", speaker: "ren", emo: 2, text: "押して上ります!" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "(……カーネーションとは、別に、一輪)" },
	],
};

// 解放: 五月の全ステージクリア後・中盤
const naganoDenwa: Vignette = {
	id: "m5-nagano-denwa",
	kind: "scene",
	month: 5,
	title: "長野からの電話",
	trigger: { at: "month-close", month: 5 },
	synopsis: "レンが五月の集計を持ってくる。かかってきた電話で、若菜は受話器を代わることになる。",
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "三日後の夕方、レンが紙を一枚持って現れた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "フォームの五月ぶん、集計しときました。時間帯ごとの件数と、色の内訳。来年これ見ると、たぶん仕入れが決めやすいですよ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "来年" },
		{ kind: "say", speaker: "ren", emo: 18, text: "来年もやるでしょ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "やります" },
		{ kind: "narration", text: "紙には、棒の長さで件数が描いてあった。日曜の午前十時の欄がいちばん長く、次が土曜の夕方だった。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "十時に、人が集まるんですね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "そうです。で、その時間だけ枠を厚くすると、たぶん列が短くなります。あと、赤が十一時前に半分減ってるんで、来年は仕入れを二回に割ってもいいかも" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "その紙、抽斗に入れておきます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "抽斗じゃなくて、帳面に挟んどいてください。抽斗のものって、二度と出てこないんで" },
		{ kind: "narration", text: "若菜が紙を持ち直したとき、勘定台の向こうで軽い音楽が鳴った。レンが慌てて携帯を取り出し、画面を見て、表情を止めた。" },
		{ kind: "say", speaker: "ren", emo: 15, text: "あ、母です。すいません、外出ます" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "そのままでどうぞ。今、客がいません" },
		{ kind: "narration", text: "レンは背を向けて、耳に当てた。桶の水を落とす音の合間に、細い声が漏れた。よく通る、少し高い声だった。" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "漣。お布団干しなさいよ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "花の話じゃないんかい" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "花はもう水に挿したよ。冷たいのが届いて、びっくりして" },
		{ kind: "say", speaker: "ren", emo: 1, text: "冷蔵便で送ったんで" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "箱に紙が入ってたでしょう。あれ、あんたの字じゃないね" },
		{ kind: "say", speaker: "ren", emo: 3, text: "店の人が書いてくれたんだよ" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "代わって" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "代わって" },
		{ kind: "narration", text: "レンは携帯を持ったまま、二歩戻ってきた。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あの、代われって言ってるんですけど。断っていいですよ、ほんとに" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "断る理由がないです" },
		{ kind: "narration", text: "手を拭いて、受け取った。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "お電話代わりました。花常です" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "まあ、突然すみません。大神の母です。花、ありがとうございました。切り直しの紙、あれ、助かりました。私、花のことは何も知らないもので" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "一センチで足ります。深く切りすぎると、かえって水を吸いません" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "一センチ。書いときます" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "息子が、そちらにご迷惑をおかけしていませんか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "配達を手伝っていただきました。坂を、押して上ってくれました" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "押して。……あの子が" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "速かったです" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "こっちにいた頃はね、花なんて、庭に咲いてても見もしない子でしたよ。裏の畑が花畑になってても、通り抜けるだけで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "そうですか" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "それが、東京に行ってから、母の日だなんだって。なにか、いいことでもあったんでしょうかね" },
		{ kind: "narration", text: "若菜は、他人の携帯を、少し持ち直した。作業場のほうで、レンが桶を洗う音を、わざと大きく立てていた。" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "いいことが、あったんだと思います" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "ふふ。じゃあ、それで" },
		{ kind: "say", speaker: "sub", name: "志乃", text: "漣に、布団を干せと、もう一度言っておいてください" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "お伝えします" },
		{ kind: "narration", text: "携帯を返すと、レンは受け取って、耳に当てずに切った。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "なに言われました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "布団を干せ、と" },
		{ kind: "say", speaker: "ren", emo: 19, text: "それだけ?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "それだけです" },
		{ kind: "narration", text: "嘘ではない。ほかにも聞いた。伝えたのは、布団のぶんだけだった。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "干します。今日は無理ですけど" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "今日は、もう暗いです" },
		{ kind: "say", speaker: "ren", emo: 15, text: "暗いと乾かないんですよね。知ってます" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "知っているのに、干していないんですね" },
		{ kind: "say", speaker: "ren", emo: 15, text: "知ってるのと、やるのは別なんですよ。三隅さんもあるでしょ、そういうの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "あります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "即答ですね" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "爪で弾いて、音のいい蕾を選べ、と教わっています" },
		{ kind: "say", speaker: "ren", emo: 19, text: "教わってるのに" },
		{ kind: "say", speaker: "wakana", emo: 5, text: "聞こえません。二十個、全部同じ音です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ、二百個弾けば違いが出るかもしれません。数が要るやつって、たいていそうなんで" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "二百" },
		{ kind: "say", speaker: "ren", emo: 15, text: "来年までに二百。俺、数えときましょうか" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "自分で数えます" },
		{ kind: "narration", text: "戸口の外で、通りの灯りがひとつずつ点いた。レンは自転車の錠を外して、坂のほうを向いた。芍薬は、もう籠にない。今月のぶんは、三日前に出ていった。" },
	],
};

// 解放: 五月の全ステージクリア後・後半
const chomen0531: Vignette = {
	id: "m5-chomen-0531",
	kind: "chomen",
	month: 5,
	title: "五月三十一日",
	trigger: { at: "month-close", month: 5 },
	synopsis: "五月末の帳面。開店以来いちばんの数字と、帳面に書いた名前の数を数える。",
	lines: [
		{ kind: "diary", text: "五月三十一日。晴れ。" },
		{ kind: "diary", text: "五月の集計。開店以来、いちばんの数字になった。フォーム経由、三十一件。電話の取り損ね、日曜はゼロ。" },
		{ kind: "diary", text: "帳面に書いた名前は、四十一。祖母の五月の頁は、数えたら六十八あった。まだ二十七、足りない。" },
		{ kind: "diary", text: "足りない、と書くのは目印のつもりだ。来年の五月に、この行を見返す。" },
		{ kind: "diary", text: "八重さんの売り子は、私より上手だった。「まるはちの仕事より向いてる」と本人が言うので、来年も頼むことにする。" },
		{ kind: "diary", text: "赤が四時に尽きた。桃色を渡した客の顔は、赤を渡した客の顔と同じだったと八重さんが言った。二百回見たそうだ。私は一回も数えていない。来年は数える。" },
		{ kind: "diary", text: "三丁目の柏餅は二つとも消えた。片方は八重さんが持っていった。三つ目があると思っていたらしい。" },
		{ kind: "diary", text: "三百円の子。名前を聞きそびれた。来年また来たら、先に名前を聞く。" },
		{ kind: "diary", text: "白を五本と赤を一本、という注文があった。同じ日に、同じ人が、二つの用で花を買う。祖母の頁にも同じ形の行がいくつもあった。私は今年、その意味を一つ覚えた。" },
		{ kind: "diary", text: "丈を長くする話を、今年は四回した。前の職場で覚えた技だ。ここでは使わないつもりでいたが、使えるものは使う。捨てるほど持っていない。" },
		{ kind: "diary", text: "十四番の配達は、二度行った。二度行けば渡せる。一度で諦めない仕事を、今年の五月の収穫として書いておく。" },
		{ kind: "diary", text: "冷蔵ケースの温度は、〇・五度下げたのが正解だった。来年は、この行を最初に読む。" },
		{ kind: "diary", text: "八重さんの話。祖母は注文の紙を腕に貼っていたそうだ。両腕。想像すると、少しおかしい。私は貼らない。貼らないが、覚えておく。" },
		{ kind: "diary", text: "五百円の束は、当日、七つ出た。全部、若い人だった。手つきは、雑にしなかったと思う。" },
		{ kind: "diary", text: "帳場の四本は、通りに出て誰かに渡す、ということをしなかった。籠に入れて、店に飾った。今年はそれでいい。" },
		{ kind: "diary", text: "芍薬の蕾は、まだ全部同じ音に聞こえる。祖母の耳は、何個弾いた耳だったのだろう。" },
		{ kind: "diary", text: "二百個。弾けば分かるようになると、彼は言った。根拠はないと思う。ないが、数える気にはなった。今月は二十個。" },
		{ kind: "diary", text: "ツケがひとつ増えた。「分かるようになった頃に、いちばんいい蕾」。気の長いツケだ。忘れないように、ここに書いておく。" },
		{ kind: "diary", text: "立て看板は、来年もあの字のまま出す。下の一行だけ、今年は書き足した。「小さな束もお作りします」。七つ出たので、この一行は残す。" },
		{ kind: "diary", text: "制服の子が三人で一つの束を買っていった。同じ紙で三つに分けた。あれは去年までの私なら、たぶん断っていた。断る理由が、思いつかなかった。" },
		{ kind: "diary", text: "長野の人と、電話で少し話した。息子は花を見もしない子だった、と言っていた。今は、月に一度、一輪だけ持って帰る。" },
		{ kind: "diary", text: "彼は母親にカーネーションを送った。なのに、いつもの一輪は、別に買っていった。" },
		{ kind: "diary", text: "一輪の宛先を、また聞きそびれた。" },
		{ kind: "diary", text: "聞きそびれている、と書くのは今月で二度目だ。次は聞く、とは書かない。聞けない気がしているから。" },
	],
};

/** 第五章 皐月。 ⚠️並び順が再生順。 */
export const M05: readonly Vignette[] = [
	chomen0501,
	denwa,
	hitoban,
	hahaNoHi,
	denpyou,
	naganoDenwa,
	chomen0531,
];
