/**
 * 花常 本文 第六章 水無月「雨の音」
 * 正本: packages/frontend/hanaawase/HANATSUNE-STORY-06.md
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ6-1の前」   → month-open 6
 *   「ステージ6-1クリア後」「ステージ6-2の前」 → stage-clear m6-1
 *   「ステージ6-2クリア後」「ステージ6-3の前」 → stage-clear m6-2
 *   「ボス「五月雨」戦の前」 → boss-before m6-3
 *   「ボス「五月雨」撃破後」 → boss-after m6-3
 *   「ステージ6-3クリア後」 → stage-clear m6-3
 *   「六月の全ステージクリア後」 → month-close 6
 */

import type { Vignette } from "./types.js";

// 解放: ステージ6-1の前
const chomen0605: Vignette = {
	id: "m6-chomen-0605",
	kind: "chomen",
	month: 6,
	title: "六月五日",
	trigger: { at: "month-open", month: 6 },
	synopsis: "梅雨入りの帳面。紫陽花の仕入れと、雨の日の店の仕度を書く。",
	lines: [
		{ kind: "diary", text: "六月五日。雨。梅雨入りが発表された。" },
		{ kind: "diary", text: "朝、店の前の側溝が詰まっていた。落ち葉と、去年の誰かの傘の骨が一本。八重さんが箒の柄で突いて流してくれた。お礼に白いトルコキキョウを二本。まるはちの勘定台の脇に挿すそうだ。" },
		{ kind: "diary", text: "紫陽花、二十鉢と切り花三十。青と、青紫と、白。雨の月は、店の中まで水の色になる。" },
		{ kind: "diary", text: "鉢の値札を書き直した。「あじさい」から「紫陽花」に。画数の多い字のほうが、雨の日は落ち着いて見える。値段は据え置き。" },
		{ kind: "diary", text: "冷蔵ケースの扉が、開けるたびに白く曇る。布巾を一枚、ケースの上に置くことにした。一日に何度も拭く。" },
		{ kind: "diary", text: "傘立てを出した。祖母の代からの、緑色の、底が抜けかけているやつ。午前で四本。夕方には二本になっていた。二本は、忘れていったのだと思う。" },
		{ kind: "diary", text: "床が濡れる。長靴の客の足跡が、勘定台の前で必ず一度止まる。止まる場所だけ、色が濃い。" },
		{ kind: "diary", text: "仕入れ表。紫陽花(鉢)二十、紫陽花(切)三十、トルコキキョウ二十、小菊十五、かすみ草十。仏花の束は月曜に十五。" },
		{ kind: "diary", text: "雨の日は切り花が売れず、鉢が売れる。濡らして帰らずに済むほうを選ぶからだと、前の職場では習った。ここでは、まだ確かめていない。" },
		{ kind: "diary", text: "昼過ぎに雨脚が強くなって、トタンの庇が鳴りはじめた。店の奥にいても、雨の強さだけは正確に分かる。" },
		{ kind: "diary", text: "ラジオを点けた。天気の話ばかりしている。今週いっぱい、傘のかたちが並んでいた。" },
		{ kind: "diary", text: "ラジオを点けると、店が広く感じる。祖母は点けていなかったと思う。作業場のラジオは、埃の積もり方からして、何年も回していない。" },
		{ kind: "diary", text: "雨の日の掃除。床は拭いても十分でまた濡れる。拭くのをやめて、勘定台の前だけ拭くことにした。祖母の帳面に「売れない日は、店を磨く日」とあるが、磨いても濡れる日のことは書いていない。" },
		{ kind: "diary", text: "父の日のポップを描くのを忘れていた。厚紙は買ってある。明日にする。" },
		{ kind: "diary", text: "紫陽花の切り花が三本、首を垂れていた。深水にして作業場に立てておく。明日の朝に見る。" },
		{ kind: "diary", text: "祖母の帳面の六月は、雨の日の客だけ、姓名で書いてある。晴れの日は姓だけ。" },
		{ kind: "diary", text: "六月の頁だけ、字が大きい。書く時間のあった月ということだと思う。" },
		{ kind: "diary", text: "余白に一行。「雨の日に花を買いに来る人は、たいてい、何かある」" },
		{ kind: "diary", text: "私にはまだ、傘の水滴しか見えない。" },
		{ kind: "diary", text: "長靴を買った。祖母のは、サイズが合わなかった。" },
		{ kind: "diary", text: "祖母の長靴は、作業場の隅に置いたままにしてある。仕舞う理由も、出す理由も、今日は見つからなかった。" },
		{ kind: "diary", text: "忘れられた傘二本は、傘立てに残しておく。取りに来る人がいるかもしれない。" },
		{ kind: "diary", text: "六月の予定。第三日曜が父の日。月末に霜月堂が水無月を出すそうで、その頃は和菓子の客が通りを歩く。花は売れないが、人は通る。" },
		{ kind: "diary", text: "梅雨のあいだ、店の奥の冷えが強い。腰に一枚、薄いものを巻くことにした。祖母が同じことをしていた形跡が、作業場の釘に残っている。膝掛けが一枚、掛けたままだった。" },
		{ kind: "diary", text: "売上、二万一千四百円。雨の日にしては、悪くない。" },
		{ kind: "diary", text: "数字の下に、今日は名前を三つ書いた。書くつもりはなかったが、書かないと誰が来たか分からなくなる月だと気づいた。雨の日は、顔より傘を覚える。" },
	],
};

// 解放: ステージ6-1クリア後
const shiroiNoWoSukoshi: Vignette = {
	id: "m6-shiroi-wo-sukoshi",
	kind: "scene",
	month: 6,
	title: "白いのを、少し",
	trigger: { at: "stage-clear", stageId: "m6-1" },
	synopsis: "雨の日にだけ来る客がある。白い花を少しだけ買っていくその人を、若菜は繰り返し迎える。",
	choices: [
		{
			id: "B-12",
			label: "雨の日の客",
			options: [
				{ key: "A", label: "ひとこと、添える" },
				{ key: "B", label: "静かに渡す" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_day", text: "その人は、雨の日にだけ来た。" },
		{ kind: "narration", text: "細い雨の火曜だった。通りに人の足音がなく、聞こえるのは庇を伝う水が縁石を叩く音だけで、店の中は水槽の底のように静かだった。若菜は切り花の桶を三つ、順に上げて水を替えていた。バケツに落ちる水の音が、雨の音と重なって、どちらがどちらだか分からなくなる。" },
		{ kind: "narration", text: "紫陽花の青が、この光では一段濃く見える。晴れた日には白く飛んでしまう色が、雨の日にだけ、ちゃんと青になる。" },
		{ kind: "narration", text: "十一時に、傘をたたまずに入ってきた男性がひとりいた。前掛けをしたままの、通りの店の人だった。" },
		{ kind: "say", speaker: "sub", name: "男性の声", text: "なんか、そのへんの、安いのを。二千円まで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ご用途は" },
		{ kind: "say", speaker: "sub", name: "男性の声", text: "妻の誕生日。忘れてて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、明るい色で" },
		{ kind: "narration", text: "若菜はガーベラとスプレーバラを手早くまとめて、紙を掛けた。男性は千八百円を置いて、来たときと同じ速さで出ていった。傘はやはりたたんでいなかった。" },
		{ kind: "narration", text: "雨の日に花を買いに来る人は、たいてい、何かある。祖母の帳面の一行を、若菜はその背中に当ててみた。当たらなかった。忘れていた誕生日は、たしかに何かではあるけれど、あの一行が指しているのはたぶん、あの速さのことではない。" },
		{ kind: "narration", text: "ガラス戸が動いたのは、二時を回った頃だった。" },
		{ kind: "narration", text: "女性は、ビニール傘を店の外できちんとすぼめてから、静かに戸を開けた。傘の先を下に向けて、水を落としてから入ってくる人だった。年の頃は分からない。疲れているのか、化粧が薄いのか、それも分からない。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "……白いのを、少し" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "白ですと、今は小菊と、トルコキキョウと、紫陽花の白が" },
		{ kind: "narration", text: "女性はケースの前に立って、しばらく動かなかった。若菜は説明を足さずに待った。前の職場なら、ここで用途を訊く。ご自宅用ですか、贈り物ですか。訊けば束の形が決まる。訊かなければ決まらない。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "紫陽花は、持ちますか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "水が下がりやすい花です。毎日、水を替えていただければ" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "毎日は、行けない日があって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、小菊とトルコキキョウを。こちらは水が保ちます" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "じゃあ、小菊と、トルコキキョウ、二本ずつ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "四本。かしこまりました" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "少なくて、すみません" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "四本の束は、四本の束にしかならない形があります" },
		{ kind: "narration", text: "女性が、初めて若菜のほうを見た。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "そういうもの、ですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "そういうものです" },
		{ kind: "narration", text: "若菜は小菊の茎を短く落として、トルコキキョウの高さに合わせた。四本を扇のように開かず、寄せて、正面をひとつに決める。少ない本数の束は、広げると貧しく見える。祖母の店の道具の中に、細い束のためだけの短い紐が一巻きあるのを、若菜は三月に見つけていた。" },
		{ kind: "narration", text: "包み紙は、迷って、白に近い灰色を選んだ。緑の紙も、透ける紙もあったが、今日の外の色に一番近いのがそれだった。リボンは掛けず、麻紐を一巻きだけ。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "その紙、いいですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "雨の日は、これが一番合います" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "花屋さんって、天気で紙を変えるんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "変える人と、変えない人がいます" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "あなたは、変えるほう" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "祖母が変える人でした" },
		{ kind: "narration", text: "言ってしまってから、若菜は紐の端を切った。女性は、それ以上は訊かなかった。訊かないでいてくれた、という言い方が正しいのかどうかは分からない。ただ、店の中の音がしばらく、包み紙の乾いた音だけになった。" },
		{ kind: "narration", text: "会計のあいだ、女性は店の中を見るでもなく、ガラス戸の外の雨を見ていた。鞄の口から、うすい水色の、大きな封筒の角が覗いていた。病院の名前が入っているような、ああいう封筒だと思ったが、それだけだった。" },
		// 【B-12=A】
		{ kind: "say", speaker: "wakana", emo: 1, when: { choice: "B-12", is: "A" }, text: "雨、あがるといいですね。お帰りまでに" },
		{ kind: "say", speaker: "sub", name: "女性の声", when: { choice: "B-12", is: "A" }, text: "——ええ。ほんとうに" },
		{ kind: "narration", when: { choice: "B-12", is: "A" }, text: "女性は、束と一緒に、その一言も受け取ったように見えた。" },
		// 【B-12=B】
		{ kind: "narration", when: { choice: "B-12", is: "B" }, text: "若菜は、何も言わずに、束の角度だけ整えて渡した。言葉より、白がきれいに見える持たせ方のほうが、この人には届く気がした。" },
		// 【合流】
		{ kind: "say", speaker: "sub", name: "女性の声", text: "……また来ます" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お待ちしています" },
		{ kind: "narration", text: "女性が出ていったあと、若菜は勘定台で、いま聞いた言葉を胸の中で繰り返した。また来ます。あの人は、また来る。雨の日に。" },
		{ kind: "narration", text: "名前は、聞かなかった。聞かないことが正しい気が、なぜかした。" },
		{ kind: "narration", text: "次の雨は、四日後に降った。" },
		{ kind: "narration", text: "女性は同じ時刻に来て、同じものを、同じ本数だけ買った。傘も同じビニール傘で、戸の外で水を落とす仕草も同じだった。ただ、包み紙を若菜が灰色に伸ばした手を見て、一度だけ口を開いた。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "同じのを、覚えてくれてるんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "四本と、灰色。それだけです" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "それだけで、じゅうぶんです" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "小菊、色が違いますね。前より白い" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "産地が替わりました。今週から長野のものです" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "産地で、白さが変わるんだ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "光と、寒暖差です。夜の冷えるところの花は、色が締まります" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "へえ。こっちのほうが、好きです" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、来週も同じものが入ります" },
		{ kind: "narration", text: "女性は少しだけ笑って、傘を持ち替えた。笑ったところを見たのは、それが最初だった。" },
		{ kind: "narration", text: "三度目は、その週の土曜だった。土砂降りで、女性の靴の先は色が変わっていた。若菜はタオルを出そうとして、やめた。出せば、この人はここに長く留まることになる。留まりたくて来ている人ではない気がした。" },
		{ kind: "narration", text: "代わりに、束を渡すときに、ビニールの袋をもう一枚重ねた。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "濡れないように" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "ありがとうございます。それじゃ" },
		{ kind: "narration", text: "戸が閉まって、雨の音が元の大きさに戻った。" },
		{ kind: "narration", text: "若菜は勘定台に肘をついて、いま出ていった人の靴の跡を見ていた。三足ぶんの水の跡が、勘定台の前で重なっている。同じ場所に立って、同じものを買って、同じところで止まる人の跡だった。拭けば消える。拭かなければ、夕方までは残る。" },
		{ kind: "narration", text: "その日の夕方、八重さんが店に来て、開口一番に言った。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "さっきの人、誰だい" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "お客様です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃそうだろうけど。三度目だろ、あの傘" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "見てるんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "うちは店の前が通りだからね。傘は覚えるよ。骨の細いビニールの、持ち手が白いやつ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "存じません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "知らないのかい、あんた" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "訊いていないので" },
		{ kind: "narration", text: "八重さんは、しばらく若菜の顔を見ていた。それから、桶の水を覗き込むふりをして、話をやめた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "……常ちゃんも、そういうとこあったよ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "祖母も" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あたしがいくら訊いても、客の話はしなかったの。腹立つったらなかったよ" },
		{ kind: "narration", text: "八重さんは大根を一本置いて帰っていった。置いていく理由は言わなかったし、若菜も訊かなかった。" },
		{ kind: "narration", text: "帳面に書くとき、若菜は少し迷って、「雨の日の人」と書いた。祖母の帳面なら、この欄には姓名が入っている。入れられるだけの何かを、祖母は雨の日に受け取っていたということになる。若菜が受け取ったのは、灰色の紙と、四本という数だけだった。" },
		{ kind: "narration", text: "灰色の紙は、あと十七枚あった。" },
		{ kind: "narration", text: "翌週の仕入れで、若菜は同じ灰色をもう一束、註文に足した。" },
		{ kind: "narration", text: "それでも、次の雨の日には、灰色の紙を先に出しておこうと思った。" },
	],
};

// 解放: ステージ6-2の前
const itsumoNoIchirin: Vignette = {
	id: "m6-itsumo-no-ichirin",
	kind: "scene",
	month: 6,
	title: "いつもの一輪",
	trigger: { at: "stage-clear", stageId: "m6-1" },
	synopsis: "閉店間際、月に一度の客が来る。紫陽花を一輪に仕立てて渡す。",
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "夕方、雨がいったん細くなって、通りの明かりが濡れた舗装に長く伸びていた。" },
		{ kind: "narration", text: "霜月堂の看板の電球が点いて、くろまつの窓が黄色くなる。花常の店先は、その二つの明かりの中間にあって、どちらの色にもなりきらない。若菜は表の鉢を半分だけ中に入れ、残りは軒の下に寄せた。夜のあいだも降るなら、外の鉢は水をやらなくていい。楽をする月は、楽をしていい理由まで天気が用意してくれる。" },
		{ kind: "narration", text: "閉店三十分前。見切り籠の中身を並べ替える。今日のうちに飾る花。首の短くなった紫陽花が二本、開ききったトルコキキョウが三本、小菊が一束。値札は書き直さない。籠に入った時点で、値段は同じになる。" },
		{ kind: "narration", text: "外で自転車のブレーキが鳴った。ブレーキの鳴き方で、誰が来たか分かるようになっている。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "こんばんは。間に合いました?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "まだ開いています" },
		{ kind: "say", speaker: "ren", emo: 1, text: "よかった。今日、講義が延びて" },
		{ kind: "narration", text: "レンはケースの前に立って、いつもの位置で首を傾けた。灰色の毛先が、雨で少し重くなっている。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "紫陽花、ですかね。今月は" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "紫陽花は、一輪に向きません" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え、だめなんすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "房が大きいので。一輪だけ置くと、部屋の中で花が勝ちます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "勝つ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花瓶より、花のほうが大きくなります" },
		{ kind: "narration", text: "若菜は切り花の中から、房の小ぶりなものを一本抜いた。それから鋏を入れて、大きな房を三つに分け、そのうちの一つだけを残した。手の中で、青が小さくまとまる。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "切っちゃっていいんですか、それ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "一輪にするというのは、そういうことです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "へえ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "残りは見切り籠に。今日のうちに飾る花です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃあ、その二つ、明日は誰かの家にいるわけっすね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "明日ではなく、今日です" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ、そうか。今日のうちに飾る花だから" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "そうです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "厳しいっすね、その籠" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "厳しくはないです。今日なら、まだ間に合うという意味です" },
		{ kind: "narration", text: "レンは籠を覗き込んで、首の短くなった紫陽花を指で軽く起こした。花房が指の腹に乗って、思ったより重かったらしい。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "重い" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "水を含んでいますので" },
		{ kind: "say", speaker: "ren", emo: 1, text: "花って、軽いもんだと思ってました。ずっと" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "軽い花もあります。かすみ草は、束でも息みたいな重さです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "息みたいな重さ。いま、いいこと言いました?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "仕入れの実感です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "実感、いいっすね。俺、実感で喋る人が好きで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "花の重さの話です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "はい。花の重さの話っす" },
		{ kind: "narration", text: "若菜は勘定台の上で、包みの端を折り込んだ。表の明かりが一つ落ちて、霜月堂が閉まったのが分かった。この時間から店を開けていても、来るのはこの人だけだと、六月に入ってからの記録が言っている。それでも三十分は開けておく。祖母の帳面の閉店時刻が、六月だけ三十分遅いからだ。理由は書いていない。" },
		{ kind: "narration", text: "若菜は水切りをして、切り口を新聞で巻いた。紫陽花は水を吸うのが下手な花で、店から家までのあいだに首を落とすことがある。若菜は濡らした紙を茎に巻き足して、その上からビニールを掛けた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "自転車の籠に、横に寝かせないでください。立てて" },
		{ kind: "say", speaker: "ren", emo: 1, text: "立てて。あー、でも籠に立てると倒れません?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "鞄で挟んでください" },
		{ kind: "say", speaker: "ren", emo: 2, text: "鞄で挟む。了解っす" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "坂は、押して上がってください" },
		{ kind: "say", speaker: "ren", emo: 4, text: "バレてます?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "毎回、息が上がって着きます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "乗って上がってるからっすね" },
		{ kind: "narration", text: "会計をしながら、レンはケースの上の曇りを指で撫でた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、結露っすよね。この時期、うちも大変で" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "うち" },
		{ kind: "say", speaker: "ren", emo: 1, text: "サークルの機材。梅雨、いちばん怖いんですよ。熱より湿気のほうが効くんで、ファンの吸い込みんとこに埃と水が来ると詰まるし、基板は結露で一発だし、除湿機回しっぱなしにしとかないと部室が——" },
		{ kind: "say", speaker: "ren", emo: 3, text: "……すみません、花屋で話すことじゃないっすね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花も、湿気で傷みます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ、一緒だ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "一緒です" },
		{ kind: "narration", text: "レンは一輪を鞄で挟んで、坂のほうへ帰っていった。自転車の後ろ姿が、濡れた舗装の光の上を、ゆっくり上がっていく。" },
		{ kind: "narration", text: "シャッターを半分下ろしてから、若菜は籠の紫陽花を一本、自分の作業台の空き瓶に挿した。売り物にしなかった花を店の中に置くのは、祖母の代からの決まりではない。決まりではないことを、少しずつ増やしている。" },
		{ kind: "narration", text: "戸を閉めて、若菜は籠に残した二つの房を眺めた。分けた花は、分けたぶんだけ、行き先が増える。祖母がこの籠に名前をつけていなかった理由が、今日は少しだけ分かる気がした。" },
	],
};

// 解放: ステージ6-2クリア後
const kome: Vignette = {
	id: "m6-kome",
	kind: "scene",
	month: 6,
	title: "米が届く",
	trigger: { at: "stage-clear", stageId: "m6-2" },
	synopsis: "雨の上がった夕方、実家から米が届いた話をする。店先の鉢を二人で中へ運ぶ。",
	lines: [
		{ kind: "narration", bg: "front_summer", text: "三日ぶりに雨がやんだ夕方だった。" },
		{ kind: "narration", text: "舗装がまだ乾ききらないうちに西日が差して、通りの水たまりが一枚ずつ光っていた。まるはちの前では八重さんが濡れた段ボールを潰していて、湿った紙の音が通りの端まで届く。若菜は店先に出した紫陽花の鉢の位置を直しながら、鉢底から抜けた水が石に描いた輪を、順に踏まないように歩いた。" },
		{ kind: "narration", text: "軒の下でスマホを耳に当てているレンは、こちらに背を向けて、片手で自転車のスタンドを起こしたり倒したりしていた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "うん。——届いた? よかった。——え? いや、いいって、当日に荷物送ってくるの。米、まだあるから。五キロも要らないって。ちゃんと炊いてるよ。炊いてるって。土鍋じゃないけど。分かった。分かったって。うん。はいはい。切るよ" },
		{ kind: "narration", text: "通話を切って、レンは若菜の視線に気づいた。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "……母です" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "五キロ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "毎年、誕生日に米を送ってくるんですよ。誕生日って歳でもないのに" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "誕生日" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "いつですか" },
		{ kind: "say", speaker: "ren", emo: 3, text: "……十六日、ですけど。あさって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "覚えました" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え、メモは" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "しません。覚えたので" },
		{ kind: "narration", text: "レンの耳が、困ったように半分倒れた。彼はスマホを尻ポケットに入れて、話題を米のほうへ押し戻した。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "毎年ですよ、ほんと。米と、あと梅干しと、なぜか乾電池" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "乾電池" },
		{ kind: "say", speaker: "ren", emo: 1, text: "なんか、東京は停電するもんだと思ってるんですよね、うちの母。単三が二十本" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "使いますか" },
		{ kind: "say", speaker: "ren", emo: 3, text: "……去年のがまだ十六本あります" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "四本は、使ったんですね" },
		{ kind: "say", speaker: "ren", emo: 2, text: "使いましたよ。ちゃんと。時計と、あとマウス" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "長野は、雨は" },
		{ kind: "say", speaker: "ren", emo: 1, text: "降りますけど、こっちみたいにずっとじゃないっす。山だから、降って、抜ける。夕方に一回どしゃっと来て、夜には星が出てる、みたいな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "抜ける" },
		{ kind: "say", speaker: "ren", emo: 1, text: "抜けます。こっちの雨は、抜けないですよね。三日目くらいから、天井が下がってきた気がして" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "天井は下がりません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "比喩っすよ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あ、そういえば。母が、この町のこと聞くんですよ。近所に何があるのって。商店街があるって言ったら、めちゃくちゃ食いついて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "何と答えたんですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "八百屋と、和菓子屋と、喫茶店と、花屋があるって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "順番が" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "並びの順番と、違います。花常、まるはち、角、くろまつ、霜月堂です" },
		{ kind: "say", speaker: "ren", emo: 6, text: "そこ直されるとは思わなかったっす" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "毎日通っている道ですので" },
		{ kind: "narration", text: "レンは笑って、自転車のスタンドをもう一度倒した。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "言っときますね、母に。花屋が最初だって" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "順番の話をされても、困られると思います" },
		{ kind: "say", speaker: "ren", emo: 2, text: "困りますよ。困って、また米送ってきます" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "米で返ってくるんですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "うちの母、返し方が全部食べ物なんで。長野から東京に送れるものって、限られてるんですよね。米と、味噌と、りんごと、あと野沢菜" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花は" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "長野は、花の産地でもあります。今日入っている小菊も長野です" },
		{ kind: "say", speaker: "ren", emo: 4, text: "マジすか。うち、そんな畑ないっすけど" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "町が違えばあります。夜が冷えるところの花は、色が締まります" },
		{ kind: "say", speaker: "ren", emo: 1, text: "夜が冷えると、色が締まる" },
		{ kind: "narration", text: "彼はその言い方を口の中で二度繰り返して、それから、感心したような顔をした。感心されるようなことは何も言っていない。市場で辰巳さんに言われたことを、そのまま渡しただけだった。" },
		{ kind: "narration", text: "若菜は勘定台の下から布巾を出して、鉢の縁の泥を拭いた。米屋の前を、自転車が水を撥ねて通り過ぎていく。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "五キロは、重いです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "重いっす。駅から坂上がるとき、毎年、来年こそ断ろうって思うんですよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "断らないんですね" },
		{ kind: "say", speaker: "ren", emo: 3, text: "断ると、次の年も同じ量が来るんで。意味ないなって" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "それは、断らないほうの理由ではないと思います" },
		{ kind: "narration", text: "レンは口を開いて、閉じた。それから彼は、負け惜しみのように付け足した。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "どうせ雨ですよ、あさっても。俺、雨の日生まれなんで。誕生日、だいたい降るんです" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "晴れの年は" },
		{ kind: "say", speaker: "ren", emo: 1, text: "二十年で、三回くらい。写真見ると、だいたい傘持ってます。だから雨、嫌いじゃないんすよね。降ってるほうが、なんか、俺の日って感じで" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "雨の子なんですね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "狼なんですけどね" },
		{ kind: "narration", text: "通りの向こうで、段ボールを潰し終えた八重さんが顔を上げた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "なんだい、若い衆。誕生日かい" },
		{ kind: "say", speaker: "ren", emo: 4, text: "聞こえてました? ここから、まるはちまで十メートルありますよ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "十メートルは近所だよ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "商店街で内緒話ができると思うんじゃないよ。米は? 米ならうち、隣が米屋だからね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "もう五キロ届いてるんで、大丈夫っす" },
		{ kind: "say", speaker: "sub", name: "八重", text: "じゃあ花だ。花屋の隣で誕生日の話をするやつは、花をもらうと決まってんの" },
		{ kind: "narration", text: "八重さんは自分の言ったことに笑って、店に引っ込んだ。あとに残ったのは、水たまりの光と、決まっているらしい話の続きだけだった。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あの、今の、真に受けなくていいんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "日にちだけ、覚えておきます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "大神くん、そこの鉢、二つ持ってっとくれ。若菜ちゃん一人じゃ日が暮れるよ" },
		{ kind: "say", speaker: "ren", emo: 2, text: "はい" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "日は、もう暮れています" },
		{ kind: "narration", text: "日が沈みかけて、通りの水たまりの光が消えた。若菜が店先の鉢を中へ入れはじめると、レンが何も言わずに反対側から二つ持ち上げた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "濡れます" },
		{ kind: "say", speaker: "ren", emo: 2, text: "もう濡れてますって" },
		{ kind: "say", speaker: "ren", emo: 1, text: "土、重いっすね。花より土のほうが重い" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "鉢はそういうものです" },
		{ kind: "narration", text: "鉢は十六。二人で運ぶと、四往復で終わった。一人だと八往復かかる。若菜は最後の一つを土間に下ろして、前掛けで手を拭いた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、毎日っすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "雨の日は、朝と夕方に" },
		{ kind: "say", speaker: "ren", emo: 4, text: "一人で" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "一人でできる数にしてあります" },
		{ kind: "say", speaker: "ren", emo: 6, text: "その言い方、ずるいっすね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "事実です" },
		{ kind: "narration", text: "レンは笑って、自転車のスタンドを蹴り上げた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃ、あさって。あ、いや、なんでもないっす。また来ます" },
		{ kind: "narration", text: "ライトが坂のほうへ遠ざかっていった。若菜は土間の鉢を、青の濃い順に並べ直した。並べ直す必要はなかった。" },
	],
};

// 解放: ステージ6-3の前
const chomen0614: Vignette = {
	id: "m6-chomen-0614",
	kind: "chomen",
	month: 6,
	title: "六月十四日",
	trigger: { at: "stage-clear", stageId: "m6-2" },
	synopsis: "月半ばの帳面。雨の日の客のことと、傘立ての忘れ物について書く。",
	lines: [
		{ kind: "diary", text: "六月十四日。晴れのち曇り。夕方から湿る。" },
		{ kind: "diary", text: "五日ぶりに店先を全部出した。鉢を出す順番を、いつのまにか決めている。青が濃いのを外側、白を戸の脇。決めた覚えはないのに、毎回同じに置いている。" },
		{ kind: "diary", text: "三日ぶりに乾いた。乾いた日は、店より先に道が匂う。" },
		{ kind: "diary", text: "鉢の水やり、二日休んだ。雨が代わりにやってくれた月の、こういうところは楽をさせてもらう。" },
		{ kind: "diary", text: "深水にした紫陽花三本、二本は起きた。一本は駄目だった。駄目だったほうを、切り詰めて見切り籠に入れた。首が短くなったぶん、水は上がっている。" },
		{ kind: "diary", text: "傘立ての忘れ傘、まだ二本。片方は骨が一本折れている。折れているほうは、たぶん戻ってこない。" },
		{ kind: "diary", text: "雨の日の人が、二度目に来た。同じ四本。同じ灰色の紙。" },
		{ kind: "diary", text: "名前は、まだ書けない。書けないというより、書かないことにしている。祖母の六月の頁に姓名が並んでいるのは、あの人が聞き出したからではないのだと思う。何度も来るうちに、向こうが置いていったのだと思う。" },
		{ kind: "diary", text: "八重さんに、あの人のことを訊かれた。答えなかった。答えられなかったのではなく、答えないことにした。この二つは違う。" },
		{ kind: "diary", text: "祖母も同じだったらしい。八重さんが腹を立てるくらいには。" },
		{ kind: "diary", text: "大根をもらった。話をしなかった礼なのか、話をさせなかった詫びなのか、どちらでもないのか、分からない。煮た。" },
		{ kind: "diary", text: "傘の水滴の向こうが、少し見えた気がした。見えたのは中身ではなくて、あの人が毎回、傘の先を下に向けてから戸を開ける、その手の順番だけだ。" },
		{ kind: "diary", text: "それでもう、四本と灰色を先に用意できるようになった。それが「見えた」ということでいいのかは、まだ分からない。" },
		{ kind: "diary", text: "大神くんの誕生日、六月十六日。あさって。" },
		{ kind: "diary", text: "帳面に書くと決まってしまうので、書かないでおこうと思ったが、書いた。" },
		{ kind: "diary", text: "雨の日の人の傘は、持ち手が白い。八重さんはそこまで見ている。私は四本と灰色しか見ていない。どちらが客をよく見ているのかは、決めないでおく。" },
		{ kind: "diary", text: "傘立ての緑の底が、とうとう抜けた。買い替えるか、直すか。直せるものかどうかも分からない。" },
		{ kind: "diary", text: "明日、市場。紫陽花の鉢を五つ足す。青の出ている鉢を選ぶ。" },
		{ kind: "diary", text: "市場は雨でも五時半。長靴で行く。買ったばかりの長靴の、内側がまだ硬い。" },
		{ kind: "diary", text: "仏花、月曜の十五束は十二束に減らす。先週三束残した。残した理由は雨だと思うが、雨のせいにばかりしていると、来年の私が困る。" },
		{ kind: "diary", text: "父の日のポップ、まだ描いていない。厚紙は、まだ買ってある。" },
		{ kind: "diary", text: "今週の売上、前年比は出さない。祖母の六月の数字は、この店が一番元気だった頃のものだ。比べるための数字ではなく、あとから読むための数字として置いておく。" },
	],
};

// 解放: ボス「五月雨」戦の前
const amayadori: Vignette = {
	id: "m6-amayadori",
	kind: "scene",
	month: 6,
	title: "雨宿り",
	trigger: { at: "boss-before", stageId: "m6-3" },
	synopsis: "本降りの日、レンが雨宿りに駆け込んでくる。二人で庇を叩く雨の音を聞く。",
	choices: [
		{
			id: "B-11",
			label: "六月十六日",
			axis: "縁",
			options: [
				{ key: "A", label: "用意していたものを、渡す", note: "縁+1" },
				{ key: "B", label: "言葉だけ、伝える" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_day", text: "十六日は、朝から本降りだった。" },
		{ kind: "narration", text: "シャッターを上げた時点で、道の向こう側が白く霞んでいた。店先に出す鉢を、若菜は半分だけにした。全部出せば全部が濡れる。濡れてもいい鉢と、そうでない鉢がある。" },
		{ kind: "narration", text: "昼までに、店の中の湿気が花より先に重くなった。包み紙が波を打ち、麻紐が指に貼りつく。値札の墨が滲まないように、書きかけの札は作業台の隅に伏せて置いた。ガラス戸は下から三分の一が曇り、拭いても十分でまた曇った。" },
		{ kind: "narration", text: "昼を過ぎても客はなく、三時に紫陽花の鉢をひとつ売ったきり、通りには傘さえ通らなくなった。" },
		{ kind: "narration", text: "雨の音だけが、店の中で一番大きい音になった。トタンを叩く音、庇の端から縁石に落ちる音、側溝を流れる音。三つが別々の速さで鳴っていて、若菜は水替えの手を止めないまま、そのどれかを数えそうになって、やめた。" },
		{ kind: "narration", text: "四時前、自転車のブレーキが鳴って、レンがずぶ濡れの一歩手前で駆け込んできた。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "すみません、雨宿りさせてください。買うもの決まってないのに" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "どうぞ。今日はどうせ、誰も来ません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "言い切りましたね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "三時から一人も通っていません。傘も" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー、坂の下、水が溜まってました。米屋の前んとこ。あそこ、へこんでるんですよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "毎年、六月にへこみます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "毎年へこむんですか、道が" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "へこんだままなだけです" },
		{ kind: "narration", text: "レンはタオルを借りて、上がり框に腰を下ろした。トタンの庇を、雨が叩き続けている。強く、弱く、また強く。二人とも、しばらく何も喋らなかった。喋らないことが、失礼にならない相手だと、いつからか互いに知っていた。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……この店、雨の音がいいっすね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "トタンですから" },
		{ kind: "say", speaker: "ren", emo: 5, text: "いや、なんか——音が、丸いんですよね。ここの雨" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "丸い" },
		{ kind: "say", speaker: "ren", emo: 5, text: "うちのアパートの雨は、四角いんですよ。カンカンカンって、角がある。ここのは、とん、とん、って落ちる。……伝わんないか" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "同じトタンでも、ですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "たぶん、下に何が入ってるかっすね。すみれ荘の庇、下が空洞なんですよ。だから響く。ここのは、下に木があるでしょ。あと、上に草が乗ってる" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "草" },
		{ kind: "narration", text: "レンは天井の向こうを指した。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "庇の端、苔生えてますよ。緑のやつ。あれが当たりを柔らかくしてるんじゃないかって、俺は思ってて。音って、当たる面の硬さで全部変わるんで。試しに録ってみたことあるんですけど、波形の立ち上がりが——" },
		{ kind: "narration", text: "彼はそこで一度言葉を止めて、雨の音を聞いた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "——立ち上がりが、ゆるいんですよ、ここ。角が丸まってる。数字で見ても丸いんです" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "録ったんですか、この店の雨を" },
		{ kind: "say", speaker: "ren", emo: 3, text: "去年の梅雨に、軒先で。すみません、勝手に" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "勝手に、ではないです。うちの前で鳴っているだけの音です" },
		{ kind: "say", speaker: "ren", emo: 3, text: "そう言われると、それはそれで、なんか" },
		{ kind: "narration", text: "雨がひとしきり強くなって、二人ぶんの声を消した。強い雨は、丸くても大きい。過ぎると、また、とん、とん、に戻った。" },
		{ kind: "narration", text: "レンは立ち上がって、戸を細く開けた。雨の音が、いきなり近くなる。彼は首だけ外に出して、庇の端を下から見上げた。前髪から水が一滴落ちて、上がり框の木を濃くした。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "ほんとに生えてる。緑の、ふさふさしたやつ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "苔は、取ったほうがいいんでしょうか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "取らないほうがいいと思います。俺の説だと、あれが音を作ってるんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "説" },
		{ kind: "say", speaker: "ren", emo: 1, text: "説っす。検証してないんで" },
		{ kind: "narration", text: "戸を閉めると、音がまた店の中の大きさに戻った。レンは框に座り直して、タオルで髪を押さえた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "風邪をひきます" },
		{ kind: "say", speaker: "ren", emo: 2, text: "狼なんで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "狼も、ひきます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "ひきますね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "祖母は、この庇を一度も替えませんでした" },
		{ kind: "say", speaker: "ren", emo: 1, text: "錆びてないですもんね。塗り直しはしてるでしょ、あれ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "三年に一度、業者を呼んでいた記録があります。替えるより高くつく年もありました" },
		{ kind: "say", speaker: "ren", emo: 5, text: "じゃあ、残したかったんですね。板じゃなくて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "祖母がトタンを替えなかった理由も、それなら分かる気がします" },
		{ kind: "say", speaker: "ren", emo: 2, text: "でしょう" },
		// 【B-11=A】
		{ kind: "narration", when: { choice: "B-11", is: "A" }, text: "何が「でしょう」なのか、今日も分からなかった。それから若菜は、作業台の下に朝から仕舞ってあった包みを出した。新聞紙を斜めに、一巻き。" },
		{ kind: "say", speaker: "wakana", emo: 1, when: { choice: "B-11", is: "A" }, text: "はい。今日、でしょう" },
		{ kind: "say", speaker: "ren", emo: 4, when: { choice: "B-11", is: "A" }, text: "え。——え?" },
		{ kind: "say", speaker: "wakana", emo: 1, when: { choice: "B-11", is: "A" }, text: "誕生日と、聞いたので" },
		{ kind: "narration", when: { choice: "B-11", is: "A" }, text: "包みの中は、青い紫陽花を小さく仕立てた一枝だった。レンの耳が、ゆっくり倒れて、戻って、また倒れた。" },
		{ kind: "say", speaker: "ren", emo: 2, when: { choice: "B-11", is: "A" }, text: "——初めてです、俺。花、もらうの。いつも買う側だったんで" },
		{ kind: "say", speaker: "wakana", emo: 2, when: { choice: "B-11", is: "A" }, text: "買う側の人に売る側から贈るのは、私も初めてです" },
		{ kind: "say", speaker: "ren", emo: 2, when: { choice: "B-11", is: "A" }, text: "じゃあ、おそろいだ" },
		// 【B-11=B】
		{ kind: "narration", when: { choice: "B-11", is: "B" }, text: "何が「でしょう」なのか、今日も分からなかった。雨の音の合間に、若菜は思い出して、言った。" },
		{ kind: "say", speaker: "wakana", emo: 1, when: { choice: "B-11", is: "B" }, text: "そういえば。おめでとうございます、今日" },
		{ kind: "say", speaker: "ren", emo: 4, when: { choice: "B-11", is: "B" }, text: "え。あ! 覚えてたんですか、ほんとに" },
		{ kind: "say", speaker: "wakana", emo: 1, when: { choice: "B-11", is: "B" }, text: "覚えたと、言いました" },
		{ kind: "say", speaker: "ren", emo: 3, when: { choice: "B-11", is: "B" }, text: "……メモなしで" },
		{ kind: "narration", when: { choice: "B-11", is: "B" }, text: "彼はそれだけで、ずいぶん長いこと、嬉しそうだった。米五キロより効いたのではないかと思う。" },
		// 【合流】
		{ kind: "narration", text: "レンはタオルを畳んで、上がり框の端に置いた。それから、店の奥のほうへ首を伸ばした。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あれ。水の音、してますね。奥" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "水場です。桶に張りっぱなしにしてあります" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあこの店、雨の日は上と下で鳴ってるんだ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "上と下" },
		{ kind: "say", speaker: "ren", emo: 1, text: "庇と、水場。挟まれてるっすよ、俺たち" },
		{ kind: "narration", text: "若菜は勘定台の前に立ったまま、その言い方を、しばらく黙って引き受けた。庇の音は変わらず丸く、奥の桶の水は、蛇口からの一滴ぶんだけ、規則正しく鳴っていた。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "傘は" },
		{ kind: "say", speaker: "ren", emo: 1, text: "持ってきてないっす" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "貸します。傘立ての、忘れ物ではないほうを" },
		{ kind: "say", speaker: "ren", emo: 4, text: "忘れ物の傘、あるんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "二本。取りに来る人がいるかもしれないので、置いてあります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "来ますよ、それ。雨の日に" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "来ますか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "来ます。俺、傘取りに戻る派なんで" },
		{ kind: "say", speaker: "ren", emo: 1, text: "傘、返しに来ますね。晴れた日に" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "雨の日でも構いません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "晴れた日にします。そのほうが、返しに来た感じがするんで" },
		{ kind: "narration", text: "雨は夕方まで、丸い音で降り続けた。" },
		{ kind: "narration", text: "店の中の湿気は、夜になっても抜けなかった。包み紙は波を打ったまま、明日には元に戻る。戻らなければ捨てる。捨てる前に、一度は乾かしてみる。" },
		{ kind: "narration", text: "閉店の時刻になっても、通りに人の影はなかった。若菜はシャッターを半分だけ下ろし、その隙間から、坂を上っていく自転車の後ろのライトが、雨の粒を一列だけ照らしていくのを見ていた。" },
	],
};

// 解放: ボス「五月雨」撃破後
const tokuShitaKao: Vignette = {
	id: "m6-toku-shita-kao",
	kind: "scene",
	month: 6,
	title: "得した顔",
	trigger: { at: "boss-after", stageId: "m6-3" },
	synopsis: "長雨が上がった朝。水の下がった花を手当てし、店先の鉢がよく売れる。",
	lines: [
		{ kind: "narration", bg: "front_summer", text: "長い雨が上がった朝、商店街は薄い湯気を立てていた。" },
		{ kind: "narration", text: "日が出たのは六日ぶりだった。舗装が乾きはじめる順番が目に見える。日の当たるところから白く、庇の影のところは黒いまま。まるはちの前で八重さんが水を撒いていて、乾きかけた石をわざわざ濡らしていた。乾くのを待たずに撒くのが、この人の順番らしい。" },
		{ kind: "narration", text: "若菜はシャッターを上げきってから、庇の下に手を入れた。トタンの裏は、まだ濡れている。指先に付いた水を前掛けで拭いて、それから店先に鉢を全部出した。" },
		{ kind: "narration", text: "店先に出した紫陽花の鉢が、どれも一回り大きく見えた。花房が水を含んで重たげに揺れて、青がひときわ深い。降られた側のはずなのに、紫陽花だけが得をした顔をしている。" },
		{ kind: "narration", text: "切り花のほうは、そうはいかない。長雨のあいだ、店の中の湿気で蒸れた茎が何本かあり、朝の水替えで持ち上げたとき、首から先だけが遅れてついてきた。" },
		{ kind: "narration", text: "若菜は水の下がった数本を作業台に並べた。茎を斜めに落とす。切り口の白い綿のような部分を、爪の先で少し掻き出す。指先に明礬を取って、切り口にすり込む。指の腹がざらついて、水の中に入れると、粉が細く一筋だけ流れて消えた。" },
		{ kind: "narration", text: "祖母の帳面で読んだ手当てだった。「紫陽花は水が下がる。切り口に明礬。深水で一晩」。書いてある通りにやると、書いてある通りに、翌朝には花が起き上がった。" },
		{ kind: "narration", text: "新聞紙で首まで巻いて、深い桶に立てる。作業場の暗いところに置いて、店を開ける。夕方に一度見て、まだ迷っている花が二本あって、そのまま置いた。翌朝、六本のうち五本が、首の角度を戻していた。戻らなかった一本は、切り詰めて見切り籠に入れた。短くなれば、水は上がる。" },
		{ kind: "narration", text: "帳面は、こういうとき、素直にすごいと思う。" },
		{ kind: "narration", text: "午前のうちに、鉢が三つ売れた。" },
		{ kind: "narration", text: "三つとも、通りすがりの人だった。買うつもりで来た顔ではなく、歩いていて足が止まった顔で、そのうちの一人は同じことを言った。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "この青、写真のより濃くないですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "今朝がいちばん濃い時間です。乾くと、少し薄くなります" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "じゃあ、家では薄くなるんだ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "土と水で戻ります。朝、水をやってください" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "朝ね。起きられるかな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "起きられなかった日は、夜でも構いません" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "花屋さんがそう言うなら" },
		{ kind: "narration", text: "若菜は鉢を新聞で包みながら、いま自分が言ったことを、頭の中でもう一度置き直した。朝の水が一番いい。それは本当だ。ただ、本当のことだけ言って帰らせると、この人は明日から鉢を負担に思う。祖母の帳面には、そういう匙加減までは書いていない。" },
		{ kind: "narration", text: "店の前の縁台も、朝のうちに拭いて出した。六日ぶりに座れる木の面になって、昼には近所の老人が二人、勝手に腰を下ろしていた。座られているあいだは、鉢がよく売れる。座っている人がいる店には、人が入る。" },
		{ kind: "narration", text: "八重さんが通りすがりに首を突っ込んで、店先の鉢を眺めた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "今年の青は、いいねえ。常ちゃんの土のせいかね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "土?" },
		{ kind: "say", speaker: "sub", name: "八重", text: "鉢の土、あの人が何年も配合してたやつだろ。青の出る土" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "……そうだったんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんた、知らないで水やってたのかい" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "知らないで、やってました" },
		{ kind: "narration", text: "八重さんは、けらけら笑って、それから鉢のひとつを指で示した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "うちの店の裏に、まだ袋で残ってるはずだよ。常ちゃんが置いてったやつ。うちは土なんか使わないのに、置き場だけ貸してくれって言われてね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "まるはちさんに" },
		{ kind: "say", speaker: "sub", name: "八重", text: "置き場代は、盆と暮れに花でもらってたけどね。安いもんだよ、あれは" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "花で" },
		{ kind: "say", speaker: "sub", name: "八重", text: "この商店街、金で払うと角が立つの。覚えときな" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花常の裏は狭いだろ。あの人、雨に当てたくないもんは全部こっちに寄越すの。土と、玉肥と、正月の飾りの箱" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "取りに伺います" },
		{ kind: "say", speaker: "sub", name: "八重", text: "取りに来るったって、あんた一人じゃ持てないよ。二十キロの袋だからね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "持てます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "腰やるよ。あの狼の子に頼みな。あの子、荷物持つとき嬉しそうな顔するだろ" },
		{ kind: "narration", text: "若菜は返事をしなかった。八重さんは返事を待たずに、水を撒いた石の上をぱたぱた歩いて帰っていった。" },
		{ kind: "narration", text: "昼前に、くろまつのマスターが店の前を通った。" },
		{ kind: "narration", text: "濡れた椅子を二脚、店の外に出して干している途中らしく、片方を軒下に置いて、片方を日向に置いた。若菜が会釈をすると、玄さんは会釈を返して、それから上着の内側から小さな紙袋を出して、勘定台の上に置いた。豆だった。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ありがとうございます" },
		{ kind: "narration", text: "玄さんは何も言わずに、店先の鉢を一つ、太い指で示した。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "青いほう、ですね" },
		{ kind: "narration", text: "玄さんは頷いた。若菜は鉢ではなく、切り花の青い一本を新聞で巻いて渡した。鉢は重い。あの椅子と一緒には持てない。" },
		{ kind: "narration", text: "玄さんは、それを片手で受け取って、もう片方の手で椅子を提げて帰っていった。カウンターの端に挿すのだろうと思った。挿してあるのを、若菜はまだ見たことがない。" },
		{ kind: "narration", text: "店先の鉢の青は、日が高くなるにつれて、少しずつ薄くなっていった。夕方にはまた、ただの水色に戻る。青がいちばん深いのは、朝の、湿った一時間だけらしかった。" },
		{ kind: "narration", text: "日が高くなるにつれて、通りの湯気は薄くなり、正午には道が完全に乾いた。乾いてしまうと、六日間降っていたことがどこにも残らない。残っているのは、鉢の青と、明礬の袋の減り方だけだった。" },
		{ kind: "narration", text: "夕方、若菜は作業場の棚を一段ずつ見た。" },
		{ kind: "narration", text: "肥料の袋、麻紐の束、古い花鋏の空箱、名前の書かれていない小瓶がいくつか。中身の分からないものは、捨てずにそのままにしてある。捨てられるようになるには、たぶん、それが何なのかを一度知らなければならない。" },
		{ kind: "narration", text: "棚の一番下に、二十キロの袋が一つだけ残っていた。口を折って、洗濯挟みで留めてある。中は、赤茶けた土と、白い粒と、黒いものが混じっていた。まるはちの裏にあるという袋と、たぶん同じものだ。" },
		{ kind: "narration", text: "若菜は指を入れて、少しだけすくった。手のひらの上で、粒の大きさが三種類あるのが分かる。分かるだけで、配合は分からない。" },
		{ kind: "narration", text: "帳面の六月の頁を、もう一度めくった。土のことは、どこにも書いていなかった。書く必要がなかったからだと思う。毎年やっている人は、毎年やっていることを書かない。" },
		{ kind: "narration", text: "知らないで受け継いでいるものが、この店にはまだいくらでも埋まっているらしかった。埋まっている場所が、店の中とはかぎらないことも、今日わかった。" },
	],
};

// 解放: ステージ6-3クリア後
const chichiNoHi: Vignette = {
	id: "m6-chichi-no-hi",
	kind: "scene",
	month: 6,
	title: "父の日",
	trigger: { at: "stage-clear", stageId: "m6-3" },
	synopsis: "父の日の日曜。母の日とはまるで違う静けさの中で、黄色いバラを並べる。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "父の日の日曜は、母の日の十分の一も売れなかった。" },
		{ kind: "narration", text: "朝のうちに黄色いバラを十本、目立つ位置に立てて、厚紙のポップも、ようやく描いて出した。「父の日 六月第三日曜」。文字の下に、黄色い丸をひとつ描いた。それ以上は思いつかなかった。" },
		{ kind: "narration", text: "十時に一組。十一時に一組。そこから昼を挟んで、通りを歩く人の数だけが増えていった。日曜の商店街は人が出る。出るが、花屋の前では止まらない。まるはちの前には行列ができていて、桃を抱えた人が次々に坂を上っていく。" },
		{ kind: "narration", text: "一時過ぎに、中年の男性が戸を半分開けて、顔だけ入れた。" },
		{ kind: "say", speaker: "sub", name: "男性の声", text: "あの、父の日って……花、なんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "黄色いバラが一般的です。ひまわりも、この時季なら" },
		{ kind: "say", speaker: "sub", name: "男性の声", text: "へえ。うち、親父が入院しててね。花、置けるかな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "病室でしたら、香りの少ないものを。鉢はご遠慮いただく決まりのところが多いです" },
		{ kind: "say", speaker: "sub", name: "男性の声", text: "詳しいんだ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花屋ですので" },
		{ kind: "narration", text: "男性は五分ほど迷って、黄色いバラを三本と、かすみ草を少しだけ買っていった。この日、いちばん大きな売上だった。" },
		{ kind: "narration", text: "三時。客足は途切れたまま戻らなかった。自転車の音がして、レンが戸を開けた。手には、まるはちの袋がひとつ下がっている。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "今日、なんか静かっすね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "父の日ですから" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ、そっか。あれ? だから静かって、どういう" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "父の日に花を贈る人は、少ないんです。毎年" },
		{ kind: "say", speaker: "ren", emo: 6, text: "なんか、切ないっすねそれ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "切なくはないです。そういう日です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "でも母の日はあんなに大騒ぎだったのに" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "五月は電話が鳴りやみませんでした。今日は、二回です" },
		{ kind: "say", speaker: "ren", emo: 4, text: "二回" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "一回は間違い電話でした" },
		{ kind: "say", speaker: "ren", emo: 6, text: "一回じゃないっすかそれ" },
		{ kind: "narration", text: "レンは袋を勘定台の端に置いた。中から桃の丸みが透けている。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、まるはちの。並んでたら八重さんに『ついでに持ってきな』って持たされて。俺、買ってないんですけど" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "うちの分ですね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "はい。俺は運んだだけっす" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "運び賃に、一つどうぞ" },
		{ kind: "say", speaker: "ren", emo: 2, text: "もらいます" },
		{ kind: "narration", text: "レンは桃を一つ手に取って、それから店先のポップに目を留めた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あれ、今日書いたやつっすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "今朝です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "黄色い丸、なんすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "バラです" },
		{ kind: "say", speaker: "ren", emo: 4, text: "バラ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "バラです" },
		{ kind: "say", speaker: "ren", emo: 6, text: "いや、いいと思います。丸だってちゃんと言われれば" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "言われないと分かりませんか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "分かんないっす。でも、あれ、外から見ると通りの端からでも黄色が見えるんですよ。字は読めないけど、黄色だけ届く。だから、あれでいいんじゃないっすかね。読ませる看板じゃなくて、見せる看板ってことで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "そう言われると、直しにくくなります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "直さないでください。俺、あれ好きなんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、丸のままにします" },
		{ kind: "say", speaker: "ren", emo: 2, text: "丸のままで" },
		{ kind: "narration", text: "四時を過ぎて、通りの人出が引いた。日曜の商店街は、夕方の引きが早い。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "明日、月曜っすね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "仏花の日です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "決まってるんですか、曜日" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "月曜に替える方が多いので。土日にお参りをして、月曜に新しくします" },
		{ kind: "say", speaker: "ren", emo: 5, text: "そういうの、全部、頭に入ってるんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "入っているのではなく、書いてあります。祖母の帳面に" },
		{ kind: "say", speaker: "ren", emo: 1, text: "でも、読めるのは入ってる人だけっすよ" },
		{ kind: "narration", text: "若菜は返事の代わりに、桃の袋を作業場のほうへ持っていった。冷やすなら早いほうがいい。冷やしすぎると味が落ちるとも聞くが、今日はもう、店に置いておくと温くなる時間だった。" },
		{ kind: "narration", text: "作業場から戻ると、レンはまだ框に座っていた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "来年の父の日、なんか考えます?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "黄色いバラを、十本入れます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "今年と同じっすか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "今年と同じです。五本売れる年が続けば、そのうち六本になります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "気の長い商売っすね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花屋ですので" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "大神くんは、お父様に何か" },
		{ kind: "say", speaker: "ren", emo: 6, text: "うち、親父は花より丸太が好きなんで。林業なんです、実家。……あ、でも" },
		{ kind: "narration", text: "レンは少し考えて、真顔になった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "丸太も、木ですもんね。花の、でかいやつっていうか。根っこは同じっていうか" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "ふ……" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、お父様は毎日、花束の中で働いてるんですね。誰よりも大きい花束の中で" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それ、今度電話で言っていいですか。親父、絶対変な顔するんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "どうぞ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "電話、まあ、しないんですけど。母としか話さないんで。親父、電話出ても『おう』しか言わないし" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "では、母上経由で" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それだ。母経由。伝言でも変な顔しますよ、たぶん" },
		{ kind: "narration", text: "黄色いバラは、閉店までにあと二本売れた。残りは五本。若菜はそれを束のまま見切り籠に移さず、翌日、店の一番目立つ場所から、目立たない場所へ動かした。売れ残りではなく、まだ来ていない客のぶんという顔で置いておく。祖母の帳面の六月にも、父の日の頁だけ、数字の下に線が引いてなかった。" },
		{ kind: "narration", text: "集計しなかったのか、するほどの数でもなかったのか、それは書いていない。" },
	],
};

// 解放: 六月の全ステージクリア後
const chomen0630: Vignette = {
	id: "m6-chomen-0630",
	kind: "chomen",
	month: 6,
	title: "六月三十日",
	trigger: { at: "month-close", month: 6 },
	synopsis: "六月末の帳面。雨の月の集計と、翌月の仕入れの下書きを書く。",
	lines: [
		{ kind: "diary", text: "六月三十日。曇り、ときどき晴れ。" },
		{ kind: "diary", text: "六月の集計。雨の月にしては、悪くない数字。紫陽花の鉢が牽引した。青の出る土のことを、八重さんに教わった。私は知らないことに水をやって、知らないまま、いい青を咲かせていた。" },
		{ kind: "diary", text: "明礬の手当て、成功。帳面の通りにやれば、帳面の通りになる。祖母の字は、こういうところでは噓をつかない。" },
		{ kind: "diary", text: "雨の日の客の人が、今月は三度来た。白いのを、少し。名前は、まだ知らない。祖母なら、もう姓名で書いている頃だと思う。私はまだ、「雨の日の人」と書く。" },
		{ kind: "diary", text: "父の日。黄色いバラ十本のうち、売れたのは五本。ポップは前日に描いた。来年は前の週に描く。" },
		{ kind: "diary", text: "祖母の帳面の父の日の頁には、数字の下に線がない。書いていないことのほうが、この人の場合は多い。" },
		{ kind: "diary", text: "傘立ての忘れ傘。二本のうち一本は、雨の日に取りに来た人がいた。骨の折れているほうが残った。来月まで置く。" },
		{ kind: "diary", text: "冷蔵ケースの布巾、六月で一枚駄目にした。次は薄いのを買う。" },
		{ kind: "diary", text: "まるはちの裏に、祖母の土が二十キロ。八重さんに教わった。来月、運ぶ手を借りる。借りると言ってしまったわけではないが、たぶん借りる。" },
		{ kind: "diary", text: "桃を一つもらった。運び賃を払ったのはこちらなのに、桃はもともとこちらのものだったらしい。この商店街の勘定は、いまだに分からない。" },
		{ kind: "diary", text: "大神くんの誕生日は、六月十六日。雨の子。米、五キロ。乾電池、単三二十本。" },
		{ kind: "diary", text: "今月の売上、四十一万二千八百円。雨の月にしては、と二度書きそうになった。" },
		{ kind: "diary", text: "内訳。鉢が四割強。切り花は伸びなかった。前の職場で習った通りの月だった。習った通りになると、少しつまらない。" },
		{ kind: "diary", text: "六月の廃棄、切り花で二十七本。五月より減った。減った理由は明礬と、見切り籠に入れる判断を早くしたこと。判断を早くすると、値段は下がるが、捨てる数は減る。どちらが正しいのかは、年末に分かると思う。" },
		{ kind: "diary", text: "傘立てを買い替えた。緑ではない。祖母のは、作業場に置いてある。置き場所が増えていく。" },
		{ kind: "diary", text: "七月の仕入れの下書き。向日葵、笹、枝物。笹は数を読み違えると一年ぶん余る。祖母の去年の数字を、今度は先に見ておく。" },
		{ kind: "diary", text: "ラジオは、結局そのままにしている。" },
		{ kind: "diary", text: "くろまつの豆、今月は二回もらった。返したのは切り花で二本。勘定が合っているのかどうか、こちらから訊く仕組みになっていない。" },
		{ kind: "diary", text: "明礬は、まだ半分残っている。祖母の買った袋だ。使い切ったら、同じものを買うか、別のものを試すか、そのときに考える。" },
		{ kind: "diary", text: "六月の頁を閉じる前に、祖母の六月をもう一度読んだ。姓名で書かれた客の名前が、二十三人分あった。私は、六人。" },
		{ kind: "diary", text: "六人でも、一月の私は零人だった。零人と六人のあいだには、店を開けた日数ぶんの天気がある。" },
		{ kind: "diary", text: "名前を書いた行が、五月より増えている。数字だけつけると決めた頁が、だんだん賑やかになってきた。決めたのは私なので、文句を言う相手がいない。" },
		{ kind: "diary", text: "明日から七月。向日葵の水は、毎日替える。" },
		{ kind: "diary", text: "来年は——と書きかけて、やめた。来年のことは、来年の帳面に書く。" },
	],
};

/** 第六章 水無月。ボス月。ボス「五月雨」はステージ 6-3。 ⚠️並び順が再生順。 */
export const M06: readonly Vignette[] = [
	chomen0605,
	shiroiNoWoSukoshi,
	itsumoNoIchirin,
	kome,
	chomen0614,
	amayadori,
	tokuShitaKao,
	chichiNoHi,
	chomen0630,
];
