/**
 * 花常 本文 第七章 文月「水替え地獄」
 * 原稿から転記した実行時シナリオデータ。
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ7-1の前」 → month-open 7
 *   「ステージ7-1クリア後」「ステージ7-2の前」 → stage-clear m7-1
 *   「ステージ7-2クリア後」「ステージ7-3の前」 → stage-clear m7-2
 *   「ステージ7-3クリア後」 → stage-clear m7-3
 *   「七月の全ステージクリア後」 → month-close 7
 */

import type { Vignette } from "./types.js";

// 解放: ステージ7-1の前
const chomen0702: Vignette = {
	id: "m7-chomen-0702",
	kind: "chomen",
	month: 7,
	title: "七月二日",
	trigger: { at: "month-open", month: 7 },
	synopsis: "夏の帳面。向日葵の水替えの手順と、七夕の笹の予約を書き出す。",
	lines: [
		{ kind: "diary", text: "七月二日。晴れ。今年最初の三十度。" },
		{ kind: "diary", text: "向日葵、四十本。夏の主役は、水を汚す主役でもある。茎の産毛が水を濁らせるので、桶の水替えは朝晩二回。腰にくる。" },
		{ kind: "diary", text: "手順を書いておく。桶を空ける、内側を布で一周、水を張り直す、切り口を指の幅ぶん落とす。四十本を二十本ずつ。慣れれば二十分。慣れるまでは倍かかった。" },
		{ kind: "diary", text: "濁りが黄色いうちは、まだいい。灰色に寄ったら、その日のうちに替える。二日目の水は、花よりも先に、桶の内側がぬめる。" },
		{ kind: "diary", text: "切り落とした茎を入れる箱が、夏はすぐ一杯になる。捨てるために仕入れているような気持ちになる日がある。" },
		{ kind: "diary", text: "三十度を超えると、昼に人は来ない。朝と、日が傾いてから。昼の二時間は、水と道具の時間にすることにした。古帳面も、七月だけ昼の記入が薄い。同じことを考えたのだと思う。" },
		{ kind: "diary", text: "冷蔵ケースの前だけが、店でいちばんいい場所になる。ラジオが節電を呼びかけているけれど、うちのケースは夏は止められない。止めれば、店には何も残らない。" },
		{ kind: "diary", text: "店先の桶に氷を落とすと、通りの人が足を止める。氷は花のためではなく、人のためのものだと思う。古帳面の七月にも、氷の仕入れがちゃんと書いてある。花屋が氷を買う理由を、祖母はどこにも説明していない。" },
		{ kind: "diary", text: "七夕の笹、五本予約。子ども会のぶん。短冊と飾りは向こうで用意するとのこと。" },
		{ kind: "diary", text: "笹は水が下がりやすい。切ってすぐは葉が青いのに、二日で葉先が丸まる。祖母は根元を割って深く立てていた。割る道具がどれか分からず、金槌でやった。たぶん合っている。" },
		{ kind: "diary", text: "市場でいちばん先に売れていくのが向日葵だった。犬飼生花の人が「今年は首が据わってる」と言った。首が据わる、という言い方を初めて聞いた。覚えておく。" },
		{ kind: "diary", text: "打ち水の当番表が回ってきた。花常は夕方の担当。雪かきの当番のときに、誰かがそう決めたらしい。決めた人は覚えていて、私は覚えていなかった。" },
		{ kind: "diary", text: "蟬が鳴き始めた。八重さんが「今年は早い」と言う。去年のことを、私は知らない。この店の去年を知らないまま、今年の帳面をつけている。" },
		{ kind: "diary", text: "桶の水は、朝に替えたものが、昼にはもう温い。温い水は、花にとっては湯だと思ったほうがいい。氷を一つ落とす。それだけで持ちが半日違う。" },
		{ kind: "diary", text: "冷蔵ケースの温度、五度から六度に上げた。切り花は冷やしすぎても傷む。祖母の帳面の夏の頁に、ケースの数字だけが赤い鉛筆で書いてある。理由は書いていない。理由を書かない人だった。" },
		{ kind: "diary", text: "向日葵は、朝いちばんに顔の向きを揃えて活け直す。揃えると、それだけで通りから見て一段よく見える。売れるのは、たいてい端の一本から。" },
		{ kind: "diary", text: "古帳面の七月の余白に一行。「水は花の言うことを聞いて張る」。深いか浅いかを、花に聞け、という意味だと思う。まだ聞こえない。" },
		{ kind: "diary", text: "今日の帳面、名前で書いた行が六。数字だけの行が十一。半年で、ずいぶん入れ替わった。" },
	],
};

// 解放: ステージ7-1クリア後
const sasaNoHi: Vignette = {
	id: "m7-sasa-no-hi",
	kind: "scene",
	month: 7,
	title: "笹の日",
	trigger: { at: "stage-clear", stageId: "m7-1" },
	synopsis: "七夕の笹を五本、店先に立てる。受け取りに来た子ども会の親子と、短冊の結び方の話になる。",
	lines: [
		{ kind: "narration", bg: "front_summer", text: "七月六日の朝、店先の壁に、笹を五本立てかけた。" },
		{ kind: "narration", text: "背丈は若菜の二倍近くあった。立てかけると穂先がトタンの庇に届いて、風が通るたび、葉と葉が擦れて音を出した。乾いた紙をゆっくり捲るような音だった。通りを行く人が、みんな一度は見上げていく。花は見上げられない。笹だけが、この店で見上げられる商品だった。" },
		{ kind: "narration", text: "根元は前の晩に金槌で割って、深い水に立ててある。バケツの水は、朝には薄く笹の色に染まっていた。" },
		{ kind: "narration", text: "笹の根元を割るとき、手が釘へ伸びた。" },
		{ kind: "narration", text: "九時に、子ども会の母親が三人と、子どもが六人、まとめてやってきた。" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "あら、思ったより立派。五本、これ全部ですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "はい。町内会館のぶんが三本、公園が一本、残りの一本は予備です" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "予備まで用意してくださったの" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "折れます。子どもが飾ると、必ず一本は折れると、祖母の帳面に書いてありました" },
		{ kind: "narration", text: "母親たちが笑った。当の子どもらは笹より、店先の桶に浮かべた氷のほうに集まっている。氷を指で押して沈めては、浮いてくるのを見て歓声を上げていた。" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "ねえ、これ竹?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "笹です" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "竹じゃないの?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "大きくなる前の竹、ではありません。笹は笹です。葉の付き方が違うんです" },
		{ kind: "narration", text: "若菜は一枚を指で裏返して見せた。子どもは三秒だけ真剣な顔をして、それから氷に戻っていった。" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "花屋さんなのに、竹売ってるの、へん" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "笹です" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "笹売ってるの、へん" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "七夕は、花屋の仕事なんです。門松も、正月には花屋が売ります" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "じゃあ花屋さんじゃなくて、木屋さんじゃん" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "……その言い方は、初めてされました" },
		{ kind: "narration", text: "母親の一人が、笹の根元のバケツを覗き込んだ。" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "去年は、うちのほうで買いに走ったのよ。駅前まで" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "去年は、店が閉まっていましたので" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "そう。だから今年は、ここでって、春の集まりで最初に決まったの" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "ここに戻ってきてくれて、こっちが助かってるのよ" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "……ありがとうございます" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "お礼を言うところじゃないでしょう。注文したんだから、こっちが" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "そうでした。毎度ありがとうございます" },
		{ kind: "narration", text: "母親は満足そうに頷いて、子どもの一人の襟首を掴んで氷から引き剥がした。" },
		{ kind: "narration", text: "自転車のブレーキが鳴った。レンが荷台に何か括りつけて坂を下りてきて、笹の前で足をついた。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "うわ、でか。これ、店に入らないでしょう" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "入りません。だから外に立てています" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あ、そうか。外に置ける商品なんだ" },
		{ kind: "narration", text: "そのあいだに、女の子が笹の一本に短冊を結びはじめていた。蝶結びを二回、力任せに。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー、それ、ほどけますよ。飾り、風で全部落ちます" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "えっ、やだ!" },
		{ kind: "say", speaker: "ren", emo: 16, text: "貸してください。ここに輪っかを作って、余ったほうを二回くぐらせて、下に垂らす。こうすると、引っ張るほど締まるんです。ほら、動かない" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "おにいさん、なんで知ってんの" },
		{ kind: "say", speaker: "ren", emo: 3, text: "親父が、山で木を括る人なんで。丸太が落ちない結び方なら、短冊くらい落ちません" },
		{ kind: "narration", text: "子どもらが一斉に短冊を差し出した。レンは笹の下にしゃがみ込んで、順番に結びはじめた。耳が笹に触れるたび、葉がさらさらと鳴った。" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "お兄さん、お店の人?" },
		{ kind: "say", speaker: "ren", emo: 6, text: "いやいや、客ですよ" },
		{ kind: "say", speaker: "sub", name: "子ども会の母親", text: "客がそんなに働くもんかしらね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "よく働く客なんです" },
		{ kind: "narration", text: "結び終わった短冊が、風で一斉にこちらを向いた。願いごとの字は、どれも大きくて、笹の丈に対して短かった。" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "おねえさんは、なに書くの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "私は書きません" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "なんで" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "うちは、笹を売る側なので" },
		{ kind: "say", speaker: "sub", name: "女の子", text: "ずるい" },
		{ kind: "say", speaker: "ren", emo: 15, text: "ずるいですよ、それは。俺もそっち側です" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "二人がかりで言わないでください" },
		{ kind: "narration", text: "隣から八重さんが顔を出した。胡瓜を洗っていた手を前掛けで拭きながら、笹を上から下まで眺める。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんも書かなかったよ。毎年、売るだけ売って、自分は一枚も書かないの" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "祖母もですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "願いごとは口に出すもんだ、ってさ。星に頼むくらいなら、隣の家に頼めって、そう言うんだよあの人は" },
		{ kind: "say", speaker: "sub", name: "八重", text: "で、隣の家ってのは、うちだよ" },
		{ kind: "narration", text: "八重さんは自分で言って自分で笑い、胡瓜を一本、子どもに握らせて帰っていった。子どもは笹より胡瓜を喜んだ。" },
		{ kind: "narration", text: "結び方を覚えた男の子が、今度は自分より小さい子の短冊を結んでやっていた。同じ手つきで、同じところを二回くぐらせている。レンは何も言わずにそれを見ていた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "継承されましたね、今" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "三分でしたね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "三分ですよ。うちの同好会なんて、引き継ぎ書に三時間かけて、結局だれも読まないんですから" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "書かずに、隣で結んで見せればいいのでは" },
		{ kind: "say", speaker: "ren", emo: 4, text: "それ、来月の合宿で言っていいですか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "花屋の受け売りだと、断ってから言ってください" },
		{ kind: "narration", text: "十時前に、笹は四本が担がれていった。子どもが二人がかりで先端を持ち、母親が根元を支え、行列は通りをゆっくり進んでいった。葉の擦れる音が、遠ざかっても長いこと聞こえていた。" },
		{ kind: "narration", text: "残った一本を、若菜は水のバケツに立て直した。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "予備って、売れなかったら余っちゃいませんか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "余ります。でも、余らせておくのが仕事です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "なるほどなあ。あ、それサーバーと一緒ですよ。予備機って、動いてないのが正解なんです。動いた瞬間に、どこかが折れてる証拠なんですよ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "折れる前提で持っておくところは、同じですね" },
		{ kind: "narration", text: "夕方、日が傾いてから、小さい男の子が一人で来た。手に百円玉を一枚握っている。" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "笹、ください。ちいさいの" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "一本は、大きすぎます" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "……うん" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "枝先なら、切って差し上げます。五十円で" },
		{ kind: "narration", text: "若菜は予備の一本から穂先を三十センチほど落として、切り口を割り、濡らした新聞紙で巻いて渡した。短冊は、子ども会が置いていった余りを一枚つけた。" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "これ、水いる?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "いります。コップでいいので、毎日替えてください" },
		{ kind: "say", speaker: "sub", name: "男の子", text: "まいにち?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "毎日です。飾りより、そこが大事です" },
		{ kind: "narration", text: "男の子は五十円を置き、五十円を握ったまま走っていった。釣りを取っていかない客は、これで二人目だった。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "残りの五十円、何に使うんですかね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "アイスだと思います。ちょうどです" },
		{ kind: "say", speaker: "ren", emo: 4, text: "計算されてる" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "子どもの財布は、いつも計算されています" },
		{ kind: "narration", text: "日が沈むころ、壁には笹の立てかけてあった跡だけが残っていた。埃の帯が五本ぶん、そこだけ拭われたように白い。若菜は箒でその白を消してから、店を閉めた。" },
	],
};

// 解放: ステージ7-1クリア後
const inuToOokami: Vignette = {
	id: "m7-inu-to-ookami",
	kind: "scene",
	month: 7,
	title: "犬と狼",
	trigger: { at: "stage-clear", stageId: "m7-1" },
	synopsis: "レンが市場を見てみたいと言い出す。数日後、配達に来た犬飼生花の息子と店先で顔を合わせる。",
	choices: [
		{
			id: "B-13",
			label: "市場見学",
			axis: "縁",
			options: [
				{ key: "A", label: "連れて行く", note: "縁+1" },
				{ key: "B", label: "断る" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_day", text: "「一回、市場ってとこ、見てみたいんですよね」と言い出したのはレンだった。" },
		// ◆選択 B-13「市場見学」(軸: 縁)
		// 【B】(※この分岐を選んだ場合、本場面は以下に差し替わる)
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 16, text: "市場は、仕事場なので。見世物ではないんです" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 6, text: "ですよね。すみません" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "彼は素直に引き下がった。引き下がったが、耳は分かりやすく萎れていた。" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 4, text: "買参の札がないと、そもそも中に入れません。祖母の札を、私が引き継いで使っています" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 5, text: "札。木の?" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 17, text: "木です。祖母の名前が彫ってあります" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 2, text: "いいなあ、それ。すごくいいです" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "彼はそれ以上は聞かずに、その日は向日葵を一本買って帰った。" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "——数日後の昼、その埋め合わせのように、店の前に犬飼生花の軽トラが停まった。追加の笹の配達だった。台車を押してきた柴犬の獣人と、ちょうど店にいたレンが、戸口でかち合った。" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "……狼?" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 5, text: "……柴?" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "柴じゃねえ、犬飼だ。名前だ" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 5, text: "大神です。名前です" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "狼で大神って、そのまんまか" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 6, text: "柴犬で犬飼も、そのまんまでしょう" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "……言うな、それは互いに" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "二人は、なぜかそこで固い握手をした。市場に行かなくても、会うものは会うのだった。" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "犬飼は台車の笹を軒下に立てかけると、店の中をぐるりと見回して、勘定台の木札に目を留めた。" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "花常さん。うちの親父が、その札の話をよくします。三隅の婆さんの札は、いつも真っ先に競り場の前に立ってたって" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 8, text: "祖母は、早かったんですか" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "一番乗りだったそうっすよ。で、いい枝は全部さらってく" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 12, text: "真似できる気が、しません" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "真似しなくていいでしょ。札が同じなら、こっちは同じ扱いしますから" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "犬飼は軽トラに戻りかけて、思い出したように振り返った。" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "おい狼。あんた、花屋の何" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 5, text: "常連です" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "sub", name: "犬飼", text: "常連が配達の手伝いすんのかよ" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "言われて初めて、レンは自分が台車の後ろを押していたことに気づいた顔をした。" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "軽トラが行ってしまうと、通りには笹の葉が擦れる音だけが残った。レンは軒下の五本を見上げて、それから若菜を見た。" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 1, text: "あれ、あそこから来るんですね。市場から" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 4, text: "そうです。四時に出て、六時半に戻ります" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 19, text: "符丁って、ほんとにあるんですか。競りの" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 1, text: "あります" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 2, text: "どんなのか、ちょっとだけ" },
		{ kind: "narration", when: { choice: "B-13", is: "B" }, text: "若菜は柄杓を置いて、少し息を吸った。それから、辰巳の速さの半分ほどで、覚えている一節を口に出した。数と色と本数が、意味を失くしたまま続いた。言い終えて、自分でおかしくなった。" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 11, text: "こんな感じです。半分も合っていないと思います" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 4, text: "今の、聞き取れなかったんですけど。日本語です?" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 15, text: "日本語です。三年目くらいで聞こえるようになるらしいです" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 16, text: "三年か。じゃあ俺、まだ何回か聞きに行かないと駄目ですね" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "wakana", emo: 1, text: "入れませんけど" },
		{ kind: "say", when: { choice: "B-13", is: "B" }, speaker: "ren", emo: 6, text: "外で待ってます" },
		// 【A】(※以下、本場面の通り)
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "夏休みに入った最初の週、約束通り、朝四時の店の前に彼は立っていた。立ってはいたが、目が開いていなかった。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 6, text: "朝って、こんなに暗いんですね。初めて知りました" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 4, text: "まだ夜です。乗ってください" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "通りのシャッターはすべて下りていて、街灯が等間隔に並んでいた。白い軽トラの荷台には、空の保冷箱とバケツが積んである。エンジンをかけると、荷台の中で何かが一度だけ転がった。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 19, text: "電車、二駅なんですよね。なんで車で" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 16, text: "帰りに荷物があります。人が乗れる場所は、行きだけです" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 19, text: "じゃあ帰り、俺はどこに乗ればいいんですか" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 15, text: "荷台の花に、席を譲ってください" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 6, text: "花に負けた" },
		{ kind: "narration", bg: "market", when: { choice: "B-13", is: "A" }, text: "浜市場に着く頃、空が白み始めた。" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "場内は外より数度低い。濡れたコンクリートの床に蛍光灯が反射して、通路の端まで白く光っていた。フォークリフトが荷を積んだまま真横を抜けていき、その風でレンの前髪が持っていかれた。段ボールの山、氷の袋、水の滴る音、誰かの怒鳴り声。競り場の熱気にレンは目を覚まし、符丁の渦に、耳をぴんと立てて見入った。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 4, text: "すごいな。全然聞き取れない。あれ、日本語です?" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 1, text: "三年目くらいで聞こえるようになるらしいです" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 2, text: "三年。いや、あれ絶対、数字と色と本数を圧縮して喋ってますよね。同じ音の組が周期で出てくるんで。あれ、法則さえ取れれば" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 13, text: "取れたら教えてください。私はまだ取れていません" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "競り台の上から、辰巳の声が飛んだ。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "辰巳", text: "おう、花常さんとこの! 今日は連れかい" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 1, text: "見学です" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "辰巳", text: "見学結構。若いのは目ぇ肥やしてけ。ただし通路の真ん中に立つな、轢かれるぞ" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "レンはその場で九十度、通路の端に移動した。" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "セリが始まると、辰巳の声は音楽のように速くなった。若菜は向日葵の列の前で、木札を上げた。三度上げて、二度は他所に流れ、一度だけ手元に来た。レンは何も言わずにそれを見ていた。見ていた、というより、聞いていた。" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "終わってから、彼は木札を指した。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 5, text: "それ、名前" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 17, text: "祖母の名前です。買参の札は、店ごとに一枚です" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 19, text: "作り直さないんですか。三隅若菜って" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 10, text: "作り直せます。まだ、していません" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 5, text: "いいと思います、そのままで" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 8, text: "理由を聞いても" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 1, text: "札が古いほうが、店が長いってことなんで。ここ、そういうのが効く場所でしょう" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 1, text: "効きます" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 18, text: "じゃあ、そのままで" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "仲卸の区画を歩いていると、台車を押した若い男と、通路の真ん中でかち合った。柴犬の獣人だった。麦わらの手ぬぐいを首に巻いて、犬飼生花の前掛けをしている。" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "男は、レンを見た。レンも、男を見た。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "……狼?" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 5, text: "……柴?" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "柴じゃねえ、犬飼だ。名前だ" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 5, text: "大神です。名前です" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "狼で大神って、そのまんまか" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 6, text: "柴犬で犬飼も、そのまんまでしょう" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "……言うな、それは互いに" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "二人は、なぜかそこで固い握手をした。若菜には、何がどう決着したのか分からなかった。犬飼と名乗った青年は、若菜の木札を見て、あ、という顔をした。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "花常さんとこの。いつも親父がどうも。——おい狼、あんた花常の関係者か" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 5, text: "常連です" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "常連が四時起きで市場来るかよ" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 6, text: "来ちゃったんですよね" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "まあいい。手ぇ空いてんなら持て。そっち、下から" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "言うが早いか、犬飼は向日葵の箱をレンの腕に載せた。レンは反射で受け止め、そのまま台車まで運んだ。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "軽いだろ。花は軽い。軽いのに、重い顔して運ぶ奴が多いんだよ" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 1, text: "潰したら怖いからでしょう" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "そう。だから箱の角持つの。花の腹は持たない" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 4, text: "なるほど" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "花常さん、今日の向日葵どれ取った" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 4, text: "三番の列の、束ね直してあったほうを" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "正解。あれ首が据わってる。こっちの束は水吸いすぎで、明後日には俯くから" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 8, text: "見ただけで、分かるんですか" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "見ただけっていうか、産地で分かる。あと親父が朝いちで触ってるんで、俺は親父の顔色で分かる" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 7, text: "それ、いちばん高性能なやつじゃないですか" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "だろ。二十年もの" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "若菜が仕入れの伝票を書いているあいだ、二人は箱を挟んで、しばらく何か話していた。犬の耳と狼の耳が、同じ角度で同じ方向に動いた。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "花常さん。この狼、うちの荷運びに借りていいすか" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 15, text: "私の狼ではないので、本人に聞いてください" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 15, text: "時給が出るなら" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "sub", name: "犬飼", text: "出ねえ" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 6, text: "じゃあ、たまにで" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "帰りの軽トラは、荷台が向日葵で埋まった。首の据わった四十本が、走るたびに揃って同じ方向へ傾く。助手席のレンは、坂を上りきる前に眠っていた。" },
		{ kind: "narration", when: { choice: "B-13", is: "A" }, text: "店に着いて荷を下ろし、桶に水を張って、最初の一本を立てたのが六時半だった。ここからが仕事だった。" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 6, text: "俺、まだ何も食ってないんですけど" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 14, text: "私もです。水を替えてからにしましょう" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "ren", emo: 4, text: "もう替えるんですか、今来たばっかりの水を" },
		{ kind: "say", when: { choice: "B-13", is: "A" }, speaker: "wakana", emo: 16, text: "向日葵ですから" },
	],
};

// 解放: ステージ7-2の前
const akitenpoNoUwasa: Vignette = {
	id: "m7-akitenpo-no-uwasa",
	kind: "scene",
	month: 7,
	title: "空き店舗の噂",
	trigger: { at: "stage-clear", stageId: "m7-1" },
	synopsis: "打ち水の時刻、八重さんが通りの空き店舗の話を持ってくる。米屋の主人も足を止める。",
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "六時を回ると、通りの西日が店の奥まで届いた。" },
		{ kind: "narration", text: "若菜は柄杓で水を汲み、店先の舗装に打った。乾いた石が、水を吸って一段濃くなる。跳ねた飛沫が氷の桶に落ちて、細かい音を立てた。向かいの米屋も同じ時刻に水を打っていて、通りの東と西から、湿った空気が真ん中でぶつかった。" },
		{ kind: "narration", text: "八重さんは「ついで」と言って胡瓜を三本置き、声をひそめて、通りの奥を顎で指した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "米屋の隣の空き店舗、あるだろ。買いたいって人が出てるらしいよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お店が入るなら、いいことじゃ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "それがね、店っていうか……なんとかって会社が、この一角まとめてどうこうって話らしくてさ。再開発ってやつかい。まだ噂だけどね" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "一角、まとめて" },
		{ kind: "say", speaker: "sub", name: "八重", text: "先週から、黒い車が三回来てる。中から出てこないで、通りの写真だけ撮って帰るんだ。三回目はあたしが見てたら、窓を閉めたよ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "どなたから聞かれたんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "霜月堂の若旦那。あすこは組合の役だから、耳が早いの。でもね、あの子も『まだ何も決まってない』の一点張りでさ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "決まっていないなら、噂ですね" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そう。噂" },
		{ kind: "narration", text: "米屋の主人が、水を打ち終えた柄杓を提げて通りかかり、話の途中に足を止めた。" },
		{ kind: "say", speaker: "sub", name: "米屋", text: "うちには何も来てないよ。隣なのにさ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃあんた、隣から声かけたら、隣が騒ぐからだろ" },
		{ kind: "say", speaker: "sub", name: "米屋", text: "じゃあ最後に来るのか、うちは" },
		{ kind: "say", speaker: "sub", name: "八重", text: "最後だろうね。うちも最後だよ" },
		{ kind: "narration", text: "米屋の主人は、なるほど、という顔をして、柄杓を提げたまま帰っていった。八重さんはその背中を見送って、声の高さを元に戻した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん。うちらの世代はさ、この話、二回目なんだ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "二回目" },
		{ kind: "say", speaker: "sub", name: "八重", text: "二十年前にも一度あったの。駅前が先に更地になってさ。こっちまで来るって言われて、みんなで判子押すの押さないので揉めて。結局、来なかった" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "来なかったんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "景気が悪くなってね。向こうが逃げたの。だからみんな、今度も来ないと思ってる。二回目って、そういうふうに効くんだよ。効きすぎるんだ、たぶん" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "祖母は、そのとき" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃん? あの人はね、判子の話には一切乗らないの。会合にも出ない。で、当日になって『店開けるよ、あたしは』って、それだけ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "祖母らしいです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "らしいけどね。あれ、いちばん強い言い方なんだよ、ああいうの" },
		{ kind: "narration", text: "八重さんは前掛けの紐を結び直しながら、若菜の顔を覗き込んだ。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんたは、どうすんの" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "明日も、店を開けます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "ああ、そう" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そういうとこだけ、よく似るんだねえ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "似てませんけど" },
		{ kind: "say", speaker: "sub", name: "八重", text: "似てるよ。言い方の短さが同じだもの" },
		{ kind: "narration", text: "八重さんは胡瓜の袋を勘定台に置き直して、通りの奥をもう一度見た。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あすこ、もとは瀬戸物屋だよ。婆さんが一人でやっててね。常ちゃんとは犬猿だった" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "祖母と、仲が悪かったんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花瓶の値段で三十年、揉めてたの。花常が花瓶を置くのは商売の邪魔だ、いや花を買った人が入れ物に困る、って。互いに一歩も引かない" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "三十年" },
		{ kind: "say", speaker: "sub", name: "八重", text: "でね、婆さんが店を畳むって日にさ、常ちゃんが花持って行ったんだよ。デカいのを一抱え。ざまあみろって顔してさ。婆さんは婆さんで、いちばん高い花瓶をタダで押しつけて帰ってきた" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "どちらも、勝った気でいますね" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そういう人たちなの、あの世代は" },
		{ kind: "narration", text: "八重さんは笑って、それから笑うのをやめた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "まだ噂。……まだ噂だけどさ" },
		{ kind: "narration", text: "八重さんは同じ言葉を二度言って、胡瓜の分の小銭も受け取らずに帰っていった。" },
		{ kind: "narration", text: "若菜は店の奥から通りを眺めた。米屋の隣の空き店舗は、シャッターの錆が目立つ。夕日が当たると、錆の色だけが赤く浮いて見える。あそこに何があったのか、若菜は知らなかった。今日、知った。" },
		{ kind: "narration", text: "閉店後、若菜は古帳面を出して、後ろから頁を繰った。仕入れと売上の数字の列を遡っていくと、十年ぶん戻ったあたりに、大きな束の記録があった。値段の欄に、線が引いてある。金額が書いていない。代わりに、余白に四文字だけ、祖母の字があった。" },
		{ kind: "narration", text: "「花瓶一個」" },
		{ kind: "narration", text: "若菜は帳面を閉じた。店の隅に、いつからあるのか分からない大ぶりの花瓶が、水も入れずに置いてある。白い地に藍の線が二本、口のところで途切れている。値札はついていない。この店で値札のついていない物は、売り物ではない物だった。" },
		{ kind: "narration", text: "若菜は花瓶を両手で持ち上げた。空なのに重かった。底に、埃と一緒に、丸めた紙が一枚入っていた。広げると、瀬戸物屋の値札だった。数字の上に、二重線が引いてある。" },
		{ kind: "narration", text: "紙は元のとおりに丸めて、底に戻した。" },
		{ kind: "narration", text: "戸締まりの前に、若菜は通りを奥まで歩いた。" },
		{ kind: "narration", text: "米屋の隣のシャッターは、下から三十センチほどのところが波打っている。何度も何かをぶつけられた形だった。脇の壁に、色の褪せた紙が一枚、糊の跡だけ残して剥がれかけている。読める字は「まで」の二文字だけだった。いつまで、なのか、どこまで、なのかは分からない。" },
		{ kind: "narration", text: "シャッターの下の隙間に、笹の葉が一枚吹き込んで挟まっていた。今朝、この通りを行列が通っていったときのものだった。" },
		{ kind: "narration", text: "若菜は葉を抜いて、手の中で丸めた。店に戻り、通りに面したガラス戸に鍵をかける前に、灯りをもう一度点けた。点けたまま、通りを一度見た。米屋の隣だけが、暗いままだった。" },
	],
};

// 解放: ステージ7-2クリア後
const ichirinBunNoBasho: Vignette = {
	id: "m7-ichirin-bun-no-basho",
	kind: "scene",
	month: 7,
	title: "一輪ぶんの場所",
	trigger: { at: "stage-clear", stageId: "m7-2" },
	synopsis: "暑い午後、レンが小さい向日葵を買いに来る。部屋のどこへ置くか、という話になる。",
	choices: [
		{
			id: "B-14",
			label: "言い掛けの続き",
			axis: "問い",
			options: [
				{ key: "A", label: "続きを促す", note: "問い+1" },
				{ key: "B", label: "待つ" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_day", text: "七月半ばの午後は、通りから音が消える。" },
		{ kind: "narration", text: "蟬だけが鳴いていた。店先の日除けの内側で、扇風機が首を振り、桶の氷はもう半分に痩せている。冷蔵ケースの硝子が汗をかいて、内側の白い花が滲んで見えた。若菜は作業台で、三度目の水替えの支度をしていた。" },
		{ kind: "narration", text: "戸が開くというより、突き飛ばされるように鳴った。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あっつ!! ——これください。向日葵。小さいやつで" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "まず、そこに立ってください。冷蔵ケースの前が、いちばん涼しいです" },
		{ kind: "narration", text: "レンは素直に立った。立って、しばらく黙って、耳の付け根まで冷やしてから戻ってきた。" },
		{ kind: "say", speaker: "ren", emo: 13, text: "生き返った。この店の、いちばんいい席ですね、ここ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花のための場所なんですけどね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "花、涼しいとこで働けていいな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花は働いていません" },
		{ kind: "narration", text: "彼は笑って、シャツの背中を扇風機に向けた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "合宿、行ってきたんですよ。山で三日。同好会の" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "山で、何を" },
		{ kind: "say", speaker: "ren", emo: 2, text: "サーバー組むんです。廃校になった小学校の教室借りて、机並べて、電源引いて。夜、涼しいんで機械の調子がいいんですよ。都会の夏って、機械のほうが先に音を上げるんで。それで山に持ってく。理科室の流しで水冷やったやつもいて、あれは怒られましたけど、でも発想としては正しくて——" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "速度が" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ。早口でした?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "早口でした。半分も分かりませんでした" },
		{ kind: "say", speaker: "ren", emo: 6, text: "すみません" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "謝らないでください。分からないのは、私の問題です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "いや、話す側の問題ですよ、それは。えっと。夏は、機械が暑がるんです。暑がると遅くなる。だから涼しいとこに持っていくと、機嫌がいい。それだけの話です" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "それは、分かります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "でしょう" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "うちのケースと同じですね。花も、暑がると早く終わります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、それですよ、それ。冷やすのは、長く保たせるためなんですよね。速くするためじゃなくて" },
		{ kind: "narration", text: "若菜は手を止めずに聞いていた。桶の水を流し、内側を布で一周する。同じ動作を、今日はもう三度している。" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "そちらは、暑いと止まるんですか" },
		{ kind: "say", speaker: "ren", emo: 5, text: "止まります。夏の夜中に鳴るんですよ、警報が。枕元で" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "枕元" },
		{ kind: "say", speaker: "ren", emo: 1, text: "起きて、窓開けて、扇風機の向き変えて、また寝ます" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "水替えと、同じですね" },
		{ kind: "say", speaker: "ren", emo: 2, text: "同じですね" },
		{ kind: "narration", text: "彼はそこで少し黙って、それから笑った。" },
		{ kind: "narration", text: "若菜は桶から向日葵を一本ずつ抜いて、切り口を水の中で落としていった。抜くたび、茎の産毛に濁った水がまとわりつく。レンはケースにもたれて、その手元を見ていた。" },
		{ kind: "say", speaker: "ren", emo: 20, text: "それ、毎日やってるんですよね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "朝と、夕方と、暑い日はもう一回" },
		{ kind: "say", speaker: "ren", emo: 15, text: "向日葵、水汚しすぎでしょう。あんな顔して" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "あんな顔をしているから、許されるんです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あー、分かる。世の中そういうやついる" },
		{ kind: "narration", text: "戸が開いて、日傘の女性が首だけ入れてきた。" },
		{ kind: "say", speaker: "sub", name: "女性の客", text: "ごめんなさい、向日葵、三本だけ。長いままで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "はい。少々お待ちください" },
		{ kind: "narration", text: "若菜は替えたばかりの桶から三本を抜き、丈を揃えて、水を切り、袋の底に湿らせた新聞を敷いた。会計まで一分もかからなかった。女性は礼を言って、日傘の下に花を入れて帰っていった。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "早" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "長いままの注文は、早いんです。切らないので" },
		{ kind: "say", speaker: "ren", emo: 1, text: "今の人、迷わなかったですね。入ってくる前から決まってる感じでした" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "夏はそうです。冬は、皆さん十分迷われます" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんでですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "暑いからです" },
		{ kind: "say", speaker: "ren", emo: 6, text: "身も蓋もない" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花屋の夏は、だいたい身も蓋もないです" },
		{ kind: "narration", text: "若菜は満杯の桶に手をかけた。持ち上げる前に、横から手が伸びてきた。" },
		{ kind: "say", speaker: "ren", emo: 16, text: "片側、持ちます" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "重いです" },
		{ kind: "say", speaker: "ren", emo: 5, text: "二人で持てば半分でしょう" },
		{ kind: "narration", text: "二人で作業場まで運び、流しに空けた。濁った水が渦を巻いて落ちていく。レンは空になった桶の内側を覗き込んだ。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "うわ、ぬるぬるしてる。すごいな、これ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "それが原因です。花より先に、桶が汚れます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、布で拭くんですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "一周。ぐるりと。角も" },
		{ kind: "narration", text: "彼は袖をまくって、言われたとおりに一周させた。二周目もやろうとしたので、若菜は止めた。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "一周で足ります。二周すると、今度は布のほうが汚れを配ります" },
		{ kind: "say", speaker: "ren", emo: 5, text: "手順が決まってるやつだ、これ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "決まっています。祖母が決めて、私が変えていません" },
		{ kind: "say", speaker: "ren", emo: 19, text: "変えないんですか" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "変えたほうがいい理由が、まだ見つかっていません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "その言い方、うちの先輩とそっくりですよ。動いてるものは触るな、って" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花屋にも、同じ言葉があります" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "小さいのばかりですね。先月も、その前も" },
		{ kind: "say", speaker: "ren", emo: 6, text: "下宿の机、狭いんですよ。モニタ二枚あるし、サーバーも枕元で回ってるし" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "枕元でサーバー" },
		{ kind: "say", speaker: "ren", emo: 15, text: "ファンの音、聞いてると寝れるんですよ。あ、引かないでください" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "引いてません。花を置く場所くらい、と思っただけです" },
		{ kind: "say", speaker: "ren", emo: 18, text: "あるんですよ、一輪ぶんだけ。窓のとこ、ちゃんと空けてるんです" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "空けている、というのは。何も置いていないということですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "そう。教科書とか積むと、すぐそこ埋まるんで。埋めないようにしてます" },
		{ kind: "narration", text: "彼はそこで、少し声の速度を落とした。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "部屋に花があると——" },
		// ◆選択 B-14「言い掛けの続き」(軸: 問い)
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "wakana", emo: 8, text: "あると?" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "ren", emo: 15, text: "……" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "ren", emo: 18, text: "いつか、ちゃんと言います。これ、ちゃんと言いたいやつなんで。中途半端に言うと、もったいないんで" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "wakana", emo: 21, text: "……では、ちゃんと言える日に" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "ren", emo: 2, text: "はい。予約で" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "wakana", emo: 4, text: "承ります。ご希望の日は" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "ren", emo: 6, text: "未定です" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "wakana", emo: 15, text: "未定の予約は、普通は受けないんですけどね" },
		{ kind: "say", when: { choice: "B-14", is: "A" }, speaker: "ren", emo: 15, text: "普通じゃない客なんで" },
		{ kind: "narration", when: { choice: "B-14", is: "A" }, text: "花の予約は受けても、言葉の予約を受けたのは初めてだった。" },
		{ kind: "say", when: { choice: "B-14", is: "B" }, speaker: "wakana", emo: 19, text: "?" },
		{ kind: "say", when: { choice: "B-14", is: "B" }, speaker: "ren", emo: 15, text: "いや。なんでもないです。とにかく、あるんです、場所" },
		{ kind: "say", when: { choice: "B-14", is: "B" }, speaker: "wakana", emo: 1, text: "場所は、聞きました" },
		{ kind: "say", when: { choice: "B-14", is: "B" }, speaker: "ren", emo: 6, text: "聞きましたね。はい。場所の話です。それだけです" },
		{ kind: "narration", when: { choice: "B-14", is: "B" }, text: "彼は同じ言葉を三回言い直して、それで終わりにした。若菜も、それで終わりにした。窓辺のことは、聞かないほうが長く続く話に思えた。" },
		// 【合流】
		{ kind: "narration", text: "若菜は向日葵の中で、いちばん小さくて、いちばん顔のいい一本を選んだ。首の据わりを指で確かめ、下の葉を二枚落とす。葉を残すと水が保たない。新聞紙を斜めに、一巻き。この頃には、手が覚えてしまっていた。" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "今月のぶんです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "どうも。あー、夏はやっぱりこれですよ。持ってるだけで暑いのに、なんか嬉しいんだよな" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "水は、毎日替えてください" },
		{ kind: "say", speaker: "ren", emo: 4, text: "毎日" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "毎日です。一本でも、桶と同じことが起きます。濁ったら、その日のうちに" },
		{ kind: "say", speaker: "ren", emo: 16, text: "了解です。監視項目が一つ増えた" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "監視" },
		{ kind: "say", speaker: "ren", emo: 2, text: "毎日決まった時間に見て、変わってたら手を打つ。それ、監視っていうんですよ、こっちの言葉で" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "……こちらの言葉では、世話といいます" },
		{ kind: "narration", text: "レンは口を開いて、何か言おうとして、やめた。それから新聞紙の包みを、抱えるでもなく、垂らすでもない持ち方に直した。" },
		{ kind: "say", speaker: "ren", emo: 18, text: "じゃあ、世話してきます" },
		{ kind: "narration", text: "戸が閉まって、蟬の音が戻ってきた。若菜は日除けの隙間から、坂を上っていく背中を見た。向日葵の顔だけが、包みの上で一つ、上を向いて揺れていた。" },
		{ kind: "narration", text: "坂の途中で自転車を降りて、彼は押して歩きはじめた。片手にハンドル、片手に包み。押していけば時間はかかる。かかるほうを選んだ理由は、たぶん花のほうにある。" },
		{ kind: "narration", text: "若菜は日除けを戻し、桶の氷を一つ足した。ケースの硝子を布で拭いて、汗を取る。四時にはまた水を替える。夕方には打ち水がある。夏の一日は、同じことを何度もやる日として組み立てられていて、それでちょうど回っていた。" },
		{ kind: "narration", text: "勘定台に戻って、帳面に一行、名前で書いた。今日の一輪の欄には、向日葵、と種類だけを書いた。宛先は、書く欄がない。" },
	],
};

// 解放: ステージ7-3の前
const chomen0720: Vignette = {
	id: "m7-chomen-0720",
	kind: "chomen",
	month: 7,
	title: "七月二十日",
	trigger: { at: "stage-clear", stageId: "m7-2" },
	synopsis: "月半ばの帳面。水替えと打ち水の日課、氷の仕入れ、市場で言われたことを書く。",
	lines: [
		{ kind: "diary", text: "七月二十日。晴れ。連日三十度超え。" },
		{ kind: "diary", text: "水替え、朝晩二回。手の甲だけ日に焼けた。腕時計の跡が白く残っている。" },
		{ kind: "diary", text: "向日葵、二度完売。夏の花は迷われない。買う人が「これ」と言うまでが早い。" },
		{ kind: "diary", text: "大神くんは、サーバー同好会の合宿の話をしてくれた。山の廃校でサーバーを組む合宿らしい。夜が涼しいと機械の調子がいい、というところまでは分かった。そこから先は分からなかった。" },
		{ kind: "diary", text: "私は花の話しかできない。それを、最近すこし、悔しく思う。" },
		{ kind: "diary", text: "悔しい、と書けるようになったのは、進歩だと思うことにする。一月の私は、この欄に本数しか書いていない。" },
		{ kind: "diary", text: "市場で、犬飼生花の息子さんに「花の腹は持つな、箱の角を持て」と言われた。三年やっていて、誰にも言われたことがなかった。言わない人は、私が知っていると思っているのだと思う。" },
		{ kind: "diary", text: "打ち水は、六時。米屋さんと同じ時刻になる。向かいで柄杓の音がすると、こちらも出る。約束はしていない。約束していないことのほうが、この通りでは続くらしい。" },
		{ kind: "diary", text: "氷は一日で二貫。氷屋さんに「花屋がいちばん買う夏だね」と言われた。人のために買っていることは、言わなかった。" },
		{ kind: "diary", text: "古帳面の七月の余白に、「夏は店が狭いくらいがいい」。今なら分かる。狭いと、涼しく見える。品物を通路の側まで出せば、客は日陰を歩いて店に入ることになる。祖母は涼しさを売っていたのだと思う。" },
		{ kind: "diary", text: "冷蔵ケースの前に立ちたがる客が増えた。花を見ているのか涼んでいるのか分からない。祖母なら、涼んでいるほうを歓迎したと思う。涼んだ人は、帰りに一本買う。" },
		{ kind: "diary", text: "空き店舗の前の黒い車を、私も一度見た。写真を撮って、すぐ行った。こちらの店の前でも、一度速度を落とした。それだけのことを、私は帳面に書いている。" },
		{ kind: "diary", text: "雨の日の人は、七月は一度も来ていない。晴れが続いているから、それはそうなのだった。それはそうなのに、ケースの白い花を見ると、数を数えてしまう。" },
		{ kind: "diary", text: "祖母の帳面の七月は、名前がぐっと減って、数字ばかりになる。暑いと、人は名前を書くのも億劫になるらしい。私も今日、三行めまで数字だった。" },
		{ kind: "diary", text: "笹の枝先を五十円で買っていった男の子が、四日後にまた来た。枯らしたと言いに来たらしい。水は替えたが、コップを日の当たる窓に置いていたそうだ。次はこうしなさい、と言ったら、真剣にうなずいて帰った。次がある前提で聞く子どもは、強いと思う。" },
		{ kind: "diary", text: "冷蔵ケースの数字を、祖母は赤鉛筆で書いていた。赤で書く必要のあるものが、この店にはいくつかあるらしい。私はまだ、全部の場所を知らない。" },
		{ kind: "diary", text: "予備の笹が一本、まだ裏に立ててある。誰も要らないまま、葉先から丸まってきた。余らせておくのが仕事だと自分で言ったのに、余ったものを見るのは、あまり気分のいいものではない。" },
		{ kind: "diary", text: "大きい花瓶に水を張ってみた。三日で澄んだままだった。いい焼き物なのだと思う。値段は、たぶん一生分からない。" },
	],
};

// 解放: ステージ7-3クリア後
const yuudachi: Vignette = {
	id: "m7-yuudachi",
	kind: "scene",
	month: 7,
	title: "夕立",
	trigger: { at: "stage-clear", stageId: "m7-3" },
	synopsis: "四時の夕立。店先の鉢を二人で軒下へ運び込み、雨の上がるまでの二十分を過ごす。",
	lines: [
		{ kind: "narration", bg: "front_summer", text: "四時の空が、いきなり暗くなった。" },
		{ kind: "narration", text: "蟬が一斉に鳴きやんだ。通りの温度がひと息に下がって、湿った風が北から吹き抜け、店先の日除けを内側から膨らませた。坂の上のほうから、屋根を伝って音が近づいてくる。まだ通りは乾いているのに、音だけが先に来ていた。" },
		{ kind: "narration", text: "最初の一粒が舗装を打ったときには、若菜はもう店先に出ていた。鉢を抱え、看板を倒し——そこへ、ちょうど坂を下りてきた自転車が急停車した。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "降ってきた!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "鉢、そっちの三つを" },
		{ kind: "narration", text: "言葉はそれだけで足りた。レンは自転車を投げるように壁に立てかけて、若菜と入れ違いに軒下へ走った。" },
		{ kind: "say", speaker: "ren", emo: 16, text: "これ、重いやつ! 持ち方は!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "下から。縁は割れます" },
		{ kind: "say", speaker: "ren", emo: 16, text: "了解!" },
		{ kind: "narration", text: "二往復した時点で、雨脚が音を変えた。三往復目には、通りの向こうの看板がもう白く霞んでいた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、うちの台! そこの台だけ入れといて!" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "ren", emo: 19, text: "隣のも運ぶんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "隣のも運びます。うちの鉢を、あちらが運ぶ日もあります" },
		{ kind: "narration", text: "四往復して、最後の鉢を軒に入れたのと、雨が本降りになったのは同時だった。トタンが鳴りはじめた。丸い音が、六月よりずっと速い。今度は、濡れなかった。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "……勝ちましたね、今の" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "勝ちました" },
		{ kind: "say", speaker: "ren", emo: 15, text: "三月は、こう、全部持っていかれたじゃないですか。簾も、俺も" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "簾は、まだ乾かしてあります。使えます" },
		{ kind: "say", speaker: "ren", emo: 2, text: "俺も使えます" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "存じています" },
		{ kind: "narration", text: "軒の下は、通りより二度ほど涼しかった。雨が庇を叩く音の下で、二人はしばらく息を整えていた。レンの髪の先だけが濡れて、肩に垂れている。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "これ、毎日来るんですか、夏って" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "毎日ではありません。来る日は、四時前に風が変わります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "風で分かるんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "音でも分かります。坂の上から屋根を伝って、先に来るので" },
		{ kind: "say", speaker: "ren", emo: 5, text: "それ、通知より早いな" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "通知" },
		{ kind: "say", speaker: "ren", emo: 1, text: "スマホの雨雲のやつです。俺、それ見て降りてきたんですよ。間に合わないと思ったけど" },
		{ kind: "say", speaker: "wakana", emo: 9, text: "間に合いましたね" },
		{ kind: "say", speaker: "ren", emo: 13, text: "間に合いました。でも、若菜さんのほうが三分早かったです" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "風のほうが早いんです。私が早いのではなくて" },
		{ kind: "narration", text: "二人は並んで、雨の向こうの商店街を見ていた。まるはちの店先で、八重さんが胡瓜の台に手早くビニールを掛けている。米屋のシャッターが半分だけ下りる。誰も慌てていなかった。夏の雨は、いつも二十分で終わると、通り全体が知っている顔をしていた。" },
		{ kind: "narration", text: "若菜は軒の先に置いたままの桶を見た。向日葵を挿した桶に、雨がまっすぐ落ちている。水面が跳ねて、濁りが縁から溢れ、澄んだ雨に押し出されていく。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "桶は、出しておきます" },
		{ kind: "say", speaker: "ren", emo: 19, text: "あれは濡らしていいんですか" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "あれは、替えてもらっているところです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "タダで水替えしてもらってる" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "夏に一度だけ、こちらが得をする日です" },
		{ kind: "narration", text: "夕立は二十分で通り過ぎた。" },
		{ kind: "narration", text: "上がったあとの商店街は、路面が黒く光って、店々の灯りが水たまりの中に、逆さまにもう一つずつ点いていた。熱を持った舗装から水が立ちのぼって、雨に叩かれた土と埃の、夏のあいだだけの匂いがした。若菜が今年、初めて嗅いだ匂いだった。" },
		{ kind: "say", speaker: "ren", emo: 13, text: "あー……夏だなあ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "夏ですね" },
		{ kind: "narration", text: "それ以上の会話はなかった。なくて、ちょうどよかった。" },
		{ kind: "narration", text: "やがてレンが軒を出て、水たまりを一つ避けそこねた。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "うわ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "六時の打ち水は、今日は要りませんね" },
		{ kind: "say", speaker: "ren", emo: 2, text: "空が当番代わってくれたんですね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "当番表には、載っていませんけど" },
		{ kind: "narration", text: "若菜は柄杓を桶に戻した。鉢を一つずつ、また表に出していく。雨に一度濡れた葉は、色が濃くなって、店先が朝より賑やかに見えた。" },
		{ kind: "narration", text: "レンは自転車を起こしながら、隣の店先を見た。八重さんが胡瓜の台のビニールを剥がして、こちらに手を挙げている。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、うちの台ありがとね。狼くんも" },
		{ kind: "say", speaker: "ren", emo: 6, text: "狼くんになってる" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "この通りでは、二回目に会うと名前が決まります" },
		{ kind: "say", speaker: "ren", emo: 19, text: "決めるの、誰なんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "八重さんです" },
		{ kind: "say", speaker: "ren", emo: 4, text: "強い" },
		{ kind: "narration", text: "坂の下の路面が、まだ薄く湯気を上げていた。レンは自転車にまたがって、それから思い出したように振り返った。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "そういえば、鉢って、雨に当てちゃ駄目なんですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "当たっても平気なものと、駄目なものがあります。土が流れるものと、葉が傷むものと" },
		{ kind: "say", speaker: "ren", emo: 19, text: "じゃあ、さっきの四往復、全部は要らなかった?" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "要らなかったものも、ありました" },
		{ kind: "say", speaker: "ren", emo: 6, text: "先に言ってくださいよ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "選んでいる時間で、全部濡れます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "なるほど。全部運ぶが最適解か" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "夏は、だいたいそうです" },
		{ kind: "narration", text: "彼は坂を上っていき、途中で一度、水たまりを大きく避けた。避けきれていなかった。" },
		{ kind: "narration", text: "若菜は最後の鉢を定位置に戻し、桶を覗いた。雨に押し出された濁りは、縁のあたりに薄く輪を残しているだけだった。指を入れると、水は朝より冷たかった。向日葵は、四十本のうち三十七本が残っている。夕方までに、あと何本か出るはずだった。" },
	],
};

// 解放: 七月の全ステージクリア後
const chomen0731: Vignette = {
	id: "m7-chomen-0731",
	kind: "chomen",
	month: 7,
	title: "七月三十一日",
	trigger: { at: "month-close", month: 7 },
	synopsis: "七月の締めの帳面。向日葵と笹の数を並べ、店の隅の大きい花瓶を使うことに決める。",
	lines: [
		{ kind: "diary", text: "七月三十一日。晴れ。" },
		{ kind: "diary", text: "七月の集計。向日葵、完売が二回。笹、五本と枝先が一本。水替えの腰痛と引き換えの数字。" },
		{ kind: "diary", text: "七夕の笹は、四本が担がれて通りを行った。子どもの行列の速さに合わせると、葉の音がずっと鳴っている。あれは商品の音ではなくて、行事の音だった。" },
		{ kind: "diary", text: "祖母は短冊を書かなかったそうだ。星に頼むくらいなら隣に頼め、と。隣とは八重さんのことだった。だいたい合っている気がする。" },
		{ kind: "diary", text: "市場に大神くんを連れて行った。犬飼生花の息子さんと、犬と狼の理屈で仲良くなっていた。理屈は分からないが、ああいうものらしい。握手の理由を二人とも説明しないので、聞くのはやめた。" },
		{ kind: "diary", text: "辰巳さんに「目ぇ肥やしてけ」と言われたのは、私ではなく彼のほうだった。少し悔しい。今月は悔しいばかり書いている。" },
		{ kind: "diary", text: "空き店舗の噂。まだ噂。八重さんが「まだ噂」と二度言うときは、噂ではなくなりかけている時だと、私はもう知っている。" },
		{ kind: "diary", text: "空き店舗は、もとは瀬戸物屋だった。祖母と三十年揉めていたそうだ。店の隅の大きい花瓶は、たぶん、その揉め事の終わりに来たものだ。水を張って、明日から使うことにする。置いてあるだけの物を、道具に戻す。" },
		{ kind: "diary", text: "彼の部屋には、一輪ぶんの場所が空けてあるらしい。埋めないようにしている、と言っていた。空けておくのは、余らせておくのと同じで、手間のかかることだと思う。" },
		{ kind: "diary", text: "「部屋に花があると」の続きを、また聞きそびれた。今度のは、聞きそびれたのではなくて、彼が言わなかったのだけど。" },
		{ kind: "diary", text: "言いかけてやめる人の続きは、待つことにしている。枝物と同じで、待てば咲く。" },
		{ kind: "diary", text: "二十年前にも、同じ噂があったと八重さんに聞いた。そのときは来なかったそうだ。来なかった、を二回続けて信じられるほど、私はこの通りを長く見ていない。" },
		{ kind: "diary", text: "祖母は会合に出ず、当日に「店開けるよ、あたしは」と言ったらしい。これも受け売りだけれど、いま書いておく。使う日が来るかもしれないので。" },
		{ kind: "diary", text: "夕立で四往復した。半分は運ばなくてよかった鉢だった。選ぶ時間で全部濡れる、と自分で言って、自分で少し驚いた。三年前の私なら、まず選別表を作っていたと思う。" },
		{ kind: "diary", text: "打ち水は結局、七月は二十二回。空が七回、代わってくれた。" },
		{ kind: "diary", text: "桶の水替え、延べ六十八回。数えていたわけではなく、腰の湿布の枚数から逆算した。" },
		{ kind: "diary", text: "大神くんが桶を一つ運んだ。布で内側を一周させて、二周目をやろうとしたので止めた。手順を人に教えたのは、この店では初めてだった。教えられる側でいるほうが、まだ楽だと思う。" },
		{ kind: "diary", text: "手の甲の日焼けは、袖の線でくっきり分かれている。祖母の写真の手も、同じところで分かれていた。同じ仕事をすると、同じところが焼けるらしい。" },
		{ kind: "diary", text: "予備の笹は、今日、裏で片付けた。余らせておくのが仕事で、片付けるところまでが仕事だった。来年も五本注文が来るなら、また六本仕入れる。" },
		{ kind: "diary", text: "七月の名前の行、四十一。数字だけの行、五十六。六月より名前が七行増えた。増やそうとして増えたわけではない。書けたから書いた、という順番だと思う。" },
		{ kind: "diary", text: "八月は盆。祖母の帳面がいちばん厚くなる月が、来る。仕入れの桁が違う。今から読んでおく。" },
	],
};
/** 第七章 文月「水替え地獄」。 ⚠️並び順が再生順。 */
export const M07: readonly Vignette[] = [
	chomen0702,
	sasaNoHi,
	inuToOokami,
	akitenpoNoUwasa,
	ichirinBunNoBasho,
	chomen0720,
	yuudachi,
	chomen0731,
];
