/**
 * 花常 本文 第八章 葉月「裏方の盆」
 * 正本: packages/frontend/hanaawase/HANATSUNE-STORY-08.md
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ8-1の前」 → month-open 8
 *   「ステージ8-1クリア後・前半」「ステージ8-1クリア後・後半」「ステージ8-2の前」 → stage-clear m8-1
 *   「ステージ8-2クリア後」「ステージ8-3の前」 → stage-clear m8-2
 *   「ステージ8-3クリア後」 → stage-clear m8-3
 *   「八月の全ステージクリア後・前半」「八月の全ステージクリア後・後半」 → month-close 8
 */

import type { Vignette } from "./types.js";

// 解放: ステージ8-1の前
const chomen0801: Vignette = {
	id: "m8-chomen-0801",
	kind: "chomen",
	month: 8,
	title: "八月一日",
	trigger: { at: "month-open", month: 8 },
	synopsis: "盆の陣立ての帳面。仏花八十束の内訳と、盆に店を開けるかどうかの迷いを書く。",
	lines: [
		{ kind: "diary", text: "八月一日。晴れ。朝で二十九度。" },
		{ kind: "diary", text: "盆の陣立て。仏花の束、去年の祖母の数字を参考に八十で仕込む。ほおずき、二十袋。りんどうの走り、三十本。" },
		{ kind: "diary", text: "一束の内訳を書いておく。白菊三、小菊の黄を二、りんどう一、樒、まわりに孔雀草。これで一束。八十束ぶんの本数に掛け直して、市場の注文票に落とすのに、朝の一時間を使った。掛け算だけで一時間かかる仕事は、そう多くないと思う。" },
		{ kind: "diary", text: "祖母の去年の八月の頁を見た。仏花七十八。訂正線が一本引いてあって、八十に直してある。途中で二束足りなくなったのだろう。だから私は最初から八十で組む。" },
		{ kind: "diary", text: "ほおずきは袋のまま吊るしておくと、乾いて、風で鳴る。祖母は売り物の脇に必ず十袋ぶら下げていた。売る気があったのかどうかは、帳面の数字からは分からない。" },
		{ kind: "diary", text: "りんどうは、まだ走り。青が薄い。本番は九月。八月のりんどうは九月の予告みたいなものだと、市場の人が言っていた。" },
		{ kind: "diary", text: "樒だけは市場ではなく、坂の上の寺の裏の畑から分けてもらう。祖母の代からの話で、値段の相談を一度もしたことがないと帳面にある。今年も同じ額を置いてきた。" },
		{ kind: "diary", text: "軽トラの荷台に八十束ぶんを積むと、二回に分けないと入らない。祖母は一回で積んでいたはずで、どう積んでいたのかは、どこにも書いていない。書いていないことのほうが、たぶん多い。" },
		{ kind: "diary", text: "去年の八月の頁には、客の名前が九つ書いてある。七月は四つだった。盆は、名前の増える月らしい。" },
		{ kind: "diary", text: "私の帳面の八月は、まだ数字しかない。" },
		{ kind: "diary", text: "暑さ対策。桶の水は朝六時、正午、夕方五時。氷は入れない。祖母の帳面に「氷は花を驚かす」とある。驚かす、という言い方が祖母らしい。" },
		{ kind: "diary", text: "店の軒に吊るすほおずきは、祖母は十袋だった。今年は十二袋にする。よく鳴る年にしたい。" },
		{ kind: "diary", text: "大神くんが手伝いに来ると言っている。束は八十、私の手は二本。増えるのはありがたいが、盆の四日を学生に潰させるのが正しいのかは、まだ分からない。" },
		{ kind: "diary", text: "祖母の帳面の八月に、一行。「花屋の盆は、人の帰る場所の裏方だから」" },
		{ kind: "diary", text: "裏方、という言葉を少し考えた。表に出ないという意味なら、この店はいつでも裏方だ。盆にだけそう書いたのには、たぶん別の意味がある。" },
		{ kind: "diary", text: "迎え火が十三日、送り火が十六日。うちの山は十三日の朝でほぼ片がつく。そこから十六日までは、余った手が余ったまま四日続く。" },
		{ kind: "diary", text: "盆に店を閉めるか、まだ迷っている。裏方が休んだら、表が困る。でも、休んだ裏方を責める人も、この町にはいない気がする。盆の入りまでに決める。" },
		{ kind: "diary", text: "冷蔵ケースの設定を二度下げた。七月には「ケースの前が店でいちばんいい場所」と書いたが、八月はケースの中に入りたい。" },
		{ kind: "diary", text: "大阪の母から留守電。「お盆、帰ってこないの」。帰る実家は、この店の二階なのだけど、母の言う「帰る」は大阪のことらしい。" },
		{ kind: "diary", text: "留守電は三回聞いた。用件は一回で分かった。" },
		{ kind: "diary", text: "盆の四日は、店を開けていても、手はそれほど要らない。要らない手が余るのが、この月のいちばん厄介なところだと思う。" },
		{ kind: "diary", text: "電話は、盆の前に折り返す。" },
	],
};

// 解放: ステージ8-1クリア後・前半
const bonNoKimegoto: Vignette = {
	id: "m8-bon-no-kimegoto",
	kind: "scene",
	month: 8,
	title: "盆の決めごと",
	trigger: { at: "stage-clear", stageId: "m8-1" },
	synopsis: "盆の入りの朝、店を開けるかどうかを決める。決めたあとの一日と、墓へ上がる石段。",
	choices: [
		{
			id: "B-15",
			label: "盆",
			options: [
				{ key: "A", label: "通して開ける" },
				{ key: "B", label: "中日の午後だけ、閉める" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "front_summer", text: "七時前の入舟銀座は、もう日が高い。アーケードのない通りは、朝からまともに焼ける。米屋のシャッターは半分だけ上がって、その下で主人が箒を使っていた。まるはちの店先には氷が積まれ、溶けた水が舗装に長い筋を引いている。花常のトタン庇は、触れば手が鳴りそうな色をしていた。" },
		{ kind: "narration", text: "盆の入りの朝、若菜は店の鍵を手に、しばらく戸の前に立っていた。" },
		{ kind: "narration", text: "その背中に、氷を跨いだ声がかかった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、開けんのかい" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "まだ、決めていなくて" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんはね、盆は一日も閉めなかったよ。四十年" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "四十年" },
		{ kind: "say", speaker: "sub", name: "八重", text: "偉いって話をしてるんじゃないよ。閉めなかった、ってだけの話。うちなんか中日は閉めるからね。息子が帰ってくるから" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "そうなんですね" },
		{ kind: "say", speaker: "sub", name: "八重", text: "決めたら札を下げときな。町の人はね、札しか見ないんだから" },
		{ kind: "narration", text: "八重さんは氷の水を跨いで戻っていった。若菜は鍵を握り直した。" },
		// ◆選択 B-15「盆」(軸: なし)
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "開ける。裏方は、休まない。" },
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "鍵を回すと、いつもの音がした。祖母が何十年、盆のたびに聞いた音だ。今年からは、私が聞く番だった。" },
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "戸を引くと、店の中の冷えた空気が、足首のあたりから外へ出ていった。桶に水を張り、仏花の棚を通りに向けて出す。八十束のうち四十束をここに積んで、残りは奥のケースに寝かせておく。" },
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "昼を過ぎると、通りを歩く人の顔ぶれが変わった。普段は見ない人ばかりだった。紙袋を提げた人、後ろに子どもを二人つれた人、この暑さで革靴の人。みんな、久しぶりにこの通りを歩く顔をしていた。" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "客の声", text: "すみません、仏花ください。二束" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "wakana", emo: 4, text: "はい。お墓とお仏壇と、両方でよろしいですか" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "客の声", text: "あ——そうか、二つ要るのか。じゃあ三束で。実家、久しぶりなもんで" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "wakana", emo: 4, text: "三束ですと、こちらとこちらで、丈が少し違います。仏壇のほうを短くしますね" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "客の声", text: "頼みます。……この店、前は、おばあさんがやってたよね" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "wakana", emo: 17, text: "はい" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "客の声", text: "そう。開いててよかった" },
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "釣り銭を渡しながら、若菜は棚の残りを数えた。閉めなかった理由が、棚の空いた場所というかたちで、少しずつ増えていった。" },
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "夕方までに、表の四十束は十一束になった。奥から二十束を出して積み直したところで、また戸が開いた。" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "子どもの声", text: "おかあさん、これ、ぜんぶおはかの?" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "客の声", text: "そう。ぜんぶお墓の" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "子どもの声", text: "おはか、そんなにあるの?" },
		{ kind: "say", when: { choice: "B-15", is: "A" }, speaker: "sub", name: "客の声", text: "よそのおうちのも、あるの" },
		{ kind: "narration", when: { choice: "B-15", is: "A" }, text: "若菜は子どもの背の高さに合わせて、余った小菊を一本、包まずに渡した。子どもはそれを旗のように持って、母親の前を歩いて出ていった。" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "中日の午後だけ、店を閉めることにした。" },
		{ kind: "narration", bg: "outskirt", when: { choice: "B-15", is: "B" }, text: "「本日、午後三時まで」の札を下げて、若菜は白菊を一束だけ持ち、バスに乗った。終点のひとつ手前で降りると、そこから先はもう店がない。蝉の声だけが、坂の両側から降ってくる。寺の石段は、暑さで白く乾いていた。" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "桶の置き場で、柄杓を先に使っていた年配の女性が、脇へずれてくれた。" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "sub", name: "女の人の声", text: "桶、お使いになる? 二つ空いてるわ" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "wakana", emo: 2, text: "ありがとうございます" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "sub", name: "女の人の声", text: "花屋さんね。その束、お店のでしょう。分かるのよ、揃いすぎてるから" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "wakana", emo: 19, text: "揃いすぎ" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "sub", name: "女の人の声", text: "褒めてるの。うちのは庭の花だから、ばらばら。ばらばらのほうが、うちのだって感じはするけどねえ" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "wakana", emo: 13, text: "うちの、という感じは、揃っていると出ないですね" },
		{ kind: "say", when: { choice: "B-15", is: "B" }, speaker: "sub", name: "女の人の声", text: "そうそう。そういうこと" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "女性は桶を提げて、先に石段を上がっていった。" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "祖母のところは、石段を上がった、風の通る場所にある。" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "若菜は花を換えて、水をかけて、それから、何も言わなかった。言うことは全部、帳面に書いている。ここでは手だけ動かせばいい。そういう間柄に、この一年でなったのだと思う。" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "帰りのバスの窓で、町が近づいてくるのを見た。裏方が半日休んでも、町は困った顔をしていなかった。" },
		{ kind: "narration", when: { choice: "B-15", is: "B" }, text: "バスを降りると、店の前に下げた「午後三時まで」の札が、思ったより堂々として見えた。若菜は札を裏返して、鍵を回した。三時二分だった。" },
		// 【合流】
	],
};

// 解放: ステージ8-1クリア後・後半
const mushinNoTe: Vignette = {
	id: "m8-mushin-no-te",
	kind: "scene",
	month: 8,
	title: "無心の手",
	trigger: { at: "stage-clear", stageId: "m8-1" },
	synopsis: "作業場で仏花を八十束組む。同じ束を同じ順で作りつづけるうち、手が頭より先に動きはじめる。",
	lines: [
		{ kind: "narration", bg: "workroom", text: "盆の入りの三日前から、奥の作業場は仏花の工場になった。" },
		{ kind: "narration", text: "床に新聞紙の山、台に輪ゴムの束、水場には切り落とした茎が溜まっていく。扇風機は首を振るのをやめさせて、若菜の手元にだけ当ててある。花に風を当てると乾くので、風は人にしか当てられない。" },
		{ kind: "narration", text: "菊、りんどう、小菊、ほおずき。同じ束を、同じ順で、同じ長さに。十束を超えたあたりから、手が考えるより先に動くようになる。二十束を超えると、頭が空になる。空になった頭に、いろんなものが勝手に出入りした。" },
		{ kind: "narration", text: "前の職場では、仏花は工場から箱で届いた。開けて、値札をつけて、並べる。それだけで一日に二百束が捌けた。ここでは、届くのは花だけで、束にする手は箱に入っていない。" },
		{ kind: "narration", text: "束ねる順番は、祖母の帳面の隅に、絵で描いてある。字ではなく、絵だった。丸が三つと、その下に短い線が二本。何度見ても意味が分からなかったのが、二十束を過ぎたあたりで急に分かった。丸は花の高さで、線は葉の位置だった。分かってから見ると、それ以外に読みようのない絵だった。" },
		{ kind: "narration", text: "指が乾くと輪ゴムが滑るので、桶の水に手を浸してから留める。留めるたびに手が冷えて、冷えた手で茎を掴むと、茎のほうが温かい。花のほうが体温を持っているような錯覚が、この時期だけ起きる。" },
		{ kind: "narration", text: "祖母は、この作業を何十年やったのだろう。" },
		{ kind: "narration", text: "三十束目を輪ゴムで留めたとき、戸が開いて、八重さんが顔だけ入れた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "精が出るね。——常ちゃんはね、その作業のとき、演歌かけてたよ" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "演歌" },
		{ kind: "say", speaker: "sub", name: "八重", text: "小さいラジオでね。うるさいくらいの音量で。この時期だけ" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "……知りませんでした" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんたは何かかけないのかい" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "私は……静かなほうが、手が動くので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そうかい。それも血だね" },
		{ kind: "narration", text: "どこが血なのか分からなかったが、八重さんは満足そうに帰っていった。若菜は三十一束目に取りかかった。静かな作業場に、輪ゴムの音だけが、ぱち、ぱち、と鳴った。" },
		{ kind: "narration", text: "四十束目で、若菜はラジオのつまみに手を伸ばしかけた。伸ばしかけて、戻した。演歌がどこの局でかかるのかも、知らなかった。" },
		{ kind: "narration", text: "そのあと少しして、戸口の影が、今度は縦に長かった。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "こんちは。——うわ、なんですかこれ。束の壁じゃないですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "仏花です。八十束" },
		{ kind: "say", speaker: "ren", emo: 4, text: "八十!? 一人でですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "一人です。手が覚えているので、数はあまり関係ないです" },
		{ kind: "say", speaker: "ren", emo: 15, text: "それ、たぶん嘘ですよね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "嘘ではないです。腰は関係あります" },
		{ kind: "narration", text: "彼は笑って、リュックを椅子の背に掛けた。" },
		{ kind: "say", speaker: "ren", emo: 16, text: "手伝いますよ。何やればいいですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "新聞を、この幅に折ってください。八十枚" },
		{ kind: "say", speaker: "ren", emo: 2, text: "折るだけですか。余裕ですって" },
		{ kind: "narration", text: "余裕は、十五枚で尽きた。" },
		{ kind: "say", speaker: "ren", emo: 17, text: "これ、同じ幅に折るの、無理じゃないですか" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "定規を使ってください。祖母は使っていなかったようですが" },
		{ kind: "say", speaker: "ren", emo: 1, text: "常さんって、目分量でやる人だったんですか" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "たぶん。帳面の数字はあんなに几帳面なのに、道具の扱いは雑です。鋏も、研ぎ跡がまっすぐじゃない" },
		{ kind: "narration", text: "レンは新聞を折る手を止めずに、少し早口になった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー、それ分かるかも。うちの同好会の先輩も、書くもんはめちゃくちゃ綺麗なのに、机の上は地層なんですよ。几帳面さって、どこに置くかが人によって違うんですよね。全部には配れないっていうか、在庫が足りないっていうか" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "在庫" },
		{ kind: "say", speaker: "ren", emo: 6, text: "……いや、なんかそういう感じで" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "分かる気はします" },
		{ kind: "say", speaker: "ren", emo: 4, text: "分かります?" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "私は、束は揃うのに、二階が散らかっています" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃあ在庫、全部下に置いてあるんですね" },
		{ kind: "say", speaker: "ren", emo: 19, text: "これ、全部おんなじやつでいいんですか。八十個" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "同じでないと、困ります" },
		{ kind: "say", speaker: "ren", emo: 19, text: "困ります?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "隣の家の仏壇と、うちの仏壇で、花が違ったら、気にする人がいます。この町くらいの狭さだと、必ず" },
		{ kind: "say", speaker: "ren", emo: 20, text: "あー、そういうのか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "だから、同じにします。同じにするのが、この束の仕事です" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんか、逆かと思ってました。花屋って、一個ずつ違うのを作る仕事だと思ってたんで" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "そういう束もあります。三月の卒業の束は、全部違いました" },
		{ kind: "say", speaker: "ren", emo: 5, text: "そっちのほうが本業でしょ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "両方が本業です。違うのを作る日と、同じのを作る日があって、同じのを作る日のほうが、店は持ちます" },
		{ kind: "say", speaker: "ren", emo: 5, text: "それ、ちょっとサーバーと似てますよ" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "サーバーと" },
		{ kind: "say", speaker: "ren", emo: 1, text: "派手なことやってる時間より、同じことをずっと回してる時間のほうが長くて、それが止まると全部終わるんですよ。誰も褒めないんですけど" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "褒められない仕事の話を、二人でしていますね" },
		{ kind: "say", speaker: "ren", emo: 15, text: "盆ですからね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "盆は関係ないと思います" },
		{ kind: "say", speaker: "ren", emo: 14, text: "常さんも、これ一人でやってたんですか。八十" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "もっと少ない年もあったようです。七十八の年に、二束足りなくなったと帳面にあります" },
		{ kind: "say", speaker: "ren", emo: 19, text: "足りなくなったら、どうするんですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "その場で組みます。お客さんに待ってもらって" },
		{ kind: "say", speaker: "ren", emo: 19, text: "待ってくれるんですか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "待つそうです。この町は" },
		{ kind: "narration", text: "日が傾いて、作業場の蛍光灯を点けた。折り上がった新聞は八十枚に届かず、六十二枚で止まった。それでも、三十枚目あたりから角は揃いはじめていた。" },
		{ kind: "narration", text: "八十束目は、その灯りの下で組んだ。最後の一束にだけ、若菜は樒を一本多く入れた。数え間違えたのではなく、余ったからだった。余ったものを捨てる気にならない日というのが、たまにある。" },
		{ kind: "narration", text: "仏花八十束のあいだ、釘の鋏は一度も下りなかった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "それ、一本多くないですか" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "見てたんですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "ずっと見てました。八十回おんなじのを見てると、違うやつはすぐ分かるんで" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "目ざといところが、変なところにありますね" },
		{ kind: "say", speaker: "ren", emo: 15, text: "褒め言葉として受け取っときます" },
		{ kind: "say", speaker: "ren", emo: 16, text: "明日も来ます。残り十八" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お代は出せません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "ラムネ一本でいいですよ" },
		{ kind: "narration", text: "ラムネ、と若菜は帳面の隅に書いた。仕入れの品目に、店で扱っていないものが一つ増えた。" },
	],
};

// 解放: ステージ8-2の前
const akaruiNoWo: Vignette = {
	id: "m8-akarui-no-wo",
	kind: "scene",
	month: 8,
	title: "あかるいのを",
	trigger: { at: "stage-clear", stageId: "m8-1" },
	synopsis: "仏花を買う客が続く午後、仏花ではない白い花を頼まれる。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "盆の入りの前日の午後、通りは白かった。簾を下ろしても、光は下から跳ね返ってくる。舗装の照り返しで、店の低いところにある花は、上より先に下から弱った。若菜は三十分おきに霧を吹いた。朝に四十束あった仏花の棚は、十二束まで減っている。" },
		{ kind: "say", speaker: "sub", name: "年配の客の声", text: "これ、樒は入ってるかい" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "入っています。宗派によっては外しますので、おっしゃってください" },
		{ kind: "say", speaker: "sub", name: "年配の客の声", text: "入ってりゃいい。うちは昔からそれ" },
		{ kind: "say", speaker: "sub", name: "年配の客の声", text: "あんた、常さんの孫かい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "sub", name: "年配の客の声", text: "顔は似とらんな" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "よく言われます" },
		{ kind: "say", speaker: "sub", name: "年配の客の声", text: "手つきが似とる。それでええ" },
		{ kind: "narration", text: "店の前には、朝から自転車が三台停まっては行った。盆の前の日は、忘れていた人の日だ。買い忘れ、頼み忘れ、帰る日を間違えた人。若菜は棚の空きに、奥から出した束を足し続けた。足すたびに棚は元に戻り、元に戻るたびに、また減った。" },
		{ kind: "narration", text: "昼過ぎに電話が二本鳴った。どちらも仏花の追加で、どちらも「おばあちゃんとこの」という言い方をされた。若菜は「はい」とだけ答えた。訂正の必要がない種類の間違いだった。" },
		{ kind: "narration", text: "二時を回ると、通りから人が消えた。この時間だけは、盆でも同じらしい。" },
		{ kind: "narration", text: "若菜が簾の隙間から通りを見ていると、その静かさの中で、戸が開いた。外は白い日差しなのに、その人は来た。" },
		{ kind: "narration", text: "雨の日の人だった。晴れの日に見るのは、初めてだった。ビニール傘の代わりに、白い日傘を提げている。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "……こんにちは" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "いらっしゃいませ" },
		{ kind: "narration", text: "若菜は、仏花の並んだ棚を目で示しかけて、やめた。決めつけるところだった。女性は、仏花の棚をゆっくり通り過ぎて、ケースの前で立ち止まった。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "今日は……あかるいのを、少し。白じゃなくて" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "あかるいの" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "ええ。持っていく先が、白い部屋なので。白い花だと、消えてしまうから" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "大きさは、どのくらいにしましょう" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "小さくて。棚の上に置ける程度で" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花瓶は、どんな形ですか" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "備え付けのコップです。背の低い、太いの" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "では、丈は短く切ります。下を重くして、倒れにくくします" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "ずいぶん、細かく聞くのね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "花は、置かれる場所で決まるので" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "そういう仕事です" },
		{ kind: "narration", text: "若菜はケースの戸を開けた。冷えた空気が足元に落ちた。りんどうを一本、抜く。青の浅い、走りの一本だった。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "これはりんどうです。本番が九月なので、まだ色が浅いんですが" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "浅いの、いいわ。濃いと、こっちが負けるから" },
		{ kind: "narration", text: "向日葵の小さいのを二本。小菊の黄を三本。ケースの奥から白の小さいのを一本足しかけて、若菜は手を戻した。白じゃなくて、と言われている。代わりにオレンジのスプレーバラを一本、青の脇に入れた。" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "水は二日にいちど替えてください。替えるとき、茎の先を指の幅ぶん切ってください" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "うちの、ふつうのはさみでも平気?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "よくはないです。ただ、切らずに替えないよりは、ずっといいです" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "正直な人ね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花屋の嘘は、三日で分かるので" },
		{ kind: "narration", text: "若菜は台に新聞を広げて、丈を切りそろえた。切り口を斜めにするか平らにするかで、水の上がり方が変わる。コップに挿すなら、平らのほうがいい。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "そんなに切ってしまうの" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "短いほうが、水が早く上がります。長いままだと、途中で息切れするので" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "息切れ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "店ではそう言います。実際は、水が上まで届かないだけなんですが" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "言い方のほうが、当たっている気がするわ" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "白は、ほんとうにだめなの。前は、好きだったのだけれど" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "では、また好きになったときに、白を出します" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "置いておいてくれるの" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "白は、いつでもあります。花屋が切らさない色なので" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "これ、どのくらい保つかしら" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "この時期なら、五日から一週間です。向日葵が先に終わります" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "一週間" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "向日葵が終わったら、抜いてください。りんどうは、そのあと三日くらい残ります" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "じゃあ、また来なきゃいけないのね" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "そうなります" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "そう" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "袋は、二重にしますか。日が強いので" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "二重に。バスに乗るので" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、口を少し開けておきます。閉じきると、中が蒸れます" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "詳しいのね。バスのことまで" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "花のことだけです。バスは、たまたま知っていました" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "きれい" },
		{ kind: "narration", text: "女性は、束を胸の高さで受け取った。それから、初めて、少しだけ笑った。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "……また、来ます" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "お待ちしています" },
		{ kind: "narration", text: "戸が閉まって、簾の隙間から通りが見えた。白い日傘が、照り返しの中を、通りの向こうへ小さくなっていった。傘は開いたままだったが、途中で一度、持ち手が右から左へ替わった。花を持ったほうの手を、日陰に入れたのだと分かった。" },
		{ kind: "narration", text: "八重さんが胡瓜を持って入ってきたのは、その五分後だった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "今の人、誰だい。見ない顔だね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お客さんです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃ見りゃ分かるよ。どこの人だい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "存じません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "聞かないのかい" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "聞きません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんた、そういうとこ常ちゃんそっくりだね。あの人も聞かない人だった。町中の噂を知ってて、客のことだけは聞かないの" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "祖母の帳面に、雨の日に来る人のことが一行だけあります。名前は書いてありません" },
		{ kind: "say", speaker: "sub", name: "八重", text: "書かないよ。書いたら噂になっちまうもの" },
		{ kind: "narration", text: "八重さんは胡瓜を三本置いて、今日は小銭を受け取って帰っていった。" },
		{ kind: "narration", text: "若菜は棚に残った白い花を数えた。十一本あった。数えたところで何にもならないのに、数えるのが癖になっている。" },
		{ kind: "narration", text: "白い部屋。若菜は、その言葉を帳面には書かないことに決めた。書かなくても、忘れない種類の言葉だった。" },
	],
};

// 解放: ステージ8-2クリア後
const oosaka: Vignette = {
	id: "m8-oosaka",
	kind: "scene",
	month: 8,
	title: "大阪",
	trigger: { at: "stage-clear", stageId: "m8-2" },
	synopsis: "盆の前の夜、二階の部屋から大阪の母へ電話を折り返す。花の苦手な母との、長い電話。",
	choices: [
		{
			id: "B-16",
			label: "母への返答",
			options: [
				{ key: "A", label: "「うん。分かってる」" },
				{ key: "B", label: "「今度、大阪にも花を送る」" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "indoor_other", text: "二階に上がる階段は急で、六段目が鳴る。祖母の代からの音で、直していない。二間のうち、若菜が使っているのは通りに面したほうだ。畳に座って、扇風機を止めて、窓を開けた。閉めた店のトタン庇に溜まった熱が、下から順に上がってくる。" },
		{ kind: "narration", text: "窓の下で、まるはちがシャッターを下ろす音がした。それから、通りが静かになった。盆の前の夜は、商店街が早く終わる。" },
		{ kind: "narration", text: "若菜は電話を折り返した。膝の上で画面を一度消して、もう一度点けた。呼び出し音は二回で切れた。" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "あ、若菜? お盆、ほんとに帰ってこないの" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "店があるから。盆は花屋の書き入れ時なの" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "そう。そうよね。おばあちゃんも、盆はぜったい閉めなかったもの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "うん" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "こっちはね、お父さんの実家に日帰りで行くだけよ。もう、そんなもんやから" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "日帰り" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "向こうもお年寄りばっかりでね。お茶飲んで、二時間で帰ってくるの。あんたが小さい頃は泊まったんやけどね" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "覚えてる。畳が広かった" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "よう覚えてるわ、そんなこと" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "畳の広さだけ覚えてる" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "ごはん、食べてる? 夏は食べんようになるからね、あんた昔から" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "食べてる。冷やし中華ばっかりだけど" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "そんなん、食べてるうちに入らんわ。——八重さんから、たまに電話くるのよ。若菜ちゃんはようやってる、って" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "八重さん、大阪に電話してるの" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "昔から。あの人、報告係やから。お母さんが子どもの頃からずっとそう" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "知らなかった" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "知らんでええことよ、そんなん" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "今日はなに作ってたん。お店で" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "仏花。八十束" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "八十。それ、一人で作るの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "手伝ってくれる人がいる。大学生の子" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "へえ。男の子? 女の子?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "男の子" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "へえ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "その『へえ』はやめて" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "なんも言うてへんやん" },
		{ kind: "narration", text: "電話の向こうで、椅子の脚が畳を擦る音がした。" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "お父さん、代わる? ——お父さーん、若菜" },
		{ kind: "say", speaker: "sub", name: "父の声", text: "おう" },
		{ kind: "say", speaker: "sub", name: "父の声", text: "暑いか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "暑いです" },
		{ kind: "say", speaker: "sub", name: "父の声", text: "そうか。ほな" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "もう、それだけなん。あの人、電話が苦手やねん" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "知ってます" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "お母さんね、あんたがお店継ぐって言うたとき、反対も、賛成も、できんかったのよ。お母さん、花、あかんから。水替えのにおいだけで、だめ" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "……初めて聞いた" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "言うてなかったもの。おばあちゃんの店、手伝わされるのがほんまに嫌でね。あんたが小さい頃、三年預けたでしょう。あのとき、あんたが桶の水替え喜んでやるのを見て、お母さん、ちょっと悔しかったわ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "悔しかったの" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "悔しかったわよ。血ぃは、一代飛ぶんやね" },
		{ kind: "narration", text: "母は笑った。電話の向こうで、大阪の団地の音がした。テレビと、食器と、父の遠いくしゃみ。" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "お店、儲かってるの。ほんまのとこ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "儲かってはいない。回ってはいる" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "それ、おばあちゃんも同じこと言うてたわ。四十年おんなじこと言うて、四十年やってはった" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "同じ言い方だったの" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "一字一句おんなじ。——さっき一代飛ぶ言うたけど、飛んで、戻ってきたんかもしれんね" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "戻り先が、私" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "気の毒に" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "気の毒って" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "冗談。半分な" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "チェーンのお店、辞めるとき、なんも言わんかったやろ。あんた" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "言ったら、止められると思ったから" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "止めへんかったわよ。お母さんは" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "お父さんは" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "止めたやろね。あの人、心配は全部黙ってやる人やから" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "さっき、暑いかって聞かれた" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "あれが最大限や" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "あの帳面、まだあるの。おばあちゃんの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "ある。毎日、読んでる" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "そう。お母さんは、よう読まんわ。字ぃ見たら、しんどいから" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "読まなくていいと思う" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "そう言うてくれるんや" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "読む人が一人いれば、帳面は足りるから" },
		{ kind: "narration", text: "しばらく、団地の音だけがした。" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "あんた、お盆に一人でおって、平気なん" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "一人ではない。お客さんが来る" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "そういうことちゃうねん" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "そういうことにしておいて" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "ほんまに、おばあちゃんの喋り方やわ" },
		{ kind: "say", speaker: "sub", name: "母の声", text: "無理はせんとってね。店より、あんたやから。お母さんは" },
		// ◆選択 B-16「母への返答」(軸: なし)
		{ kind: "say", when: { choice: "B-16", is: "A" }, speaker: "wakana", emo: 17, text: "……うん。分かってる" },
		{ kind: "say", when: { choice: "B-16", is: "B" }, speaker: "wakana", emo: 16, text: "……うん。あのね、今度、そっちにも花を送る" },
		{ kind: "say", when: { choice: "B-16", is: "B" }, speaker: "sub", name: "母の声", text: "花はあかんて言うたやん、お母さん" },
		{ kind: "say", when: { choice: "B-16", is: "B" }, speaker: "wakana", emo: 4, text: "においの少ないのにする。りんどうなら、大丈夫" },
		{ kind: "say", when: { choice: "B-16", is: "B" }, speaker: "sub", name: "母の声", text: "……もう。ほんなら、青いのにしてよ。青は好きやから" },
		{ kind: "say", when: { choice: "B-16", is: "B" }, speaker: "wakana", emo: 8, text: "知らなかった。青、好きなんだ" },
		{ kind: "say", when: { choice: "B-16", is: "B" }, speaker: "sub", name: "母の声", text: "言うてなかったもの" },
		{ kind: "narration", when: { choice: "B-16", is: "B" }, text: "言うてなかったことが、母にもまだ、あるらしかった。" },
		// 【合流】
		{ kind: "narration", text: "電話を切って、若菜は二階の窓から商店街を見た。盆提灯の入った家が、ぽつ、ぽつ、と灯っている。裏方の夜だった。" },
		{ kind: "narration", text: "坂の上のほうは暗かった。学生アパートの窓は、この時期はいくつも消えている。みんな、帰る場所へ帰ったのだろう。" },
		{ kind: "narration", text: "若菜は窓を閉めた。閉めても、庇の熱は下から上がってきた。階下では、冷蔵ケースが低く鳴っている。この店で夜に鳴っているのは、それだけだった。" },
	],
};

// 解放: ステージ8-3の前
const chomen0814: Vignette = {
	id: "m8-chomen-0814",
	kind: "chomen",
	month: 8,
	title: "八月十四日",
	trigger: { at: "stage-clear", stageId: "m8-2" },
	synopsis: "盆の中日の帳面。仏花とほおずきの数を書き、自分の帰る場所のことに触れる。",
	lines: [
		{ kind: "diary", text: "八月十四日。晴れ。夜になっても二十八度。" },
		{ kind: "diary", text: "盆の中日。仏花、残り十九束。ほおずきは十七袋出た。軒の三袋は売らずに残す。祖母がそうしていたので、そうする。" },
		{ kind: "diary", text: "今日、二階の階段の六段目が鳴った。いつも鳴るのに、今日はその音だけが階下まで届いた。町が静かだったからだと思う。" },
		{ kind: "diary", text: "帰る実家は、この二階だ。私は毎晩、実家に帰っていることになる。通勤時間、十二秒。" },
		{ kind: "diary", text: "母の言う「帰る」は大阪のことだった。母にとっての帰る場所は、順番でいえば、もっと前にこの店だったはずなのに。花があかんかったから、母は帰る場所を一つ手放したのだと思う。" },
		{ kind: "diary", text: "手放してよかったのだと思う。手放さなかったら、私に回ってこなかった。" },
		{ kind: "diary", text: "盆というのは、帰る人のための四日間らしい。うちは、帰る人を待つ側でも、帰る側でもなくて、帰る人が持っていく花を作っている。" },
		{ kind: "diary", text: "中日の午後は、通りを歩く人が朝と入れ替わる。朝は花を買いに来る人、夕方は帰ってきた人。夕方の人は花を買わない。もう供えたあとだから。" },
		{ kind: "diary", text: "仏花の値段は、一年で唯一、私がまったく迷わずにつけられる値段だ。祖母の数字をそのまま使っている。迷わない値段が一つあるだけで、月がずいぶん楽になる。" },
		{ kind: "diary", text: "前の職場では、盆は「第二商戦」と呼ばれていた。呼び方は間違っていない。間違っていないのに、この店でその言葉を使う気にならない。" },
		{ kind: "diary", text: "ほおずきを一袋、軒から外して取っておいた。誰にやるとも決めていない。決めていないのに外した。" },
		{ kind: "diary", text: "送り火は十六日。祖母の帳面の十六日には、「くろまつ」とだけ書いてある。三年ぶんとも同じ。何のことか、まだ分からない。" },
		{ kind: "diary", text: "「人の帰る場所の裏方」。祖母の一行を、今日は三回読んだ。" },
		{ kind: "diary", text: "三回読んでも、まだ全部は分からない。分からないまま、八十束目まで組んだ。" },
		{ kind: "diary", text: "大神くんが新聞を折っている。まだ十八枚足りない。彼にも、帰らなかった夏があるらしい。" },
		{ kind: "diary", text: "帰らない人が二人で店にいるのは、盆の店の絵としては少し変だと思う。変だけれど、暗くはない。" },
	],
};

// 解放: ステージ8-3クリア後
const ramune: Vignette = {
	id: "m8-ramune",
	kind: "scene",
	month: 8,
	title: "ラムネ",
	trigger: { at: "stage-clear", stageId: "m8-3" },
	synopsis: "盆の中日の夕方、店の縁台でラムネを二本飲む。夏の話と、四十年の話。",
	lines: [
		{ kind: "narration", bg: "front_summer", text: "盆の中日の夕方、通りの舗装は打ち水で黒く濡れて、その上を蝉の声が渡っていった。日が低くなると、庇の影が縁台のちょうど半分までのびる。若菜は影のほうに座った。" },
		{ kind: "narration", text: "縁台の板は、日の当たっていたほうだけ、まだ熱を持っている。手のひらを置くと、店の中の空気で冷やした手が、すぐに元へ戻ってしまう。通りの向こうで、霜月堂が氷の旗を仕舞っていた。" },
		{ kind: "narration", text: "店の縁台に、ラムネが二本並んだ。" },
		{ kind: "narration", text: "まるはちの店先の冷蔵ケースから、八重さんが「売れ残り」と言って持たせてくれたものだった。売れ残りにしては、よく冷えていた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "はい、これ。売れ残り" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "まだ十分、売れるものだと思いますが" },
		{ kind: "say", speaker: "sub", name: "八重", text: "盆に売れ残ったもんは、売れ残りなんだよ。——狼の坊も飲みな。折ったんだろ、新聞" },
		{ kind: "say", speaker: "ren", emo: 5, text: "六十二枚です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "十八枚足りないじゃないか" },
		{ kind: "say", speaker: "ren", emo: 6, text: "明日、明日で" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、あんた盆に何食べたんだい" },
		{ kind: "say", speaker: "wakana", emo: 14, text: "冷やし中華です" },
		{ kind: "say", speaker: "sub", name: "八重", text: "四日ともかい" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "四日ともです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あとで胡瓜持ってくるからね。あれは食べ物のうちに入らないよ" },
		{ kind: "say", speaker: "ren", emo: 17, text: "うちは、カップ麺でした" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんたはもっと駄目だ" },
		{ kind: "narration", text: "八重さんは笑って戻っていった。玉を押し込む音が、二つ続けて鳴った。" },
		{ kind: "say", speaker: "ren", emo: 10, text: "俺も今年、帰らなかったんですよね。長野" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "サークルですか" },
		{ kind: "say", speaker: "ren", emo: 15, text: "サーバーの番です。夏はマシンが熱で落ちるんで、誰か見てないと。……っていうのが、半分で" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "番、というのは、何をするんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それがですね、部屋のエアコンをつけっぱなしにしとくのが一番手っ取り早いんですけど、うちのアパート、ブレーカーが弱くて、エアコンとサーバーとレンジが同時に行くと落ちるんですよ。だから温度計をネットに繋いで、三十五度超えたら俺の携帯が鳴るようにして、鳴ったら走って帰る。走って帰る係が、俺なんです" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "それは、番と言っていいんですか" },
		{ kind: "say", speaker: "ren", emo: 3, text: "言いたいんですって。番って言うと、なんかちゃんとしてる感じがするんで" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "花屋も、水を替えてるだけの日があります" },
		{ kind: "say", speaker: "ren", emo: 16, text: "それは番でしょ、完全に" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "では、番ということにします" },
		{ kind: "narration", text: "ラムネの玉が、からん、と鳴った。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "盆って、花屋は忙しいんですね。正直、暇なもんだとばかり思ってました" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "一年で二番目です。一番は五月" },
		{ kind: "say", speaker: "ren", emo: 4, text: "二番目なんだ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "盆に忙しいのは、花屋と、坊さんと、高速道路だけです" },
		{ kind: "say", speaker: "ren", emo: 19, text: "そこ並べます?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "並びます。全部、人が帰るための仕事なので" },
		{ kind: "narration", text: "レンはラムネの瓶を、目の高さまで上げた。中の玉が、夕方の光を一つぶん拾っている。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "それ、裏方ってやつでしょ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "なんでその言葉が出るんですか" },
		{ kind: "say", speaker: "ren", emo: 19, text: "え。今、そういう話じゃなかったですか" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "祖母の帳面に、同じ言葉が書いてあります。八月の頁に、一行だけ" },
		{ kind: "say", speaker: "ren", emo: 20, text: "なんて書いてあるんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花屋の盆は、人の帰る場所の裏方だから" },
		{ kind: "narration", text: "レンは、しばらく瓶を下ろさなかった。" },
		{ kind: "say", speaker: "ren", emo: 20, text: "いい言葉だなあ、それ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "意味は、まだ半分しか分かりません" },
		{ kind: "say", speaker: "ren", emo: 15, text: "半分が多いなあ、今日は" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "多いですね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "夏、あとどのくらい残ってるんですかね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "店の中は、もう九月です。りんどうと、菊の走りが入ってきているので" },
		{ kind: "say", speaker: "ren", emo: 4, text: "一か月早いんですか、花屋の季節" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "一か月から二か月。桜は一月に入ってきます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "一月に桜" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "啓翁桜という、促成の桜です。正月の枝物なので" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ三隅さんは、外が夏でも、頭の中は秋なんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "そうなります" },
		{ kind: "say", speaker: "ren", emo: 14, text: "それ、しんどくないですか。今を今として過ごせないっていうか" },
		{ kind: "narration", text: "若菜は瓶を傾けて、中の玉を下に落とした。からん、と鳴った。" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "今日は、今日として過ごしています。ラムネなので" },
		{ kind: "say", speaker: "ren", emo: 2, text: "うまい返しですね、それ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "母親からは、毎年来ないのかって言われます。今年は野菜が送られてきました。段ボールで。まるはち経由で" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "まるはち経由" },
		{ kind: "say", speaker: "ren", emo: 6, text: "住所、間違ってたんですよ。花常の隣、みたいな書き方で。八重さんが持ってきてくれて" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "何が入っていたんですか" },
		{ kind: "say", speaker: "ren", emo: 19, text: "茄子とトウモロコシと、あと、分かんない葉っぱが二種類。名前も書いてないんですよ。食えってことだと思うんですけど" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "名前も書かずに送るんですか" },
		{ kind: "say", speaker: "ren", emo: 6, text: "うち、山なんで。名前のない葉っぱが日常なんです" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "花屋としては、名前のない植物は落ち着かないです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃあ持ってきます、明日。鑑定してください" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "鑑定はできません。食べられるかどうかは、分かりませんので" },
		{ kind: "say", speaker: "ren", emo: 15, text: "花屋なのに" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花屋だからです。うちは、食べられないものばかり扱っています" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "お母さんは、ここのことをご存じなんですね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "電話でしゃべってるんで。花屋によく行く、って" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "どういうふうに" },
		{ kind: "say", speaker: "ren", emo: 3, text: "いや、それは。勘弁してください" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "半分" },
		{ kind: "say", speaker: "ren", emo: 15, text: "もう半分は、なんとなく、です" },
		{ kind: "narration", text: "蝉は、もう夕方の声になっている。" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "……私も、半分はなんとなくです" },
		{ kind: "say", speaker: "ren", emo: 4, text: "三隅さんも? 帰るとこ、あるんですか" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "大阪に、両親が。でも帰る実家は、ここの二階な気もしていて。どっちがどっちだか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー、分かります。俺も、長野の家と、二〇三と、どっちが『帰る』なんだろうって、たまになります" },
		{ kind: "say", speaker: "ren", emo: 6, text: "実家帰ると、三日目くらいでそわそわしてくるんですよ。で、こっち戻ると、戻った感じがするんです。戻った感じがするほうが家なんじゃないかって思うんですけど、それ言うと母親の機嫌が悪くなるんで、言わないんですけど" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "言わないほうがいいと思います" },
		{ kind: "say", speaker: "ren", emo: 4, text: "そこ、止めます?" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "言わなくても、たぶん伝わっているので。伝わっていることを言葉にすると、角が立ちます" },
		{ kind: "say", speaker: "ren", emo: 15, text: "うわ、経験者だ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "さっき、電話で一度やりました" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "どっちなんですか、今は" },
		{ kind: "narration", text: "レンはラムネを一口飲んで、少し考えた。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "花のあるほう、ですかね" },
		{ kind: "narration", text: "蝉の声が、一段、遠くなった。若菜は何も言わずに、ラムネの残りを飲んだ。何か言うと、この時間が終わってしまう気がした。" },
		{ kind: "say", speaker: "ren", emo: 18, text: "じゃ、おそろいですね。二階に住んでる人と、花のある部屋の人で" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "……おそろいですね" },
		{ kind: "narration", text: "若菜は店に戻って、ケースからりんどうを一本抜いた。走りの、青の浅い一本。新聞を斜めに、一巻き。" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "今月のぶんです" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ、忘れてました。忘れてたのに、出てくるんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "八回目なので" },
		{ kind: "say", speaker: "ren", emo: 5, text: "八回。もう八回か" },
		{ kind: "narration", text: "彼は空いた瓶を縁台に置いて、りんどうを、瓶を持っていたほうの手に持ち替えた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、九月が本番のやつですよね" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "よく知ってましたね" },
		{ kind: "say", speaker: "ren", emo: 3, text: "この前、市場で聞いたんで。犬飼さんに" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "犬飼さんと、連絡を取っているんですか" },
		{ kind: "say", speaker: "ren", emo: 6, text: "向こうから来るんですよ。狼、元気か、って。用件はないんですけど" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "用件のない連絡は、いいものだと思います" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃ、今度そう言っときます。用件がないのがいいらしいぞ、って" },
		{ kind: "say", speaker: "ren", emo: 20, text: "常さんも、盆は休んでなかったんですよね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "四十年、閉めなかったそうです。八重さんが言っていました" },
		{ kind: "say", speaker: "ren", emo: 4, text: "四十年" },
		{ kind: "say", speaker: "wakana", emo: 12, text: "私は、まだ一年目です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あと三十九年ですか" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "数えないでください" },
		{ kind: "say", speaker: "ren", emo: 16, text: "じゃあ数えないで、毎年来ます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "三隅さんって、休みの日、何してるんですか" },
		{ kind: "say", speaker: "wakana", emo: 14, text: "休みが、まだ来ていません" },
		{ kind: "say", speaker: "ren", emo: 14, text: "一月からずっとですか" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "半日なら、何度かありました。今日みたいな日です" },
		{ kind: "say", speaker: "ren", emo: 19, text: "今日、休みなんですか。これ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "ラムネを飲んでいるので、休みです" },
		{ kind: "say", speaker: "ren", emo: 6, text: "基準がゆるい" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "ゆるくしないと、一年もたないので" },
		{ kind: "narration", text: "日が完全に落ちて、通りの街灯が点いた。縁台の板から、熱がやっと抜けた。" },
		{ kind: "say", speaker: "ren", emo: 16, text: "明日は十八枚ですね" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "もう八十束、終わりました" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "昨日の夜に、全部組みました" },
		{ kind: "say", speaker: "ren", emo: 19, text: "じゃあ俺の六十二枚は" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "使いました。全部" },
		{ kind: "narration", text: "レンは何か言いかけて、やめた。" },
		{ kind: "say", speaker: "ren", emo: 13, text: "じゃ、無駄にはなってないですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "明日は、新聞を折らなくていいです" },
		{ kind: "say", speaker: "ren", emo: 19, text: "じゃあ、何しに来ればいいですか" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "来なくてもいいですけど" },
		{ kind: "say", speaker: "ren", emo: 16, text: "来ます" },
	],
};

// 解放: 八月の全ステージクリア後・前半
const okuribi: Vignette = {
	id: "m8-okuribi",
	kind: "scene",
	month: 8,
	title: "送り火",
	trigger: { at: "month-close", month: 8 },
	synopsis: "八月十六日の日暮れ、通りの店々が軒先で送り火を焚く。花常も一本を出す。",
	lines: [
		{ kind: "narration", bg: "street", text: "八月十六日の日暮れ、入舟銀座の店々が、いつもより早く表を片づけはじめた。米屋は七時前にシャッターを下ろし、霜月堂は暖簾を仕舞って、代わりに軒下に小さな火を焚いた。麻の茎を折ってくべる、細い火だった。通りの端から端まで、同じ火が点々と並ぶ。川風が上がってきて、火はみな川のほうへ倒れた。" },
		{ kind: "narration", text: "通りの真ん中で、子どもが二人、火のまわりを回っていた。回るなと親が言い、子どもは回るのをやめて、こんどは灰を棒でつつきはじめた。" },
		{ kind: "narration", text: "若菜は店の前を掃いてから、軒のほおずきを一袋、外した。" },
		{ kind: "narration", text: "くろまつの戸が開いて、玄が出てきた。紙の袋を提げている。マスターは若菜の前まで来ると、袋を勘定台ではなく、縁台のほうに置いた。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……豆" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "ありがとうございます。今日は、何にしましょう" },
		{ kind: "narration", text: "玄は通りの火を見て、それから、店先の桶を見た。桶には仏花の余りの小菊が三本、残っている。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……それで" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "小菊で、いいんですか" },
		{ kind: "say", speaker: "sub", name: "玄", text: "盆だ" },
		{ kind: "narration", text: "若菜は三本を新聞に巻いて渡した。玄は片手で受け取ると、もう片方の手で自分の店の軒先を指した。細い火が、そこで揺れている。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……そこに" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "お供え、ですか" },
		{ kind: "say", speaker: "sub", name: "玄", text: "常が、毎年" },
		{ kind: "narration", text: "それだけ言って、玄は戻っていった。若菜は小菊がくろまつの軒下に置かれるのを、店の前から見ていた。火は、そこだけ少し長く燃えた。" },
		{ kind: "narration", text: "縁台の紙袋を開けると、豆はいつもより多かった。量りを使う人ではないので、多いか少ないかは、袋の重さで分かるだけだ。" },
		{ kind: "narration", text: "まるはちの方から、下駄の音が近づいてきた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、うちの火、もう消えちまったよ。ちょっと分けとくれ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "火は、うちにもないです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "じゃあ、これでいいね" },
		{ kind: "narration", text: "八重さんは、まるはちの軒先から燃え残りの麻を一本つまんできて、花常のトタン庇の下に立てた。誰も頼んでいないのに、花常の前にも火が点いた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "常ちゃんとこの前が暗いと、通りが締まらないんだよ" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "勝手に点けていいものなんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "盆に細かいこと言うんじゃないよ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、あんた、ここの送り火やったことあるかい" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "見たことは、あります。小さい頃に" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そんならもう、やったことあるうちだよ。見てりゃ、そのうち自分でやる番が来るんだから" },
		{ kind: "narration", text: "坂を下りてくる自転車の音がした。ブレーキが、火の手前で鳴った。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "うわ、これ、通りじゅう火だらけじゃないですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "送り火です" },
		{ kind: "say", speaker: "ren", emo: 1, text: "送り火。あー、うちのほうでもやりますよ。ただ、川原でやるんで、こんなふうに店の前ではやらないですね" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "長野は、大きいんですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "山があるんで。山のほうへ送るんですよ。こっちは、どっちに送るんですか" },
		{ kind: "narration", text: "若菜は通りを見た。火はどれも、同じ方向に倒れている。" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "たぶん、川です。この町は、水の町なので" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃあ、風がちゃんと仕事してるってことですね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "風は、うちでは敵のほうが多いですが" },
		{ kind: "say", speaker: "ren", emo: 2, text: "今日だけは味方でしょ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "うち、送り火のとき、婆ちゃんが毎年おんなじこと言うんですよ。『足元気ぃつけて帰れ』って。火に向かって" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "火に向かって" },
		{ kind: "say", speaker: "ren", emo: 6, text: "毎年です。俺、子どもの頃、火が返事すると思ってました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "返事、しましたか" },
		{ kind: "say", speaker: "ren", emo: 10, text: "一回もしてくれないです" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "うちも、しません" },
		{ kind: "narration", text: "若菜は、外しておいたほおずきの袋を開けた。" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "これ、どうぞ" },
		{ kind: "say", speaker: "ren", emo: 19, text: "ほおずき? これ、食べるやつでしたっけ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "食べません。鳴らします" },
		{ kind: "say", speaker: "ren", emo: 4, text: "鳴る?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "中身を出して、皮だけにして、舌で押すと鳴ります。子どもの遊びです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "やってみたい。やり方、教えてくださいよ" },
		{ kind: "narration", text: "若菜は袋から一つ取って、爪の先で実の底に小さく穴を開けた。中身を押し出すのに、指の力の加減が要る。破けると、鳴らない。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "破けました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "もう一つあります" },
		{ kind: "say", speaker: "ren", emo: 6, text: "二回目も破けました" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "三つ目で最後です。売り物なので" },
		{ kind: "say", speaker: "ren", emo: 6, text: "厳しい" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "四つ目は、あります" },
		{ kind: "narration", text: "三つ目は破けなかった。レンはそれを口に入れて、しばらく黙って、それから、ぷう、と情けない音を鳴らした。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "鳴った!" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "鳴りました" },
		{ kind: "say", speaker: "ren", emo: 4, text: "これ、九月も売ってます?" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "盆までです。来年まで待ってください" },
		{ kind: "say", speaker: "ren", emo: 16, text: "来年までに練習しときます" },
		{ kind: "narration", text: "通りの火が、順に小さくなっていった。霜月堂が水をかけ、米屋が灰を掃いた。最後まで残ったのは、八重さんが花常の前に立てた一本だった。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "これ、消さなくていいんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "消えるまで、置いておきます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "来年もやるんですよね、これ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "たぶん" },
		{ kind: "say", speaker: "ren", emo: 19, text: "たぶん?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "来年のことは、花屋は言わないんです。天気の商売なので" },
		{ kind: "say", speaker: "ren", emo: 16, text: "じゃあ、俺が言っときます。来年もやります" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "大神くんの店ではないですが" },
		{ kind: "say", speaker: "ren", emo: 2, text: "客が言うぶんには自由でしょ" },
		{ kind: "narration", text: "二人は縁台に座って、それが消えるのを見ていた。火が消えると、通りは急に、ただの夜になった。" },
		{ kind: "narration", text: "店々のシャッターが順に下りて、最後にくろまつの明かりが消えた。若菜は勘定台の脇の丸椅子を通り過ぎて、店の奥の電気を落とした。二階へ上がる階段の、六段目が鳴った。" },
	],
};

// 解放: 八月の全ステージクリア後・後半
const chomen0831: Vignette = {
	id: "m8-chomen-0831",
	kind: "chomen",
	month: 8,
	title: "八月三十一日",
	trigger: { at: "month-close", month: 8 },
	synopsis: "八月の締めの帳面。盆の集計と、りんどうの走りの数から翌月を読む。",
	lines: [
		{ kind: "diary", text: "八月三十一日。晴れ。夜だけ、秋の風。" },
		{ kind: "diary", text: "盆の集計。仏花八十、完売。ほおずき残り二袋は、店の軒に吊るした。よく鳴る。" },
		{ kind: "diary", text: "りんどうは走りが三十本、追加で二十本。八月に出た走りの数の倍が九月の初週に出る——というのが祖母の帳面の数字から読めることで、これは私の発見ではなく、書き写しただけの発見だ。それでも、読んだのは私だ。" },
		// 【B-15=A】
		{ kind: "diary", when: { choice: "B-15", is: "A" }, text: "盆は通しで開けた。四日間、鍵を一度も掛けなかった。祖母が四十年やったことを、一年ぶんだけやった。" },
		// 【B-15=B】
		{ kind: "diary", when: { choice: "B-15", is: "B" }, text: "中日の午後だけ閉めた。閉めても町は困らなかった。困らないと分かったことが、今年の収穫かもしれない。" },
		{ kind: "diary", text: "八月の集計を、七月と並べて書いた。売上は七月の一・四倍。手間は二倍。二倍働いて一・四倍というのが盆で、それを四十年やった人がいる。" },
		{ kind: "diary", text: "ほおずきは十二袋吊るして、十袋出た。二袋残ったのは、私が途中で一袋、帳面につけずに外したからで、帳面の上では数が合わない。合わないまま残しておく。" },
		{ kind: "diary", text: "十四日に外した一袋のことも書いておく。三つ破けて、四つ目で鳴った。" },
		{ kind: "diary", text: "樒の代金を、今年も同じ額で置いてきた。来年も同じにする。値段を変えない取引が一つあると、それが柱になる。" },
		{ kind: "diary", text: "前の職場の同期から、盆明けにメッセージが来た。そっちはどうか、と。忙しい、とだけ返した。忙しい、と書けるのが、去年の私からいちばん遠いところだと思う。" },
		{ kind: "diary", text: "十六日の送り火。くろまつのマスターに小菊を三本渡した。祖母が毎年そうしていたと、初めて聞いた。聞いてから、そうする側になった。" },
		{ kind: "diary", text: "八重さんが、うちの前にも火を立てていった。頼んでいない。あの人はいつもそうだ。" },
		{ kind: "diary", text: "母と電話をした。母は花がだめだと初めて知った。血は一代飛ぶらしい。飛んだ先が私で、よかったと思う。こういうことを書くようになった、この帳面は。" },
		// 【B-16=B】
		{ kind: "diary", when: { choice: "B-16", is: "B" }, text: "大阪へ青いのを送る約束をした。九月の、本番のりんどうで。母が青を好きなのを、二十七年目に知った。" },
		{ kind: "diary", text: "演歌はかけなかった。私は静かな方の血で、祖母はうるさい方の血だった。同じ店で、それでいいらしい。" },
		{ kind: "diary", text: "晴れの日に、雨の日の人が来た。あかるい束を持って帰った。白い部屋、と言っていた。" },
		{ kind: "diary", text: "大神くんは新聞を六十二枚折った。最後のほうは角が揃っていた。三日で上手くなるものらしい。折らせた新聞は全部使った。使ったと言ったら、彼は何か言いかけてやめた。何を言いかけたのかは、聞かなかった。" },
		{ kind: "diary", text: "私の八月の頁を、祖母の八月の頁と並べてみた。名前が七つ書いてある。九つには届かない。届かないが、一月は一つも書いていなかった。" },
		{ kind: "diary", text: "数字だけつけると決めて始めた帳面が、八か月で、こうなった。決めたことのほうが先に折れるらしい。" },
		{ kind: "diary", text: "今月の一輪は、りんどう。走りの、青の浅いのを一本。" },
		{ kind: "diary", text: "「花のあるほう」が帰る場所だと、彼は言った。" },
		{ kind: "diary", text: "九月は台風が来る。祖母の帳面の九月の頁は、他の月より書き込みが多い。書き込みの多い月は、荒れた月だ。" },
		{ kind: "diary", text: "祖母の一行の意味が、少しだけ、手の中に来た気がする。" },
	],
};
/** 第八章 葉月「裏方の盆」。 ⚠️並び順が再生順。 */
export const M08: readonly Vignette[] = [
	chomen0801,
	bonNoKimegoto,
	mushinNoTe,
	akaruiNoWo,
	oosaka,
	chomen0814,
	ramune,
	okuribi,
	chomen0831,
];
