/**
 * 花常 本文 第九章 長月「野分」
 * 原稿から転記した実行時シナリオデータ。
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ9-1の前」 → month-open 9
 *   「ステージ9-1クリア後」「ステージ9-2の前」 → stage-clear m9-1
 *   「ステージ9-2クリア後」 → stage-clear m9-2
 *   「ボス「野分」戦の前」 → boss-before m9-3
 *   「ボス「野分」撃破後」 → boss-after m9-3
 *   「ステージ9-3クリア後」 → stage-clear m9-3
 *   「九月の全ステージクリア後」 → month-close 9
 *
 * ⚠️「ろうそく」だけは1つの場面に選択が2つある（B-17 / B-18）。
 * 原稿が1場面として書かれているため、場面を割らずに choices を2つ持たせている。
 */

import type { Vignette } from "./types.js";

// 解放: ステージ9-1の前
const chomen0901: Vignette = {
	id: "m9-chomen-0901",
	kind: "chomen",
	month: 9,
	title: "九月一日",
	trigger: { at: "month-open", month: 9 },
	synopsis: "九月初めの帳面。敬老の日の予約の受付と、台風の進路図の見方を書く。",
	lines: [
		{ kind: "diary", text: "九月一日。曇り。" },
		{ kind: "diary", text: "りんどう三十、菊の走り二十。敬老の日の予約、受付開始。" },
		{ kind: "diary", text: "予約票、初日で十一件。うち八件が「祖父母へ」。残りの三件は「両親へ」と書いてあった。" },
		{ kind: "diary", text: "敬老、という言葉の届く範囲は、書く人によって違うらしい。訂正はしない。花は届く先の名前で決めるもので、こちらの物差しで決めるものではない。" },
		{ kind: "diary", text: "りんどうは持ちがいい。水は浅め、切り口は斜め。茎が中空なので、束の胴を握り込むと潰れる。箱から出すときは腰を持つ。" },
		{ kind: "diary", text: "菊は走り。市場の隅に、内藤さんの畑のものが少しだけ出ていた。辰巳さんが「まだ早い」と言いながら、いちばん締まったのを木札の上に置いていった。" },
		{ kind: "diary", text: "南の海に、大きい渦がひとつ。週間予報の後半に、傘と風の印が並んでいる。" },
		{ kind: "diary", text: "進路図の白い円は、先へ行くほど大きくなる。あれは「ここに来る」の図ではなく「どこに来るか分からない」の図だと、去年の予報の解説で読んだ。" },
		{ kind: "diary", text: "分からない、を図にすると、あんなに大きい。" },
		{ kind: "diary", text: "祖母の帳面の九月、頭に一行。「棚は縛れ。花は諦めるな」" },
		{ kind: "diary", text: "——これは、三月にも書いてあった。同じ字で、同じ言葉が、年に二回。" },
		{ kind: "diary", text: "それだけ大事だということだと思う。縄を買い足した。" },
		{ kind: "diary", text: "ホームセンターで太いのを二十メートル。レジの前に、同じ縄を抱えた人が三人並んでいた。町ごと、同じことを考えている。" },
		{ kind: "diary", text: "段ボールは潰して奥。バケツは水を張って重しにする。桶は積まない。積むと風に取られる。" },
		{ kind: "diary", text: "看板は二階へ上げる。上げる、と書いて気づいたけれど、去年までこの看板を上げていたのは私ではない。" },
		{ kind: "diary", text: "予約票の余白に、常連の電話番号を控え直した。停電したときに、こちらから掛ける先がいる。" },
		{ kind: "diary", text: "明日、庇の樋を掃除する。トタンは音がうるさいだけで、丈夫だ。詰まらせると、音が変わるらしい。祖母の字で「樋、九月前に必ず」とある。必ず、に傍点がついている。" },
		{ kind: "diary", text: "軽トラは満タンにした。彼岸前に一度、市場へ余分に行く。台風で市場が止まると、彼岸の入荷が丸ごと後ろにずれる。" },
		{ kind: "diary", text: "去年の九月の頁と、今年の予約数を並べてみた。件数はほぼ同じ。並びの名前は、半分が同じで、半分が知らない人だった。" },
		{ kind: "diary", text: "半分入れ替わりながら、総数が変わらない。町というのは、そういうふうにできているらしい。" },
		{ kind: "diary", text: "商店街の防災無線の点検放送が、昼にあった。毎年同じ声。毎年同じ音量で、割れている。" },
		{ kind: "diary", text: "彼岸の仕込み、二十日から。樒の確保、忘れないこと。" },
		{ kind: "diary", text: "敬老の日の予約票に、「メッセージカード希望」の欄を作る。去年の頁を見ると、当日に頼まれて慌てた形跡がある。数字の脇に「カード!」とだけ書いてあった。" },
		{ kind: "diary", text: "祖母も慌てることがあったらしい。感嘆符のついた字は、この帳面で初めて見た。" },
		{ kind: "diary", text: "走りの菊は、思ったより早く出る。次の市で追加。内藤さんの畑のは、来月から本番。" },
	],
};

// 解放: ステージ9-1クリア後
const keirouNoHi: Vignette = {
	id: "m9-keirou-no-hi",
	kind: "scene",
	month: 9,
	title: "敬老の日",
	trigger: { at: "stage-clear", stageId: "m9-1" },
	synopsis: "敬老の日の週。りんどうの青を選びに、孫たちが次々と店へ来る。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "敬老の日の週は、りんどうの青が店の主役になった。" },
		{ kind: "narration", text: "朝いちばんの光は九月に入ってから角度が変わって、店先の縁台の端までしか届かなくなった。その手前のバケツに、りんどうを立てる。青は、遠くから見ると紫に寄る。近づくと、筒の内側だけが白い。八月まで通りを埋めていた向日葵の黄色が抜けたぶん、店の前が一段静かに見えた。" },
		{ kind: "narration", text: "隣の青果から、八重さんが段ボールを抱えて出てきた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、巨峰。傷ものだけどね、味は同じ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "いつもすみません。ただ八重さん、それ、店の中には置けないので" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あー、はいはい。ガスが出るんだったね。花が早く咲いちゃうんだっけ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "早く咲いて、早く終わります。りんどうは特に嫌がります" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花の気持ちが分かるようになったねえ。常ちゃんもね、うちの林檎を一遍だけ店に置いて、次の日えらい顔してたよ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "祖母がですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃあ怒鳴られたよ、こっちが。『八重、林檎は敵だ』って" },
		{ kind: "narration", text: "台をひとつ外へ出して、ぶどうはそこに置くことで話がついた。八重さんが引き上げてすぐ、通りの向こうから、ランドセルの音が近づいてきた。" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "あの! じいちゃんに花買うの、いくらからできますか!" },
		{ kind: "narration", text: "小学生が、握りしめた小銭を勘定台に置いた。五百円玉がひとつと、百円玉が三つ。指の跡がつくくらい握っていたらしく、硬貨は生温かかった。" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "八百円ですと……りんどうを二本と、小さい菊を一本。立派な束になりますよ" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "りんどうって、どれですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "この青いの。竜の胆、と書いて、りんどうです" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "竜?! じいちゃん、竜好きです!" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "では、話が早いです" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "ひとつ聞いてもいいですか。お祖父様は、家の中で過ごされる方ですか。それとも、外の方ですか" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "外です。畑ばっかり" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "では、丈を高くします。畑の人は、低いところに置いた花を見ません。腰から上に飾るので" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "なんで知ってるんですか" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "そういう方を、この店で何十年ぶんか見ているからです" },
		{ kind: "narration", text: "自分の口から出た「この店で」を、若菜は束ねる手を止めずに通り過ぎた。りんどうを二本、走りの菊を一本、足元に小さく葉を回す。包みは紙一枚。子どもの手には、その方が持ちやすい。" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "あの、僕、字、書けます" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "字" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "なんか、こう、つける紙みたいなの" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "メッセージカードですね。ありますよ。値段には入っていませんので、書いてください" },
		{ kind: "narration", text: "男の子は勘定台に肘をついて、たっぷり三分かけて七文字を書いた。書き終えた紙を、若菜は覗かなかった。差し出された束の首に、輪ゴムで留めて返す。" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "見ないんですか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "宛名がお祖父様なので" },
		{ kind: "narration", text: "竜の花束は、男の子の全速力と一緒に商店街を駆けていった。角を曲がる直前、束が一度大きく傾いで、それでも花は落ちなかった。" },
		{ kind: "narration", text: "昼を過ぎると、客の年齢が上がった。" },
		{ kind: "say", speaker: "sub", name: "老婦人の声", text: "うちのは私より年下でね、敬老の日に花もらうと、機嫌が悪いのよ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "では、名目を変えましょう。ただの秋の花、ということで" },
		{ kind: "say", speaker: "sub", name: "老婦人の声", text: "あら。それなら文句のつけようがないわ" },
		{ kind: "say", speaker: "sub", name: "老婦人の声", text: "ねえ、この青いの、去年より濃くない?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "濃いです。今年は夏の夜が暑かったので、産地が高いところのものに切り替わりました" },
		{ kind: "say", speaker: "sub", name: "老婦人の声", text: "花にも、そういうのがあるのねえ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "毎年、少しずつ違います。同じ年はありません" },
		{ kind: "narration", text: "昼下がりに、勤め帰りらしい背広の男が、店先で長いこと迷っていた。" },
		{ kind: "say", speaker: "sub", name: "男の声", text: "その、義理の母に。仲は、まあ、普通なんですが" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "普通が、いちばん難しいです。派手でも地味でも角が立つので" },
		{ kind: "say", speaker: "sub", name: "男の声", text: "そうなんですよ。それでずっと、ここで立ってて" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、りんどうに白を一輪だけ混ぜます。全部青だと、選びすぎに見えます。少し外すと、気を遣っていないふりができます" },
		{ kind: "say", speaker: "sub", name: "男の声", text: "ふり、が要るんですか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "義理は、ふりの分だけ、楽になります" },
		{ kind: "narration", text: "男は、少し笑って、青と白の束を持って帰った。若菜は頁に「気を遣わないふり希望」と書いて、その下に線を引いた。" },
		{ kind: "narration", text: "夕方には、孫の写真を財布に入れた常連たちが、それぞれの青を選んでいった。りんどうの箱は三十本が七本になり、走りの菊は、思っていたより早く尽きた。" },
		{ kind: "narration", bg: "shop_evening", text: "閉店間際、レンがフォームの改修に来て、その話を聞いた。ノートパソコンを勘定台の隅に開いて、画面の白い光が、暗くなりかけた店を下から照らしている。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "予約フォーム、項目ひとつ増やしますね。『渡す相手との関係』。プルダウンで、祖父母・両親・その他" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "その他は要りますか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "要ります。要らないと思って消すと、だいたい後で要るんですよ。人間、その他の生き物なんで" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "変な言い方をしますね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "褒め言葉のつもりでした" },
		{ kind: "narration", text: "キーの音が続いた。三十秒ほどして、レンが顔を上げる。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "竜の胆で竜好きに刺さるの、いいなあ。俺も、じいちゃん生きてたら買ったんだけどな、竜" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "お祖父様も、林業を?" },
		{ kind: "say", speaker: "ren", emo: 1, text: "山です、ずっと。冬は雪囲い、春は植え付け。俺が小さい頃、山に連れてかれて、木の根元で寝てたらしいですよ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "起こされなかったんですか" },
		{ kind: "say", speaker: "ren", emo: 15, text: "起こす人じゃなかったんで。……俺が獣人なの、じいちゃん譲りなんですよ。親父は人間なんで" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "そうなんですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "隔世っていうか、飛ぶんですよね、ああいうの" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "……血は、一代飛ぶって、うちの母も言ってました" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、おそろいだ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "三隅さんとこは、何が飛んだんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花です。母は、花が苦手なので" },
		{ kind: "say", speaker: "ren", emo: 4, text: "苦手" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "切り花の水の匂いが駄目だと、はっきり言われたことがあります。祖母は一度も直そうとしませんでした" },
		{ kind: "say", speaker: "ren", emo: 20, text: "直すもんじゃないですもんね、そういうのは" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい。それで、私に飛びました" },
		{ kind: "narration", text: "レンは画面から手を離して、りんどうの残った七本を見た。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃあ竜は、二代ぶん飛んで、ここに着いたってことで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "話が大きくなっています" },
		{ kind: "say", speaker: "ren", emo: 18, text: "竜ですから" },
	],
};

// 解放: ステージ9-2の前
const akiHigan: Vignette = {
	id: "m9-aki-higan",
	kind: "scene",
	month: 9,
	title: "秋彼岸",
	trigger: { at: "stage-clear", stageId: "m9-1" },
	synopsis: "彼岸の入り。一対の仏花を組みながら、家ごとの決まりごとを聞き取る。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "彼岸の入りは、朝から曇って、風がなかった。" },
		{ kind: "narration", text: "作業場の水場に、樒と菊と鶏頭を並べる。仏花は左右で対になるので、同じものを二度作る。一度目に迷って、二度目は迷わない。作業台の縁に、切り落とした茎が溜まっていく。水を張った桶の底で、菊の切り口が白く光った。" },
		{ kind: "narration", text: "表のガラス戸が開いて、閉まって、また開いた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、おはぎ。うちのじゃないよ、霜月堂のだよ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "わざわざありがとうございます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "わざわざじゃないの。うちの分を買いに行って、多く買っちゃっただけ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "その言い方、祖母もしていました" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃあね。四十年、隣で同じ嘘ついてたんだから" },
		{ kind: "narration", text: "八重さんは、対になった束を両方とも覗き込んで、片方の鶏頭の位置を指で示した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "こっち、赤が右に寄ってない?" },
		{ kind: "say", speaker: "wakana", emo: 12, text: "……寄っています" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花のことは分かんないけどさ、二つ並んでると、ずれてるのだけは分かるんだよ" },
		{ kind: "narration", text: "直してから、若菜は左右を入れ替えて、もう一度見た。八重さんはもう表に出ていて、通りで誰かと台風の話をしている。「進路がねえ」「まだ分かんないってさ」。同じ会話が、この三日で商店街を何周かしていた。" },
		{ kind: "narration", text: "昼前に、墓参りの帰りらしい客が続いた。" },
		{ kind: "say", speaker: "sub", name: "老人の声", text: "一対でな。線香は持っとる" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "はい。持ちを良くしたいので、水は現地で足してください。桶が置いてあるはずです" },
		{ kind: "say", speaker: "sub", name: "老人の声", text: "桶な。あそこの桶は、柄杓の柄が短くてかなわん" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "では、この束は少し短く切っておきます。屈む回数が減ります" },
		{ kind: "say", speaker: "sub", name: "老人の声", text: "花屋がそこまで考えるか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "考えます。持って行った先で、格好がつかないと困りますので" },
		{ kind: "say", speaker: "sub", name: "若い女の声", text: "あの、初めてで。何を買えばいいのか、まったく分からなくて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "どなたの、どちらへ持って行かれますか" },
		{ kind: "say", speaker: "sub", name: "若い女の声", text: "夫の実家のお墓です。私、嫁いで初めての彼岸で" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、無難にします。無難は、悪い意味ではありません。初めての年は、その家の流儀が分かりませんので" },
		{ kind: "say", speaker: "sub", name: "若い女の声", text: "流儀" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "家によって、菊だけ、と決まっているところがあります。色を入れない家もあります。今年よく見て、来年から少し足していけばいいです" },
		{ kind: "say", speaker: "sub", name: "若い女の声", text: "来年" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "来年も、いらっしゃると思いますので" },
		{ kind: "narration", text: "女性は一対を抱えて、二度お辞儀をして出ていった。若菜は、頁の上に「初彼岸のお嫁さん」と書いて、あとで名前を聞き忘れたことに気づいた。" },
		{ kind: "narration", text: "戸がまた開いて、常連の花木さんが、いつもの菊を取りに来た。" },
		{ kind: "say", speaker: "sub", name: "花木さん", text: "若菜ちゃん、台風、店は縛るの?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今夜、縛ります。花木さんのお宅は" },
		{ kind: "say", speaker: "sub", name: "花木さん", text: "うちはもう板張った。爺さんが張り切っちゃってさ。年に一回、あの人が役に立つ日なんだよ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "役に立つ日が、決まっているんですね" },
		{ kind: "say", speaker: "sub", name: "花木さん", text: "決まってんの。あとの三百六十四日は、こたつでみかん" },
		{ kind: "narration", text: "菊を包みながら、若菜は表の空を一度見た。まだ、風はなかった。雲だけが、高いところを速く流れていた。" },
		{ kind: "narration", text: "昼を回った頃、戸が静かに開いて、そのまま静かに閉まった。熊谷玄が、紙袋をひとつ勘定台に置いていた。中身は挽きたての豆で、袋の口が几帳面に二回折ってある。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……豆" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "ありがとうございます。今日は、りんどうでいいですか" },
		{ kind: "narration", text: "玄は答えなかった。答えないのが返事ではないことを、若菜は三月から知っている。" },
		{ kind: "narration", text: "玄は、ケースの前まで行って、りんどうではなく、走りの菊の最後の一本を見た。それから、若菜を見た。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "そちらですね。分かりました" },
		{ kind: "narration", text: "包んだ一本を受け取って、玄は片手を上げて出ていった。会話は、ぜんぶで二音だった。丸椅子の上には、いつも通り、何も残っていない。" },
		{ kind: "narration", text: "客足の切れた午後、若菜は勘定台の下から古帳面を出した。去年の九月の頁を開く。彼岸の三日間に、祖母の字が縦に詰まっていた。" },
		{ kind: "narration", text: "数字ではなかった。名前だった。「戸田さん一対」「くろまつ 菊一」「西村さんとこの嫁さん、初彼岸」。売上の合計は、頁のいちばん下に、思い出したように小さく書いてある。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "……順番が、逆" },
		{ kind: "narration", text: "言ってから、自分の帳面を開いた。今年の九月の頁は、まだ数字が上にある。名前は、余白に漏れているだけだった。" },
		{ kind: "narration", text: "若菜は、彼岸の三日ぶんの客を、思い出せる限り書き足した。書き足せたのは、思っていたより多かった。" },
	],
};

// 解放: ステージ9-2クリア後
const chomen0919: Vignette = {
	id: "m9-chomen-0919",
	kind: "chomen",
	month: 9,
	title: "九月十九日",
	trigger: { at: "stage-clear", stageId: "m9-2" },
	synopsis: "彼岸の中日の帳面。祖母の帳面に年二度だけ現れる同じ言葉に気づく。",
	lines: [
		{ kind: "diary", text: "九月十九日。曇りのち晴れ。彼岸の中日。" },
		{ kind: "diary", text: "一対の仏花、二十二対。単発の菊、十八。鶏頭は、来年もう少し多く取る。" },
		{ kind: "diary", text: "くろまつのマスターが豆を置いていった。持って帰ったのは、りんどうではなく走りの菊の最後の一本。" },
		{ kind: "diary", text: "菊は、あの人にとって、たぶん青より上らしい。理由は聞いていない。聞かなくても、来年また分かる。" },
		{ kind: "diary", text: "古帳面、去年の彼岸の頁。名前が上で、数字が下だった。私は逆に書いている。" },
		{ kind: "diary", text: "逆に書いていると気づいたので、書き足した。書き足せた名前が、去年の私よりは多い。" },
		{ kind: "diary", text: "台風。進路が固まった。明後日の夜、この町のあたりを通る。円は、まだ大きい。" },
		{ kind: "diary", text: "祖母の帳面をもう一度繰った。九月の頭の「棚は縛れ。花は諦めるな」。" },
		{ kind: "diary", text: "三月の頁と、並べて見た。同じ字ではあるけれど、同じではなかった。" },
		{ kind: "diary", text: "三月のほうは筆圧が強い。九月のほうは、線が細くて、まっすぐで、書き慣れている。" },
		{ kind: "diary", text: "——年に二回、同じ言葉を、何十年も書いてきた人の手だ。" },
		{ kind: "diary", text: "一度目は自分に言い聞かせるために、二度目は、確認のために書いたのだと思う。" },
		{ kind: "diary", text: "私はまだ、一度目の書き方しかできない。" },
		{ kind: "diary", text: "それでいいのだと思う。二度目の書き方は、二度目にならないと書けない。" },
		{ kind: "diary", text: "三月の頁の下に、その年の被害が書いてある。「簾一枚。花、全部無事」。私も同じ形で書くことにした。形を借りるのは、真似ではなくて、続きだと思うことにする。" },
		{ kind: "diary", text: "縄、二十メートルでは足りない。もう二十メートル買った。太さの違うものを混ぜると結び目が滑ると、店の人に言われた。同じ太さで揃えた。" },
		{ kind: "diary", text: "明後日は臨時休業にする。貼り紙を出した。「台風のため休みます。二十二日から通常どおり」。" },
		{ kind: "diary", text: "通常どおり、と書いてから、少し迷って、そのままにした。書いておかないと、こちらの分が心細い。" },
		{ kind: "diary", text: "予約の三件に、前倒しで届けると電話した。三軒とも、こちらが謝る前に「気をつけてね」と言われた。" },
		{ kind: "diary", text: "冷蔵ケースの取扱説明書を、初めて最後まで読んだ。停電時の記述は、六行しかなかった。" },
		{ kind: "diary", text: "六行で止まっている。残りは店の人間が考える。" },
		{ kind: "diary", text: "彼岸の売上、去年の九割。彼岸の入りが平日だったせいだと思う。数字は、そう書いておく。" },
		{ kind: "diary", text: "名前は、二十二人ぶん書けた。頁が足りなくなったので、罫線を無視して横に書いた。" },
		{ kind: "diary", text: "樒、二把余り。台風のあとに使う。仏花は、風の日でも要る。要る日に店を閉めるのは、今回だけにしたい。" },
	],
};

// 解放: ボス「野分」戦の前
const shibaruYoru: Vignette = {
	id: "m9-shibaru-yoru",
	kind: "scene",
	month: 9,
	title: "縛る夜",
	trigger: { at: "boss-before", stageId: "m9-3" },
	synopsis: "台風の夜を前に、商店街ごと店じまいにかかる。犬飼が荷運びに合流し、縄の引き方を教わる。",
	lines: [
		{ kind: "narration", bg: "front_autumn", text: "台風は、夜に来ると予報が言った。" },
		{ kind: "narration", text: "昼過ぎの空は、雲の下だけ白く明るかった。雲が高いところを速く流れて、その下の空気だけが動かない。通りの旗が垂れたまま、いっさい揺れなかった。風の前は静かになる、と誰もが知っていて、それでも毎回、静かさのほうに驚く。" },
		{ kind: "narration", text: "午後から商店街は店じまいの音で忙しくなった。シャッターの下りる音、脚立を畳む音、板を打ちつける釘の音。花常でも、桶を全部奥へ、ケースの中身を詰め直し、看板は二階へ。レンは講義のあと直行で来て、腕まくりをした。" },
		{ kind: "say", speaker: "ren", emo: 16, text: "縛りもの、全部やります! 縄どこですか!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "作業場の壁に掛けてあります。太いほうを使ってください" },
		{ kind: "say", speaker: "ren", emo: 1, text: "棚、手前から縛ります?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "風下から。風上から縛ると、途中で緩んだときに全部持っていかれます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "そういうのがあるんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "祖母の帳面に書いてありました。理屈は書いてありません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "理屈のない手順って、いちばん強いやつでしょ。運用で生き残ったやつなんで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "看板を、二階へ上げてもらえますか。急な階段なので、後ろ向きで" },
		{ kind: "say", speaker: "ren", emo: 19, text: "後ろ向き?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "前向きだと、看板が先に見えて、足元が見えません。毎年、それで一段踏み外す人がいます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "その『毎年いる人』、けっこう出てきますね、この町" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "同じ失敗を、みんなが一回ずつします。だから手順になります" },
		{ kind: "narration", text: "レンが看板を抱えて、階段を後ろ向きに上がっていった。途中で一度、足を止める音がした。段の高さが一段だけ違う、あの段だった。" },
		{ kind: "narration", text: "そこへ、台車の音。市場帰りの犬飼が、軽トラを店の前に停めた。荷台には、空の花箱が高く積んである。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "親父が、花常さん見てこいって。うちはもう閉めた" },
		{ kind: "say", speaker: "wakana", emo: 9, text: "助かります。お父様に、後日きちんとお礼を" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "いいって。台風のたんびに、常さんとこは市場から誰か来る決まりだったんだよ。——おい狼、縄の結び、できんのか" },
		{ kind: "say", speaker: "ren", emo: 6, text: "南京結びなら、こないだ動画で" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "動画かよ。どけ、教える" },
		{ kind: "narration", text: "犬飼の手元で、縄は生き物のように締まった。二回ひねって、輪を作って、そこへ通した端を引く。それだけの動きなのに、レンが同じようにやると、輪が潰れて締まらない。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "力じゃねえ。角度" },
		{ kind: "say", speaker: "ren", emo: 20, text: "角度" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "引く方向。荷物に対して斜め下。上に引いたら、荷物が浮くだろうが" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あー、なるほど。ベクトルの話ですね" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "知らねえよ、そんな言葉" },
		{ kind: "narration", text: "レンが真似て、二回失敗して、三回目に決まった。締めた縄を、犬飼が親指で弾く。硬い音がした。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "よし。覚えたな。次の台風から、あんたが誰かに教えろ" },
		{ kind: "say", speaker: "ren", emo: 4, text: "俺がですか" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "そういうもんだろ、結びってのは" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "俺だって、親父じゃなくて、市場の爺さんに教わったんだ。名前も覚えてねえ爺さんに" },
		{ kind: "say", speaker: "ren", emo: 19, text: "それ、教わったって言うんですかね" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "言うんだよ。手が覚えてんだから" },
		{ kind: "narration", text: "犬飼が、作業場の一番大きな棚に手をかけて、揺すった。上の段が、こと、と鳴る。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "ここ、上段が遊んでる。中身入れたまま縛るな。重心が上に来る" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "先に下ろします" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "下ろしたら、下の段から縛れ。上から縛ると、下を締めるときにほどく羽目になる" },
		{ kind: "narration", text: "レンが、言われた順に段を空けて、下から縄をかけていった。二段目で手が止まる。輪の角度を、さっき教わったとおりに探していた。口を結んで、縄の端だけを見ている。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "ここ、斜め下" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "そう。引け" },
		{ kind: "narration", text: "締まった。棚を揺すっても、もう鳴らない。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "よし。飲み込みは早いな、狼" },
		{ kind: "say", speaker: "ren", emo: 15, text: "手が、でしょ。さっき褒めてくれたの、手なんで" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "調子に乗るな" },
		{ kind: "narration", text: "犬飼が、軽トラの荷台から空の花箱を店の中へ運び込みはじめた。中身のない箱でも積み方があるらしく、口を互い違いにして重ねていく。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "箱は逃がしとけ。外に出しとくと、風の日は凧になる" },
		{ kind: "say", speaker: "ren", emo: 4, text: "凧" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "去年、まるはちの林檎箱が坂の上まで飛んでった。八重さんが追いかけてったよ" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "追いかけて、どうするんですか" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "どうもしねえ。悔しいから追うんだ、人は" },
		{ kind: "narration", text: "三人で、二十枚ほどの箱を奥に積んだ。レンが最後の一枚を、犬飼の積み方どおり、口を互い違いにして載せた。犬飼が横目でそれを見て、何も言わなかった。言わないのが、合格らしかった。" },
		{ kind: "narration", text: "軽トラの荷台から、犬飼が古い波板を三枚下ろした。ガラス戸の外側に立てかけて、下を重しのブロックで押さえる。" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "そこまでしていただかなくても" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "飛んでくるもんは、花屋の都合を聞かねえの。この通り、看板の多い町だから" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "あと、狼。おまえ、耳しまえよ。飛来物、耳から来るぞ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "しまえないんですよ、これ" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "知ってる。言ってみたかっただけだ" },
		{ kind: "say", speaker: "ren", emo: 15, text: "犬のくせに人が悪い" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "柴だ" },
		{ kind: "narration", text: "三人で、店先の鉢を最後にひとつずつ運んだ。りんどうの残りは、奥のケースの下段に寝かせた。立てておくと、揺れで首が折れる。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "花、寝かすんだな" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "立っているものは、倒れます。最初から寝ていれば、倒れません" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "うちの親父と同じこと言うな、あんた" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "同じ市場で覚えたことですので" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それ、サーバーも同じですよ。落ちて困るものは、先に落としとく" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "なんの話だ" },
		{ kind: "say", speaker: "ren", emo: 5, text: "同じ話です" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "気色悪いな、あんたら" },
		{ kind: "narration", text: "隣の青果から、八重さんが顔を出した。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、うち、二階の雨戸が一枚建て付け悪くてね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今から伺います" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "俺が行く。花屋は花見てろ" },
		{ kind: "narration", text: "犬飼が隣へ消えて、少しして、板を叩く音と八重さんの笑い声が聞こえてきた。レンは縄の残りを腕に巻き取りながら、その音のするほうを見ていた。" },
		{ kind: "narration", text: "巻き取り方が、途中から変わった。腕に八の字に掛けて、最後に真ん中を締める。犬飼が教えたのは結びだけで、巻き方までは教えていない。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "その巻き方は、どちらで" },
		{ kind: "say", speaker: "ren", emo: 19, text: "え。あー、これは、なんか、そうやるもんだと思ってました" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "そうですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "ほどけないんですよ、こうすると。次に使うとき、早いんで" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "早いです。とても" },
		{ kind: "narration", text: "若菜は縄をそれ以上見ずに、作業場へ戻って、鋏を工具箱に片付けた。台風の前に開ける引き出しと、そうでない引き出しがある。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "この町、非常時の手順が全員に入ってるんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "毎年来ますから" },
		{ kind: "say", speaker: "ren", emo: 6, text: "毎年来るものに、毎年ちゃんと備えるのって、けっこう難しいんですよ。人間、慣れるとサボるんで" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "サボると、花が駄目になります。翌朝すぐに" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー。止まると困るもんがあると、人間、続くんですよね" },
		{ kind: "narration", text: "棚を縛り終えた頃、レンのスマホが鳴った。スピーカーから、先輩の声が漏れる。" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "大神ー、サークルのサーバー、雷サージ来る前にシャットダウンしとけよ" },
		{ kind: "say", speaker: "ren", emo: 5, text: "もうしました。無停電電源も確認済みです" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "はっや。バックアップは" },
		{ kind: "say", speaker: "ren", emo: 1, text: "昨日の分、外に逃がしてます。部室のブレーカーも落としました。窓、内側からテープ貼ってあるんで、割れても飛び散らないです" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "おまえ何時に部室いたんだよ" },
		{ kind: "say", speaker: "ren", emo: 5, text: "一限の前です" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "……こわ。おまえ今どこ" },
		{ kind: "say", speaker: "ren", emo: 15, text: "……花屋です" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "は? 花屋?" },
		{ kind: "say", speaker: "ren", emo: 21, text: "こっちにも、落ちたら困るサーバーがあるんで" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "花屋にサーバーがあんの?" },
		{ kind: "say", speaker: "ren", emo: 15, text: "ある、みたいなもんです" },
		{ kind: "say", speaker: "sub", name: "堂本の声", text: "なんだそれ。冠水したら帰れねえぞ、川沿いだろそこ" },
		{ kind: "say", speaker: "ren", emo: 5, text: "知ってます。地図、見ました" },
		{ kind: "say", speaker: "sub", name: "堂本", text: "お前、去年もそれ言ってたな。花屋、花屋って" },
		{ kind: "say", speaker: "ren", emo: 8, text: "言ってないですって" },
		{ kind: "say", speaker: "sub", name: "堂本", text: "言ってた。閉まってるって、ずっと言ってた" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……" },
		{ kind: "narration", text: "電話は、怪訝な音を残して切れた。若菜は、聞こえなかったふりをして、最後の桶を運んだ。運びながら、地図、という一語が耳の奥に残った。" },
		{ kind: "narration", text: "八重さんのところから戻ってきた犬飼が、軍手を外して荷台に放った。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "雨戸、直しといた。あとは、二階に上げた看板が落ちてこなけりゃいい" },
		{ kind: "say", speaker: "ren", emo: 16, text: "落としません。後ろ向きで上げたんで" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "後ろ向き? 誰に教わった" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "私です" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "そうか。常さんとこの手順だな、それも" },
		{ kind: "narration", text: "犬飼は軽トラに乗って、窓から片手を出した。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "花屋、無理すんな。無理して守るもんでもねえ、花は。また作りゃいい" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "作ります。無事だったら、無事だった花で" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "それでいい。——狼、飯は自分で買え。花屋に集るなよ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "集ってないですって" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "顔に書いてある" },
		{ kind: "narration", text: "軽トラのテールランプが、静かな通りを川のほうへ下っていった。曲がり角で一度だけ、ブレーキの赤が長く灯って、消えた。" },
		{ kind: "narration", text: "日が落ちる前に、最後の確認をした。ケースの温度を下げきっておく。断熱のために、扉の内側に段ボールを一枚。作業場の窓に、内側からテープを×に貼る。バケツに水を張って、床に四つ並べる。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、飛ばないようにってことですよね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "それと、断水したときの水です。花に使う分ではありませんが" },
		{ kind: "say", speaker: "ren", emo: 4, text: "断水も来るんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "来たことがあるそうです。祖母の帳面に、風呂に水を張れと書いてあります" },
		{ kind: "say", speaker: "ren", emo: 1, text: "二階、風呂あるんですね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "あります" },
		{ kind: "say", speaker: "ren", emo: 6, text: "変な意味じゃないです。備蓄の話です" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "分かっています" },
		{ kind: "narration", text: "戸を閉める前に、通りを一度見た。商店街から、看板という看板が消えていた。並びが急に低くなって、空が広い。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "なんか、町が縮こまってるみたいですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "頭を下げて、やり過ごすんです。毎年" },
		{ kind: "say", speaker: "ren", emo: 6, text: "花屋の言うことじゃないでしょ、それ" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "花屋の言うことです。折れなければ、また立ちます" },
	],
};

// 解放: ボス「野分」撃破後
const rousoku: Vignette = {
	id: "m9-rousoku",
	kind: "scene",
	month: 9,
	title: "ろうそく",
	trigger: { at: "boss-after", stageId: "m9-3" },
	synopsis: "停電した夜、ろうそく二本の灯りで風の通り過ぎるのを待つ。長い夜の話と、その返事。",
	choices: [
		{
			id: "B-17",
			label: "停電の夜",
			axis: "縁",
			options: [
				{ key: "A", label: "二階に泊める", note: "縁+1" },
				{ key: "B", label: "風が緩んだら、送り出す" },
			],
		},
		{
			id: "B-18",
			label: "返答",
			options: [
				{ key: "A", label: "「努力します」" },
				{ key: "B", label: "「なくしません」" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "shop_night", text: "風の芯が通り過ぎたのは、九時過ぎだった。" },
		{ kind: "narration", text: "その少し前に、商店街ごと停電した。冷蔵ケースの唸りが消えて、店の中に、それまで聞こえていなかった音がいくつも現れた。トタン庇に何かが当たる音。ガラス戸が枠の中で細かく鳴る音。奥の水場で、蛇口の先の一滴が桶に落ちる音。" },
		{ kind: "narration", text: "花常の店の中は、ろうそく二本の灯りになった。勘定台に一本、作業台に一本。炎は、風のたびに縦に伸びたり、横に寝たりした。ガラス戸の外を、風がまだ太い音で通っている。レンの終電は、とうに諦めがついていた。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "まあ、こういう夜も、あるもんですねえ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "懐中電灯もあります。ろうそくは、祖母の置き土産です" },
		{ kind: "say", speaker: "ren", emo: 20, text: "置き土産" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "戸棚に十本ありました。賞味期限のない備蓄というのは、なんというか、油断のない人です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "花屋の備蓄、渋いなあ" },
		{ kind: "narration", text: "レンは、勘定台の上のろうそくの高さに目を落としてから、時計を見た。針は、暗くてもよく見える位置にあった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "三隅さん、ケースの中って、何度まで平気なんですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今の時季なら、十五度を超えなければ。菊は強いです。りんどうも、そこそこ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ扉は、開けないほうがいいですね。何回開けたか数えときます" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "数えるんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "開閉回数と復電時刻がわかると、あとで庫内の熱の入り方を逆算できるんで。次から扉の開け方が決まるんですよ。あと、外気温も測っときたいんですけど、温度計あります?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "作業場に、水温を見るのがあります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "最高じゃないですか" },
		{ kind: "narration", text: "早口だった。レンが温度計を取りに立って、戻ってきて、ろうそくの脇にそれを寝かせた。ガラスの管の中の赤い線が、灯りの中で細く光っている。" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "大神さんは、停電が楽しいんですか" },
		{ kind: "say", speaker: "ren", emo: 3, text: "楽しくはないですけど。手順があると、落ち着くんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "分かります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ、分かるんですね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "花屋も、慌てても花は保たないので。順番を決めて、そのとおりにやるだけです" },
		{ kind: "narration", text: "外で、大きな音がした。金属が転がる音が、通りを東から西へ抜けていった。二人とも動かなかった。動いても、どうにもならない類の音だった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "今の、たぶん米屋の看板ですね" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "音で分かるんですか" },
		{ kind: "say", speaker: "ren", emo: 15, text: "距離と、あと、音の高さで。耳、そこそこいいんで" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "便利ですね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "便利じゃないですよ。大学の講義中、後ろの席の腹の音まで聞こえるんで" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "それは、聞かないであげてください" },
		{ kind: "say", speaker: "ren", emo: 6, text: "努力はしてます" },
		{ kind: "narration", text: "若菜は立って、暗いケースの前まで手探りで行った。扉は開けない。ガラス越しに、掌を当てるだけにする。冷たさは、まだ残っていた。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "開けないで分かるんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "扉が冷たければ、中も冷たいです。手のひらが温度計です" },
		{ kind: "say", speaker: "ren", emo: 6, text: "それ、俺の温度計、いらなかったやつじゃ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "両方あるといいです。あなたのは数字が出ます。私のは、出ません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "引き分けってことで" },
		{ kind: "narration", text: "作業台の上で、若菜は手を滑らせて、鋏の位置を確かめた。刃を閉じて、柄を奥に向けて置き直す。暗い中で刃先が外を向いていると、次に触った人が指を切る。見えなくても、置き方だけは変えない。" },
		{ kind: "narration", text: "スマホが短く鳴った。レンが画面を伏せて、また表に返す。" },
		{ kind: "say", speaker: "ren", emo: 13, text: "犬飼さんです。『着いた。店は無事か』って" },
		{ kind: "say", speaker: "wakana", emo: 9, text: "着きましたか" },
		{ kind: "say", speaker: "ren", emo: 13, text: "着きましたね" },
		{ kind: "say", speaker: "ren", emo: 1, text: "なんて返します" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花、無事。人も無事。とだけ" },
		{ kind: "narration", text: "レンが親指を動かして、すぐに返事が来た。画面の光が、レンの顔を下から一瞬だけ照らした。" },
		{ kind: "say", speaker: "ren", emo: 6, text: "『狼に飯食わすな』って書いてあります" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "余計なお世話です" },
		{ kind: "say", speaker: "ren", emo: 6, text: "食わせてもらってないんで、事実ではあります" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "乾麺ならあります" },
		// ◆選択 B-17「停電の夜」(軸: 縁)
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "wakana", emo: 10, text: "二階に、祖母の客用布団があります。あとで出します" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "wakana", emo: 16, text: "この風の中を歩かせて、何かあったら、私が困ります" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "ren", emo: 3, text: "お世話になります" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "wakana", emo: 4, text: "階段が急なので、灯りなしで上がらないでください。段の高さが、途中で一段だけ違います" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "ren", emo: 19, text: "なんで一段だけ" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "wakana", emo: 15, text: "知りません。祖母もそう言っていました。知らないまま、みんな気をつけて上がっています" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "ren", emo: 2, text: "バグを直さないで運用でカバーするやつだ" },
		{ kind: "say", when: { choice: "B-17", is: "A" }, speaker: "wakana", emo: 3, text: "そういう言い方をされると、少し嫌です" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "wakana", emo: 16, text: "風が緩んだら、タクシーを呼びます。代金はうちが持ちます。労賃です" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "ren", emo: 19, text: "え、いや、自転車が" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "wakana", emo: 16, text: "自転車は明日、取りに来てください。この風に、大事な常連を出すわけにはいかないので" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "ren", emo: 4, text: "大事な" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "wakana", emo: 11, text: "常連を、です" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "ren", emo: 18, text: "はい。大事な常連です、俺" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "wakana", emo: 3, text: "自分で言わないでください" },
		{ kind: "say", when: { choice: "B-17", is: "B" }, speaker: "ren", emo: 2, text: "言っときました。証拠が残るんで" },
		// 【合流】
		{ kind: "narration", text: "ろうそくの火が、二人の影を壁で大きくしたり小さくしたりした。風が鳴るたび、ケースの中の花が、灯りの中で少し揺れて見えた。停電したケースの温度を、若菜は頭の隅で数えている。朝までなら、もつ。" },
		{ kind: "narration", text: "先に、乾麺を茹でた。カセットコンロの火が、店の中でいちばん明るかった。湯の沸く音が、風の音の下でだけ、はっきり聞こえる。丼はひとつしかなくて、鍋のまま、箸を二膳出した。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "鍋から直だ。贅沢だなあ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "洗い物が、断水だと困りますので" },
		{ kind: "say", speaker: "ren", emo: 6, text: "理由が渋い" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "渋くないです。ただの水の勘定です" },
		{ kind: "narration", text: "麺は、暗い中で茹で加減が読めなくて、少し柔らかくなった。二人とも、それには触れなかった。" },
		{ kind: "narration", text: "湯が残ったので、そのままカセットコンロで沸かし直して、玄の豆を落とした。ドリッパーはあるが、電気ケトルは使えない。湯の細い筋が、暗い中では見えなくて、音だけで加減した。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "暗いとこで淹れる珈琲、うまいってことにしません?" },
		{ kind: "say", speaker: "wakana", emo: 12, text: "実際、濃いです。湯の落ちる量が読めませんでした" },
		{ kind: "say", speaker: "ren", emo: 2, text: "濃いのは正義でしょ" },
		{ kind: "narration", text: "二つのカップを持って、勘定台の前に並んで腰を下ろした。床は、昼間の熱をもう手放していた。勘定台の奥に、丸椅子がひとつある。二人とも、そこには座らなかった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "この豆、くろまつのですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "彼岸に置いていかれたものです。あの方は、代金を受け取りません" },
		{ kind: "say", speaker: "ren", emo: 19, text: "じゃあ、どうすんですか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "花を持って帰ってもらいます。祖母の代からそうだったそうです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "物々交換だ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "豆と花です。相場は誰も決めていません" },
		{ kind: "say", speaker: "ren", emo: 20, text: "いい相場ですね。値段つけたら、たぶん壊れるやつだ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "この店、停電しても、あんまり変わらないですね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "真っ暗ですが" },
		{ kind: "say", speaker: "ren", emo: 1, text: "いや、そうじゃなくて。物が、ぜんぶ電気なしで使えるやつじゃないですか。桶とか、鋏とか、箒とか。うち、コンセント抜いたら何も残らないですよ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "レジは動きません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あれ、俺が直したやつなんで、動かなくても俺のせいじゃないってことにします" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "二月から数えて、一度も止まっていません" },
		{ kind: "say", speaker: "ren", emo: 3, text: "そうなんですか" },
		{ kind: "narration", text: "風が、一段強く鳴った。ガラスが枠の中で細かく震えて、波板が外側で低い音を返した。犬飼が立てていった三枚が、そのぶんの音を引き受けている。" },
		{ kind: "say", speaker: "ren", emo: 14, text: "犬飼さん、家に着いたかな" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "あの方は、着いていると思います" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんでそんなに信用があるんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "縄の引き方が、着く人のそれでした" },
		{ kind: "say", speaker: "ren", emo: 4, text: "その基準、初めて聞いた" },
		{ kind: "narration", text: "風の音の質が、少しずつ変わっていった。太いうなりに、時々、高い笛のような音が混じる。店と店の隙間を、風が通っている音だった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "今の高い音、霜月堂の看板じゃないですか。金具のあいだで鳴ってる" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "そこだと思います。毎年、同じところが鳴ります。あとで直す場所の、目星がつきます" },
		{ kind: "say", speaker: "ren", emo: 20, text: "停電を、点検にしてるんですね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "暗いと、耳のほうが働きます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "それ、俺の台詞だったんですけど" },
		{ kind: "narration", text: "炎が短くなって、蝋が台に一滴垂れた。しばらく、風の音しかしない時間があった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……三隅さん" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "ren", emo: 14, text: "来年も——" },
		{ kind: "narration", text: "炎が、風の入り口を探すように一度傾いだ。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "この店、なくならないでくださいね" },
		{ kind: "narration", text: "風が鳴っているあいだ、その声だけが、鳴っていない場所から来た。" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "……" },
		// ◆選択 B-18「返答」(軸: なし)
		{ kind: "say", when: { choice: "B-18", is: "A" }, speaker: "wakana", emo: 10, text: "……努力します" },
		{ kind: "say", when: { choice: "B-18", is: "A" }, speaker: "ren", emo: 15, text: "約束とかじゃなくて。いや、なんだろな。言いたかっただけです、たぶん" },
		{ kind: "say", when: { choice: "B-18", is: "A" }, speaker: "wakana", emo: 16, text: "はい。聞きました、たしかに" },
		{ kind: "say", when: { choice: "B-18", is: "A" }, speaker: "ren", emo: 6, text: "聞きましたって、なんか、受付みたいですね" },
		{ kind: "say", when: { choice: "B-18", is: "A" }, speaker: "wakana", emo: 15, text: "受付です。控えを取りました" },
		{ kind: "say", when: { choice: "B-18", is: "B" }, speaker: "wakana", emo: 18, text: "……なくしません" },
		{ kind: "say", when: { choice: "B-18", is: "B" }, speaker: "ren", emo: 4, text: "言い切った" },
		{ kind: "say", when: { choice: "B-18", is: "B" }, speaker: "wakana", emo: 16, text: "言い切りました。言った以上、そういうことです" },
		{ kind: "say", when: { choice: "B-18", is: "B" }, speaker: "ren", emo: 2, text: "はい。証人になります、俺" },
		// 【合流】
		{ kind: "narration", text: "ろうそくが一本、短くなって消えた。レンは残った一本を見て、それから、いつもの声に戻った。" },
		{ kind: "say", speaker: "ren", emo: 14, text: "ろうそく、もう一本あります? 俺、暗いの平気ですけど、花は暗いと寂しそうなんで" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "花は、暗いほうが保ちます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "事実で殴らないでください" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "戸棚に、あと八本あります" },
		{ kind: "narration", text: "新しい一本に火を移すと、店の奥までもう一度、輪郭が戻った。ケースの中で、りんどうの青が、灯りの色を吸って濃く見える。" },
		{ kind: "say", speaker: "ren", emo: 13, text: "風、さっきより丸くなってません?" },
		{ kind: "say", speaker: "wakana", emo: 9, text: "音が変わりました。芯が抜けたんだと思います" },
		{ kind: "say", speaker: "ren", emo: 19, text: "抜けたって、分かるもんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "祖母が言っていました。行きの風と、帰りの風は、鳴り方が違うと" },
		{ kind: "say", speaker: "ren", emo: 2, text: "花屋、気象台みたいなことしますね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "気象台のほうが正確です。ただ、こちらのほうが早いです" },
		{ kind: "narration", text: "温度計の赤い線は、夜のあいだ、ほとんど動かなかった。" },
	],
};

// 解放: ステージ9-3クリア後
const takebouki: Vignette = {
	id: "m9-takebouki",
	kind: "scene",
	month: 9,
	title: "竹箒",
	trigger: { at: "stage-clear", stageId: "m9-3" },
	synopsis: "風の去った朝、店の前がもう掃かれていた。通りには、新しい貼り紙が一枚。",
	lines: [
		{ kind: "narration", bg: "front_autumn", text: "風の去った朝は、嘘のように晴れた。" },
		{ kind: "narration", text: "空の色が、九月のものではなくなっていた。青が高くて、雲が一枚もない。通りには、濡れた葉と土の匂いが低く残っていて、それが台風の翌朝のいちばん確かな印だった。" },
		// 【B-17=A】
		{ kind: "narration", when: { choice: "B-17", is: "A" }, text: "若菜が二階から降りると、店の前の通りが、もう掃かれていた。飛んできた葉と小枝が、店の脇に几帳面な山になっている。レンが竹箒を持って、最後のひと掃きをしていた。" },
		// 【B-17=B】
		{ kind: "narration", when: { choice: "B-17", is: "B" }, text: "若菜がシャッターを上げると、店の前の通りが、もう掃かれていた。自転車を取りに来たらしいレンが、竹箒を持って、最後のひと掃きをしていた。何時に来たのか、聞くのが怖い程度には、通りは綺麗だった。" },
		// 【合流】
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、おはようございます。電気、復旧してますよ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "……早いですね。掃除まで" },
		{ kind: "say", speaker: "ren", emo: 13, text: "目が覚めちゃって。倒れたの、看板だけです。花は、無事" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "看板は、どのあたりに" },
		{ kind: "say", speaker: "ren", emo: 1, text: "そこの側溝んとこまで行ってました。角、ちょっと欠けてます" },
		{ kind: "narration", text: "若菜は看板を起こして、欠けた角を指でなぞった。春に欠けたのと、同じ角だった。同じ角が同じように欠けるのは、置き方に理由があるということだ。次から、向きを変える。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "あと、ケース、五度ちょっとでした。復電が四時二十分。開閉、夜のうちに二回" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "記録していたんですか" },
		{ kind: "say", speaker: "ren", emo: 18, text: "言ったじゃないですか、数えとくって" },
		{ kind: "narration", text: "穂先を寝かせて、押すのではなく引く。手首は動かさず、腰から回す。掃いた葉を、風上に立って一箇所に寄せていく。店の人間の、掃き方だった。" },
		{ kind: "narration", text: "穂先が路面を擦る音が、通りに規則正しく続いた。しゃ、しゃ、と、同じ間隔で。濡れた葉は重くて散らばらない。乾いた小枝だけが、箒の先で跳ねる。レンは、跳ねた小枝を追わずに、次のひと掃きで一緒にさらっていった。追わないほうが、早い。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "大神さん、その掃き方は" },
		{ kind: "narration", text: "若菜がそれを言葉にする前に、通りの先から八重さんの声がした。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃーん。無事かい。——ありゃ、もう掃いてある" },
		{ kind: "say", speaker: "ren", emo: 2, text: "おはようございます! 無事です、二人とも!" },
		{ kind: "narration", text: "二人とも、のところで、八重さんが片眉を上げたのが、朝日の中でよく見えた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "ふうん。二人ともね" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "八重さん" },
		{ kind: "say", speaker: "sub", name: "八重", text: "なんも言ってないよ。うちの雨戸、旬くんが直してってくれてさ。今朝、ちゃんと閉まってた" },
		{ kind: "say", speaker: "sub", name: "八重", text: "町内、被害は米屋の看板と、くろまつの日除けくらいだってさ。あとねえ、若菜ちゃん。あそこ、見た?" },
		{ kind: "narration", text: "八重さんが顎で示した先は、米屋の隣の空き店舗だった。シャッターの脇に、風雨をくぐったばかりの紙が一枚、真新しい養生テープで留めてある。四隅がまだ乾いていない。" },
		{ kind: "narration", text: "近づいて読むと、大きい字でこう書いてあった。「入舟銀座 再開発準備組合(仮称) 説明会のご案内」。日付の欄は空白で、「追ってお知らせします」と小さく添えてある。" },
		{ kind: "say", speaker: "ren", emo: 12, text: "昨日の夜、これ、なかったですよね" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "なかったです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "台風の次の日に貼るんだよ、こういうのは。みんな片付けで忙しいからね" },
		{ kind: "say", speaker: "sub", name: "八重", text: "まあ、仮称だって。仮称のうちは、まだなんも決まってないってことさ" },
		{ kind: "say", speaker: "ren", emo: 5, text: "準備組合って、地権者じゃないと入れないやつですよね" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あんた、そういうの知ってんの" },
		{ kind: "say", speaker: "ren", emo: 15, text: "大学の一般教養で、都市計画のやつ取ってたんで。ちょっとだけです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "花屋のとこの狼は、なんでも知ってるねえ" },
		{ kind: "say", speaker: "ren", emo: 6, text: "花屋のとこの、じゃないです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "はいはい" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "仮称、という三文字が、いちばん本気に見えます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "……若菜ちゃん、たまに常ちゃんみたいなこと言うね" },
		{ kind: "narration", text: "八重さんは、それだけ言って、自分の店の水撒きに戻っていった。レンは貼り紙をもう一度見て、それから花常のほうを振り返った。" },
		{ kind: "say", speaker: "ren", emo: 12, text: "これ、この店にも来るやつですか" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "来るとしても、今日ではないです。今日は、開店の時間です" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……そうですね" },
		{ kind: "narration", text: "通りには、まだ人が出てきていた。米屋の主人が看板を拾いに来て、くろまつの日除けが片側だけ垂れ下がっているのが見えた。玄は脚立にも上がらず、それを下から眺めていた。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "玄さん、あんた背が届くんだから直しなよ" },
		{ kind: "narration", text: "玄は日除けを片手で押し上げて、そのまま留め金をはめた。脚立は出ないまま、話が終わった。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "今の、道具なしで直りました?" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "あの方は、そういう方です" },
		{ kind: "narration", text: "レンが、掃き終わった竹箒を、店の脇の元あった場所に立てかけた。穂先を上にして、壁に軽くもたせる。穂を下にして置くと、湿った穂が曲がって癖がつく。それも、店の人間の置き方だった。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "大神さん。箒、穂を上にしましたね" },
		{ kind: "say", speaker: "ren", emo: 19, text: "あ。なんか、下にすると駄目な気がして" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "駄目です。曲がります" },
		{ kind: "say", speaker: "ren", emo: 15, text: "でしょうね。なんとなくなんですけど" },
		{ kind: "narration", text: "若菜は、それ以上聞かなかった。今日は、開店の時間だった。" },
		{ kind: "narration", text: "商店街の音が、少しずつ普段の高さに戻っていく。シャッターの上がる音が、東から順に聞こえた。" },
		{ kind: "narration", text: "シャッターの前に桶を戻し、水を張って、りんどうを立てた。夜のあいだ寝かせていた花は、一本も折れていなかった。走りの菊が、箱の底に一本だけ残っている。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "大神さん" },
		{ kind: "say", speaker: "ren", emo: 1, text: "はい" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "今月の分です。持って帰ってください" },
		{ kind: "narration", text: "差し出したのは、その一本だった。白い、まだ固い菊。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "菊、いいんですか。仏花じゃないですか、これ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "そう決めているのは、この国の一部の人だけです。ヨーロッパでは普通に部屋に飾ります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃあ、うちの部屋はヨーロッパってことで" },
		{ kind: "say", speaker: "ren", emo: 19, text: "これ、飾ったら、部屋が線香くさくなったりしないですよね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "なりません。匂いは、焚くほうにあります。花のほうにはありません" },
		{ kind: "say", speaker: "ren", emo: 15, text: "よかった。じいちゃんち思い出すの、飯の時だけにしときたいんで" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "いい思い出し方です" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "水は浅めで。切り口は、明日また斜めに切ってください" },
		{ kind: "narration", text: "レンは菊を自転車の前籠に横に寝かせて、ハンドルを押しながら坂のほうへ歩いていった。掃き寄せられた葉の山が、店の脇で、朝日を受けて乾きはじめていた。" },
	],
};

// 解放: 九月の全ステージクリア後
const chomen0930: Vignette = {
	id: "m9-chomen-0930",
	kind: "chomen",
	month: 9,
	title: "九月三十日",
	trigger: { at: "month-close", month: 9 },
	synopsis: "九月の締めの帳面。被害を数え、無事だった花の数を数える。",
	lines: [
		{ kind: "diary", text: "九月三十日。晴れ。" },
		{ kind: "diary", text: "九月は、雨が十一日あった。雨の日の人は、一度も来なかった。灰色の紙は、まだ十七枚のままだった。" },
		{ kind: "diary", text: "台風、一回。負けなかった。これで祖母の帳面と、二季ぶん同じことを書けた。" },
		{ kind: "diary", text: "被害。看板一枚(春に欠けた角と同じ角)。ケースの温度、朝まで持った。最高で五度台。" },
		{ kind: "diary", text: "無事だった花の数を数えた。りんどう七、菊二十四、鶏頭の残り九、店先の鉢が六。折れは一本もなし。寝かせて正解だった。" },
		{ kind: "diary", text: "看板は、来年から向きを変えて置く。同じ角が二度欠けるのは、風のせいではなく置き方のせい。" },
		{ kind: "diary", text: "犬飼さんに南京結びを教わった。結びは、そうやって町を回っているらしい。" },
		{ kind: "diary", text: "犬飼さんは、名前も覚えていない市場の老人から教わったと言っていた。名前が消えても、手が残る。花屋の帳面とは逆の残り方だ。" },
		{ kind: "diary", text: "波板三枚、返しに行く。お礼は花にする。仲卸に花を持って行くのは、少し可笑しいけれど。" },
		{ kind: "diary", text: "停電の夜に、「なくならないでくださいね」と言われた。" },
		{ kind: "diary", text: "努力します、と答えた。帳面には、もう少し正直に書いておく——なくすつもりは、ない。" },
		{ kind: "diary", text: "米屋の隣の空き店舗に、説明会の貼り紙が出た。「再開発準備組合(仮称)」。仮称、という三文字が、いちばん本気に見える。" },
		{ kind: "diary", text: "日付は空欄で、「追ってお知らせします」。追って、というのは、こちらの都合とは関係なく来るという意味だ。" },
		{ kind: "diary", text: "うちは借地ではない。それだけは確かめてある。確かめてあるのに、貼り紙の前で足が止まった。" },
		{ kind: "diary", text: "八重さんは「仮称のうちは何も決まってない」と言った。私はそうは思わない。ただ、今日の分の花は、今日売る。" },
		{ kind: "diary", text: "臨時休業は一日で済んだ。二十二日から通常どおり、と書いたとおりになった。書いておいてよかった。" },
		{ kind: "diary", text: "朝、通りが掃いてあった。竹箒の使い方が、店の人間のそれだった。" },
		{ kind: "diary", text: "どこで覚えたのだろう。聞きそびれた——のではなく、また、聞かなかった。" },
		{ kind: "diary", text: "今月の一輪は、走りの菊。仏花じゃないかと言われたので、ヨーロッパの話をした。" },
		{ kind: "diary", text: "内藤さんの畑のものが、来月から本格的に出る。菊の頁を、そろそろ広く取っておく。" },
		{ kind: "diary", text: "犬飼さんの言葉を、ひとつ書き写しておく。「次はあんたが誰かに教えろ」。" },
		{ kind: "diary", text: "私はまだ、教わる側の数のほうが多い。それでも、今月は少年に花の丈のことをひとつ教えた。畑の人は腰から上に飾る、という、祖母から来た話を。" },
		{ kind: "diary", text: "帳面の頁の上のほうに、名前が増えてきた。数字は、下でいい。" },
	],
};
/** 第九章 長月「野分」。ボス月。ボス「野分」はステージ m9-3。 ⚠️並び順が再生順。 */
export const M09: readonly Vignette[] = [
	chomen0901,
	keirouNoHi,
	akiHigan,
	chomen0919,
	shibaruYoru,
	rousoku,
	takebouki,
	chomen0930,
];
