/**
 * 花常 本文 第十一章 霜月「まだ咲かない」
 * 原稿から転記した実行時シナリオデータ。
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ11-1の前」 → month-open 11
 *   「ステージ11-1クリア後」「ステージ11-2の前」 → stage-clear m11-1
 *   「ステージ11-2クリア後」「ステージ11-3の前」 → stage-clear m11-2
 *   「ステージ11-3クリア後」 → stage-clear m11-3
 *   「十一月の全ステージクリア後・前半」「十一月の全ステージクリア後・後半」 → month-close 11
 */

import type { Vignette } from "./types.js";

// 解放: ステージ11-1の前
const chomen1105: Vignette = {
	id: "m11-chomen-1105",
	kind: "chomen",
	month: 11,
	title: "十一月五日",
	trigger: { at: "month-open", month: 11 },
	synopsis: "十一月初めの帳面。初めて点けたストーブと、市場に出はじめた梅の切枝を書く。",
	lines: [
		{ kind: "diary", text: "十一月五日。晴れ。朝、初めてストーブを点けた。" },
		{ kind: "diary", text: "芯の掃除を忘れていたので、最初のひと息が煤くさかった。店中の水の匂いに、灯油が一本、細く混ざる。慣れれば気にならないと祖母の代からの客に言われた。慣れる前の日が、毎年一日だけあるということらしい。" },
		{ kind: "diary", text: "祖母の帳面の十一月一日の欄に、「ストーブ、芯」とだけ書いてある。一日にやる仕事だったらしい。四日遅れ。" },
		{ kind: "diary", text: "灯油は米屋さんが配達してくれることになった。「先代んときからそうだよ」と言われたので、そうですかと答えた。この町では、私が知らないことを、町のほうが憶えている。憶えていてくれるうちに、こちらも憶えないといけない。" },
		{ kind: "diary", text: "桶の水が朝いちで冷たい。手が赤くなるまで冷たさに気づかない。軍手を一組、作業場に足した。作業用の薄いのと、荷用の厚いの。厚いほうは指先が利かないので、枝物のときだけ。" },
		{ kind: "diary", text: "七五三の予約、四件。千歳飴の袋を提げた家族が、写真館との間を往復する季節。" },
		{ kind: "diary", text: "内訳。持ち込みの櫛に合わせるのが二件、一から作るのが二件。白の小菊を多めに、絞りの椿を少し。当日の飛び込みが必ずあるので、材料は倍で見ておく。" },
		{ kind: "diary", text: "髪飾りは仕入れではなく仕事だ。仕入れは売れ残るが、仕事は売れ残らない。そのかわり、時間が残らない。十一月の午後は、たぶんずっと作業台の前になる。" },
		{ kind: "diary", text: "見切りの籠は、今月から夕方に出すことにした。日が落ちるのが早いので、四時に出しても遅い。" },
		{ kind: "diary", text: "くろまつのマスターに、今月ぶんの花を持っていった。帰りに豆を渡された。何も言われなかった。渡す量が、少しずつ増えている気がする。数えたことはない。" },
		{ kind: "diary", text: "市場に、梅の切枝が出はじめた。年末年始の縁起物の走り。室内に置けば、正月に咲く。" },
		{ kind: "diary", text: "促成の枝を見ると、季節を前借りしているようで、少し落ち着かない。でも仕入れた。根元の詰まった音のを、ひと箱。" },
		{ kind: "diary", text: "——叩いて選べた。二月の私に教えたい。" },
		{ kind: "diary", text: "辰巳さんは、私が叩いているあいだ、何も言わずに隣の台の値をつけていた。何も言われないのが、たぶん、いちばん言われている。" },
		{ kind: "diary", text: "犬飼さんは「枝は重いから台車ごと持ってけ」と言って、そのまま軽トラまで押していった。押しながら、ずっと文句を言っていた。文句の量と、押した距離が、合っていない。" },
		{ kind: "diary", text: "十一月の祖母の欄は、字が細い。数字と、枝の本数と、たまに名前。夏の頁より行数が少ない。" },
		{ kind: "diary", text: "私の欄は、名前のほうが多くなってきた。数えたら、今月はもう七人ぶん書いている。五日で七人。" },
		{ kind: "diary", text: "十一月は静かに堅い月だ、と祖母の集計を見て思う。派手な商戦がないぶん、毎日、同じ量が売れる。母の日のような山がない代わりに、谷もない。" },
		{ kind: "diary", text: "静かに堅い、というのは、たぶん、店にとっていちばんいい形なのだと思う。派手な月のほうが、後になって疲れが出る。" },
		{ kind: "diary", text: "縁台を、今月から夕方に中へ入れることにした。夜露で濡れると、朝いちで拭く手間が増える。祖母は出したままにしていたらしく、天板の右半分だけが白く焼けている。" },
		{ kind: "diary", text: "出したままにしていた理由は、書いていない。書いていないことのほうが、この帳面には多い。" },
		{ kind: "diary", text: "十二月の頁は、まだ開いていない。" },
	],
};

// 解放: ステージ11-1クリア後
const shichigosan: Vignette = {
	id: "m11-shichigosan",
	kind: "scene",
	month: 11,
	title: "七五三",
	trigger: { at: "stage-clear", stageId: "m11-1" },
	synopsis: "七五三の日曜。写真館の順番待ちの家族が、髪飾りや持たせる花を求めて店に寄る。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "日曜の商店街を、着物の子どもが千歳飴を引きずって歩いていく。" },
		{ kind: "narration", text: "袋は霜月堂のもので、五歳の背丈より長い。写真館の前には朝から順番待ちの列ができていて、待ちくたびれた家族が三組、花常の店先の縁台まではみ出していた。若菜は縁台の埃を払って、そのままにしておいた。" },
		{ kind: "narration", text: "作業台には、朝のうちに下ごしらえした小菊が並べてある。花首を短く落として、ワイヤーを一本ずつ通したもの。四十個。この時期だけ、この作業が、店を開ける前の仕事になる。" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "すみません、髪に挿せる小さいの、あります? 写真の予約が三時で——" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "白い小菊で作れます。十五分ください" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "十五分。間に合いますか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "間に合います。櫛は、お持ちですか" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "これなんですけど。母の代のもので、ちょっと大きくて" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "大きいほうが合わせやすいです。花を小さくすればいいので" },
		{ kind: "narration", text: "一月の成人式と、同じ手順だった。ワイヤー、テープ、小さく、軽く。違うのは、仕上がりを受け取る頭の高さだけ。" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "あの、こういうの、造花じゃだめですか。せっかくだから、取っておきたくて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "造花のほうがいい場合もあります。お店で作ってもらえます" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "でも、ここは花屋さんだから" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "うちは、今日しか保ちません。かわりに、今日はいちばんきれいです" },
		{ kind: "say", speaker: "sub", name: "母親の声", text: "……今日だけ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "写真が残ります。花のほうは、今日で終わりでいいと思っています" },
		{ kind: "narration", text: "母親は少し黙って、それから、生花でお願いします、と言った。" },
		{ kind: "narration", text: "十五分は、十三分で済んだ。かがんで挿してやると、子どもは鏡の中の自分を、たっぷり三十秒眺めた。" },
		{ kind: "say", speaker: "sub", name: "女の子の声", text: "おひめさま?" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "おひめさまです。今日は" },
		{ kind: "say", speaker: "sub", name: "女の子の声", text: "きょうは?" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "明日は、ちがうかもしれないので、今日のうちにたくさん見ておいてください" },
		{ kind: "narration", text: "母親が笑って、女の子は鏡をもう三十秒占領した。出ていくとき、女の子は戸口で振り返って、髪に手をやりかけて、母親に手首を掴まれていた。" },
		{ kind: "narration", text: "昼を過ぎて、列がいちど途切れた。次に戸を開けたのは、羽織袴の男の子を連れた家族で、本人は完全に飽きていた。父親の膝の裏を、袴のまま蹴っている。" },
		{ kind: "say", speaker: "sub", name: "父親の声", text: "男の子にも、何か持たせるものってありますか。上の子のときに花を買ったんで、こっちにも何かないと、あとで揉めるんです" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "胸元に、小さいのを一つなら。動いても落ちないように、留めます" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "花いらない" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "むむ" },
		{ kind: "say", speaker: "sub", name: "父親の声", text: "すみません、朝からずっとこれで" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "よくあります" },
		{ kind: "narration", text: "若菜は少し考えて、ケースではなく、奥のバケツのほうへ行った。千両の枝を一本抜いて、指の長さに切る。赤い実が七つ、まとまってついていた。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "では、これは花ではないことにしましょう" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "花じゃない?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "実です。花ではないので、大丈夫です" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "食べれる?" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "食べられません。そこは、我慢してください" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "落とさずに写真館まで持っていけたら、たぶん、かなり強いです" },
		{ kind: "say", speaker: "sub", name: "男の子の声", text: "どのくらい" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "お父さんより強いと思います" },
		{ kind: "narration", text: "男の子は実を握って、父親より先に店を出ていった。父親が慌てて千円札を置いて、追いかけていく。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "二百円です。おつり、写真館まで持っていきます" },
		{ kind: "say", speaker: "sub", name: "父親の声", text: "いいです、いいです。強くなったんで" },
		{ kind: "narration", text: "三時前に、四件目の予約の家族が来た。祖母と孫の二人連れで、母親は仕事だという。" },
		{ kind: "say", speaker: "sub", name: "付添の方の声", text: "うちの嫁がね、写真だけは撮っときなさいって。私が連れてきたんですよ。着付けも私" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "きれいに着せてあります" },
		{ kind: "say", speaker: "sub", name: "付添の方の声", text: "そりゃあ、三人育ててますからね。——花、私の若い頃はねえ、こんな凝ったのは付けなかったのよ。赤い造花をひとつ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今日は、白でお作りしました" },
		{ kind: "say", speaker: "sub", name: "付添の方の声", text: "白。……はいはい、いいわね。白のほうが、着物が立つ" },
		{ kind: "narration", text: "孫のほうは、鏡ではなく、店のケースをずっと見ていた。若菜が視線の先を追うと、いちばん下の段の、りんどうの残りだった。" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "その青が、好きですか" },
		{ kind: "say", speaker: "sub", name: "女の子の声", text: "うん" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、髪には白を、手には青を持ってください。写真は、そのほうが面白いです" },
		{ kind: "say", speaker: "sub", name: "付添の方の声", text: "あらまあ。商売上手" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "一本ぶんです。百五十円で" },
		{ kind: "narration", text: "夕方、片づけをしていると、八重さんが柿を三つ持って寄った。エプロンのポケットに、輪ゴムが束で入っている。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "今日はもう、写真館の行列がうちの店先まで来ちゃってねえ。大根の上に子どもが座るのよ" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "うちは、花が売れました" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃ結構。——常ちゃんもね、この時期は髪飾りばっかり作ってたよ。あの人、大きい花束より、ちまちました仕事のほうが好きだったから" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "祖母のは、見たことがないです" },
		{ kind: "say", speaker: "sub", name: "八重", text: "そりゃあ見られないよ。作ったそばから、みんな頭に載せて帰っちまうんだもの。——それにね、あの人、写真は撮らせない人だったから" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "そうなんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "撮ろうとすると鋏を持って逃げるの。何十年やっても、写真だけは駄目でねえ" },
		{ kind: "narration", text: "八重さんは柿を勘定台に置いて、大根の話に戻りながら帰っていった。若菜は使い残した小菊の花首を短く落として、見切りの籠に並べた。今日のうちに飾る花が、七つ。" },
		{ kind: "narration", text: "戸を閉める前に、もう一度、商店街を見た。千歳飴の袋が、遠くをひとつ、まだ引きずられていた。" },
	],
};

// 解放: ステージ11-2の前
const choudoIi: Vignette = {
	id: "m11-choudo-ii",
	kind: "scene",
	month: 11,
	title: "ちょうどいい",
	trigger: { at: "stage-clear", stageId: "m11-1" },
	synopsis: "ストーブを点けた店で、梅の枝の咲く日の話をする。レンが今月の一輪を選ぶ。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "十一月の店は、朝と夕方で明るさがまるで違う。三時を回ると、ガラス戸から入る光が勘定台の角まで届いて、そこから先には行かない。ストーブの上のやかんが、ときどき小さく鳴った。" },
		{ kind: "narration", text: "土間には、朝に市場から下ろした梅の枝が、箱のまま二つ置いてある。まだ水に立てていない。枝物は、切り口を割ってから深水に立てる。急ぐ仕事ではないので、客の切れ間にやることにしていた。" },
		{ kind: "narration", text: "レンは、いつもの時間に、いつもより赤い耳で入ってきた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "うわ、あったかい。ストーブ出したんですね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今朝から点けています。戸、閉めてください" },
		{ kind: "say", speaker: "ren", emo: 6, text: "閉めます閉めます。——外、坂の上のほうがもう霜っぽくて。自転車のサドルが凍ってました" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "凍ったサドルに座ったんですか" },
		{ kind: "say", speaker: "ren", emo: 6, text: "座りましたね。学習しないんで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "新聞紙を一枚、鞄に入れておいてください。敷けます" },
		{ kind: "say", speaker: "ren", emo: 4, text: "新聞紙。花屋さん、なんでも新聞紙で解決しません?" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "だいたい解決します" },
		{ kind: "narration", text: "レンは鞄を縁台に置いて、手をこすった。その手が、土間の箱でいちど止まる。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "あ、それ、梅ですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "梅です。年末年始の縁起物で、今ごろから出ます" },
		{ kind: "say", speaker: "ren", emo: 19, text: "まだ十一月なのに?" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "暖かい部屋に置くと、ひと月ほどで咲きます。正月に合わせて、この時期に出るんです" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ、外に生えてる梅が咲くのは" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "二月です。あれは、寒さに当たってから咲きます" },
		{ kind: "say", speaker: "ren", emo: 20, text: "順番が逆ですね。切ったほうが先に咲くのか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "切ったほうが、暖かい部屋に入れますから" },
		{ kind: "narration", text: "レンは箱の前にしゃがみ込んだ。枝を一本、持ち上げようとして、やめて、そのまま覗き込む姿勢になった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、蝋梅ってやつとは別ですか。前に商店街の、米屋さんの裏に咲いてたやつ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "別です。蝋梅は名前に梅が入っているだけで、別の木です。咲く時期は近いですけど" },
		{ kind: "say", speaker: "ren", emo: 6, text: "紛らわしいなあ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花の名前は、だいたい紛らわしいです" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それって、いつ咲くか計算できるんですか。温度の積み上げで。何度の日が何日続いたら開く、みたいな" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "むむ" },
		{ kind: "say", speaker: "ren", emo: 2, text: "いや、ありますって、そういうの。積算温度っていうか、閾値があって、越えたら開花フラグが立つ、みたいな。データ取れば絶対モデル作れますって。窓際か部屋の真ん中かで日射も変わるし、夜間の最低気温のほうが効くかもしれないですね。温度計置いて一時間ごとにログ取って、蕾の写真を毎朝同じ角度で撮れば、それ分かってたら、狙った日に咲かせられるってことになるから——" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "大神くん" },
		{ kind: "say", speaker: "ren", emo: 6, text: "はい" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "花は、計算通りには咲きません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "そこをなんとか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "なんとかしません" },
		{ kind: "say", speaker: "ren", emo: 4, text: "即答ですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "即答です。同じ箱から出した枝でも、咲く日は二週間ずれます。同じ日に切って、同じ日に運んで、同じ部屋に置いてもです" },
		{ kind: "say", speaker: "ren", emo: 4, text: "二週間。けっこう、ずれるんですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "ずれます。だから、当てにいくと、外します" },
		{ kind: "narration", text: "若菜は箱から枝を一本抜いて、ケースの脇のバケツに立てた。細い枝で、蕾はまだ、粟粒ほどしかない。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "じゃあ、花屋さんはどうやって間に合わせるんですか。正月のやつ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "間に合わせません。置き場所を変えるだけです。早すぎれば玄関に出して、遅ければストーブの近くに寄せます" },
		{ kind: "say", speaker: "ren", emo: 2, text: "それ、めちゃくちゃ制御ですよ。手動の" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "制御ではありません。世話です" },
		{ kind: "say", speaker: "ren", emo: 20, text: "世話" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "毎朝見て、今日はここ、と決めるだけです。決めた通りにならないので、次の朝また決めます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "それ、フィードバックって言うんですけど" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "言いません" },
		{ kind: "narration", text: "やかんが鳴った。若菜が火を弱めているあいだに、戸が開いて、常連の年配の客が入ってきた。梅の箱を見て、まっすぐそこへ行く。" },
		{ kind: "say", speaker: "sub", name: "客の声", text: "もう出たの。早いねえ" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今朝入りました。三本からお分けします" },
		{ kind: "say", speaker: "sub", name: "客の声", text: "うちは仏間に置くから、寒いんだよ。咲くかね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "寒いなら、蕾の多いのを選んでください。数があれば、いくつかは開きます" },
		{ kind: "say", speaker: "sub", name: "客の声", text: "なるほどね。じゃ、多いのを五本" },
		{ kind: "narration", text: "客が出ていくと、レンはまだ箱の前にいた。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "今の、さっきと逆のこと言ってません? 数で当てにいってるっていうか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "当てにいっていません。諦め方を選んでもらいました" },
		{ kind: "say", speaker: "ren", emo: 20, text: "諦め方" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "全部咲かせるのは無理なので、いくつか咲けばいいことにする。そういう選び方です" },
		{ kind: "narration", text: "レンは、しばらく黙って、それから立ち上がった。いつもの位置に戻る。勘定台の、右の端。" },
		{ kind: "narration", text: "十一月の月に一度は、梅の枝だった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "今月のぶん、あれにします。梅の枝" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "咲いてませんよ。ただの枝です、今は" },
		{ kind: "say", speaker: "ren", emo: 15, text: "みたいですね" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "咲くまで、ひと月かかります。部屋が暖かければ、年明けくらいに" },
		{ kind: "say", speaker: "ren", emo: 18, text: "ちょうどいいです" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "何が、ちょうどいいんですか" },
		{ kind: "say", speaker: "ren", emo: 15, text: "んー……" },
		{ kind: "narration", text: "レンは、枝の先の固い蕾を、指の背でそっと触った。大きな手が、枝には触れないように、蕾のところだけ。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……年明けに咲くのが、ちょうどいいんです" },
		{ kind: "narration", text: "それ以上は言わなかった。若菜は、いちばん蕾の数の多い一本ではなく、いちばん根元の音のいい一本を選んで、新聞紙を斜めに巻いた。枝物は、祖母の鋏で、手元を整えた。いい音がした。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、いい音" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "聞こえるんですか" },
		{ kind: "say", speaker: "ren", emo: 18, text: "狼なんで" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "では、狼さんに宿題です。水は、花より少なめに。深く挿しすぎると、根元が傷みます" },
		{ kind: "say", speaker: "ren", emo: 1, text: "少なめ。了解です" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "瓶は、口の細いものを。倒れます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "口の細いの。麦茶の瓶しかないですね、うち" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "麦茶の瓶なら、水を三分の一まで" },
		{ kind: "say", speaker: "ren", emo: 2, text: "三分の一。覚えました" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "水は、二日に一度替えてください。替えるとき、切り口を一センチ落とすと保ちます" },
		{ kind: "say", speaker: "ren", emo: 19, text: "切っていいんですか。短くなりません?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "短くなります。そのぶん、長く保ちます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "なんか、割に合ってるような、合ってないような" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "合っています。花屋は、だいたいそういう取引をしています" },
		{ kind: "say", speaker: "ren", emo: 6, text: "あと、部屋、暖房あんまり点けないんですけど、大丈夫ですか。電気代がしんどくて" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "点けないと、咲きません" },
		{ kind: "say", speaker: "ren", emo: 16, text: "点けます" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "点けてください" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃ、咲いたら報告しますね。写真撮って" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "毎朝撮るんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "撮りますよ。データなんで" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "むむ" },
		{ kind: "narration", text: "戸口でレンが枝を肩に担ぐと、背丈より頭ひとつぶん長かった。庇の下で一度、枝の先が引っかかって、レンは膝を折ってくぐった。坂を上っていく後ろ姿の、枝の先だけが、しばらく人の頭の上に見えていた。" },
		{ kind: "narration", text: "若菜は帳面を開いて、十一月の欄に書いた。一輪ぶんの記録は、今月は「梅の枝」になった。花の名前を書く欄が、いつのまにか十一行目まで来ていた。" },
		{ kind: "narration", text: "一月の水仙から数えて、十一。あと一行で、この欄は一年ぶんになる。" },
	],
};

// 解放: ステージ11-2クリア後
const sakaNoShitaKara: Vignette = {
	id: "m11-saka-no-shita-kara",
	kind: "scene",
	month: 11,
	title: "坂の下から",
	trigger: { at: "stage-clear", stageId: "m11-2" },
	synopsis: "写真館へ配達に行った帰り、坂の下から、ある窓を見上げる。",
	choices: [
		{
			id: "B-22",
			label: "窓のこと",
			axis: "問い",
			options: [
				{ key: "A", label: "書く", note: "問い+1" },
				{ key: "B", label: "書かない" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "outskirt", text: "配達は、写真館の記念撮影用の花で、二段の飾りだった。日曜に使うぶんを、前の日の夕方に運ぶ。毎年の仕事だと、電話口で言われた。" },
		{ kind: "narration", text: "スタジオは、店の奥の、天井の高い部屋だった。背景の紙が三本、巻いて立てかけてある。床に養生テープの跡が何本も残っていて、そのうちの一本だけが新しかった。天井の照明が四つ、全部違う向きを向いている。" },
		{ kind: "narration", text: "若菜は水を張った器を二つ運び入れ、脚立の下で枝の向きを直した。主人が上から高さを見る。" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "もうちょい右。——そう。去年もそこだった" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "去年の写真、残っていますか" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "あるある。飾りの写真だけ毎年撮ってあるんだ。次の年に同じにするために" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "うちの帳面と、同じ使い方ですね" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "そうかい。——去年はね、暮れに一度、電話したんだよ。花常さんに。誰も出なくてね" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "去年は、閉めていました" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "知ってる。あんときは造花屋から借りたよ。悪くはないんだけどね、写真にするとね、なんか、光り方が違うんだよ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "光り方" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "うまく言えないんだけど。生きてるやつは、影が柔らかいの。だから今年は、開いてるうちに頼もうと思って、早めに電話したの" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "来年も、早めにお願いします" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "そのつもり。——お嬢さん、この飾り、来年もこの形でいい?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "来年は、少し低くしたいです。子どもの背丈に合わせて" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "なるほどね。じゃあ来年はそれで" },
		{ kind: "narration", text: "来年の話が、あっさり決まった。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "明日は、何組ですか" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "十一組。朝の九時から、休みなしだね" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "休みなし" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "この時期だけだよ。あとの十一か月は、証明写真と遺影とお見合いだから" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "静かな商売ですね" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "静かだよ。花屋さんもそうだろ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "うちも、だいたい静かです" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "静かなのがいいんだよ。忙しい年はね、こっちが憶えてらんない。誰を撮ったんだか、あとで分かんなくなる" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "うちは、帳面に書くようにしています" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "そりゃいい。うちは顔で憶えるしかないからね。——先代は、憶えてたよ。花の好みで客を憶えてた。あの人、名前より先に花が出てくるんだ" },
		{ kind: "narration", text: "若菜は器の水の高さを直しながら、その言い方を、いちど頭の中で置き直した。" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "花のほうが、先に" },
		{ kind: "say", speaker: "sub", name: "写真館の主人", text: "そう。『黄色の好きな奥さん』とかね。名前は最後まで出てこないの" },
		{ kind: "narration", text: "主人は笑って、脚立を持って奥へ行った。若菜は水をこぼさないように器の位置を最後に一度だけずらして、それ以上は触らなかった。" },
		{ kind: "narration", text: "外に出ると、写真館の軒下に、明日の順番の紙が貼ってあった。十一組ぶんの名字が、縦に並んでいる。若菜の知っている名字が、三つあった。" },
		{ kind: "narration", text: "軽トラに戻って、エンジンをかける。暖房が効くまでに、坂をひとつ下りきってしまう。荷台が軽くなったぶん、よく跳ねた。空の水桶が、カーブのたびに一度ずつ鳴る。" },
		{ kind: "narration", text: "商店街の入口で、霜月堂の若旦那が暖簾を出しに出てきて、片手を上げた。若菜も上げ返した。店の前の台には、千歳飴の袋がまだ半分残っている。明日で全部出るのだろう。" },
		{ kind: "narration", text: "坂の下の信号で、赤に捕まった。" },
		{ kind: "narration", text: "夕方の五時で、もう薄暗い。左手に川、右手に坂。街灯がひとつずつ、時間をずらして点いていく。坂の上に、すみれ荘の窓が並んで見えた。四月に見たときは、どの窓も同じ形をしていると思った。今も、形は同じだった。" },
		{ kind: "narration", text: "ただ、二階の右から二番目の窓にだけ、色があった。" },
		{ kind: "narration", text: "小さな、白っぽい色。窓枠の内側に、瓶らしい影と、細い枝。この距離では、それが何の花かまでは分からない。分からないが——若菜には、分かった。" },
		{ kind: "narration", text: "信号は、まだ赤だった。" },
		{ kind: "narration", text: "窓の色は、動かない。部屋の奥のほうで、いちど影が横切って、また戻った。" },
		{ kind: "narration", text: "坂の上の窓は、全部で二十四ある。数えたのは、四月に一度きりのはずだった。今日は数えなくても、右から二番目がどれか、目のほうが先に行った。" },
		{ kind: "narration", text: "枝は、窓枠の高さの半分より上に出ていた。瓶は、たぶん背が低い。麦茶の瓶かどうかまでは、分からない。" },
		{ kind: "narration", text: "前の車が動いた。信号が青になっていた。後ろの車が短く鳴らして、若菜は、ゆっくりアクセルを踏んだ。ミラーの中で、色のある窓は、他の窓と同じ大きさに戻っていった。" },
		{ kind: "narration", text: "川沿いの道は、この時間だけ、水の面のほうが空より明るい。" },
		{ kind: "narration", bg: "shop_evening", text: "店に戻って、シャッターを半分だけ下ろした。ストーブがまだ温い。若菜は水桶を作業場に片づけて、手を拭いて、勘定台の丸椅子に座った。" },
		{ kind: "narration", text: "帳面を開いて、今日の欄に書くことを、しばらく考えた。" },
		{ kind: "narration", text: "ペンの尻を、二回、台に当てた。" },
		// ◆選択 B-22「窓のこと」(軸: 問い)
		{ kind: "narration", when: { choice: "B-22", is: "A" }, text: "書くことにした。——坂の上の窓に、色がある。それだけ。誰の窓とも、何の花とも、書かない。書いた分だけ、確かめたい気持ちに形が生まれるのが、自分でも分かった。" },
		{ kind: "narration", when: { choice: "B-22", is: "A" }, text: "一行だけの行が、数字の列の中で、白く空いて見えた。若菜はその下に、配達先と金額を続けて書いた。書いてしまえば、あとは数字に紛れる。" },
		{ kind: "narration", when: { choice: "B-22", is: "A" }, text: "閉じる前に、その一行の上を、指でいちど撫でた。インクはもう乾いていた。" },
		{ kind: "narration", when: { choice: "B-22", is: "B" }, text: "結局、書いたのは仕入れの数字だけだった。" },
		{ kind: "narration", when: { choice: "B-22", is: "B" }, text: "窓のことは、書かない。書いたら、確かめたくなる。確かめたくなったら、たぶん、確かめてしまう。" },
		{ kind: "narration", when: { choice: "B-22", is: "B" }, text: "帳面を閉じてから、若菜はもう一度開いて、今日の欄の余白の広さを見た。数字は五行で終わっていて、その下が、全部空いている。" },
		{ kind: "narration", when: { choice: "B-22", is: "B" }, text: "それから、また閉じた。" },
		// 【合流】
	],
};

// 解放: ステージ11-3の前
const chomen1120: Vignette = {
	id: "m11-chomen-1120",
	kind: "chomen",
	month: 11,
	title: "十一月二十日",
	trigger: { at: "stage-clear", stageId: "m11-2" },
	synopsis: "月半ばの帳面。祖母の古帳面の十一月に、数字と数字のあいだの一行を見つける。",
	lines: [
		{ kind: "diary", text: "十一月二十日。曇り。寒い。" },
		{ kind: "diary", text: "朝からストーブを強くしている。灯油が一缶、五日で空になった。祖母の帳面には「灯油、月三缶」とある。だいたい合っている。合っていることが、少し可笑しい。" },
		{ kind: "diary", text: "梅の枝、二十本ほど残り。売れ方が読めないので、半分は表に、半分は奥に置いた。表のぶんは冷えるので、開くのが遅くなる。遅いほうがいい家と、早いほうがいい家がある。" },
		{ kind: "diary", text: "注文票を見返して気づいた。仏間に置く家は、蕾の多いのを選ぶ。玄関に置く家は、形のいいのを選ぶ。同じ枝の、違う見方。" },
		{ kind: "diary", text: "どこに置くかを聞いてから出すようにしたら、返品が減った。今年から始めたことだが、祖母の帳面には「置き場所」と書いた列が最初からある。始めたのではなく、追いついただけらしい。" },
		{ kind: "diary", text: "祖母の帳面の十一月を読んでいて、手が止まった。" },
		{ kind: "diary", text: "頁の下のほう、数字の列の外側。余白に、細い字で、日付なしの一行。" },
		{ kind: "diary", text: "「狼の子に梅を持たせた。咲く頃にまた来る、と約束した」" },
		{ kind: "diary", text: "——狼の子。" },
		{ kind: "diary", text: "二月に見つけた書き込みと、同じ呼び方。水切りを教わった、筋のいい、狼の子。" },
		{ kind: "diary", text: "梅を持たせた。咲く頃にまた来ると、約束した。" },
		{ kind: "diary", text: "前後の頁を三回読んだ。他には何も書いていない。名前も、歳も、いつのことかも。" },
		{ kind: "diary", text: "その一行の上下は、ただの仕入れの数字だ。梅、二十本。松、下見。数字と数字のあいだに、この一行だけが挟まっている。" },
		{ kind: "diary", text: "挟まっているというより、書く場所がそこしかなかったように見える。" },
		{ kind: "diary", text: "頁の紙の焼け方は、他の頁と変わらない。この帳面は途中から日付が飛ぶので、年の見当がつかない。" },
		{ kind: "diary", text: "祖母は、大事なことほど短く書く人だった。数字のほうが長い。売上の桁は丁寧に揃えるのに、人のことは一行で済ませる。" },
		{ kind: "diary", text: "写真館のご主人が、祖母は花の好みで客を憶えていた、と言っていた。それなら、この一行の「狼の子」も、名前を憶えていなかったのではなく、名前で憶える必要がなかっただけかもしれない。" },
		{ kind: "diary", text: "梅を持たせた人。それで祖母の中では足りていた。" },
		{ kind: "diary", text: "今月、うちの店で、梅の枝を買っていった人がいる。「年明けに咲くのが、ちょうどいい」と言った人が。" },
		{ kind: "diary", text: "まさか、ね。" },
		{ kind: "diary", text: "何年前の書き込みかも分からない。祖母は五十年この店をやっていた。狼の獣人は、町に何人もいる。犬飼さんの言い方を借りれば、犬だか狼だか、その程度の話だ。" },
		{ kind: "diary", text: "大学が坂の上にあるのだから、学生が店に出入りするのは当たり前でもある。五十年ぶんの学生。" },
		{ kind: "diary", text: "……まさか、で済ませるには、揃いすぎている。でも、確かめるのが、少し怖い。" },
		{ kind: "diary", text: "確かめたら、あの人の一輪の意味が、全部変わってしまう気がする。" },
		{ kind: "diary", text: "今のところ、あの人は、月に一度うちで花を買う人だ。それでちゃんと成り立っている。" },
		{ kind: "diary", text: "成り立っているものを、こちらから崩す理由が、私にあるだろうか。" },
		{ kind: "diary", text: "理由はない。理由はないのに、帳面の同じ行を、今日はもう四回読んでいる。" },
		{ kind: "diary", text: "一度、頁に付箋を貼って、剥がした。貼ったままにすると、毎日そこを開いてしまう。" },
		{ kind: "diary", text: "明日は市場。犬飼さんに会う。会っても、余計なことは聞かない。" },
		{ kind: "diary", text: "と、ここに書いておけば、明日の私が読む。読んだところで、聞くかもしれない。" },
		{ kind: "diary", text: "帳面は、決めたことを守らせる道具ではないらしい。決めたことを、あとから数えるための道具だ。" },
	],
};

// 解放: ステージ11-3クリア後
const saguri: Vignette = {
	id: "m11-saguri",
	kind: "scene",
	month: 11,
	title: "探り",
	trigger: { at: "stage-clear", stageId: "m11-3" },
	synopsis: "市場で犬飼に、少しだけ探りを入れてみる。話は思ったところへは行かない。",
	choices: [
		{
			id: "B-21",
			label: "確かめるか",
			axis: "問い",
			options: [
				{ key: "A", label: "犬飼に探りを入れる", note: "問い+1" },
				{ key: "B", label: "聞かない" },
			],
		},
	],
	lines: [
		{ kind: "narration", bg: "market", text: "十一月の浜市場は、床が濡れていると滑る。長靴の底の減り方が、この時期だけ早い。五時半のセリの前に、辰巳の声が場内を一往復した。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "花常のとこの! 梅、もう入れたか。今年は堅いぞ、堅いのがいい年だ!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "ひと箱、入れました" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "叩いたか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "叩きました" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "ん" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "それだけですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "それだけだ。次から自分で分かるんだからよ、俺が言うことねえだろ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "二月は、ずいぶん言われました" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "二月のあんたは、枝を目で選んでたからな。目で選ぶやつぁ、花屋になれても枝屋になれねえんだ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "枝屋という商売があるんですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "ねえよ。——おい、そこの箱、退かせ! 通るぞ!" },
		{ kind: "narration", text: "辰巳は次の台のほうへ行ってしまった。掛け声が場内の反対側から戻ってくる頃には、もう別の値をつけていた。" },
		{ kind: "narration", text: "若菜は木札を出して、自分のぶんの荷を確かめた。梅がひと箱、菊が二箱。番号を照らし合わせているあいだ、指の先が、箱の縁で冷えていった。" },
		// ◆選択 B-21「確かめるか」(軸: 問い)
		{ kind: "narration", when: { choice: "B-21", is: "A" }, text: "セリが終わって、荷が動きはじめた頃、若菜は犬飼の台車を呼び止めた。呼び止めてから、何をどう聞くのかを、まだ決めていないことに気づいた。" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 10, text: "犬飼さん。変なことを聞きますが" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "変なこと以外で呼び止められたことがねえよ、あんたに" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 13, text: "大神くんて、昔から、うちの店に来てました? 私が継ぐ前から" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "あー? 知らねえよ、あいつと会ったの七月だぞ、俺" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 5, text: "ですよね" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "本人に聞けよ。電話一本で済むだろ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 10, text: "済みません" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "済むだろ。番号知らねえのか" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 17, text: "知っています" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "じゃあなんで聞かねえんだよ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 10, text: "……荷物、通してください" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "はいはい。——なんだよ、喧嘩でもしたか" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 1, text: "してません。ありがとうございました" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "ならいいけどよ。あいつ、あれで面倒くさいとこあるからな。台風ん時も、荷ぜんぶ自分で持とうとしやがって。ああいうのは、こっちが半分持たねえと、いつまでも持ってんだよ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 13, text: "半分" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "そう。半分。俺はそうしてる。——あ、待て。そういや親父が言ってたな。花常の先代んとこに、でかい学生が出入りしてたって。犬だか狼だか" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 8, text: "いつ頃の話ですか" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "知らね。親父に聞け。うちの親父、二十年こっち市場出てねえけど、昔の話だけは無限に出てくるからな" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 10, text: "聞けますか" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "聞けるけど、正月まで待て。年末はうちも死ぬから。——おい、顔。どうした" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 17, text: "なんでもないです。荷物、通してください" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "二回言うなよ、それ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 3, text: "二回言いました" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "言ったな。——あんたさ、聞きたいこと、まだ一個も聞いてねえだろ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 19, text: "聞きました" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "聞いてねえよ。俺に聞いたって、俺は七月からの話しか持ってねえの。持ってねえ人間に聞いてるうちは、聞いてねえのと同じだ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 17, text: "……そうかもしれません" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "sub", name: "犬飼", text: "そうなんだよ。荷はな、持ってるとこから取るんだよ。市場と同じだ" },
		{ kind: "narration", when: { choice: "B-21", is: "A" }, text: "犬飼は台車を押して、人混みのほうへ行った。三歩で、もう別の店に怒鳴っていた。" },
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "聞かない、と決めた。" },
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "決めて、台車の脇をすり抜けて、木札を出して、荷を積んで、それで終わるはずだった。" },
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "決めたのに、犬飼のほうから台車を停めた。" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "おい、花常の。ちょっといいか" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 1, text: "なんでしょう" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "梅、そっちいくつ取った。うち、あと三箱余ってんだよ。堅いのばっかりで、みんな怖がって買わねえ" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 4, text: "堅いほうが保ちます" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "だろ? そう言ってんだけどよ、正月に咲かなかったら文句言われるのはこっちだからな。——そういや、親父が変なこと言ってたぞ。先代の頃、店にでかい学生が出入りしてたって。犬だか狼だか、って" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 8, text: "……" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "狼っていやあ、あいつしかいねえだろって、親父と話してたんだが。何年前の話か聞いたら、憶えてねえってよ。使えねえ親父だ" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 17, text: "……そうですか" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "おい、顔。どうした" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 10, text: "なんでもないです。荷物、どうぞ" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "変な奴だな、あんたも。——梅、三箱、置いてくぞ。堅いの、あんたなら売れるだろ" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 4, text: "売ります。値段は" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "余りもんだ。二箱ぶんでいい" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 16, text: "三箱ぶん払います" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "なんでだよ" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 16, text: "余りものにしたくないので" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "sub", name: "犬飼", text: "……あんた、そういうとこな" },
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "犬飼は舌打ちのような音を出して、台車を押していった。押しながら、三箱ぶんの伝票を書いて、振り返らずに片手で渡してきた。" },
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "聞かないと決めても、町のほうが教えに来る。この町は、そういう町だった。" },
		// 【合流】
		{ kind: "narration", text: "台車が通り過ぎて、市場の喧騒が戻ってきた。若菜はしばらく、その場に立っていた。荷を積んだ台車が二台、三台と、若菜の脇をよけて通っていく。誰も、立っている理由を聞かなかった。市場では、立ち止まっている人間のほうが、よけられる側になる。" },
		{ kind: "narration", text: "犬だか、狼だか。" },
		{ kind: "narration", text: "軽トラの荷台に枝の箱を載せて、若菜は、来た道を戻った。荷台のロープを結ぶとき、指がうまく動かなくて、二回結び直した。" },
		{ kind: "narration", text: "川沿いに出るまでの三つの信号は、全部青だった。青のときほど、考える時間が長い。" },
		{ kind: "narration", text: "店に着く頃には、空がすっかり明るくなっていた。シャッターを上げて、ストーブに火を入れて、水を張って、箱を開けた。" },
		{ kind: "narration", text: "枝は、昨日と同じ顔をしていた。切り口を割って、深水に立てる。二十本を立て終わるまでに、店はじゅうぶん暖かくなった。" },
		{ kind: "narration", text: "八時に、まるはちの前で八重さんが箒を使う音がしはじめた。九時に、最初の客が来て、菊を三本買っていった。十一月は、そういう順番で始まる日が続く。" },
		{ kind: "narration", text: "若菜は勘定台の上に、市場の伝票を広げた。三箱ぶんの数字が、犬飼の字で書いてある。数字の下に、読めない走り書きが一行あった。何度見ても読めなかったので、そのまま挟んでおいた。" },
	],
};

// 解放: 十一月の全ステージクリア後・前半
const hatsushimo: Vignette = {
	id: "m11-hatsushimo",
	kind: "scene",
	month: 11,
	title: "初霜",
	trigger: { at: "month-close", month: 11 },
	synopsis: "初霜の朝、桶の水に薄い氷が張る。冬の囲いの相談をする。",
	lines: [
		{ kind: "narration", bg: "front_autumn", text: "十一月の末の朝、店先の桶の水に、薄い氷が張った。" },
		{ kind: "narration", text: "厚さは紙一枚ぶんで、竹箒の先で触れると、音もなく割れた。商店街の敷石が白い。米屋の軽トラが灯油を下ろしていく音が、二軒先から聞こえる。まるはちの店先では、八重さんが大根を新聞紙でくるんでいた。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "うわ、氷! もうそんな時期ですか" },
		{ kind: "narration", text: "朝いちで寄ったレンが、桶を覗き込んで、白い息を吐いた。" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "今夜から、囲いをします。水道も、タオルを巻かないと" },
		{ kind: "say", speaker: "ren", emo: 1, text: "囲いって、どういうやつですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "店先の鉢に、ビニールを掛けます。夜だけ。朝には外します" },
		{ kind: "say", speaker: "ren", emo: 4, text: "毎日?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "毎日です。凍らせたら、それで終わりなので" },
		{ kind: "say", speaker: "ren", emo: 19, text: "一晩で駄目になるんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "なります。葉が水っぽくなって、次の日に黒くなります。戻りません" },
		{ kind: "say", speaker: "ren", emo: 14, text: "戻らないのは、けっこう厳しいですね" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "厳しいです。だから、掛けます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、水道のとこ、去年の発泡スチロールが物置に入ってるはずだよ。常ちゃんが毎年しまってたやつ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "探してみます。ありがとうございます" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あるある。あの人、そういうのは捨てないんだから。ビニールもね、破れたとこにガムテープ貼って、何年も使ってた" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "新しいのを買おうと思っていました" },
		{ kind: "say", speaker: "sub", name: "八重", text: "買いなさい買いなさい。あれは倹約じゃなくて、ただの意地だから" },
		{ kind: "say", speaker: "ren", emo: 19, text: "意地なんですか" },
		{ kind: "say", speaker: "sub", name: "八重", text: "意地だよ。あんた、大神くんだっけ。あんたも気をつけな、この店にいると意地が移るから" },
		{ kind: "say", speaker: "ren", emo: 18, text: "もう移ってる気がします" },
		{ kind: "say", speaker: "sub", name: "八重", text: "あらまあ。手遅れだ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "八重さん" },
		{ kind: "say", speaker: "sub", name: "八重", text: "はいはい、大根の続きがあるから" },
		{ kind: "narration", text: "八重さんは大根を抱えて店に引っ込んだ。引っ込みぎわに、もう一度こちらを見て、何か言いかけて、やめた。レンは軍手も嵌めずに、桶のふちの氷の粒を指で拾っていた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "これ、朝の何度で張るんですかね。氷点下いってなくても、放射冷却で表面だけ下がることあるじゃないですか。晴れた日の朝のほうが危ないってことですよね。風がないと余計に——雲があると逆に張らないはずで、だから天気予報の最低気温だけ見てちゃ駄目で" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "大神くん" },
		{ kind: "say", speaker: "ren", emo: 6, text: "はい。手、動かします" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "手は動かさなくていいです。手袋をしてください" },
		{ kind: "say", speaker: "ren", emo: 3, text: "あ。はい" },
		{ kind: "say", speaker: "ren", emo: 16, text: "手伝います。夜、講義ないんで" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "……助かります。大神くん、いつも" },
		{ kind: "say", speaker: "ren", emo: 19, text: "いつも?" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "……いえ。夜に、お願いします" },
		{ kind: "narration", text: "言いかけた言葉を、若菜は飲み込んだ。いつも、どうして、ここまでしてくれるんですか——と聞くのは、簡単だった。簡単で、たぶん、全部を動かしてしまう。" },
		{ kind: "narration", text: "梅はまだ、咲かない。咲くまでは、枝のままにしておく。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "あ、そうだ。梅、玄関に置いてたんですけど、部屋の中に入れました" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "そのほうがいいです。玄関は冷えます" },
		{ kind: "say", speaker: "ren", emo: 19, text: "まだ全然、蕾のままですね。毎朝見てるんですけど、昨日と違うところが分かんなくて" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "一週間、見ないでください。そのほうが分かります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "見ないほうが分かるんですか" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "毎日見ると、変わっていないように見えます。そういうものです" },
		{ kind: "say", speaker: "ren", emo: 20, text: "そういうもんですか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "急かすと、いいことがありません。枝も、人も" },
		{ kind: "say", speaker: "ren", emo: 18, text: "……はい" },
		{ kind: "say", speaker: "ren", emo: 6, text: "じゃ、一週間見ないでおきます。無理っぽいけど" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "無理でしたら、写真だけ撮って、見ないでください" },
		{ kind: "say", speaker: "ren", emo: 6, text: "それ、いちばん難しいやつですよ" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "難しいですけど、そのほうが、咲いた日が分かります" },
		{ kind: "say", speaker: "ren", emo: 4, text: "分かるんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "分かります。一週間ぶりに見ると、はっきり変わっています" },
		{ kind: "say", speaker: "ren", emo: 16, text: "じゃあ、次の日曜まで見ないでおきます" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "日曜に、教えてください" },
		{ kind: "say", speaker: "ren", emo: 2, text: "教えます" },
		{ kind: "narration", text: "レンは鞄を担ぎ直して、坂のほうへ数歩行って、振り返った。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "夜! 軍手、二組いりますよね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "二組、あります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "じゃ、六時に" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "六時に" },
		{ kind: "narration", text: "角を、レンは左に曲がりかけて、右に直した。" },
		{ kind: "narration", text: "レンは駆けていって、角でもう一度、腕を大きく振った。若菜は箒を持ったまま、それを見送った。" },
		{ kind: "narration", text: "それから、物置に入って、発泡スチロールを探した。奥の棚の、米袋の裏にあった。祖母の字で「水道」と書いた紙が、貼ったまま残っている。剥がそうとして、指を止めて、そのまま持ち出した。" },
		{ kind: "narration", text: "ビニールは、破れたところにガムテープが四か所貼ってある。八重さんの言った通りだった。広げてみると、破れは全部、同じ端に寄っている。掛けるときにいつも同じところを引っ張っていたからだ、と、広げてから分かった。" },
		{ kind: "narration", text: "新しいのを買いに行く前に、若菜はもう一度、それを畳んだ。" },
		{ kind: "narration", text: "割れた氷を桶の水に沈める。氷は水の中で、しばらく白いままだった。" },
		{ kind: "narration", text: "商店街の敷石の白さは、日が高くなる前に消えた。" },
	],
};

// 解放: 十一月の全ステージクリア後・後半
const chomen1130: Vignette = {
	id: "m11-chomen-1130",
	kind: "chomen",
	month: 11,
	title: "十一月三十日",
	trigger: { at: "month-close", month: 11 },
	synopsis: "十一月の締めの帳面。七五三と枝物の数字を並べ、梅がまだ咲かないことを書く。",
	lines: [
		{ kind: "diary", text: "十一月三十日。晴れ。初氷。" },
		{ kind: "diary", text: "時雨。傘立ては、空だった。" },
		{ kind: "diary", text: "十一月の集計。七五三と枝物で、静かに堅い月だった。売上は先月をわずかに下回り、仕入れは減った。差し引きで、少し残った。" },
		{ kind: "diary", text: "髪飾り、六件。うち二件は当日の飛び込み。来年は材料を先に組んでおくこと。四十個では足りない。六十個。" },
		{ kind: "diary", text: "梅の枝、残り四本。表に出したぶんから先に売れた。人は、寒いほうの窓際に置いてある枝を選ぶらしい。理由は聞いていない。" },
		{ kind: "diary", text: "犬飼さんから引き取った堅い三箱も、月末までにほぼ出た。堅いのが売れないというのは、たぶん、売り方の問題だった。" },
		{ kind: "diary", text: "霜囲い、完了。手伝い一名。軍手、二組。" },
		{ kind: "diary", text: "発泡スチロールは物置の奥。紙は剥がさずに使った。" },
		{ kind: "diary", text: "ビニールは新しいのを買った。古いほうは、畳んで棚に戻した。捨てるかどうかは、まだ決めていない。決めなくても、来年まで場所は空いている。" },
		{ kind: "diary", text: "夜の作業は一時間半で終わった。二人だと、鉢を持つ人と掛ける人に分かれるので、片手で全部やらなくていい。去年まで祖母は、これを一人でやっていたことになる。" },
		{ kind: "diary", text: "手伝いを頼むという発想が、私にはまだない。頼まなくても来る人がいるので、なおさら身につかない。" },
		{ kind: "diary", text: "写真館の飾り、来年は低くする。この帳面に書いておかないと、来年の私が同じ高さで作る。" },
		{ kind: "diary", text: "犬飼さんのお父さんが、昔、先代の店に出入りする「でかい学生」を見ている。犬だか狼だか、とのこと。年は憶えていないらしい。" },
		{ kind: "diary", text: "すみれ荘の、二階の右から二番目の窓に、色がある。" },
		// 【B-22=A】
		{ kind: "diary", when: { choice: "B-22", is: "A" }, text: "月の半ばに書いた通りだ。書いた分だけ、確かめたい気持ちは形になった。形になったものは、もう消えない。" },
		// 【B-22=B】
		{ kind: "diary", when: { choice: "B-22", is: "B" }, text: "書かない、と決めたのに、月末の今、結局書いている。決めごとより、帳面のほうが強いらしい。この帳面は、数字だけのはずだったのに、もうとっくに、そういう帳面ではない。" },
		{ kind: "diary", text: "今月、名前を書いた回数を数えた。三十一。先月より多い。" },
		{ kind: "diary", text: "祖母の十一月の頁と並べてみると、数字の並び方はよく似ていて、余白の使い方だけが違う。祖母は余白に短く書く。私は余白に長く書く。" },
		{ kind: "diary", text: "短く書ける人になるには、あと何年か要るのだと思う。" },
		{ kind: "diary", text: "一輪の記録、十一行目。今月は梅の枝。あと一行で、一年ぶんになる。" },
		{ kind: "diary", text: "市場で辰巳さんに、二月は目で枝を選んでいたと言われた。自分では気づいていなかった。十か月かけて、耳で選ぶようになったらしい。" },
		{ kind: "diary", text: "犬飼さんに、荷は持っているところから取れ、と言われた。花の話ではなかったと思う。" },
		{ kind: "diary", text: "十二月が来る。松市の日取りを確認すること。注連飾りの数、去年の祖母の欄を写しておくこと。葉牡丹の注文、今週中。" },
		{ kind: "diary", text: "松は市が立つ日に行かないと、いいのが残らない。祖母の欄には日付だけあって、何時に出たかが書いていない。早いに越したことはないので、四時に出る。" },
		{ kind: "diary", text: "縁台の天板を拭いた。白く焼けている側は、拭いても色が戻らない。戻らないものを拭くのは、掃除ではなく癖だと思う。" },
		{ kind: "diary", text: "来月の予定を書き出したら、十四行になった。今年のどの月より多い。" },
		{ kind: "diary", text: "十二月の頁を開いた。祖母の欄は、途中まである。" },
		{ kind: "diary", text: "一年前の十二月のことを、書ける気が、まだしない。でも十二月は来る。" },
		{ kind: "diary", text: "梅は、まだ咲かない。" },
	],
};
/** 第十一章 霜月「まだ咲かない」。 ⚠️並び順が再生順。 */
export const M11: readonly Vignette[] = [
	chomen1105,
	shichigosan,
	choudoIi,
	sakaNoShitaKara,
	chomen1120,
	saguri,
	hatsushimo,
	chomen1130,
];
