/**
 * 花常 本文 第十二章 師走「大霜」
 * 正本: packages/frontend/hanaawase/HANATSUNE-STORY-12.md
 *
 * ⚠️本文はそのまま移してある。要約・書き換え・表情タグの付け替えを禁止する（SPEC §9.7.15）。
 * ⚠️表情【①〜⑥】は本文に人間が割り当て済み。推測で足さない。
 * ⚠️解放スロットの対応:
 *   「ステージ12-1の前」 → month-open 12
 *   「ステージ12-1クリア後」 → stage-clear m12-1
 *   「ステージ12-2クリア後」 → stage-clear m12-2
 *   「ボス「大霜」戦の前」 → boss-before m12-3
 *   「ボス「大霜」撃破後」 → boss-after m12-3
 *   「ステージ12-3クリア後・前半」「ステージ12-3クリア後・後半」 → stage-clear m12-3
 *   「十二月の全ステージクリア後」 → month-close 12
 *
 * ⚠️十二月に ◆選択 はない（原稿の指定どおり。全ルートがここへ合流する）。
 * ⚠️「年の瀬の夜」の開幕だけ、原稿が【問い高】/【問い低】で二通りに書かれている。
 *   これは「問い」軸（B-14 / B-22 / B-21）の積み上げを指す指定だが、軸の値は保存しない決まりなので
 *   （types.ts の ChoiceOption.note 参照）、直前の問い軸の選択 B-21「確かめるか」で代表させている。
 *   B-21 は十一月の m11-3 クリアで必ず答が出ており、十二月に入る条件そのものなので、未回答にはならない。
 */

import type { Vignette } from "./types.js";

// 解放: ステージ12-1の前
const chomen1201: Vignette = {
	id: "m12-chomen-1201",
	kind: "chomen",
	month: 12,
	title: "十二月一日",
	trigger: { at: "month-open", month: 12 },
	synopsis: "十二月初めの帳面。松市としめ飾りの段取りを書き出す。祖母の帳面の終わりの頁にも、少しだけ触れる。",
	lines: [
		{ kind: "diary", text: "十二月一日。晴れ。風が変わった。" },
		{ kind: "diary", text: "朝、戸を開けたら、通りの空気が乾いて硬くなっていた。息が白い。トタン庇の内側に、細かい霜。ストーブの灯油を一缶、追加で頼む。" },
		{ kind: "diary", text: "松市の段取り。市場は十四日と二十日、二回立つ。根引き松、若松、若松の小、それぞれ何束。注文控えの写しを勘定台に貼る。" },
		{ kind: "diary", text: "しめ飾りの仕入れ、葉牡丹、千両、椿、南天。松以外を数えるほうが手間だと、去年の帳面を見て分かった。" },
		{ kind: "diary", text: "しめ縄は二十日の市で仕入れる。神棚の小さいのから玄関の大きいのまで、六種。去年の控えには、種類ごとに印がついていた。◯と×。×が売れ残りの印だと気づくのに、しばらくかかった。×の大きいしめ縄を、今年は二つ減らす。" },
		{ kind: "diary", text: "椿は、寒が来るほど色が濃くなる。市場のは形が揃い、坂の下の農家のは色が濃い。どちらも仕入れる。形の日と、色の日と、客によって出すものを変える。" },
		{ kind: "diary", text: "ストーブの芯を、今朝、切り詰めた。灯油の減りが去年より速い気がして、去年の帳面を見たら、同じ日に「芯を切る」と書いてあった。偶然ではなく、たぶん、寒さの来る日付が、毎年、同じなのだ。" },
		{ kind: "diary", text: "注文控えの写しに、もう十七件、名前がついた。まるはちの八重さんは根引きの大を一対。すみれ荘の大家さんは若松の小、二階の窓辺に置くぶんだと言う。霜月堂は、店に飾る松と、正月の詰め合わせに使う千両を一箱。去年の控えを見ると、同じ客が、同じものを頼んでいる。名前の横に去年の数を書き添えるだけで、今年の数が、ひとりでに決まっていく。" },
		{ kind: "diary", text: "配達は十四日と二十日の午後にまとめる。坂の上と川向こうを分けて、坂の上を先に回る。寒い日は、遠いところから先に凍るからだ。去年の帳面の隅に、祖母の字で「坂上先」とだけ書いてあった。意味が分かるまで、まる一年かかった。" },
		{ kind: "diary", text: "犬飼生花の台車は、二十日だけ借りる約束をした。軽トラに積みきれない松を、店まで運んでもらう。電話で頼んだら、向こうは用件より先に「狼はどうしてる」と聞いてきた。用件は、そのあとだった。" },
		{ kind: "diary", text: "しめ飾りの下げ札を、六種ぶん、夜のうちに書いた。神棚用、玄関用、車用、勝手口用。字の大きさを、種類で変える。大きいものほど、札は小さくていい。値段を大きく書くと、かえって安く見えると、これも祖母の帳面にあった。" },
		{ kind: "diary", text: "松脂で手が汚れる季節でもある。一度つくと、石鹸では落ちない。湯を沸かして、指の腹をこする。この黒い汚れは、去年の私の手には、まだなかった。" },
		{ kind: "diary", text: "祖母の字は、真似しないと決めた。真似ると、祖母の帳面の続きになってしまう。私の帳面は、私の字で埋める。下手でも、私の字で。ただ、数字の書き方だけは、いつのまにか似てきた。似せたのではない。毎日書いていると、似てくるものらしい。" },
		{ kind: "diary", text: "年末は花屋の戦だと、今年は身体で知っている。三月の嵐も、九月の野分も、あれは天気が敵だった。十二月の敵は、注文の数と、自分の手の速さだ。" },
		{ kind: "diary", text: "段取りを書き出して、あと、書くことがなくなった。" },
		{ kind: "diary", text: "一年前の今月、祖母は倒れた。" },
		{ kind: "diary", text: "祖母の帳面は、十二月八日で終わっている。八日の欄は、途中で切れている。松の束数の「三」まで書いて、その先がない。" },
		{ kind: "diary", text: "九日からの頁は、白い。三十一日まで、罫線だけがまっすぐ引いてある。" },
		{ kind: "diary", text: "白い頁を、私はまだ、まっすぐ見られない。見られないまま、自分の帳面のほうに、こうして書いている。" },
		{ kind: "diary", text: "埋めようと思ったことは、一度だけある。四月の、桜の売れ残りを始末した夜だ。鉛筆を持って、開いて、閉じた。" },
		{ kind: "diary", text: "それでいい、ということにする。十二月は、忙しい。忙しいのは、今月は、ありがたい。" },
		{ kind: "diary", text: "明日から、店の前を掃く時間を三十分早める。霜が降りると、竹箒の当たりが変わるらしい。らしい、と書いたのは、まだ自分で確かめていないからだ。" },
	],
};

// 解放: ステージ12-1クリア後
const matsuichi: Vignette = {
	id: "m12-matsuichi",
	kind: "scene",
	month: 12,
	title: "松市",
	trigger: { at: "stage-clear", stageId: "m12-1" },
	synopsis: "一年でいちばん人の多い松市。松の山のあいだで木札を握り、犬飼の手を借りて一日を回す。",
	lines: [
		{ kind: "narration", bg: "market", text: "松市の朝の市場は、一年でいちばん人が多い。" },
		{ kind: "narration", text: "四時半に軽トラを出した。町はまだ暗くて、川沿いの道の欄干が白く光っていた。浜市場の駐車場は、着いた時点でもう半分埋まっていた。荷台に空の番重を積んだ軽トラが、二台に一台。" },
		{ kind: "narration", text: "場内に入ると、床が見えなかった。松である。根引き松の束が壁のように積まれ、その谷間を人が歩く。天井の蛍光灯まで届きそうな山が、通路の両側に、奥まで続いていた。競り場に松の香が満ちて、若菜は木札を握り直した。" },
		{ kind: "narration", text: "どの顔も知らない顔で、どの顔も急いでいた。買参人の木札が、頭の上でいくつも揺れている。番号だけ書かれた札を、みな胸の前ではなく、耳の高さで持っていた。そのほうが競り人から見えるのだと、一月に辰巳から教わった。若菜も、いつのまにか同じ高さで持つようになっていた。床には松の葉が散って、歩くたびに、折れた葉から青さが立った。長靴の底が、その葉を踏んで、しめった音を返す。競り場の隅で、湯気の立つ紙コップを片手にした男が、もう片方の手だけで三山を落としていった。慣れとは、ああいう手のことを言うのだと思った。" },
		{ kind: "narration", text: "辰巳の声は、いつもより二割高かった。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "はい次っ、根引き二十、飛騨の! 目ぇ肥やしてけっ、今日は肥やす日じゃねえ、買う日だ!" },
		{ kind: "narration", text: "隣の買参人が笑った。若菜も手を挙げた。" },
		{ kind: "narration", text: "札が、あちこちで上がった。若菜の斜め前で、犬飼生花の法被が手を挙げた。飛騨の根引きの、いちばんいい一山だった。若菜も上げた。犬飼が上げ返した。二人のあいだで、値が三度、跳ねた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "犬飼と常サンとこで競っとる! 朝から熱いねえ! はい、どっちだ、どっちだ!" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "……引くよ。うちは業務用、そっちは店売り。用途が違う" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "引きやがった! 潔いねえ、柴犬は!" },
		{ kind: "narration", text: "若菜の手に、一山が落ちた。犬飼が振り向いて、声には出さず、口の形だけで「高く売れよ」と言った。" },
		{ kind: "narration", text: "若菜は根引き松と若松をひと山、椿を二箱、千両を——気づけば、去年の祖母と同じ数だけ競り落としていた。控えに書き付けた数字を、二度、見直した。" },
		{ kind: "narration", text: "競りが終わって、床の松屑を踏んで歩いていると、辰巳が台の上から声を投げてきた。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "常サンとこの! 今年ァ、いい買いっぷりだったぞ!" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "来年は、もっと早く手を挙げます" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "はっ。言うようになったな" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "一月に来たときはよ、木札の持ち方から違ったんだぞ、あんた。こう、賞状みてえに持ってた" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "そんなには、していません" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そんなにだ。ま、松を張り合って買う顔になりゃ、こっちも張り合いがある" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "一つ、伺っても" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "おう" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "祖母は、松を、どこを見て選んでいましたか" },
		{ kind: "narration", text: "辰巳は木槌を台に置いて、腕を組んだ。" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "根だな。根引きは根だ。太いのがいいと思うだろ。ちがう。細くても、まっすぐ下に伸びてんのがいい。曲がってんのは、畑で邪魔されてる。常サンはな、束の下に手ぇ突っ込んで、いっぺん持ち上げてた。重さで分かるってさ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "重さで" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "俺には分からん。四十年やってても分からんもんは分からん。あの人は、耳と手だけで買ってた" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "重さは、何を教えてくれるんですか" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "水だよ。切ってから水を吸ってねえ松は、軽い。日保ちしねえ。重いのは、根が最後まで水を上げてた証拠だ。常サンはそれを、持っただけで当てた。俺は秤に載せなきゃ分からん。あの人のは、秤のいらねえ秤だった" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "秤のいらない秤" },
		{ kind: "say", speaker: "sub", name: "辰巳", text: "そう。俺のこの手も、四十年で少しは秤に近づいたと思っとったが、まだ遠い。あんたのは、始めたばっかりだ。焦んな。四十年やって、それでも分からんのが、この商売の面白えとこだ" },
		{ kind: "narration", text: "若菜は、山の端の根引き松の束に手を入れて、持ち上げてみた。重かった。重い、以上のことは、分からなかった。" },
		{ kind: "narration", text: "競り場の奥に、椿だけを並べた小さな台があった。市場の椿は、形がそろっている。花びらが、判で押したように同じ向きに開いていた。若菜は二箱競り落として、木札の番号を控えに写した。坂の下の農家の椿は、市場には出ない。あとで軽トラで寄る。形はばらばらだが、色が濃い。寒が深いほど、赤が黒に近づく。形の椿を、店の顔にする。色の椿を、分かる客のために、奥に置く。どちらがいいという話ではない、出す相手が違うだけだと、祖母の帳面にあった。" },
		{ kind: "narration", bg: "shop_day", text: "軽トラに積みきれない分は、犬飼生花の台車が運んでくれた。犬飼は店まで来て、ついでに午前中いっぱい、松の荷ほどきを手伝っていった。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "うちの仲卸、松市の日は配達までがセットなの。得したと思わないでよ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "思っています" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "思うなよ。あーもう、この結束バンド硬い。誰だこんなにきつく締めた奴。俺だ" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "ていうか多いって、あんた。去年の常さんと同じ量、買ったでしょ。荷台見て分かったもん。常さんもこの量、毎年ひとりで捌いてたんだよなあ。ばけもんだよ、ほんと" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "化け物ではありません。段取りだと、帳面に書いてありました" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "段取りねえ。段取りで手が四本になるならやってみ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "四本足の話は" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "してない。狼の話じゃない。今のは俺の手の話。二本じゃ足りねえって話" },
		{ kind: "narration", text: "犬飼は結束バンドを一本、歯で切った。残りは、腰の鞘から出した自分の鋏で落としていった。" },
		{ kind: "narration", text: "店先に松が並ぶと、通りが一気に年末の色になった。八重さんが白菜を抱えたまま出てきて、しばらく眺めていった。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "まあ。常ちゃんの店先だわ、これ" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、去年と同じ数、買ったでしょう" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "なぜ、それを" },
		{ kind: "say", speaker: "sub", name: "八重", text: "同じ並びだもの。あの人、右に根引き、左に若松って決めててね。理由は聞いたことないけど" },
		{ kind: "narration", text: "若菜は、自分が何も考えずに置いた並びを見た。右に根引き、左に若松だった。理由なら、たぶんある。朝日が右から差す通りだから、日を長く当てたい若松を、左の日陰に置く。根引きは日に強い。習う前に、写していた。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "——おい、狼は" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "午後から来ます。試験だそうです" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "学生かよ、あいつほんとに" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "学生です" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "いや知ってるけどさ。市場じゃ荷持ちの化け物なんだよあいつ。この前の台風んとき、濡れた段ボール、俺の倍運んだからね。犬より速い狼っておかしいだろ。四本足の話じゃないんだから" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "四本足の話は、していません" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "……そうだね。うん、俺が悪かった" },
		{ kind: "narration", text: "荷ほどきが終わると、犬飼は軍手を叩いて、店の中を見回した。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "いい店だね、ここ。松が似合う" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "ありがとうございます" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "常さんの店だからね。俺が仲卸入ったばっかのころ、常さん、俺のこと『犬飼んとこの小僧』って呼んでてさ。もう小僧じゃないんだけど、市場だと、いまだに小僧なんだよな" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "祖母は、人を、屋号で呼ぶ人でした" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "そう。花常の、って呼ばれると、こっちも背筋伸びたよ。……あんたも、そのうちそうなる。もうなりかけてる" },
		{ kind: "narration", text: "台車を返しに行く犬飼を、若菜は通りの角まで見送った。角を曲がる前に、犬飼は振り返って、松の山を指さした。" },
		{ kind: "say", speaker: "sub", name: "犬飼", text: "それ、売り切ってよ。うちが競り負けた分だから" },
		{ kind: "narration", text: "その日、若菜は一日、祖母の鋏だけで仕事をした。" },
		{ kind: "narration", text: "松も、椿の枝も、しめ飾りの直しも。意識してそうしたのではない。夕方、自分の鋏が作業台の引き出しから一度も出ていないことに気づいただけだった。飴色の柄は、一日握っても、手に馴染んで熱かった。" },
		{ kind: "narration", text: "松の根元を落とすと、鋏は太い音で鳴った。椿の枝は、それより一段高い。千両の細い茎は、音がしない。祖母は、この音で枝の善し悪しまで聴き分けたという。若菜には、まだ、太い音と高い音の区別しかつかない。善し悪しは、その音の、もう一つ向こうにあるらしかった。刃を閉じる指の力を、枝ごとに変えている自分の手を、若菜は途中から他人のように見ていた。" },
		{ kind: "narration", text: "夕方、荷を全部さばいて、作業台に松屑が山になった。掃き集めて、庇の下に出て、通りを見た。どの店先にも松があった。" },
		{ kind: "narration", text: "飴色の柄は、一日握った手のかたちのまま、まだ温かかった。" },
	],
};

// 解放: ステージ12-2クリア後
const seiyaNoYouka: Vignette = {
	id: "m12-seiya-no-youka",
	kind: "scene",
	month: 12,
	title: "聖夜の洋花",
	trigger: { at: "stage-clear", stageId: "m12-2" },
	synopsis: "クリスマスの週、店の一角が赤と緑になる。商店街に豆電球の灯る夜のこと。",
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "クリスマスの週だけ、店の一角が赤と緑になる。" },
		{ kind: "narration", text: "薔薇とポインセチアと、白い小さな花。松の隣に置くと、二つの正月が喧嘩しているように見えたので、間に葉牡丹を一列はさんだ。それでどうにか休戦になった。" },
		{ kind: "narration", text: "商店街の街灯に、誰が付けたのか豆電球が巻かれて、夜はささやかに光った。米屋の前だけ二重に巻いてあって、そこだけ明るい。日が落ちるのが早いぶん、灯りのついている時間が長い。" },
		{ kind: "narration", text: "豆電球は、去年の暮れの売れ残りだと八重さんが言っていた。誰かが箱で買って、誰かが配って、いつのまにか通り全部に回っていた。青果まるはちの軒は緑、霜月堂は赤、花常はどちらも巻かず、店先の桶の水にだけ、向かいの光が映っていた。水面が揺れるたび、赤と緑が混ざって、名前のつかない色になる。夕方になると、坂を下りてくる学生の足が、この一角で少しゆるむ。買わなくても、覗いていく。暗い坂を下りてきた目には、赤が効くらしかった。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "おー、うちの店っぽくない一角だ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "うちの店です" },
		{ kind: "say", speaker: "ren", emo: 6, text: "いや、いい意味です。……ケーキ屋の行列、すごかったですよ。霜月堂の若旦那が対抗して『クリスマス大福』出してました" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "大福を" },
		{ kind: "say", speaker: "ren", emo: 2, text: "苺のやつ。並んでるの、ほぼ商店街の身内でしたけど" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "霜月堂さんは、七五三のときも詰め合わせを考えていました。思いつくのが早い人です" },
		{ kind: "say", speaker: "ren", emo: 6, text: "早いですよ。俺、味の感想を聞かれて『甘いです』って答えたら怒られました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "それは、感想ではないので" },
		{ kind: "say", speaker: "ren", emo: 6, text: "言われました、若旦那にも" },
		{ kind: "narration", text: "レンは赤い薔薇の桶を覗き込んで、値札を見て、少し首を傾けた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "薔薇って、この時期だけ高くなるんですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "十二月と、二月です。母の日の芍薬と同じで、要る日が決まっている花は、その日に向かって上がります" },
		{ kind: "say", speaker: "ren", emo: 2, text: "なるほど。……サーバーの帯域と一緒ですね。年末に上がるやつ" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "一緒ですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "一緒ですよ。みんなが同じ日に同じもの欲しがるんで。だから同好会は、二十四日の夜にメンテ入れるんです。誰も見てないんで" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "誰も見ていない日に、働くんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "誰も見てない日に働くと、褒められないけど、怒られもしないんで。最高です" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花屋の盆と、少し似ています" },
		{ kind: "say", speaker: "ren", emo: 1, text: "盆と年末、両方きついんですね、花屋" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "暇なのは、二月と六月だけです。あとは、何かしらの日があります" },
		{ kind: "say", speaker: "ren", emo: 6, text: "サーバーとは逆ですね。うちは何もない日がいちばん平和で、何かある日はだいたい落ちてる" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "落ちる" },
		{ kind: "say", speaker: "ren", emo: 2, text: "サーバーが。人が来すぎると、落ちるんですよ。花は、来すぎても落ちないでしょ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "花は、売り切れるだけです" },
		{ kind: "narration", text: "レンは、松と洋花の境目に挟んだ、白い小さな花に目を止めた。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "この白いの、なんて名前ですか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "かすみ草です。主役の花を、大きく見せるための花です" },
		{ kind: "say", speaker: "ren", emo: 20, text: "脇役ってことですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "脇役です。ただ、かすみ草だけを束ねて買っていく人も、年に何人かいます" },
		{ kind: "say", speaker: "ren", emo: 18, text: "脇役だけ、いいなあ。そういうの、俺は好きなんですよ" },
		{ kind: "narration", text: "夜になると、赤い一角の前で足が止まる客が増えた。学生らしい二人組が、いちばん安い薔薇を三本だけ買って、一本ずつ分けて、一本余らせて笑っていた。子どもを連れた父親が、ポインセチアの鉢を抱えて、鉢は重いですよと言う前に持ち上げて、少しよろけた。" },
		{ kind: "say", speaker: "sub", name: "子ども", text: "これ、なんで赤いの!" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "寒くなると、てっぺんの葉から赤くなるんです。上の葉だけ、赤い" },
		{ kind: "say", speaker: "sub", name: "子ども", text: "ぜんぶ赤くないの、へんなの!" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "変ですね。私も、初めて見たときは、色を塗り忘れたのかと思いました" },
		{ kind: "narration", text: "父親が笑って、いちばん赤いのを選んでいった。レンは、桶の陰から、その様子を見ていた。" },
		{ kind: "say", speaker: "ren", emo: 16, text: "なんか、手伝うことないですか。荷物持つとか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、ポインセチアの鉢を、内側に入れてください。夜、冷えると、外側の鉢から傷むので" },
		{ kind: "narration", text: "レンは鉢を三つ、両手で抱えて、松の内側へ運んだ。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "これ、花より鉢が主役ですね。重さが" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "鉢が主役の花も、あります。冬は、特に" },
		{ kind: "narration", text: "閉店間際に、レンはもう一度、店の入口から中を見渡した。" },
		{ kind: "say", speaker: "ren", emo: 10, text: "……去年のいまごろ、この通り、暗かったんですよね" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "私は、見ていません" },
		{ kind: "say", speaker: "ren", emo: 5, text: "そうか。そうですね" },
		{ kind: "say", speaker: "ren", emo: 21, text: "じゃ、今年ぶんは俺が覚えとくんで。明るかったってことで" },
		{ kind: "narration", text: "若菜は、その言い方を、否定しなかった。窓の外の豆電球が、風もないのに一度だけ暗んで、また点いた。" },
		{ kind: "narration", text: "聖夜の店じまいのあと、若菜は売れ残りの白い薔薇を一本、帳場の瓶に挿した。白菊の隣に、今月だけの白が並んだ。表の桶の水には、まだ、向かいの赤と緑が映っていた。その水を、明日の朝に替える。年内、最後の水替えになる。" },
	],
};

// 解放: ボス「大霜」戦の前
const shimogakoi: Vignette = {
	id: "m12-shimogakoi",
	kind: "scene",
	month: 12,
	title: "霜囲い",
	trigger: { at: "boss-before", stageId: "m12-3" },
	synopsis: "この冬いちばんの寒波を前に、よしずと毛布で店に霜囲いをする。",
	lines: [
		{ kind: "narration", bg: "front_winter", text: "年の瀬の寒波は、予報より二日早く来た。" },
		{ kind: "narration", text: "昼過ぎから風が北に回って、通りの端の空き店舗のシャッターが、一定の間隔で鳴りはじめた。四時には日が落ちた。夕方の空気が金物みたいに冷えて、店先に出しっぱなしの桶の水面が、もう固まりかけている。指で押すと、薄い膜が音もなく割れた。" },
		{ kind: "narration", text: "ラジオの予報は、今夜が底だと言っていた。この冬いちばん、と繰り返す声が、作業場のストーブの上で小さく鳴っている。通りの向こうで、まるはちの八重さんが、大根の桶に古毛布をかけているのが見えた。どの店も、同じ時間に、同じことをしていた。年末の寒波は、商店街の共同作業だった。" },
		{ kind: "narration", text: "若菜は店の裏から、去年の囲いの材料を出してきた。よしずと、古い毛布と、丸めた麻布。どれも、自分では一度も使ったことのないものだった。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "これ、どう組むんですか" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "分かりません" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "使ったことがないので。去年の写真もありません。祖母は、写真を撮る人ではなかったので" },
		{ kind: "say", speaker: "ren", emo: 16, text: "じゃあ、考えましょう。風、どっちから来てます?" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "北です。通りをまっすぐ" },
		{ kind: "say", speaker: "ren", emo: 1, text: "なら、北側を厚くして、南は開けとくのがいいですよ。全部囲うと、朝、日が入らないんで" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "詳しいですね" },
		{ kind: "say", speaker: "ren", emo: 15, text: "長野の実家、これやるんで。畑じゃなくて、水道の元栓ですけど。父親が無言でやるのを、無言で手伝う行事です" },
		{ kind: "narration", text: "よしずは思ったより重く、二枚重ねると、若菜ひとりでは立てられなかった。レンが下端を押さえ、若菜が上を起こす。息が合うまで、二度、倒した。三度目で立った。下端を縁台の脚に噛ませ、麻布は椿の鉢の根元に巻いた。毛布は椿と椿のあいだに渡して、寒さの通り道をふさいだ。手がかじかんで、麻紐の結び目が、指の言うことをきかない。" },
		{ kind: "narration", text: "水道の蛇口には、古タオルを二重にしてから、その上にビニールをかぶせた。レンは、元栓のほうにも古タオルを巻いた。長野の実家の手つきだと言った。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "蛇口、少し開けときましょう。糸みたいに、水を落としたまま" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "出したままにするんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "出したままです。止まった水から凍るんで。動いてる水は、凍る暇がないんですよ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "花と、逆ですね。花は、動かして水を吸わせると、早く傷みます" },
		{ kind: "say", speaker: "ren", emo: 20, text: "あー。同じ水でも、逆なんですね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "同じ水でも、逆です" },
		{ kind: "say", speaker: "ren", emo: 2, text: "こっちの結び、南京でやっときました! 犬飼直伝!" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "覚えてたんですね" },
		{ kind: "say", speaker: "ren", emo: 18, text: "教わったら、次は教えるんで。誰かに" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "では、私に教えてください" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え、いま?" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "いま覚えないと、来年、また分からないので" },
		{ kind: "narration", text: "レンは軍手を外して、麻紐の端を若菜の手に握らせた。輪を作って、通して、引く。三度目で、締まった。四度目で、緩んだ。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "そう、そこ。引くとき、下向きじゃなくて横です" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "横" },
		{ kind: "say", speaker: "ren", emo: 2, text: "横。あ、いま締まった。締まりました、いま" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "締まりました" },
		{ kind: "say", speaker: "wakana", emo: 18, text: "もう一度" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え、まだやるんですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "もう一度やらないと、指が忘れます。頭は覚えても、指は忘れるので" },
		{ kind: "narration", text: "レンは黙って、結びをほどいて、麻紐を若菜の手に戻した。今度は、口を出さずに見ていた。輪、通し、横に引く。一度で締まった。若菜は、締まった結び目を、指の腹で二度、確かめた。" },
		{ kind: "say", speaker: "ren", emo: 2, text: "筋いいですよ" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "その言い方は、しないでください" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんでですか。褒めたのに" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "なんとなくです" },
		{ kind: "narration", text: "二人で立てたよしずの前に立つと、風の音が、確かに半分になっていた。よしずの内側と外側で、空気の冷たさが違う。若菜は手をかざして、その境目を確かめた。境目は、指一本ぶんの厚みもなかった。よしず一枚で、冬が一枚、薄くなる。" },
		{ kind: "narration", text: "風が通りを鳴らして、二人は同時に首をすくめた。レンは軍手の手に息を吹きかけて、ふと、囲いの向こうの椿を見た。" },
		{ kind: "say", speaker: "ren", emo: 1, text: "……椿って、寒いほど色が出るんですよね。センセ——" },
		{ kind: "say", speaker: "ren", emo: 10, text: "……" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "?" },
		{ kind: "say", speaker: "ren", emo: 6, text: "……いや。誰かが、言ってました。手、悴んできましたね。中入りましょう" },
		{ kind: "narration", text: "よしずの内側で、椿は、風のないぶんだけ黙っていた。" },
	],
};

// 解放: ボス「大霜」撃破後
const toshiNoSeNoYoru: Vignette = {
	id: "m12-toshi-no-se-no-yoru",
	kind: "scene",
	month: 12,
	title: "年の瀬の夜",
	trigger: { at: "boss-after", stageId: "m12-3" },
	synopsis: "寒波の抜けた静かな晩。くろまつの玄が豆を置いていき、閉店間際にレンが来る。丸椅子を出して、長く話す。",
	lines: [
		{ kind: "narration", bg: "shop_night", text: "寒波が抜けた翌日は、拍子抜けするほど静かな晩になった。" },
		{ kind: "narration", text: "風がやむと、商店街は音のない場所になる。豆電球だけが残って、シャッターの下りた店先を等間隔に照らしていた。若菜は霜囲いのよしずを一枚だけ外して、そこから店の灯りが通りに漏れるようにした。" },
		{ kind: "narration", text: "昨夜まで鳴っていた空き店舗のシャッターが、今夜は黙っている。風が運んでいた音を、全部持っていってしまったようだった。桶の水は、朝に張っていた氷が溶けて、また元の高さに戻っていた。若菜は指を入れて、水の冷たさを確かめた。冷たかったが、もう膜は張らなかった。外したよしずを立てかけて、店の中を見た。灯りが、通りに細い帯になって伸びている。その帯が、坂のほうへ、少しだけ届いていた。" },
		{ kind: "narration", text: "七時前に、くろまつの玄が来た。戸を開ける前に、ガラスの向こうで一度、店の中を確かめる大きな影が映った。それから戸が開いて、のれんの向こうから出てきたそのままの前掛けで、片手に紙の袋を提げた玄が入ってきた。外の冷えが、玄の背中のうしろから、一度だけ流れ込んだ。" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……豆" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "いつも、ありがとうございます" },
		{ kind: "narration", text: "玄は袋を勘定台に置いた。置いてから、もう一つ、上着のポケットから同じ袋を出して、隣に並べた。" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "……二つ" },
		{ kind: "say", speaker: "sub", name: "玄", text: "……ああ" },
		{ kind: "say", speaker: "sub", name: "玄", text: "浅いのと、深いの。若いのは、深いほうがいい" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "若いの" },
		{ kind: "say", speaker: "sub", name: "玄", text: "あの、耳の" },
		{ kind: "narration", text: "玄はそれだけ言って、椿の桶から一輪を選び、新聞紙を待たずに手に持って帰っていった。若菜は、袋を二つ、並べたまましばらく見ていた。それから、深いほうを棚の上の段に上げた。" },
		{ kind: "narration", text: "深いほうの袋は、浅いほうより、手に持つと重かった。挽き方の違いだと思ったが、たぶん、量も少し多い。玄は、そういう間違え方をする人ではなかった。若菜は棚を見上げて、袋の高さを、目で覚えた。" },
		{ kind: "narration", text: "大晦日の二日前、閉店の三十分前に、レンは来た。" },
		{ kind: "narration", text: "戸が開く前に、通りの松屑が一掃きされる音がした。穂先を上にして壁にもたせる音。それから、戸が開いた。" },
		// 【問い高】(※11月までの「問い」選択が多い場合の開幕)
		{ kind: "narration", when: { choice: "B-21", is: "A" }, text: "勘定台の上には、若菜が先に、紺の帳面を出して置いていた。" },
		{ kind: "narration", when: { choice: "B-21", is: "A" }, text: "戸を開けたレンは、挨拶の途中で、それに気づいた。" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "ren", emo: 4, text: "こんばん——……" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "ren", emo: 5, text: "……それ" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 18, text: "話が、あるんでしょう。……私にも、あります。どちらから先にするかだけ、決めましょう" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "ren", emo: 16, text: "……俺からで、いいですか。順番的に、たぶん、俺からなんで" },
		{ kind: "say", when: { choice: "B-21", is: "A" }, speaker: "wakana", emo: 21, text: "どうぞ。……座りますか" },
		// 【問い低】(※「待つ」を選び続けた場合の開幕)
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "ren", emo: 1, text: "こんばんは。……今月の、まだ選んでなくて" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 1, text: "松と、椿が残っています" },
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "外は乾いた寒さで、店の中ではストーブの芯が細く鳴っていた。レンはいつものように桶を一周して——今日は、選ばなかった。椿の前で立ち止まったまま、動かない。" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "ren", emo: 16, text: "……三隅さん。ちょっと、長い話していいですか" },
		{ kind: "say", when: { choice: "B-21", is: "B" }, speaker: "wakana", emo: 21, text: "どうぞ。……座りますか" },
		// 【合流】
		{ kind: "narration", text: "若菜は、勘定台の奥から、丸椅子を出した。" },
		{ kind: "narration", text: "一月から、誰も座っていない椅子だった。レンは椅子を見て、一拍おいて、静かに腰を下ろした。大きな身体に、椅子は少し小さかった。それでも、収まりが良く見えた。椅子の脚が、床のいつもの窪みに、かちりと嵌まった。向きは、この向きだった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "俺、一年生のとき——二年半前です。誰も知り合いいなくて。長野から出てきて、大学とコンビニと部屋の三角形だけで生きてて" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "ren", emo: 5, text: "この店の前、毎日通って帰ってたんです。花なんか、興味なかったのに。なんか……ここだけ、明るくて" },
		{ kind: "narration", text: "ストーブが、こん、と鳴った。" },
		{ kind: "say", speaker: "ren", emo: 19, text: "ある日、店先で、その、水やりしてた——" },
		{ kind: "say", speaker: "ren", emo: 18, text: "……おばあさんが。呼び止めてくれたんです。『あんた、毎日通るね』って。で、いきなり、水仙を一輪、持たされて" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "……" },
		{ kind: "say", speaker: "ren", emo: 1, text: "金、いいから、って。そのかわり、って言われたんです。『一輪だけ持っていきな。部屋に花があると、部屋が部屋になるから』" },
		{ kind: "say", speaker: "ren", emo: 2, text: "ほんとでした。机の上に一輪あるだけで、部屋、帰る場所になるんですよ。三角形が、四角になった" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "月に一度、というのは" },
		{ kind: "say", speaker: "ren", emo: 15, text: "金がなかったんで。一輪が、俺の贅沢だったんです。バイト代入った次の日に来て、その月いちばん安いのを一輪。センセイ、俺の顔見ると、もう水切りの桶、出してくれてて" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "水切りを、教わったんですか" },
		{ kind: "say", speaker: "ren", emo: 2, text: "教わりました。最初、俺、茎を空気中で切って、なんで水吸わないんだって文句を言ったんです。そしたら、水の中で切れって。茎に空気を入れたら水が上がらないって。センセイ、理屈から教える人だったんです。俺が情報工学だって言ったら、じゃあ理屈で教えるって" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "理屈で" },
		{ kind: "say", speaker: "ren", emo: 2, text: "花に、理屈があると思ってなかったんです、俺。きれいなだけかと。そしたら全部、理屈だった。水の高さも、切る角度も、日の当て方も。なんか、プログラムと一緒でした。ちゃんと、理由がある" },
		{ kind: "say", speaker: "ren", emo: 18, text: "それから月イチで通って。水切り教わって、レジの調子悪い日は俺が叩いて直して。……俺、勝手に『センセイ』って呼んでました。あの人、笑って許してくれたんで" },
		{ kind: "say", speaker: "wakana", emo: 19, text: "……祖母を" },
		{ kind: "say", speaker: "ren", emo: 10, text: "はい。……センセイが倒れたって、八百屋のおばちゃんから聞いて。それから店、閉まって。……俺、来られなかったんです。ずっと。この通り自体、避けて帰ってました。遠回りして" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "どのくらい" },
		{ kind: "say", speaker: "ren", emo: 10, text: "駅から、坂の上まで。川の橋を一本ぶん向こうに渡って、住宅街を抜けて。十五分よけいにかかるんですけど、そっちのほうが早く帰れる気がしてました" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "一年、そうしていたんですか" },
		{ kind: "say", speaker: "ren", emo: 17, text: "はい" },
		{ kind: "narration", text: "若菜は、勘定台の縁に置いた自分の手を見た。指の腹に、松脂の黒い跡が残っている。一日洗っても落ちない種類の汚れだった。" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "この通りは、去年の十二月から、ずっと閉まっていたわけではありません。まるはちさんも、くろまつさんも、開いていました" },
		{ kind: "say", speaker: "ren", emo: 11, text: "知ってます。だから、なおさら駄目だったんです。ここだけ閉まってるのが" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "……" },
		{ kind: "say", speaker: "ren", emo: 13, text: "正月に、久しぶりに通ったら——灯りがついてて" },
		{ kind: "say", speaker: "ren", emo: 18, text: "……よかった、って。ほんとに、それだけ言いに入ったんです、あの日。気づいたら水仙買ってました。センセイに最初にもらったのが、水仙だったから" },
		{ kind: "narration", text: "若菜は勘定台に手をやって、レジの引き出しを開けて、閉めた。鳴らなかった。" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "二月から、聞きたかったんです" },
		{ kind: "say", speaker: "ren", emo: 6, text: "聞きませんでしたね" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "聞くと、あなたの一輪の意味が、変わる気がして" },
		{ kind: "narration", text: "店の外を、風のない夜が過ぎていく。豆電球のひとつが、遠くで点いたり消えたりしている。若菜は、レンの空いた手を見た。今日は、まだ一輪も選んでいない手だった。" },
		// 【問い高】
		{ kind: "narration", when: { choice: "B-21", is: "A" }, text: "若菜は、勘定台の上の紺の帳面に手を置いた。最初から、このために出してあった帳面だった。レンの前へ滑らせて、二月の頁を開く。" },
		// 【問い低】
		{ kind: "narration", when: { choice: "B-21", is: "B" }, text: "若菜は黙って、勘定台のいちばん深い引き出しを開けた。紺の帳面。角の擦り切れた、数字の几帳面な、あの帳面を、レンの前に置いて、二月の頁を開いた。" },
		// 【合流】
		{ kind: "narration", text: "数字の脇の、小さな字。" },
		{ kind: "narration", text: "「狼の子、また来た。水切りを教えた。筋がいい」" },
		{ kind: "narration", text: "レンは、頁を長いこと見ていた。毛の色と同じ灰色の目が、ゆっくり瞬きをして、それから、耳が、ぺたんと倒れた。" },
		{ kind: "narration", text: "レンの指が、頁の隅で一度止まった。紙が、そこだけ薄く曇っている。四角い跡だった。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……ここ、何か貼ってました?" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "貼りました。剥がしました" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんでですか" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "貼ったままにすると、毎日そこを開くので" },
		{ kind: "say", speaker: "ren", emo: 3, text: "……筋がいい、って書いてあります?" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "書いてあります。ここに" },
		{ kind: "say", speaker: "ren", emo: 9, text: "……ですよね。俺、筋いいんですよ。センセイ、俺には点数辛かったのに" },
		{ kind: "narration", text: "声の途中が、少し濡れていた。若菜は、聞こえなかったことにした。レンは、袖口で目のあたりを一度こすった。灰色の毛が、そこだけ濡れて濃くなった。それから、指先で、頁の隅を、汚さないようにそっと押さえた。数字の几帳面な、あの帳面の隅を。若菜は、十一月の頁をめくって、もうひとつの書き込みを見せた。" },
		{ kind: "narration", text: "「狼の子に梅を持たせた。咲く頃にまた来る、と約束した」" },
		{ kind: "say", speaker: "ren", emo: 4, text: "——これ" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "二年前の、十一月ですよね。たぶん" },
		{ kind: "say", speaker: "ren", emo: 9, text: "はい。その梅、咲いたんです。二月に。見せに来るつもりで……写真も撮って……間に合わなかった" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "……" },
		{ kind: "say", speaker: "ren", emo: 5, text: "センセイの写真、ないんですか" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "ありません" },
		{ kind: "say", speaker: "ren", emo: 10, text: "……ですよね" },
		{ kind: "say", speaker: "ren", emo: 11, text: "約束、破ったんです。俺" },
		{ kind: "narration", text: "店の中は、ストーブの音だけになった。若菜は、少し待ってから、口を開いた。" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "——先月の梅は、どうですか" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "今、育ててる枝。咲きそうですか" },
		{ kind: "say", speaker: "ren", emo: 13, text: "……膨らんでます。あと少し" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "年が明けたら、咲きます。そうしたら、見せに来てください。写真じゃなくて、窓に飾ったのを、また坂の下から見ますから" },
		{ kind: "say", speaker: "ren", emo: 4, text: "……坂の下から?" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "二階の、右から二番目" },
		{ kind: "narration", text: "レンの耳が、ぴんと立って、それから、見たことのない角度に倒れた。" },
		{ kind: "say", speaker: "ren", emo: 3, text: "……見えてたんですか" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "見えてました。十一月から" },
		{ kind: "say", speaker: "ren", emo: 3, text: "うわ" },
		{ kind: "say", speaker: "ren", emo: 2, text: "……うわー" },
		{ kind: "narration", text: "彼は両手で顔を覆って、それから、笑った。濡れたままの声で、いつもの、店じゅうに響く笑い方だった。" },
		{ kind: "narration", text: "ストーブの上の薬缶が、そろそろと鳴りはじめた。若菜は火を細めて、湯を、沸かし切らないところで止めた。玄の豆の、深いほうの袋を棚から下ろす。背伸びをして、さっき目で覚えた高さから、下ろした。豆を手回しの挽き器に入れて、回す。かり、かり、と店の隅で音がして、レンの耳が、その音のほうへ一度、向いた。挽き器の下に、深い色の粉が小さな山になった。粉を紙の漉し器に移して、湯を、糸のように細く落とす。最初のひと回しで、粉が息をするように膨らんだ。膨らんで、しぼんで、それから、色のついた滴が、下の杯に落ちはじめた。待つあいだ、二人とも黙っていた。滴の落ちる音だけが、ストーブの音のあいだに、規則正しく挟まった。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え、それ、くろまつの" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "二袋、置いていかれました。浅いのと、深いの" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんで二つ" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "若いのは深いほうがいい、と" },
		{ kind: "narration", text: "レンは丸椅子の上で、姿勢を直した。耳が一度、前に向いた。" },
		{ kind: "say", speaker: "ren", emo: 3, text: "……マスター、俺のこと、若いのって呼んでるんですか" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "耳の、と言っていました" },
		{ kind: "say", speaker: "ren", emo: 18, text: "耳の。まあ、合ってます" },
		{ kind: "say", speaker: "ren", emo: 6, text: "マスター、二年、ひとことも俺に喋りかけてこなかったんですよ。碁の相手にもしてくれないし" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "豆を、二袋置いていく人です。数えている人です" },
		{ kind: "say", speaker: "ren", emo: 20, text: "数えてる" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "浅いのと、深いの。数えないと、二袋にはなりません" },
		{ kind: "narration", text: "湯気の立つ杯を二つ、勘定台に並べた。若菜は自分のぶんを一口飲んでから、思い出したような顔をしないよう気をつけて、聞いた。" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "一つ、伺ってもいいですか" },
		{ kind: "say", speaker: "ren", emo: 1, text: "どうぞ" },
		{ kind: "say", speaker: "wakana", emo: 10, text: "五月の、カーネーション" },
		{ kind: "say", speaker: "ren", emo: 1, text: "あー、はいはい。長野に送ったやつ" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "宛先が、志乃さん、でしたね" },
		{ kind: "say", speaker: "ren", emo: 6, text: "母です。志乃。毎年送れって言われるんですよ、電話で。『漣、今年は忘れてないでしょうね』って先に釘さされて、忘れてても忘れてないことになるんで" },
		{ kind: "say", speaker: "wakana", emo: 9, text: "……そうですか" },
		{ kind: "say", speaker: "ren", emo: 19, text: "なんですか、いま" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "なんでもありません" },
		{ kind: "say", speaker: "ren", emo: 6, text: "顔に出てますけど" },
		{ kind: "say", speaker: "wakana", emo: 3, text: "出ていません" },
		{ kind: "say", speaker: "ren", emo: 2, text: "出てます。ちょっと安心した顔してました、いま" },
		{ kind: "say", speaker: "wakana", emo: 11, text: "珈琲が熱いだけです" },
		{ kind: "say", speaker: "ren", emo: 18, text: "はい" },
		{ kind: "narration", text: "杯の底が見えるまで、二人とも黙っていた。外を、除夜の鐘にはまだ早い自転車が、一台通っていった。" },
		{ kind: "narration", text: "帰り際、レンは椿を一輪選んだ。寒いほど色の出る、いちばん赤いのを。それから若菜は、若松の枝を一本、断りもなく添えた。" },
		{ kind: "say", speaker: "ren", emo: 4, text: "え、これ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "十二月ですから。正月まで、部屋に置いてください" },
		{ kind: "say", speaker: "ren", emo: 19, text: "一輪じゃなくないですか" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "一輪と、一枝です" },
		{ kind: "narration", text: "新聞紙を斜めに一巻き——今では若菜の手が、誰に教わったのか知っている包み方で。" },
		{ kind: "say", speaker: "ren", emo: 5, text: "……センセイの帳面、また読ませてください。いつか" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "いつでも。……ただし、貸出はしません。ここで読んでください" },
		{ kind: "say", speaker: "ren", emo: 13, text: "はい。ここで" },
		{ kind: "say", speaker: "ren", emo: 1, text: "三隅さん" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "はい" },
		{ kind: "say", speaker: "ren", emo: 16, text: "俺、来年も、月イチで来ていいですか。一輪ずつ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "どうぞ。ただし、十二月だけは、一輪と一枝です。今年で、分かったので" },
		{ kind: "say", speaker: "ren", emo: 2, text: "一輪と一枝。覚えました" },
		{ kind: "narration", text: "戸が閉まって、椿の赤が、夜の商店街を坂のほうへ帰っていった。" },
		{ kind: "narration", text: "若菜は、丸椅子を勘定台の奥へ戻さず、そのままにした。明日も、たぶん、誰かが座る。二つ並んだ杯を洗って、深いほうの袋を、また棚の上の段に上げた。残りは、あと三杯ぶんだった。" },
	],
};

// 解放: ステージ12-3クリア後・前半
const hareNoHiNi: Vignette = {
	id: "m12-hare-no-hi-ni",
	kind: "scene",
	month: 12,
	title: "晴れの日に",
	trigger: { at: "stage-clear", stageId: "m12-3" },
	synopsis: "よく晴れた年の瀬の昼、雨の日にだけ来ていた人が、晴れの日に店へ寄る。",
	lines: [
		{ kind: "narration", bg: "shop_day", text: "年の瀬の、よく晴れた昼だった。" },
		{ kind: "narration", text: "霜が溶けて、通りのアスファルトが濡れたまま光っていた。庇の下まで日が差し込んで、桶の水がぬるむ。若菜は店先に椅子を出して、正月用の松の値札を書き直していた。日向で書くと、墨の乾きが速い。" },
		{ kind: "narration", text: "昨夜の冷えが嘘のように、風がなかった。どの店も、雪よけの毛布を外して、軒に干している。まるはちの大根が、また表に戻ってきた。日向は暖かく、日陰はまだ夜のままで、通りには、暖かい帯と冷たい帯が、縞になっていた。若菜の書く値札の墨が、日向の帯の上で、みるみる乾いていく。" },
		{ kind: "narration", text: "戸が開いて、若菜は一瞬、誰だか分からなかった。雨の日の人が、晴れの日に、コートを着て立っていた。頬に、前より色があった。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "……こんにちは" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "いらっしゃいませ" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "今日は、あかるいのを——たくさん、ください。白い部屋、出られたんです" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "……" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "おめでとうございます" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "よくなったんです。この店の花、ずっと、窓のところにあったんですよ。ぜんぶ" },
		{ kind: "say", speaker: "wakana", emo: 8, text: "ぜんぶ、ですか" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "ぜんぶです。三本のときも、五本のときも。看護師さんに、そこの花屋さんですかって聞かれて、そうですって答えるのが、なんだか自慢でした" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "ありがとうございます" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "白ばっかり頼んでたのは、白しか見ない部屋にいたからなんです。壁も、シーツも、白くて。だから、白いのを置くと、境目が分からなくなって、いいなと思って" },
		{ kind: "say", speaker: "wakana", emo: 13, text: "境目が" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "花のところだけ、ちょっと膨らむんです。壁が。変な言い方ですけど" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "分かります。花のあるところだけ、少し、部屋が広くなります。膨らむで、合っています" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "よかった。看護師さんには、うまく言えなかったんです。膨らむって言ったら、笑われて" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "笑う人は、白い部屋にいたことのない人です" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "三本の週は、お金がなかったんじゃなくて、それだけしか持てなかった週なんです。花瓶まで、腕が届かなくて" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "持てなかった" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "五本持てた週は、あ、今週はいける、って。花の数で、自分の調子が分かるんです。体温計より、正直で" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "今日は、数えないくらい、ください" },
		{ kind: "narration", text: "若菜は、店にあるいちばん明るい色を、腕に余るほど束ねた。黄色のスプレー菊、オレンジのガーベラ、赤い椿を三輪、真ん中に。葉物は少なめにした。抱えたときに、顔の前が明るくなる高さで揃えた。" },
		{ kind: "narration", text: "束ねながら、若菜は、この半年、この人が頼んできた花を思い出していた。六月の白い小花。八月の、仏花ではなかった白。どれも白だった。白ばかり選ぶ客の欄を、祖母なら、どう書いただろう。たぶん、色のことは書かない。次に来る日のことだけ、書く。今日の欄には、初めて、白以外の色が並ぶ。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "重い" },
		{ kind: "say", speaker: "wakana", emo: 7, text: "重いです。持てますか" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "持ちます。今日は、持てます" },
		{ kind: "narration", text: "会計のとき、女性は初めて名乗った。" },
		{ kind: "say", speaker: "sub", name: "女性の声", text: "雨宮です。……来年からは、晴れの日にも来ますね" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "お待ちしています。雨宮さん" },
		{ kind: "narration", text: "雨宮さんは、両手で花を抱えて、日向の帯のほうへ歩いていった。花の高さが顔を隠して、通りの向こうから見たら、明るい色が一人で歩いているように見えたかもしれない。角を曲がるとき、抱えたまま、器用に振り返って、もう一度だけ会釈した。" },
		{ kind: "narration", text: "帳面には、今夜、姓名で書く。祖母がそうしていたように。" },
	],
};

// 解放: ステージ12-3クリア後・後半
const saimatsuNoHitotaba: Vignette = {
	id: "m12-saimatsu-no-hitotaba",
	kind: "scene",
	month: 12,
	title: "歳末の一束",
	trigger: { at: "stage-clear", stageId: "m12-3" },
	synopsis: "大晦日の前日、仕事納めの帰りに春野くんが寄る。用途を決めないまま、一束を選ぶ。",
	lines: [
		{ kind: "narration", bg: "shop_evening", text: "大晦日の前日、スーツの春野くんが、仕事納めの帰りに寄った。" },
		{ kind: "narration", text: "夕方の商店街は、この一年でいちばん人が多かった。買い物袋を提げた人が二列ですれ違い、霜月堂の前には行列ができている。店先の松は、朝に並べた数の半分に減っていた。" },
		{ kind: "narration", text: "日が落ちるのが早く、五時にはもう、通りの豆電球が主役になっていた。数の子だの蒲鉾だのを提げた人が、坂を上っていく。買い忘れを思い出した顔で、また下りてくる。通りの向こうから、八重さんの声がした。" },
		{ kind: "say", speaker: "sub", name: "八重", text: "若菜ちゃん、うちの大根、あと二本! いる人いたら回してあげて!" },
		{ kind: "narration", text: "年末の商店街は、少しだけ、祭りに似ていた。" },
		{ kind: "narration", text: "三月に袴の母娘の隣で立っていた青年は、コートの肩に雪でもないのに手をやる癖がついていた。鞄が、四月に見たものより大きい。" },
		{ kind: "say", speaker: "sub", name: "春野", text: "一年、世話になった人に、って思って。……誰にとは決めてないんですけど、買いたくなって" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "決めていなくても、買っていいんですよ、花は" },
		{ kind: "say", speaker: "sub", name: "春野", text: "決めてないのに買うと、変ですかね" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "変ではありません。決めてから買う人のほうが、たぶん少ないです" },
		{ kind: "say", speaker: "sub", name: "春野", text: "そうなんですか" },
		{ kind: "say", speaker: "wakana", emo: 1, text: "先に花を買って、それから渡す相手を思い出す人を、今年、何人も見ました" },
		{ kind: "say", speaker: "sub", name: "春野", text: "花屋さんって、そういう人ばっかり見てるんですね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "花を買う人には、たいてい、渡したい人がいます。渡す前の顔を、いちばん近くで見る仕事です" },
		{ kind: "say", speaker: "sub", name: "春野", text: "渡す前の顔" },
		{ kind: "say", speaker: "wakana", emo: 17, text: "渡したあとの顔は、私は見られません。それは、花を持っていった先の話なので" },
		{ kind: "say", speaker: "sub", name: "春野", text: "……じゃあ、いちばんいいやつください。予算、初任給のときの倍で" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "出世しましたね" },
		{ kind: "say", speaker: "sub", name: "春野", text: "してないです。……でも、名刺は、受け取ってもらえるようになりました" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "では、それを祝う束にしましょう" },
		{ kind: "narration", text: "若菜は、千両を芯にして、白い菊と、葉牡丹の小さいのを合わせた。年末の色で、けれど仏花に見えない配置にするのに、少し手間をかけた。仏花に見せないためには、白を散らさず、片側に寄せる。反対側に、千両の赤い実を集める。左右で色を分けると、束は、供えるための顔ではなく、渡すための顔になる。春野くんは、コートのポケットに手を入れたまま、若菜の手元を見ていた。" },
		{ kind: "say", speaker: "sub", name: "春野", text: "それ、習うんですか。学校とかで" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "習ったのは、型だけです。仏花に見せない置き方は、この店で覚えました" },
		{ kind: "say", speaker: "wakana", emo: 15, text: "教わったというより、間違えて、直された回数で、覚えました" },
		{ kind: "say", speaker: "sub", name: "春野", text: "これ、正月まで持ちますか" },
		{ kind: "say", speaker: "wakana", emo: 4, text: "持ちます。水を、三日に一度替えてください。切り口は、そのたびに一センチ落として" },
		{ kind: "say", speaker: "sub", name: "春野", text: "一センチ" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "はい。忘れたら、また来てください。切りに来てくれれば、こちらで落とします" },
		{ kind: "say", speaker: "sub", name: "春野", text: "来ます。三月から数えて、ここ、何回目だろ" },
		{ kind: "say", speaker: "wakana", emo: 2, text: "六回目です" },
		{ kind: "say", speaker: "sub", name: "春野", text: "数えてるんですか" },
		{ kind: "say", speaker: "wakana", emo: 20, text: "帳面に、書いてありますので" },
		{ kind: "say", speaker: "sub", name: "春野", text: "なんか、覚えられてると、また来ようって思いますね" },
		{ kind: "say", speaker: "wakana", emo: 16, text: "そう思ってもらえるように、書いています" },
		{ kind: "say", speaker: "sub", name: "春野", text: "来年も、よろしくお願いします" },
		{ kind: "say", speaker: "wakana", emo: 21, text: "よいお年を。七回目、お待ちしています" },
	],
};

// 解放: 十二月の全ステージクリア後
const chomen1231: Vignette = {
	id: "m12-chomen-1231",
	kind: "chomen",
	month: 12,
	title: "十二月三十一日",
	trigger: { at: "month-close", month: 12 },
	synopsis: "大晦日の帳面。一年でいちばんの数字を書き、一年ぶんの帳面を閉じる。",
	lines: [
		{ kind: "diary", text: "十二月三十一日。晴れ。年の瀬の風。" },
		{ kind: "diary", text: "松、完売。椿、残り三輪は、うちの分。しめ飾り、完売。千両、葉牡丹、完売。南天だけ二束残った。来年は南天を減らす。" },
		{ kind: "diary", text: "一年でいちばんの数字で、一年が終わる。電卓を三度叩いて、三度とも同じ数字が出たので、信じることにした。" },
		{ kind: "diary", text: "内訳を書く。松と若松で、去年の一・二倍。しめ飾りは、×印を減らしたぶん、売れ残りがゼロになった。減らすことでゼロになる、というのが、一年やって分かった数字の面白さだ。仕入れを増やすより、売れ残りを減らすほうが、帳面はきれいになる。" },
		{ kind: "diary", text: "椿を三輪残した。一輪は、二十六日から、深い引き出しの上にある。あとの二輪は、帳場と、二階。三隅の家の、今年の正月の花だ。" },
		{ kind: "diary", text: "五時に閉めて、店を磨いた。売れない日は店を磨く日、と祖母は書いていたが、いちばん売れた日にも磨くことになるとは書いていなかった。作業台の松脂は、湯でないと落ちない。" },
		{ kind: "diary", text: "磨きながら、勘定台の縁の、右の角だけ、色が変わっているのに気づいた。手が当たる場所だ。一年、私の手がそこに当たっていた。その下の層は、たぶん、祖母の手が五十年当てた色だ。私の一年は、その上に、薄く一枚、乗っただけだった。乗っただけでも、色は、少し変わる。" },
		{ kind: "diary", text: "閉めるとき、通りはまだ人が残っていた。霜月堂の行列は、大福が売り切れてもまだ続いていた。八重さんが、うちの南天の残りを二束、持っていった。正月の間、まるはちの棚に飾るからと。売れ残りを、隣の店の棚が引き取る。これも、帳面には書きようのない売り方だ。" },
		{ kind: "diary", text: "祖母の帳面の白い頁は、白いままにしておく。埋めるのは、祖母の字の仕事で、私の仕事は、こっちの帳面を埋めることだから。" },
		{ kind: "diary", text: "一年、書いた。" },
		{ kind: "diary", text: "祖母のようには、できなかった。水切りは追いついた気がする。枝の音は、半分。蕾の音は、まだ。爪で弾いても、私の耳には、どれも同じに鳴る。" },
		{ kind: "diary", text: "音のことは、あと何年やっても、身につかないかもしれない。それでもいい、ということにする。祖母は耳で買い、私は帳面で買う。同じ松を、違うやり方で、同じ数だけ、落とせるようになった。松市の帰り、辰巳さんに「焦んな」と言われた。焦っていないつもりだったが、そう言われて、少し、肩の力が抜けた。" },
		{ kind: "diary", text: "客の名前は——ずいぶん、書いた。" },
		{ kind: "diary", text: "数えてみた。一月の頁の名前は、二つ。五月は三十九。十二月は、数えるのをやめた。" },
		{ kind: "diary", text: "数字だけつける、と一頁目に書いた帳面は、数字より名前の多い帳面になった。祖母の五月の頁と、同じだ。" },
		{ kind: "diary", text: "八重さん。マスター。辰巳さん。犬飼さん。内藤さん。霜月堂の若旦那。春野さん。雨宮さん。すみれ荘の大家さん。名前を書くと、その人が次に来る日のことを、勝手に考えるようになる。祖母が数字より名前を書いた理由は、たぶん、それだけのことだ。" },
		{ kind: "diary", text: "八重さんは大根を売りに来て、私の顔を見に来る。玄さんは豆を持って、常の店がまだあるかを確かめに来る。私も、たぶん、花を売りながら、誰かが来るのを待っている。" },
		{ kind: "diary", text: "狼の子は、センセイの客で、今は、私の客だ。" },
		{ kind: "diary", text: "センセイ、と書いてみて、消した。私は、その呼び方をする人ではない。私にとっては、祖母だ。同じ人を、二人が、違う名で呼んでいる。呼び名が二つあるだけ、その人は、少しだけ長く、この店にいる。" },
		{ kind: "diary", text: "珈琲の豆が、二袋ある。浅いのと、深いの。深いほうは、あと三杯ぶん。" },
		{ kind: "diary", text: "三杯ぶん、というのは、狼の子が三回来れば、なくなる量だ。玄さんが、そこまで計算して二袋置いたのなら、あの人は、喋らないだけで、いちばん喋っている。次の豆をいつ持ってくるかで、あの人の返事が分かる。" },
		{ kind: "diary", text: "今年は、天気と三度戦った。三月の嵐、九月の野分、十二月の大霜。三度とも、店は残った。祖母の帳面に「棚は縛れ。花は諦めるな」と二度書いてあった意味が、三度目で、やっと身体に入った。縛れば、残る。縛らなければ、飛ぶ。それだけのことを、一年かけて、手で覚えた。" },
		{ kind: "diary", text: "大霜の夜、水道の元栓に、狼の子がタオルを巻いた。長野のやり方だと言っていた。長野の父親も、無言でそれをやるらしい。無言で手を動かす人が、この町にも、あの山にも、いる。私は、そういう人たちの手つきを、少しずつ、写している。" },
		{ kind: "diary", text: "梅は、まだ咲かない。でも、膨らんでいる。坂の上の窓は、今夜も点いている。" },
		{ kind: "diary", text: "窓の色は、帳面には書かないことにした。書くと、確かめに行きたくなる。確かめないほうがいい種類のことが、世の中には、少しだけある。年が明けて、梅が咲いて、坂の下から見えたら、そのとき初めて書く。それまでは、点いている、とだけ、覚えておく。" },
		{ kind: "diary", text: "来年のことは、来年の帳面に書く。——その帳面は、もう買ってある。" },
		{ kind: "diary", text: "十一月の市場の帰りに、文具屋で。同じ紺の、同じ罫の。一冊しか置いていなかった。" },
	],
};
/** 第十二章 師走「大霜」。ボス月。ボス「大霜」はステージ m12-3。 ⚠️並び順が再生順。 */
export const M12: readonly Vignette[] = [
	chomen1201,
	matsuichi,
	seiyaNoYouka,
	shimogakoi,
	toshiNoSeNoYoru,
	hareNoHiNi,
	saimatsuNoHitotaba,
	chomen1231,
];
