<!-- SPDX-FileCopyrightText: Tolehata and hatasaba-project
SPDX-License-Identifier: AGPL-3.0-only -->
<template><span class="todo-check" :data-motion="animations ? 'on' : 'off'"><span class="check" :style="{ width: `${size}px`, height: `${size}px` }"><span :key="`box-${run}`" class="circle" :class="{ done, play }"><svg v-if="done" viewBox="0 0 12 12" aria-hidden="true"><path class="tick" :class="{ play }" d="M2.4 6.3 5 8.8 9.8 3.6" pathLength="1"/></svg></span><template v-if="play"><span :key="`ripple-${run}`" class="ripple"></span><span v-for="(particle, index) in burst" :key="`${run}-${index}`" class="particle" :class="{ blue: rewarded && particle.big }" :style="{ '--dx': `${particle.dx}px`, '--dy': `${particle.dy}px`, '--delay': `${80 + index % 3 * 20}ms`, width: particle.big ? '5px' : '3.5px', height: particle.big ? '5px' : '3.5px' }"></span><span v-if="rewarded" :key="`reward-${run}`" class="reward"><i class="ti ti-droplet-filled" aria-hidden="true"></i>+1</span></template></span><span v-if="title" :key="`title-${run}`" class="title" :class="{ done, play }">{{ title }}</span></span></template>
<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from 'vue';
const props = withDefaults(defineProps<{ done: boolean; rewarded?: boolean; animations?: boolean; size?: number; title?: string }>(), { rewarded: false, animations: true, size: 18 });
const run = ref(0); const play = ref(false); let timer: ReturnType<typeof setTimeout> | undefined;
const burst = Array.from({ length: 10 }, (_, i) => { const angle = i / 10 * Math.PI * 2 - Math.PI / 2; const distance = i % 2 ? 15 : 22; return { dx: Math.cos(angle) * distance, dy: Math.sin(angle) * distance, big: i % 2 === 0 }; });
watch(() => props.done, (done, previous) => { if (!done || previous || !props.animations) { play.value = false; return; } if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; run.value++; play.value = true; if (timer) clearTimeout(timer); timer = setTimeout(() => { play.value = false; }, 1200); });
onBeforeUnmount(() => { if (timer) clearTimeout(timer); });
</script>
<style scoped>
.todo-check{display:inline-flex;align-items:center;gap:8px;min-width:0}.check{position:relative;display:grid;place-items:center;flex:none}.title{min-width:0;overflow-wrap:anywhere;background-image:linear-gradient(currentColor,currentColor);background-repeat:no-repeat;background-position:0 55%;background-size:0 1.5px}.title.done{color:var(--fg-3);background-size:100% 1.5px}.title.play{animation:check-strike .34s .18s cubic-bezier(.65,0,.35,1) backwards}.circle{box-sizing:border-box;width:100%;height:100%;display:grid;place-items:center;border:2px solid color-mix(in srgb,var(--fg) 34%,transparent);border-radius:50%;background:transparent;color:#fff;transition:background-color .18s,border-color .18s}.circle.done{border-color:var(--accent);background:var(--accent)}.circle.play{animation:check-pop .5s cubic-bezier(.34,1.56,.64,1)}svg{width:66%;height:66%;overflow:visible}.tick{fill:none;stroke:#fff;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.tick.play{stroke-dasharray:1;stroke-dashoffset:1;animation:check-draw .28s .14s cubic-bezier(.65,0,.35,1) forwards}.ripple{position:absolute;inset:0;border:2px solid var(--accent);border-radius:50%;pointer-events:none;animation:check-ripple .6s cubic-bezier(.2,0,0,1) forwards}.particle{position:absolute;left:50%;top:50%;border-radius:50%;background:var(--accent);opacity:0;pointer-events:none;animation:check-burst .62s var(--delay) cubic-bezier(.2,.7,.3,1) forwards}.particle.blue{background:#4a8fd6}.reward{position:absolute;left:50%;bottom:100%;display:flex;align-items:center;gap:1px;color:#4a8fd6;font:800 11px 'Archivo',sans-serif;white-space:nowrap;opacity:0;pointer-events:none;animation:check-reward 1s .2s cubic-bezier(.2,.7,.3,1) forwards}.reward i{font-size:13px}@keyframes check-strike{from{background-size:0 1.5px;color:var(--fg)}to{background-size:100% 1.5px;color:var(--fg-3)}}@keyframes check-pop{0%{transform:scale(.6)}45%{transform:scale(1.28)}72%{transform:scale(.92)}100%{transform:scale(1)}}@keyframes check-draw{to{stroke-dashoffset:0}}@keyframes check-ripple{from{transform:scale(.8);opacity:.75}to{transform:scale(2.6);opacity:0}}@keyframes check-burst{0%{transform:translate(-50%,-50%) scale(.3);opacity:1}100%{transform:translate(calc(-50% + var(--dx)),calc(-50% + var(--dy))) scale(1);opacity:0}}@keyframes check-reward{0%{transform:translate(-50%,8px);opacity:0}25%{opacity:1}100%{transform:translate(-50%,-26px);opacity:0}}[data-motion=off] *{animation:none!important;transition:none!important}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}.ripple,.particle,.reward{display:none}}
</style>
