<!-- SPDX-FileCopyrightText: Tolehata and hatasaba-project
SPDX-License-Identifier: AGPL-3.0-only -->
<template><div class="weather" :class="season" :data-motion="animations ? 'on' : 'off'" aria-hidden="true"><div v-if="season === 'winter'" class="snow-ground"></div><span v-for="item in items" :key="`${season}-${item.index}`" class="fall" :style="item.style"><span class="sway" :style="{ '--sway': `${item.sway}px`, animationDuration: `${item.swayDuration}s` }"><span class="flutter" :style="{ '--spin': `${item.spin}deg`, animationDuration: `${item.spinDuration}s` }"><svg v-if="season === 'spring'" viewBox="0 0 20 20"><path d="M10 1C14 5 16 9 15 13c-1 4-4 6-5 6s-4-2-5-6C4 9 6 5 10 1Z" :fill="item.color"/><path d="M10 1l-1.4 3.2L10 3l1.4 1.2Z" fill="#fff" opacity=".6"/></svg><svg v-else-if="season === 'autumn' && item.index % 5 >= 2 && item.index % 5 <= 3" viewBox="0 0 24 24"><path d="M12 14C8 13 3 9 2 4c4-2 7-1 9 2 1-1 1-1 2 0 2-3 5-4 9-2-1 5-6 9-10 10Z" :fill="item.color"/><path d="M12 14v9" stroke="#b58a2a" stroke-width="1.3"/></svg><svg v-else-if="season === 'autumn'" viewBox="0 0 24 24"><path d="M12 1l2 5 3-2-1 5 5-1-3 4 3 2-6 1 1 4-4-3-4 3 1-4-6-1 3-2-3-4 5 1-1-5 3 2Z" :fill="item.color"/><path d="M12 12v11" :stroke="item.color" stroke-width="1.4"/></svg><svg v-else viewBox="0 0 10 10"><circle cx="5" cy="5" r="4" fill="#fff" stroke="#dfe8f3" stroke-width=".6"/></svg></span></span></span></div></template>
<script setup lang="ts">
import { computed } from 'vue';
type Season = 'spring' | 'summer' | 'autumn' | 'winter';
const props = withDefaults(defineProps<{ season: Season; animations?: boolean }>(), { animations: true });
const settings = { spring: { count: 18, min: 9, max: 14, duration: [7, 11], sway: 22, spin: 260, colors: ['#f7c5d3','#f3aec2','#fde0e8'] }, summer: { count: 0, min: 0, max: 0, duration: [0, 0], sway: 0, spin: 0, colors: [] }, autumn: { count: 16, min: 12, max: 18, duration: [8, 12], sway: 30, spin: 420, colors: ['#d9532e','#e87a2e','#f0c23a','#e8b52a','#b83c2a'] }, winter: { count: 40, min: 3, max: 8, duration: [6, 12], sway: 14, spin: 0, colors: ['#fff'] } } as const;
function rnd(index: number, channel: number): number { const value = Math.sin(index * 127.1 + channel * 311.7) * 43758.5453; return value - Math.floor(value); }
const items = computed(() => { const fx = settings[props.season]; return Array.from({ length: fx.count }, (_, index) => { const size = fx.min + rnd(index, 1) * (fx.max - fx.min); const duration = fx.duration[0] + rnd(index, 2) * (fx.duration[1] - fx.duration[0]); return { index, color: fx.colors[index % fx.colors.length], sway: fx.sway * (.5 + rnd(index, 7)), swayDuration: 2.4 + rnd(index, 8) * 2, spin: (rnd(index, 9) > .5 ? 1 : -1) * fx.spin, spinDuration: 3 + rnd(index, 10) * 3, style: { left: `${rnd(index, 4) * 100}%`, width: `${size}px`, height: `${size}px`, opacity: props.season === 'winter' && size < 5 ? .7 : .95, filter: props.season === 'winter' && size < 5 ? 'blur(.6px)' : 'drop-shadow(0 1px 1px rgba(60,40,20,.18))', '--drift': `${(rnd(index, 5) - .5) * 80}px`, '--static-y': `${rnd(index, 6) * 200}px`, animationDuration: `${duration}s`, animationDelay: `${-rnd(index, 3) * duration}s` } }; }); });
</script>
<style scoped>
.weather{position:absolute;inset:0;z-index:2;overflow:hidden;pointer-events:none}.weather.spring{background:linear-gradient(180deg,rgba(255,214,228,.28),transparent 55%)}.weather.summer{background:radial-gradient(ellipse at 80% 0%,rgba(255,236,160,.35),transparent 60%)}.weather.autumn{background:linear-gradient(180deg,rgba(255,196,120,.2),transparent 55%)}.weather.winter{background:linear-gradient(180deg,rgba(225,236,250,.55),rgba(255,255,255,.1) 60%)}.snow-ground{position:absolute;left:12%;right:10%;bottom:14%;height:18px;border-radius:50%;background:radial-gradient(ellipse at 50% 60%,rgba(255,255,255,.85),rgba(255,255,255,0) 70%)}.fall{position:absolute;top:0;display:block;animation:weather-fall linear infinite}.sway,.flutter{display:block;width:100%;height:100%}.sway{animation:weather-sway ease-in-out infinite}.flutter{animation:weather-flutter linear infinite}.winter .flutter{animation:none}svg{display:block;width:100%;height:100%}@keyframes weather-fall{from{transform:translate3d(0,-30px,0)}to{transform:translate3d(var(--drift),calc(100cqh + 30px),0)}}@keyframes weather-sway{0%,100%{transform:translateX(calc(var(--sway) * -.5))}50%{transform:translateX(calc(var(--sway) * .5))}}@keyframes weather-flutter{to{transform:rotate(var(--spin)) rotateX(360deg)}}.weather{container-type:size}[data-motion=off] .fall{animation:none;transform:translateY(var(--static-y))}[data-motion=off] .sway,[data-motion=off] .flutter{animation:none}[data-motion=off] .fall:nth-of-type(n+9){display:none}@media(prefers-reduced-motion:reduce){.fall{animation:none;transform:translateY(var(--static-y))}.sway,.flutter{animation:none}.fall:nth-of-type(n+9){display:none}}
</style>
