<!-- SPDX-FileCopyrightText: Tolehata and hatasaba-project
SPDX-License-Identifier: AGPL-3.0-only -->
<template><div v-if="visible" class="outer" :class="{ leaving }" :data-motion="animations ? 'on' : 'off'"><div class="clip"><section class="card" :aria-label="copy.title"><img src="/client-assets/hatakyu/watering-flower.png" alt=""/><div class="body"><small>NEW</small><h3>{{ copy.introTitle }}</h3><ol><li><span>1</span><span>{{ copy.introStepOne }}</span></li><li><span>2</span><span>{{ copy.introStepTwo }}</span></li><li><span>3</span><span>{{ copy.introStepThree }}</span></li></ol><button type="button" @click="dismiss">{{ copy.start }}<i class="ti ti-arrow-right" aria-hidden="true"></i></button></div></section></div></div></template>
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';
import { i18n } from '@/i18n.js';
const copy = i18n.ts._hata._hatask._flowerIntro;
const props = withDefaults(defineProps<{ animations?: boolean }>(), { animations: true });
const emit = defineEmits<{ dismiss: [] }>();
const visible = ref(true); const leaving = ref(false); let timer: ReturnType<typeof setTimeout> | undefined;
function dismiss() { if (leaving.value) return; const reduce = !props.animations || window.matchMedia('(prefers-reduced-motion: reduce)').matches; if (reduce) { visible.value = false; emit('dismiss'); return; } leaving.value = true; timer = setTimeout(() => { visible.value = false; emit('dismiss'); }, 440); }
onBeforeUnmount(() => { if (timer) clearTimeout(timer); });
</script>
<style scoped>
.outer{container-type:inline-size;display:grid;grid-template-rows:1fr;margin-bottom:0;opacity:1;transform:scaleY(1);transform-origin:50% 0;transition:grid-template-rows .42s cubic-bezier(.4,0,.2,1),margin-bottom .42s cubic-bezier(.4,0,.2,1),opacity .28s ease,transform .42s cubic-bezier(.4,0,.2,1)}.outer.leaving{grid-template-rows:0fr;margin-bottom:-18px;opacity:0;transform:scaleY(.96)}.clip{min-height:0;overflow:hidden;padding:0 2px 24px;margin:0 -2px -24px}.card{position:relative;display:grid;grid-template-columns:120px minmax(0,1fr);gap:8px 18px;align-items:center;min-width:0;padding:18px 20px;border:1px solid var(--rule);border-radius:24px;box-shadow:var(--shadow);background:var(--masthead);color:var(--fg);font-family:var(--htk-font-body,inherit)}img{width:120px;height:120px;object-fit:contain;justify-self:center}.body{min-width:0}.body small{color:var(--accent-ink);font-size:11px;font-weight:800;letter-spacing:.1em}h3{margin:2px 0 6px;font:700 18px var(--htk-font-head,inherit);overflow-wrap:anywhere}ol{display:grid;gap:6px;margin:0 0 12px;padding:0;list-style:none;font-size:13px}li{display:flex;align-items:flex-start;gap:10px;min-width:0;line-height:1.5;overflow-wrap:anywhere}li>span:first-child{flex:0 0 22px;height:22px;display:grid;place-items:center;border-radius:50%;background:var(--fill-2);color:var(--accent-ink);font:800 12px 'Archivo',sans-serif}.body button{display:inline-flex;align-items:center;gap:8px;min-height:46px;padding:8px 20px;border:0;border-radius:999px;background:var(--accent);color:var(--on-accent);font:800 15px var(--htk-font-body,inherit);box-shadow:var(--shadow);cursor:pointer}.body button i{font-size:18px}@container(max-width:450px){.card{grid-template-columns:minmax(0,1fr);padding:16px}.card img{width:94px;height:94px}.body{text-align:left}}@media(prefers-reduced-motion:reduce){.outer{transition:none}}
</style>
