<!-- SPDX-FileCopyrightText: Tolehata and hatasaba-project
SPDX-License-Identifier: AGPL-3.0-only -->
<template>
	<div class="watering">
		<div class="can">
			<div class="heading"><strong>じょうろ</strong><button type="button" aria-label="育て方" title="育て方" :aria-expanded="infoOpen" @click="infoOpen = !infoOpen"><i class="ti ti-info-circle" aria-hidden="true"></i></button></div>
			<div class="controls" :aria-label="`しずく ${drops}こ`"><span class="drop"><i class="ti ti-droplet-filled" aria-hidden="true"></i></span><span class="count">{{ drops }}</span><span class="store">/{{ store }}</span><button class="pour" type="button" :disabled="busy || drops <= 0 || (target === 'self' && bloomed)" @click="emit('pour')"><i class="ti ti-droplet" aria-hidden="true"></i><span>{{ target === 'self' && bloomed ? '咲いています' : drops <= 0 ? 'しずくがありません' : target === 'festival' ? '花壇に注ぐ' : '水をあげる' }}</span></button></div>
		</div>
		<div v-if="festivalAvailable" class="targets" role="group" aria-label="注ぎ先"><button type="button" :aria-pressed="target === 'self'" @click="emit('update:modelValue', 'self')"><i class="ti ti-plant-2" aria-hidden="true"></i>自分のお花</button><button type="button" :aria-pressed="target === 'festival'" @click="emit('update:modelValue', 'festival')"><i class="ti ti-users" aria-hidden="true"></i>みんなの花壇</button></div>
		<div v-if="infoOpen" class="info" role="note"><ul><li><i class="ti ti-heart" aria-hidden="true"></i>あげなくても時間で育ち、枯れません</li><li><i class="ti ti-droplet" aria-hidden="true"></i>1しずく=約{{ pourDuration }}はやく咲く</li><li v-if="festivalAvailable"><i class="ti ti-users" aria-hidden="true"></i>花壇に注いだ分は花まつりの合計に</li></ul><button type="button" aria-label="閉じる" title="閉じる" @click="infoOpen = false"><i class="ti ti-x" aria-hidden="true"></i></button></div>
	</div>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue';
const props = withDefaults(defineProps<{ drops: number; store?: number; pourMinutes?: number; bloomed?: boolean; busy?: boolean; festivalAvailable?: boolean; modelValue?: 'self' | 'festival'; animations?: boolean }>(), { store: 20, pourMinutes: 120, modelValue: 'self', bloomed: false, busy: false, festivalAvailable: true, animations: true });
const emit = defineEmits<{ 'update:modelValue': [value: 'self' | 'festival']; pour: [] }>();
const infoOpen = ref(false);
const target = computed(() => props.festivalAvailable ? props.modelValue : 'self');
const pourDuration = computed(() => { const minutes = Math.max(0, Math.ceil(props.pourMinutes)); return minutes < 60 ? `${minutes}分` : `${Math.floor(minutes / 60)}時間${minutes % 60 ? `${minutes % 60}分` : ''}`; });
</script>
<style scoped>
.watering{container-type:inline-size;display:flex;align-items:center;gap:14px;flex-wrap:wrap;min-width:0;font-family:var(--htk-font-body,inherit);color:var(--fg)}.can{flex:1 1 220px;min-width:0}.heading{display:flex;align-items:center;gap:4px}.heading strong{font-family:var(--htk-font-head,inherit);font-size:15px}.heading button{width:32px;height:32px;display:grid;place-items:center;border:0;border-radius:50%;background:none;color:var(--fg-2);cursor:pointer}.heading i{font-size:18px}.controls{display:flex;align-items:center;gap:clamp(4px,2vw,10px);margin-top:4px;min-width:0}.drop{flex:none;width:40px;height:40px;display:grid;place-items:center;border-radius:50%;background:color-mix(in srgb,#4a8fd6 16%,var(--surface));color:#4a8fd6;box-shadow:inset 0 0 0 1px color-mix(in srgb,#4a8fd6 40%,transparent)}.drop i{font-size:21px}.count,.store{font-family:'Archivo',sans-serif;font-variant-numeric:tabular-nums}.count{font-size:26px;font-weight:800;line-height:1}.store{margin-left:-6px;color:var(--fg-2);font-size:15px;font-weight:700}.pour{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-width:0;min-height:44px;margin-left:6px;padding:8px clamp(10px,3vw,18px);border:0;border-radius:999px;background:var(--accent);color:var(--on-accent);font:800 14px/1.3 var(--htk-font-body,inherit);white-space:nowrap;box-shadow:var(--shadow);cursor:pointer}.pour i{flex:none;font-size:18px}.pour:disabled{opacity:.55;cursor:default}.targets{display:flex;gap:4px;padding:4px;border-radius:999px;background:color-mix(in srgb,var(--fg) 7%,transparent)}.targets button{display:flex;align-items:center;justify-content:center;gap:6px;min-height:38px;padding:0 14px;border:0;border-radius:999px;background:transparent;color:var(--fg-2);font:800 13px var(--htk-font-body,inherit);white-space:nowrap;cursor:pointer}.targets button[aria-pressed=true]{background:var(--masthead);color:var(--fg)}.targets i{font-size:16px}.info{position:relative;flex-basis:100%;padding:10px 40px 10px 12px;border:1px solid var(--rule);border-radius:14px;background:var(--masthead);box-shadow:0 12px 32px #0002;font-size:12px;line-height:1.6}.info ul{display:grid;gap:4px;margin:0;padding:0;list-style:none}.info li{display:flex;gap:6px;overflow-wrap:anywhere}.info li i{margin-top:3px;color:var(--accent-ink)}.info>button{position:absolute;top:2px;right:2px;width:36px;height:36px;border:0;border-radius:50%;background:none;color:var(--fg-2);cursor:pointer}@container(max-width:310px){.drop{width:34px;height:34px}.count{font-size:23px}.store{font-size:13px}.controls{gap:4px}.pour{gap:4px;margin-left:2px;padding-inline:8px;font-size:12px}.store{margin-left:-2px}.targets{max-width:100%;width:100%}.targets button{flex:1;min-width:0;padding:0 5px;font-size:11px}}
</style>
