/*
 * SPDX-FileCopyrightText: Tolehata and hatasaba-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Column, Entity, Index, JoinColumn, ManyToOne, PrimaryColumn } from 'typeorm';
import { id } from './util/id.js';
import { MiUser } from './User.js';

/** Hatask の端末ローカル花ギャラリーを同期する最小のサーバー側記録。 */
@Entity('hatask_flower')
@Index('IDX_hatask_flower_user_client', ['userId', 'clientFlowerId'], { unique: true })
@Index('IDX_hatask_flower_harvested', ['harvestedAt', 'id'])
export class MiHataskFlower {
	@PrimaryColumn(id())
	public id: string;

	@Column({
		...id(),
		comment: 'The owner user ID.',
	})
	public userId: MiUser['id'];

	@ManyToOne(type => MiUser, {
		onDelete: 'CASCADE',
	})
	@JoinColumn()
	public user: MiUser | null;

	/** Stable ID generated by the owning client. Never unique across users. */
	@Column('varchar', { length: 64 })
	public clientFlowerId: string;

	@Column('varchar', { length: 32 })
	public emoji: string;

	@Column('varchar', { length: 80 })
	public name: string;

	@Column('varchar', { length: 256, default: '' })
	public hanakotoba: string;

	@Column('timestamp with time zone')
	public harvestedAt: Date;
}
