/*
 * SPDX-FileCopyrightText: tolehata
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import type { IntroCourse } from './content.js';
import { courses } from './content.js';

export type { IntroCourse } from './content.js';

export interface IntroReference {
	id: string;
	title: string;
	body: string;
	iconClass: string;
	tips: string[];
	link: string | null;
	linkLabel?: string;
	course: string;
	where: string;
	related: string[];
	source: string;
	lead: string;
	steps?: string[];
	stepsTitle?: string;
	keywords?: string[];
	help?: [string, string][];
	diagram?: {
		title: string;
		nodes: [string, string][];
		note?: string;
	};
}

export const references: IntroReference[] = [
	{
		id: 'ref-hataskOverview',
		title: 'Hataskとは',
		body: 'Hataskは、予定・ToDo・きもち・ごはん・お花をまとめて使う場所です。\n\n暁テーマでは、PCは左メニュー、スマートフォンは下部タブから移動します。ホームでは、そのときに使いたい項目を選べます。「おすすめ」に戻すと、予定や記録に応じた内容が表示されます。\n\nHatask AppとHataskey Appには、関連するアプリやツールの入口があります。',
		iconClass: 'ti ti-layout-dashboard',
		tips: ['テーマを変えても予定や記録は残ります', 'スマホの下部タブにない機能は、Hatask Appから探せます'],
		link: '/hatask',
		linkLabel: 'Hataskを開く',
		course: 'hatask',
		where: 'Hatask → ホーム。暁ではPCの左メニュー／スマホの下部タブから切り替える',
		related: ['todo', 'calendar', 'mood'],
		source: 'pages/hatask.vue · components/hatask/HataskAkatsukiLayout.vue',
		lead: '予定と毎日の記録を、一か所から開く',
	},
	{
		id: 'ref-calendarAttendance',
		title: 'カレンダー・出欠確認',
		body: '月ごとの予定を見たり、新しい予定を登録したりできます。一覧表示へ切り替え、日・週・月ごとに確認することもできます。<br><br>予定を公開して参加確認を有効にすると、ほかの利用者が「行く・検討中・辞退」で回答できます。主催者は回答状況と締め切りを確認できます。',
		iconClass: 'ti ti-calendar',
		tips: ['複数日にまたがる予定や、お知らせ時刻も設定できます', '出欠確認は、予定の公開範囲と参加確認の設定を確かめてから使います。非公開の予定では利用できません'],
		link: '/hatask?tab=cal',
		linkLabel: 'カレンダーを開く',
		course: 'hatask',
		where: 'Hatask → カレンダー → 日付または予定を選ぶ',
		related: ['calendar'],
		source: 'components/hatask/HataskCalendarPlanner.vue · pages/hatask.vue',
		diagram: {
			title: '予定を作る・読む・出欠を確かめる',
			nodes: [
				['何もない日付を選ぶ', '新しい予定を作るか、既存の予定をコピー・移動するかを選ぶ'],
				['予定を選ぶ', 'PCでは日付付近の吹き出し、スマホではモーダルで詳細を読む'],
				['公開する予定だけ、参加確認を使う', '公開範囲と参加確認の設定、受付中か締め切り済みかを確かめる'],
			],
		},
		lead: '月ごとの予定を見たり、新しい予定を登録したりできます',
	},
	{
		id: 'ref-todoList',
		title: 'やることリスト',
		body: 'ToDoは、やることを追加して、終わった項目を完了にするリストです。期限・フォルダー・優先度を設定して整理できます。\n\n繰り返す用事や、いくつかの作業に分かれる用事には、繰り返し設定やサブタスクを使います。作成日・期限などの並び順を選ぶと、次に取り組む項目を探しやすくなります。',
		iconClass: 'ti ti-checkbox',
		tips: ['期限を過ぎた項目は赤く表示されます', '操作場所は、下の「やることを整理する」の図で確認できます'],
		link: '/hatask?tab=todo',
		linkLabel: 'やることリストを開く',
		course: 'hatask',
		where: 'Hatask → ToDo',
		related: ['todo'],
		source: 'components/hatask/HataskTodoPlanner.vue · pages/hatask.vue',
		lead: 'ToDoは、やることを追加して、終わった項目を完了にするリストです',
	},
	{
		id: 'ref-moodLog',
		title: 'きもち記録',
		body: 'その日の気分を5段階で記録し、最近の傾向を振り返れます。過去7日間の平均や、記録した時間帯ごとの傾向も確認できます。',
		iconClass: 'ti ti-mood-smile',
		tips: ['過去の記録はあとから編集・削除できます', '記録を促すお知らせも設定できます'],
		link: '/hatask?tab=mood',
		linkLabel: 'きもち記録を開く',
		course: 'hatask',
		where: 'Hatask → きもち → 記録・履歴・振り返り',
		related: ['mood'],
		source: 'components/hatask/HataskJournal.vue',
		lead: 'その日の気分を5段階で記録し、最近の傾向を振り返れます',
	},
	{
		id: 'ref-mealLog',
		title: 'ごはん記録',
		body: '朝・昼・夜・間食について「食べられた・少しだけ・食べられなかった」から選び、必要なら理由や短いメモを残せます。<br><br>量やカロリーを計算したり、結果に点数を付けたりはしません。どの状態も責めず、穏やかに振り返るための機能です。',
		iconClass: 'ti ti-bowl',
		tips: ['体調の不安が続くときは医療機関へご相談ください', 'タイトル付近の丸囲み i ボタンから説明を読み返せます'],
		link: '/hatask?tab=meal',
		linkLabel: 'ごはん記録を開く',
		course: 'hatask',
		where: 'Hatask → ごはん',
		related: ['mood'],
		source: 'components/hatask/HataskJournal.vue · pages/hatask.vue',
		steps: ['朝・昼・夜・間食から、記録したい食事を選ぶ', '「食べられた・少しだけ・食べられなかった」から、そのときの状態を選ぶ', '必要なら理由やメモを添えて記録する。履歴から編集・削除もできる'],
		diagram: {
			title: '記録するのは、そのときの様子',
			nodes: [
				['どの食事？', '朝・昼・夜・間食'],
				['どんな状態？', '食べられた・少しだけ・食べられなかった'],
				['残したいことは？', '必要なときだけ、理由や短いメモを添える'],
			],
			note: '状態に優劣を付けたり、カロリーを計算したりする図ではありません',
		},
		help: [
			['記録を間違えたら？', '履歴から該当する記録を開き、編集または削除できます'],
		],
		lead: '朝・昼・夜・間食について「食べられた・少しだけ・食べられなかった」から選び、必要なら理由や短いメモを残せます',
	},
	{
		id: 'ref-garden',
		title: 'お花を育てる・咲いた花を見る',
		body: 'Hataskeyを使っている時間に応じて、お花が少しずつ育ちます。咲いた花には名前を付けられ、これまでのお花の一覧に加わります。<br><br>ホームのウィジェットでも、育成中の花の進み具合と咲いた花をコンパクトに確認できます。',
		iconClass: 'ti ti-plant',
		tips: ['公開範囲は「公開・フォロワー・非公開」から選べます。初期設定は公開です', '育て終えた花の名前はあとから変更できます'],
		link: '/hatask?tab=garden',
		linkLabel: 'お庭を開く',
		course: 'hatask',
		where: 'Hatask → おはな',
		related: [],
		source: 'pages/hatask.vue',
		steps: ['「おはな」を開き、育成中の花の進み具合を見る', '公開範囲を確認する。初期設定は「公開」なので、自分だけに残したいときは「非公開」を選ぶ', '花が咲いたら名前を付ける。あとから名前を変更することもできる', '自分のお花の一覧と、みんなのお花の一覧を切り替えて見る'],
		diagram: {
			title: '育成から、お花の一覧へ',
			nodes: [
				['使っている時間に少しずつ育つ', '今の進み具合を確認する'],
				['咲いた花に名前を付ける', '名前はあとから変更できる'],
				['自分のお花に残る', 'みんなに見せるかどうかは公開範囲で選ぶ'],
			],
		},
		help: [
			['並び順の N・O は何？', '暁の「みんなのお花」では、Nは新しい順、Oは古い順を表します'],
		],
		lead: 'Hataskeyを使っている時間に応じて、お花が少しずつ育ちます',
	},
	{
		id: 'ref-hataskEye',
		title: 'ホームのひとこと（Hatask Eye）',
		body: 'Hataskのホームに、タスクや予定、きもちの記録に合わせたひとことメッセージを表示します。',
		iconClass: 'ti ti-eye',
		tips: ['EYEという独立タブはありません。ホームのひとこと表示の説明です'],
		link: '/hatask?tab=home',
		linkLabel: 'Hataskのホームを開く',
		course: 'hatask',
		where: 'Hatask → ホーム',
		related: ['todo', 'calendar', 'mood'],
		source: 'pages/hatask.vue · components/hatask/HataskAkatsukiLayout.vue',
		lead: 'Hataskのホームに、タスクや予定、きもちの記録に合わせたひとことメッセージを表示します',
	},
	{
		id: 'ref-hataskAppearance',
		title: 'Hataskのテーマを変える',
		body: 'Hataskには「暁・季・花信・刷・ハタキュ」の5つのテーマがあります。見た目を変えても予定・ToDo・きもちなどの記録は残ります。\n\nHataskのテーマはレイアウトや装飾を選ぶ設定です。Hataskey全体のライト・ダークなどの配色は、別のテーマ設定から変更します。暁の背景も本体のテーマカラーに合わせて表示されます。',
		iconClass: 'ti ti-palette',
		tips: ['本体全体の配色を変えたいときは、下のテーマの操作ガイドへ'],
		link: '/hatask',
		linkLabel: 'Hataskを開く',
		course: 'hatask',
		where: 'Hatask → 歯車 → テーマ',
		related: ['theme'],
		source: 'pages/HataskSettings.vue · utility/hatask-daylight.ts',
		lead: 'Hataskの見た目と、本体全体の配色を分けて選ぶ',
		steps: ['Hataskの歯車から設定を開く', 'テーマの候補を見比べ、使いたいものを選ぶ。選択時に保存される', 'Hataskへ戻り、予定や記録と合わせて表示を確かめる'],
	},
	{
		id: 'ref-hatadyOverview',
		title: 'Hatadyとは',
		body: '勉強や読書、映画の鑑賞、ゲームのプレイを自分のペースで記録する場所です。「マイログ」「みんなの活動」「コレクション」から、記録を残したり公開された活動を読んだり、本・映画・ゲームを整理したりできます。',
		iconClass: 'ti ti-book-2',
		tips: ['記録ごとに公開する相手を選べます', '自分だけの記録としても使えます'],
		link: '/hatady',
		linkLabel: 'Hatadyを開く',
		course: 'apps',
		where: 'Hatady → マイログ・みんなの活動・コレクション',
		related: ['hatady'],
		source: 'pages/hatady.vue',
		lead: '学び・映画・ゲームの記録を、ひとつの流れで振り返る',
		diagram: {
			title: '種類が違っても、活動の流れはひとつに',
			nodes: [
				['学んだこと・観た映画・遊んだゲームを記録', '記録ごとに公開する相手を選ぶ'],
				['マイログで自分の活動を読む', '種類を切り替えて絞り込むこともできる'],
				['みんなの活動・コレクションへ', '公開された活動や、気になる本・作品も探せる'],
			],
		},
	},
	{
		id: 'ref-studyAndBookshelf',
		title: '学習記録と本棚',
		body: '学習の記録には、題材・分野・かかった時間・短いメモを残せます。読書ではページ数や進み具合も記録できます。\n\n本棚は「読書中・読み終えた・積読・読みたい」に分けて整理します。本の詳細で状態を選び、進捗やメモを変更したら保存します。',
		iconClass: 'ti ti-notebook',
		tips: ['記録はあとから編集できます'],
		link: null,
		course: 'apps',
		where: 'Hatady → コレクション → 本 → 本の詳細',
		related: ['hatady'],
		source: 'pages/hatady.vue · components/HatadyBookDetail.vue',
		lead: '学習の記録には、題材・分野・かかった時間・短いメモを残せます',
	},
	{
		id: 'ref-bookmarksNotesMaterials',
		title: 'しおり・メモ・学習題材',
		body: '本の気になったページにしおりとメモを残せます。学習題材を登録すると、同じ題材の記録をあとから探しやすくなります。',
		iconClass: 'ti ti-bookmark',
		tips: [],
		link: null,
		course: 'apps',
		where: '本のしおり：Hatady → コレクション → 本 → 本の詳細。学習の題材：活動を記録 → 学習',
		related: ['hatady'],
		source: 'components/HatadyBookDetail.vue · components/HatadyComposer.vue · pages/hatady.vue',
		lead: '本の気になったページにしおりとメモを残せます',
	},
	{
		id: 'ref-goalsReview',
		title: '目標と振り返り',
		body: '学習時間、記録数、読んだ本の数、続けた日数をまとめて確認できます。日ごとの活動や科目ごとの時間も見られるため、無理のない目標づくりに使えます。',
		iconClass: 'ti ti-chart-line',
		tips: ['続けた日数は競争ではなく振り返りの目安です'],
		link: null,
		course: 'apps',
		where: 'Hatady → 目標',
		related: ['hatady'],
		source: 'components/HatadyGoals.vue · pages/hatady.vue',
		steps: ['「目標」から新しい目標を作る', '短期・長期、期限、達成の判定方法を選ぶ。手動・学習時間・記録数・読了数が使える', '内容を確認して作成する。記録がたまったら、統計や目標の進み具合を振り返る'],
		lead: '学習時間、記録数、読んだ本の数、続けた日数をまとめて確認できます',
	},
	{
		id: 'ref-publicStudy',
		title: 'みんなの活動',
		body: '公開された学習・映画鑑賞・ゲームプレイの記録を、新しい順・注目順・フォロー中に分けて読めます。気になる活動や作品を見つけたら、リアクションで気持ちを伝えられます。\n\n返信する機能もありますが、読むだけ・反応するだけの使い方でも大丈夫です。',
		iconClass: 'ti ti-users',
		tips: ['非公開の活動はほかの人に表示されません'],
		link: null,
		course: 'apps',
		where: 'Hatady → みんなの活動',
		related: ['hatady'],
		source: 'pages/hatady.vue',
		lead: '公開された学習・映画鑑賞・ゲームプレイの記録を、新しい順・注目順・フォロー中に分けて読めます',
	},
	{
		id: 'ref-hatadySettings',
		title: '見た目・表示言語・書き出し',
		body: 'Hatadyは3種類の見た目を選べます。歯車から見た目の設定を開き、変更後に保存します。表示言語はHataskey本体の設定に従います。\n\n記録を書き出すときは、対象・期間・形式を選びます。学習はTXT、映画・ゲームはJSONまたはTXTで手元へ保存できます。',
		iconClass: 'ti ti-settings',
		tips: [],
		link: '/hatady',
		linkLabel: 'Hatadyを開く',
		course: 'apps',
		where: 'Hatady → 右上の歯車／書き出し',
		related: ['hatady'],
		source: 'components/HatadyDisplaySettings.vue · components/HatadyExportDialog.vue',
		lead: 'Hatadyは3種類の見た目を選べます',
	},
	{
		id: 'ref-externalOverview',
		title: '外部アカウント連携とは',
		body: '設定に表示される対応サーバーのアカウントを連携すると、接続先の投稿を読んだり、投稿・リアクションなどの操作をしたりできます。連携先のアカウントで行う操作なので、投稿する先を確認して使います。\n\n連携時は、接続先の確認画面で許可する内容を確かめてください。接続先の利用規約も事前に確認します。',
		iconClass: 'ti ti-link',
		tips: ['連携しない場合は、この設定を有効にする必要はありません', '以前の連携先が設定の候補にない場合は、現在の対応サーバーを確認してください'],
		link: '/settings/external-account',
		linkLabel: '連携設定を開く',
		course: 'external',
		where: '設定 → 外部アカウント連携',
		related: ['timeline'],
		source: 'pages/settings/external-account.vue · utility/external-api.ts',
		lead: '別のアカウントをつなぐ前に、許可する操作を確認する',
		steps: ['設定の「外部アカウント連携」を開き、案内を読んで有効にする', '接続先を選んで連携へ進む。接続先の画面で、許可する内容を確認する', 'Hataskeyの設定へ戻ったら、表示されたサーバー名とアカウントを確認する', '外部ホーム・外部ローカルのうち、表示したいタイムラインを選ぶ'],
		diagram: {
			title: '連携する場所と、ノートを読む場所',
			nodes: [
				['Hataskeyの設定', '接続先を選び、連携を始める'],
				['接続先の確認画面', 'どのアカウントの、どの操作を許可するか確かめる'],
				['Hataskeyに戻る', '連携済みのアカウントと、表示するタイムラインを確認する'],
			],
			note: 'この図ではログイン・認証・連携を行いません',
		},
		help: [
			['連携の設定が終わったのにタブがない', '連携済みの表示に加え、外部ホーム・外部ローカルそれぞれの表示設定を確認してください'],
		],
	},
	{
		id: 'ref-externalPosts',
		title: '外部の投稿を見る',
		body: '外部ホームは、連携先のアカウントがフォローしている人の投稿を読む場所です。外部ローカルは、連携先サーバーの公開投稿を読む場所です。\n\nHataskey UIでは、外部用の家・惑星のアイコンから切り替えます。連携が有効で、各タイムラインの表示設定をオンにしている場合だけ追加されます。',
		iconClass: 'ti ti-device-tv',
		tips: ['表示する項目は連携設定で個別に切り替えられます'],
		link: '/settings/external-account',
		linkLabel: '連携設定を開く',
		course: 'external',
		where: '設定 → 外部アカウント連携 → タイムラインの表示設定。読むときはHataskey UIの上部バー',
		related: ['timeline'],
		source: 'pages/settings/external-account.vue · ui/simple.vue',
		lead: '外部ホームは、連携先のアカウントがフォローしている人の投稿を読む場所です',
	},
	{
		id: 'ref-favoriteReactionEmoji',
		title: 'お気に入りのリアクション絵文字',
		body: '外部の投稿でよく使う絵文字をお気に入りへ入れると、絵文字を選ぶ画面の先頭からすぐ使えます。',
		iconClass: 'ti ti-star',
		tips: ['本体側の絵文字リアクションと、外部アカウント用のお気に入りは別に管理します'],
		link: '/settings/external-account',
		linkLabel: 'お気に入り絵文字を管理',
		course: 'external',
		where: '設定 → 外部アカウント連携 → お気に入り絵文字',
		related: ['reaction'],
		source: 'pages/settings/external-account.vue · components/MkExternalReactionPicker.vue',
		lead: '外部の投稿でよく使う絵文字をお気に入りへ入れると、絵文字を選ぶ画面の先頭からすぐ使えます',
	},
	{
		id: 'ref-externalNotifications',
		title: '外部アカウントの通知',
		body: '連携先で届いた通知をHataskeyでも受け取れます。新しい通知は画面の端に表示され、専用ページでまとめて確認できます。',
		iconClass: 'ti ti-bell-ringing',
		tips: ['外部アカウントを利用していない人には、外部通知を使う必要はありません', '通知ポップアップを無効にすると、新着通知の接続とバッジの更新も止まります'],
		link: '/my/external-notifications',
		linkLabel: '外部通知を開く',
		course: 'external',
		where: '連携済みの場合：外部通知のページ。受け取り方は設定 → 外部アカウント連携',
		related: ['timeline'],
		source: 'pages/settings/external-account.vue · navbar.ts · utility/external-notification-stream.ts',
		help: [
			['外部通知の入口が見つからない', '外部連携が有効か、連携済みアカウントがあるかを設定で確認してください'],
		],
		lead: '連携先で届いた通知をHataskeyでも受け取れます',
	},
	{
		id: 'ref-languageSupport',
		title: 'Hataskey独自機能の表示言語',
		body: 'Hataskey独自機能は、日本語に加えて英語と中国語（簡体字）で表示できます。Hatadyを含む対応機能は、Hataskey本体の表示言語に従ってまとめて切り替わります。<br><br>自分で入力した投稿・記録・名前は自動翻訳されません。地震・津波情報は、引き続き日本語のみです。',
		iconClass: 'ti ti-language',
		tips: ['設定の「UIの表示言語」から変更できます', '言語を変えてもHatadyの記録や各ツールの設定はそのまま引き継がれます'],
		link: '/settings/preferences',
		linkLabel: '言語設定を開く',
		course: 'settings',
		where: '設定 → UIの表示言語',
		related: ['layout'],
		source: 'pages/settings-redesign/settings-preferences-catalog.ts · pages/settings/preferences.vue',
		lead: 'Hataskey独自機能は、日本語に加えて英語と中国語（簡体字）で表示できます',
	},
	{
		id: 'ref-chooseUi',
		title: '画面の種類を選ぶ',
		body: '標準の画面、Hataskey UI、複数の列を並べるデッキ画面から選べます。Hataskey UIはスマートフォンでも操作しやすい構成です。',
		iconClass: 'ti ti-device-mobile',
		tips: ['通常表示とデッキ表示の切り替えは、下のデッキの図で確認できます'],
		link: '/settings/hata-custom',
		linkLabel: '画面の設定を開く',
		course: 'settings',
		where: 'Hataskey UIでは左サイドメニュー左下のUI切り替え。画面全体の種類は設定から選べる',
		related: ['layout', 'deck'],
		source: 'ui/simple.vue · pages/settings/hata-custom.vue',
		lead: '標準の画面、Hataskey UI、複数の列を並べるデッキ画面から選べます',
	},
	{
		id: 'ref-hatasabaUi',
		title: 'Hataskey UI',
		body: 'Hataskey UIは、投稿を見ることを中心にした画面です。上部の項目や左右スワイプで、ホーム・ローカル・グローバルなどを切り替えられます。スワイプで切り替えたくない場合は設定で止められます。<br><br>Hataskey UI 2の見た目もこの画面に統合されており、カードをすりガラス風にするか、透け具合をどの程度にするかを選べます。通常表示とデッキ表示の両方に反映されます。',
		iconClass: 'ti ti-layout-list',
		tips: ['ナビ・ガラスとぼかし・ノート・デッキ・サイドメニュー・折りたたみ端末を、設定内で切り替えて調整できます', '設定は独立した小窓ではなく、設定画面に統合されています'],
		link: '/settings/hata-custom',
		linkLabel: 'Hataskey UIの設定を開く',
		course: 'settings',
		where: '設定 → Hataskey UI',
		related: ['layout', 'timeline'],
		source: 'pages/settings-redesign/HatasabaUi2SettingsSurface.vue · components/HatasabaUi2SettingsBody.vue',
		lead: 'Hataskey UIは、投稿を見ることを中心にした画面です',
	},
	{
		id: 'ref-deck',
		title: 'Hataskey UIのデッキ表示',
		body: 'パソコンでは、ホーム、ローカル、通知、リスト、チャンネル、クリップ、お気に入りなどを複数の列に並べられます。列ごとに内容を更新でき、チャンネルの列からそのチャンネルへ直接投稿できます。',
		iconClass: 'ti ti-columns',
		tips: ['投稿一覧が広がりすぎないよう、列の中だけで表示します'],
		link: null,
		course: 'timeline',
		where: 'PCのHataskey UI → 左サイドメニュー左下 → デッキ表示',
		related: ['deck'],
		source: 'ui/simple.vue',
		lead: 'パソコンでは、ホーム、ローカル、通知、リスト、チャンネル、クリップ、お気に入りなどを複数の列に並べられます',
	},
	{
		id: 'ref-noteAnimation',
		title: '新しい投稿が現れる動き',
		body: '新しい投稿が表示される方向を、上・左・右・毎回ランダムから選べます。動きが気になる場合は、端末の「視差効果を減らす」設定も利用できます。',
		iconClass: 'ti ti-movie',
		tips: [],
		link: '/settings',
		linkLabel: '設定を開く',
		course: 'timeline',
		where: '設定の検索で「新規ノートのアニメーション方向」を探す',
		related: ['timeline', 'layout'],
		source: 'pages/settings/hata-custom.vue · pages/settings-redesign/index.vue',
		lead: '新しい投稿が表示される方向を、上・左・右・毎回ランダムから選べます',
	},
	{
		id: 'ref-hideReactionEmoji',
		title: 'リアクション絵文字の非表示',
		body: '見たくないリアクション絵文字を個別に隠せます。パソコンでは絵文字を右クリック、スマートフォンでは投稿の「…」メニューから設定できます。ミュートした人が付けたリアクションをまとめて隠すこともできます。',
		iconClass: 'ti ti-eye-off',
		tips: ['ミュートした人のリアクションを隠す設定は、この端末だけに適用されます', '管理者のリアクションなど、非表示にならない場合もあります'],
		link: '/settings/hidden-reactions',
		linkLabel: '表示を管理する',
		course: 'notes',
		where: 'ノートのリアクションを右クリック／スマホではノートの「…」。管理は設定 → 非表示のリアクション',
		related: ['reaction'],
		source: 'pages/settings/hidden-reactions-manage.vue · pages/settings/hata-custom.vue',
		lead: '見たくないリアクション絵文字を個別に隠せます',
	},
	{
		id: 'ref-hideBotPosts',
		title: 'Bot投稿の非表示',
		body: '自動投稿を行うBotアカウントの投稿を、タイムラインから隠せます。表示を許可する例外も選べますが、候補にはBotアカウントだけが表示され、通常アカウントは追加できません。<br><br>通常の人がBotの投稿をリノートした場合も隠し、Botが通常の人の投稿をリノートした場合は元の投稿を表示します。',
		iconClass: 'ti ti-robot',
		tips: ['通知画面や投稿単体の画面では隠しません'],
		link: '/settings',
		linkLabel: '設定を開く',
		course: 'timeline',
		where: '設定の検索で「Bot 投稿の非表示」を探す',
		related: ['quiet'],
		source: 'pages/settings/hata-custom.vue · pages/settings-redesign/index.vue',
		lead: '自動投稿を行うBotアカウントの投稿を、タイムラインから隠せます',
	},
	{
		id: 'ref-weatherBackground',
		title: '天気の背景演出',
		body: '投稿に雨・雪・晴れ・風・夜のあいさつなどの言葉があると、背景に控えめな演出を表示できます。雨粒、日差し、葉、流れ星などが画面に現れます。<br><br>強い点滅や雷のような演出は使いません。初期状態では無効で、動きが苦手な場合はいつでも止められます。',
		iconClass: 'ti ti-cloud-rain',
		tips: ['演出を表示する長さも選べます', '体調に違和感があればすぐに無効にしてください'],
		link: '/settings',
		linkLabel: '設定を開く',
		course: 'timeline',
		where: '設定の検索で「天気エフェクト」を探す',
		related: ['timeline'],
		source: 'pages/settings/hata-custom.vue · pages/settings-redesign/index.vue',
		lead: '投稿に雨・雪・晴れ・風・夜のあいさつなどの言葉があると、背景に控えめな演出を表示できます',
	},
	{
		id: 'ref-drawingTool',
		title: 'Hatadint',
		body: 'Hataskeyの画面内で絵を描けます。線の太さ・色・透明さを変え、複数の層に分けて描いたり、直前の操作を取り消したりできます。スマートフォンの指操作にも対応しています。',
		iconClass: 'ti ti-brush',
		tips: ['端末に保存する操作と、ドライブに保存・投稿に添付する操作は別です', 'ドライブ保存や投稿添付では、初回の同意確認があります。添付しただけではノートは投稿されません'],
		link: null,
		course: 'apps',
		where: '投稿フォームのHatadintボタン、またはHataskey App → Hatadint',
		related: ['draw'],
		source: 'components/MkDrawingTool.vue · components/MkPostForm.vue',
		lead: 'Hataskeyの画面内で絵を描けます',
	},
	{
		id: 'ref-hataCardMaker',
		title: 'HataCardMaker',
		body: '自分のプロフィールから、デジタル通行証カードを作れます。アクセント色やデザインを選び、完成したPNG画像を端末へ保存できます。\n\nゴールドのデザインは、アカウント作成から365日が経過すると利用できます。名前やアイコンは本体のプロフィール設定から変更します。',
		iconClass: 'ti ti-id',
		tips: ['保存したカード画像に、見せたくないプロフィール情報が含まれていないか確認してください'],
		link: '/hatask/card-maker',
		linkLabel: 'カードメーカーを開く',
		course: 'apps',
		where: 'Hatask → Hataskey App',
		related: ['card'],
		source: 'utility/hata-card-maker.ts · pages/hata-card-maker.vue',
		lead: '自分のプロフィールから、デジタル通行証カードを作れます',
	},
	{
		id: 'ref-hatalyze',
		title: 'HATAlyze',
		body: 'Hataskey内で、選んだ範囲の自分の投稿を端末内で集計し、言葉や利用傾向を振り返る機能です。履歴には集計結果・条件・分析版だけを保存し、投稿本文は保存しません。医療・診断目的ではありません。',
		iconClass: 'ti ti-mood-search',
		tips: ['履歴から2つの集計結果を比較できます', '取得した投稿を分析結果以外の目的で保存しません'],
		link: '/hatask/emotion-analysis',
		linkLabel: 'HATAlyzeを開く',
		course: 'apps',
		where: 'Hatask → Hataskey App → HATAlyze',
		related: ['analyze'],
		source: 'pages/hata-emotion-analysis.vue',
		lead: 'Hataskey内で、選んだ範囲の自分の投稿を端末内で集計し、言葉や利用傾向を振り返る機能です',
	},
	{
		id: 'ref-drawingButton',
		title: '投稿フォームのHatadintボタン',
		body: '投稿を書く画面からHatadintを開き、描いた絵をそのまま添付できます。ボタンが不要な場合はHataskey独自設定で隠せます。',
		iconClass: 'ti ti-brush',
		tips: [],
		link: '/settings',
		linkLabel: '設定を開く',
		course: 'post',
		where: '設定の検索で「Hatadintボタンを表示」を探す',
		related: ['composer', 'draw'],
		source: 'pages/settings/hata-custom.vue · components/MkPostForm.vue · pages/settings-redesign/index.vue',
		lead: '投稿を書く画面からHatadintを開き、描いた絵をそのまま添付できます',
	},
	{
		id: 'ref-visibilityBorder',
		title: '投稿範囲ごとの枠色',
		body: '公開、ホーム、フォロワー、ダイレクトのどこへ投稿するかに応じて、投稿フォームの枠色を変えられます。投稿先の選び間違いに気づきやすくするための機能で、色は自分で選べます。',
		iconClass: 'ti ti-palette',
		tips: ['枠色は確認の補助です。誰が読めるかは、投稿フォームの公開範囲の文字とアイコンで確認してください'],
		link: '/settings',
		linkLabel: '設定を開く',
		course: 'post',
		where: '設定の検索で「投稿フォームの枠色」を探す',
		related: ['visibility', 'composer'],
		source: 'pages/settings/hata-custom.vue · components/MkPostForm.vue · pages/settings-redesign/index.vue',
		lead: '公開、ホーム、フォロワー、ダイレクトのどこへ投稿するかに応じて、投稿フォームの枠色を変えられます',
	},
	{
		id: 'ref-privateChannel',
		title: 'プライベートチャンネル',
		body: '招待されたメンバーだけが内容を見られるチャンネルです。作成者と副管理者はメンバーを追加・除外でき、本人にも通知されます。あいことばで参加する方法もあります。\n\nチャンネル外へのリノートや引用はできません。一度プライベートにしたチャンネルは、公開へ戻せません。',
		iconClass: 'ti ti-lock',
		tips: ['作成には管理者から付与された権限が必要です', '参加していない人には投稿内容を表示しません'],
		link: '/channels',
		linkLabel: 'チャンネルを開く',
		course: 'timeline',
		where: 'チャンネル → 作成・編集 → プライベート。作成には権限が必要',
		related: ['channels'],
		source: 'pages/channel-editor.vue · pages/channel.vue',
		lead: 'メンバーだけで読む場所。公開へ戻せない点を先に確認する',
		diagram: {
			title: '見える相手と、外へ出せる操作',
			nodes: [
				['メンバーが参加する', '招待やあいことばで参加した人が読む'],
				['チャンネル内でやり取りする', '参加していない人には内容を表示しない'],
				['外部へのリノート・引用はできない', 'プライベートから公開への変更もできない'],
			],
			note: '閲覧した人によるコピーや撮影まで防ぐ仕組みではありません。個人情報は必要以上に書かないでください',
		},
		help: [
			['プライベートを選べない', '作成権限が必要です。公開チャンネルを先に作って代用せず、サーバーの案内を確認してください'],
		],
	},
	{
		id: 'ref-feastChallenge',
		title: '宴（うたげ）チャレンジ',
		body: '「宴」「うたげ」「utage」を含む投稿をローカルへ出すと、15分間のチャレンジが始まります。誰からも反応されずに逃げ切ると成功、途中でリアクション・返信・リノートを受けると失敗です。',
		iconClass: 'ti ti-confetti',
		tips: ['初回に遊び方を表示します', '成功回数はプロフィールで確認できます'],
		link: null,
		course: 'post',
		where: '公開ノートの投稿フォーム。ローカルへ流れる投稿で参加する',
		related: ['composer'],
		source: 'packages/backend/src/core/UtageService.ts · components/MkPostForm.vue',
		lead: '「宴」「うたげ」「utage」を含む投稿をローカルへ出すと、15分間のチャレンジが始まります',
	},
	{
		id: 'ref-gamesOverview',
		title: 'Hataskey Gamesとは',
		body: 'Hataskeyのゲームをまとめたページです。各ゲームへの入口があり、対応するゲームでは記録をほかの利用者と比べられます。',
		iconClass: 'ti ti-device-gamepad-2',
		tips: ['ゲームごとに遊び方や対戦モードが異なります。各ゲームの開始画面で確認してください'],
		link: '/games',
		linkLabel: 'ゲーム一覧を開く',
		course: 'games',
		where: 'もっと！ → ゲーム',
		related: [],
		source: 'pages/games.vue',
		lead: 'Hataskeyのゲームをまとめたページです',
	},
	{
		id: 'ref-stackingGame',
		title: 'つみつみタワー',
		body: '絵文字を積み上げて高さを競うゲームです。一人で遊ぶほか、強さを選んでコンピューターとも対戦できます。',
		iconClass: 'ti ti-building',
		tips: ['一人・CPU対戦のほか、サーバー対戦ではロビーから人との対戦に進めます'],
		link: '/stacking-game',
		linkLabel: 'つみつみタワーで遊ぶ',
		course: 'games',
		where: 'ゲーム一覧 → つみつみタワー',
		related: [],
		source: 'pages/stacking-game.vue',
		lead: '絵文字を積み上げて高さを競うゲームです',
	},
	{
		id: 'ref-whackEmoji',
		title: '絵文字叩きゲーム',
		body: '次々に現れる絵文字を時間内に叩くゲームです。時間内の得点を競う遊び方、押しそびれるまで続く遊び方、コンピューターとの対戦があります。',
		iconClass: 'ti ti-hammer',
		tips: ['サーバー対戦では、ロビーから人との対戦に進めます'],
		link: '/whack-emoji',
		linkLabel: '絵文字叩きで遊ぶ',
		course: 'games',
		where: 'ゲーム一覧 → 絵文字叩きゲーム',
		related: [],
		source: 'pages/whack-emoji.vue',
		lead: '次々に現れる絵文字を時間内に叩くゲームです',
	},
	{
		id: 'ref-emojiShoot',
		title: 'カスタムエモジシュート',
		body: '迫ってくる絵文字を撃ち落とすゲームです。進むほど相手が増え、通常とは違う不利な条件が付く遊び方も選べます。',
		iconClass: 'ti ti-rocket',
		tips: [],
		link: '/emoji-shoot',
		linkLabel: 'エモジシュートで遊ぶ',
		course: 'games',
		where: 'ゲーム一覧 → カスタムエモジシュート',
		related: [],
		source: 'pages/emoji-shoot.vue',
		lead: '迫ってくる絵文字を撃ち落とすゲームです',
	},
	{
		id: 'ref-whatsNewGuide',
		title: '更新内容の案内',
		body: '更新後にHataskeyを開くと、主な新機能と変更点の案内が表示されます。閉じたときに、この端末でその版の案内を読んだことが記録されます。\n\n読み返すときは「もっと！」の「ヘルプ」から「直近の更新内容」を開きます。',
		iconClass: 'ti ti-news',
		tips: ['案内の各ボタンから、紹介している機能へ直接移動できます'],
		link: null,
		course: 'help',
		where: 'もっと！ → ヘルプ → 直近の更新内容',
		related: [],
		source: 'navbar.ts · boot/main-boot.ts · utility/hata-whats-new.ts',
		lead: '更新後にHataskeyを開くと、主な新機能と変更点の案内が表示されます',
	},
	{
		id: 'ref-loginDaysAchievements',
		title: 'ログイン日数・実績',
		body: 'Hataskeyへログインした日数や、次の節目までの日数をHataskのホームで確認できます。',
		iconClass: 'ti ti-calendar-stats',
		tips: [],
		link: '/hatask',
		linkLabel: 'Hataskを開く',
		course: 'hatask',
		where: 'Hatask → ホームのきろく',
		related: ['todo', 'calendar'],
		source: 'pages/hatask.vue',
		lead: 'Hataskeyへログインした日数や、次の節目までの日数をHataskのホームで確認できます',
	},
	{
		id: 'ref-hataskSearch',
		title: 'Hatask内検索',
		body: 'Hataskの検索ボタンから、予定、やること、きもち記録などをまとめて探せます。',
		iconClass: 'ti ti-search',
		tips: [],
		link: null,
		course: 'hatask',
		where: 'Hatask → PCは上部の検索欄／スマホは虫眼鏡',
		related: ['todo', 'calendar', 'mood'],
		source: 'pages/hatask.vue · components/hatask/HataskAkatsukiLayout.vue',
		steps: ['検索欄を開き、探したい記録の言葉を入力する', '検索結果で予定・ToDo・きもちを確認する。予定は結果から詳細を開ける', 'ToDoやきもちを編集したいときは、それぞれのタブを開く。検索結果は閉じるボタンで閉じられる'],
		lead: 'Hataskの検索ボタンから、予定、やること、きもち記録などをまとめて探せます',
	},
	{
		id: 'ref-hataskTutorial',
		title: 'Hataskの初回案内',
		body: 'Hataskを初めて開いたとき、画面の主な場所を順番に案内します。設定からいつでも再表示できます。',
		iconClass: 'ti ti-school',
		tips: [],
		link: '/hatask',
		linkLabel: 'Hataskを開く',
		course: 'hatask',
		where: 'Hatask → 歯車 → ヘルプ → 初回案内の再表示',
		related: ['todo', 'calendar', 'mood'],
		source: 'pages/HataskSettings.vue · pages/hatask.vue',
		lead: 'Hataskを初めて開いたとき、画面の主な場所を順番に案内します',
	},
	{
		id: 'ref-announcementsFilter',
		title: 'お知らせの絞り込み',
		body: 'お知らせは「現在・過去」を切り替えたり、情報・警告・完了・メンテナンスなどの種類で絞り込んだりして読めます。\n\n「現在」タブでは、メンテナンスのお知らせは種類の絞り込みにかかわらず表示します。過去のお知らせまで、常に同じ場所へ表示するという意味ではありません。',
		iconClass: 'ti ti-speakerphone',
		tips: [],
		link: '/announcements',
		linkLabel: 'お知らせを開く',
		course: 'help',
		where: 'お知らせ → 現在・過去／種類の絞り込み',
		related: [],
		source: 'pages/announcements.vue',
		lead: 'お知らせは「現在・過去」を切り替えたり、情報・警告・完了・メンテナンスなどの種類で絞り込んだりして読めます',
	},
	{
		id: 'ref-mascotOverview',
		title: 'マスコット機能とは',
		body: '好きなキャラクター画像を画面に表示し、表情やセリフを設定できます。複数のキャラクターを登録して切り替えられます。',
		iconClass: 'ti ti-mood-happy',
		tips: ['画像はドライブから選べます', '利用には管理者から付与された権限が必要な場合があります'],
		link: '/mascot',
		linkLabel: 'マスコットを開く',
		course: 'mascot',
		where: '設定 → Hataskey独自ツール → マスコット・ハタキュ。専用ページからは「設定」で開く',
		related: [],
		source: 'pages/MkMascotSettings.vue · pages/mascot.vue',
		lead: '好きなキャラクター画像を画面に表示し、表情やセリフを設定できます',
	},
	{
		id: 'ref-mascotDisplay',
		title: '画面上での表示',
		body: 'マスコットを好きな位置へ動かし、最小化、左右反転、透明さ、ぼかしを調整できます。位置は次回も引き継がれます。',
		iconClass: 'ti ti-drag-drop',
		tips: [],
		link: null,
		course: 'mascot',
		where: '表示中のマスコット／マスコット設定',
		related: [],
		source: 'components/MkMascotFloating.vue · pages/MkMascotSettings.vue',
		lead: 'マスコットを好きな位置へ動かし、最小化、左右反転、透明さ、ぼかしを調整できます',
	},
	{
		id: 'ref-expressionsLines',
		title: '表情とセリフ',
		body: '複数の表情と、それぞれに合うセリフを登録できます。表情には、跳ねる・揺れる・回るなどの動きも付けられます。吹き出しの位置、大きさ、向き、文字色も選べます。',
		iconClass: 'ti ti-mood-smile',
		tips: [],
		link: null,
		course: 'mascot',
		where: 'マスコット設定 → キャラクターを選ぶ → 表情・セリフ',
		related: [],
		source: 'pages/MkMascotSettings.vue',
		lead: '複数の表情と、それぞれに合うセリフを登録できます',
	},
	{
		id: 'ref-autoSwitch',
		title: '表情とセリフの自動切り替え',
		body: '表示中の表情やセリフを、5秒から30分までの間隔で自動的に切り替えられます。',
		iconClass: 'ti ti-refresh',
		tips: [],
		link: null,
		course: 'mascot',
		where: 'マスコット設定 → マスコットが伝えること → 表情・文言の入れ替わり間隔',
		related: [],
		source: 'pages/MkMascotSettings.vue',
		lead: '表示中の表情やセリフを、5秒から30分までの間隔で自動的に切り替えられます',
	},
	{
		id: 'ref-notificationBirthday',
		title: '通知・誕生日の演出',
		body: '通知が届いたときや誕生日に、専用の表情とセリフを表示できます。通知用の表情は2種類まで登録できます。',
		iconClass: 'ti ti-bell',
		tips: [],
		link: null,
		course: 'mascot',
		where: 'マスコット設定 → マスコットが伝えること。キャラクターごとの「通知用の表情」「誕生日用の表情」も設定する',
		related: [],
		source: 'pages/MkMascotSettings.vue',
		lead: '通知が届いたときや誕生日に、専用の表情とセリフを表示できます',
	},
	{
		id: 'ref-hataskMascot',
		title: 'Hataskホームのマスコット',
		body: 'マスコットを利用できるアカウントで画像を設定すると、暁・ハタキュのホームにカードとして表示されます。\n\nHataskを開いている間は、画面上に浮かぶマスコットの表示が隠れます。季・花信・刷のホームにはマスコットのカードは表示しません。',
		iconClass: 'ti ti-home',
		tips: [],
		link: '/hatask',
		linkLabel: 'Hataskを開く',
		course: 'mascot',
		where: '画像などの準備：Hataskey App → マスコット。カード表示：暁・ハタキュのホーム',
		related: [],
		source: 'pages/hatask.vue · components/MkMascotFloating.vue',
		lead: 'マスコットを利用できるアカウントで画像を設定すると、暁・ハタキュのホームにカードとして表示されます',
	},
	{
		id: 'ref-mascotTransfer',
		title: '設定の保存と読み込み',
		body: '選んだキャラクターと一部の表示設定を、.hmtkファイルへ書き出せます。読み込むと、新しいキャラクターとして追加されます。\n\n画像そのものは同梱せず、ドライブの画像への参照を保存します。同じサーバーで使ってください。すべてのキャラクター・設定を一度に保存する完全なバックアップではありません。',
		iconClass: 'ti ti-file-import',
		tips: [],
		link: '/mascot',
		linkLabel: 'マスコットを開く',
		course: 'mascot',
		where: 'マスコット設定 → キャラクター → このキャラを書き出し／ファイルから読み込み',
		related: [],
		source: 'pages/MkMascotSettings.vue',
		lead: '選んだキャラクターと一部の表示設定を、.hmtkファイルへ書き出せます',
	},
	{
		id: 'ref-hatafeedOverview',
		title: 'HataFeedとは',
		body: 'Hataskeyの不具合報告、要望、改善案、絵文字の申請をまとめて受け付ける場所です。投稿された話題は種類・状態・投稿者で絞り込み、返信やリアクションで話し合えます。特定の返信へ返事を付けたり、大切な返信や確認が必要な返信に印を付けたりもできます。<br><br>進行予定、お知らせ、絵文字申請も同じ画面から切り替えられます。自分の投稿への反応は通知で受け取れます。安全に関わる報告はスタッフだけが見られる場所で扱います。',
		iconClass: 'ti ti-message-report',
		tips: ['報告番号を選ぶと該当する内容へ直接移動できます', '絵文字申請は完成イメージを確認してから送信できます'],
		link: '/hatafeed',
		linkLabel: 'HataFeedを開く',
		course: 'apps',
		where: 'Hatask → Hataskey App → HataFeed',
		related: ['feed'],
		source: 'pages/hatafeed.vue',
		lead: 'Hataskeyの不具合報告、要望、改善案、絵文字の申請をまとめて受け付ける場所です',
	},
	{
		id: 'ref-bousai-0',
		title: '地震・津波情報を見る',
		body: '気象庁が発表した地震情報と津波情報を、地図と一覧で確認できます。震源、最大震度、市区町村ごとの震度、発表中の津波警報・注意報、お住まいの都道府県で観測された地震を表示します。<br><br>地震が起きる前の緊急地震速報は扱いません。発表済みの情報だけを表示します。',
		iconClass: 'ti ti-activity',
		tips: ['情報提供は気象庁とP2P地震情報です', 'ウィジェットやHataskey UIのデッキにも置けます'],
		link: '/earthquake',
		linkLabel: '地震・津波情報を開く',
		course: 'apps',
		where: 'Hataskey App → 地震・津波情報',
		related: [],
		source: 'pages/earthquake.vue',
		lead: '気象庁が発表した地震情報と津波情報を、地図と一覧で確認できます',
	},
	{
		id: 'ref-bousai-1',
		title: '地震・津波の通知',
		body: '選んだ震度以上の地震、またはお住まいの都道府県で揺れが観測された地震を端末へ通知できます。津波警報・注意報の発表と解除も通知します。<br><br>都道府県名は通常この端末だけに保存します。地域だけの通知を有効にしたときに限り、通知の判定に必要な都道府県名を旗鯖へ保存します。市区町村や現在地は送りません。',
		iconClass: 'ti ti-bell',
		tips: [],
		link: '/earthquake',
		linkLabel: '通知を設定する',
		course: 'apps',
		where: '地震・津波情報 → 通知設定',
		related: [],
		source: 'pages/earthquake.vue · components/MkEarthquakeSettings.vue',
		lead: '選んだ震度以上の地震、またはお住まいの都道府県で揺れが観測された地震を端末へ通知できます',
	},
	{
		id: 'ref-betaOverview',
		title: '開発中の機能を試す',
		body: 'HataFeedの「ベータ」から、開発中の機能を試せます。短いC・C++のプログラムを自分の端末内で動かす遊び場や、投稿を送信する前に待ち時間を設ける設定があります。\n\n正式機能になった項目には、現在の設定場所への案内が表示されます。実験中の項目は、案内と制約を読んでから使ってください。',
		iconClass: 'ti ti-flask',
		tips: ['正しく動かない場合はHataFeedでお知らせください'],
		link: '/hatafeed/beta',
		linkLabel: 'HataFeedを開く',
		course: 'help',
		where: 'HataFeed → ベータ → ベータ機能を試す',
		related: ['feed'],
		source: 'pages/hatafeed-beta.vue · utility/hatafeed.ts',
		lead: 'HataFeedの「ベータ」から、開発中の機能を試せます',
	},
];

export const referenceById: Record<string, IntroReference> = Object.fromEntries(references.map(reference => [reference.id, reference]));

export const referenceCourses: IntroCourse[] = [
	{
		id: 'external',
		label: '外部アカウント',
		title: '外部アカウント',
		desc: '連携の準備、読む場所、絵文字と通知',
		icon: 'link',
		tone: 'blue',
		features: [],
	},
	{
		id: 'mascot',
		label: 'マスコット',
		title: 'マスコット',
		desc: '表示する場所、表情・セリフ、設定の保存',
		icon: 'mood-happy',
		tone: 'pink',
		features: [],
	},
	{
		id: 'games',
		label: 'ゲーム',
		title: 'ゲーム',
		desc: '遊ぶ場所と、ゲームごとの違い',
		icon: 'device-gamepad-2',
		tone: 'green',
		features: [],
	},
	{
		id: 'help',
		label: 'お知らせ・お試し',
		title: 'お知らせ・お試し',
		desc: '更新内容を読み返す、開発中の機能を試す',
		icon: 'speakerphone',
		tone: 'blue',
		features: [],
	},
];

export const allCourses: IntroCourse[] = [...courses, ...referenceCourses];
