<!-- SPDX-FileCopyrightText: Tolehata and hatasaba-project
SPDX-License-Identifier: AGPL-3.0-only -->
<template>
<div :class="$style.garden" :data-motion="motion">
	<header :class="$style.masthead"><span :class="$style.brand">Hatask</span><span><i class="ti ti-plant-2"></i> お花</span><small>説明用のサンプル</small></header>
	<div :class="$style.intro"><img :src="'/client-assets/hatakyu/watering-flower.png'" alt=""/><div><small>毎日の小さなことが、お花の力に。</small><strong>しずくをためて、育てよう。</strong><p>ToDo・<span :class="$style.brand">Hatady</span>・ログインからしずくを集めて、自分のお花やみんなの花壇へ。</p></div></div>
	<div :class="$style.layout">
		<section :class="[$style.card, $style.care]">
			<h3>育てているお花 <i class="ti ti-help"></i></h3>
			<div :class="$style.growing"><div :class="$style.ring"><svg viewBox="0 0 160 160"><circle cx="80" cy="80" r="70"/><circle :class="$style.progress" cx="80" cy="80" r="70"/></svg><img :class="$style.flower" :src="'/twemoji/1f33b.svg'" alt=""/><i :class="$style.fallingDrop" class="ti ti-droplet-filled"></i></div><div :class="$style.flowerCopy"><strong>コスモス</strong><p>花言葉：調和</p><b>咲きました！</b><p>育成 100% · 秋のお花</p></div></div>
			<div :class="$style.harvest"><i class="ti ti-scissors"></i> 収穫して名前をつける</div>
			<div :class="$style.watering"><strong>じょうろ</strong><div :class="$style.controls"><span :class="$style.drop"><i class="ti ti-droplet-filled"></i></span><b>6</b><small>/20</small><span :class="$style.pour"><i class="ti ti-droplet"></i> 咲いています</span></div><div :class="$style.targets"><span>自分のお花</span><span>みんなの花壇</span></div></div>
			<p :class="$style.note"><i class="ti ti-heart"></i> 時間でも育ち、枯れません。<br/><i class="ti ti-droplet"></i> 1しずくで約2時間はやく咲きます。</p>
			<div :class="$style.todo"><strong><span :class="$style.brand">Hatask</span> ToDo</strong><div><span :class="$style.check"><i class="ti ti-check"></i></span><span>今日のひとつを終えた</span><span :class="$style.reward"><i class="ti ti-droplet-check"></i> +1</span></div></div>
		</section>
		<div :class="$style.collection">
			<section :class="[$style.card, $style.zukan]"><h3>おはな図鑑 <i class="ti ti-layout-grid"></i></h3><p :class="$style.caption">咲かせたお花が、思い出になる。</p><div :class="$style.seasons"><span>春</span><span>夏</span><span :class="$style.active">秋 3/12</span><span>冬</span></div><div :class="$style.slots"><div v-for="flower in flowers" :key="flower.name" :class="$style.slot"><img :src="flower.src" alt=""/><strong>{{ flower.name }}</strong><small>{{ flower.meaning }}</small></div></div><div :class="$style.seed"><i class="ti ti-gift"></i><span>8種類集めると、次の季節のたね</span><b>3/8</b></div></section>
			<section :class="[$style.card, $style.festival]"><h3>秋の花まつり <i class="ti ti-users"></i></h3><p :class="$style.caption">みんなのしずくで、花壇を満開に。</p><div :class="$style.festivalTotal"><b>360</b><span>/ 500しずく</span></div><div :class="$style.track"><span></span></div><div :class="$style.people"><span><b>は</b> はなさんが注ぎました</span><span><b>そ</b> そらさんが注ぎました</span></div><p :class="$style.festivalNote"><i class="ti ti-sparkles"></i> 満開になると、参加した人に月見草のたね。</p></section>
		</div>
	</div>
</div>
</template>
<script setup lang="ts">
defineProps<{ motion: boolean }>();
const flowers = [
	{ name: 'コスモス', meaning: '調和', src: '/twemoji/1f33b.svg' },
	{ name: 'モミジ', meaning: '美しい変化', src: '/twemoji/1f341.svg' },
	{ name: 'ススキ', meaning: '心が通じる', src: '/twemoji/1f33e.svg' },
];
</script>
<style module>
.garden { --pink:#e0567a; --ink:#b02e56; --bg:#fff3ec; --surface:rgba(255,255,255,.82); --fg:#2b1f2c; --muted:#6a5566; --fill:#2b1f2c10; --rule:rgba(80,50,70,.18); color-scheme:light; color:var(--fg); background:var(--bg); padding:22px; font-family:'LINE Seed JP',system-ui,sans-serif; font-size:13px; line-height:1.6; overflow-wrap:anywhere; }
.brand { font-family:Righteous,sans-serif; font-weight:400; font-synthesis:none; }
.masthead { display:flex; align-items:center; gap:14px; flex-wrap:wrap; }.masthead > .brand { font-size:26px; color:var(--ink); }.masthead > span:nth-child(2) { font-weight:700; }.masthead small { margin-left:auto; color:var(--muted); font-size:11px; }
.intro { display:flex; align-items:center; gap:18px; margin:10px 0 20px; }.intro > img { width:96px; height:96px; object-fit:contain; flex:none; }.intro > div { min-width:0; }.intro small { color:var(--ink); font-weight:700; }.intro strong { display:block; font-size:22px; line-height:1.5; }.intro p { margin:5px 0 0; color:var(--muted); }
.layout { display:grid; grid-template-columns:minmax(0,1fr) minmax(0,1fr); gap:18px; align-items:start; }.card { min-width:0; background:var(--surface); border:1px solid var(--rule); border-radius:24px; padding:18px; box-shadow:0 20px 40px -28px rgba(90,50,70,.55); }.card h3 { display:flex; align-items:center; justify-content:space-between; gap:8px; margin:0 0 12px; font-size:15px; }.card h3 i { color:var(--muted); font-size:19px; }.growing { display:grid; grid-template-columns:110px minmax(0,1fr); align-items:center; gap:16px; }.ring { width:110px; height:110px; position:relative; display:grid; place-items:center; }.ring svg { position:absolute; inset:0; fill:none; stroke:var(--rule); stroke-width:4; }.ring .progress { stroke:var(--pink); stroke-linecap:round; stroke-dasharray:440; transform:rotate(-90deg); transform-origin:center; }.flower { width:50px; height:50px; }.flowerCopy strong { font-size:22px; }.flowerCopy p { margin:3px 0; color:var(--muted); font-size:12px; }.flowerCopy b { display:block; margin-top:7px; font-size:14px; color:var(--ink); }.fallingDrop { position:absolute; left:48px; top:0; color:#4a8fd6; opacity:0; }.harvest { display:flex; align-items:center; justify-content:center; gap:8px; margin-top:15px; padding:10px 14px; background:var(--ink); color:white; border-radius:999px; font-weight:700; }
.watering { margin-top:18px; padding-top:15px; border-top:1px solid var(--rule); }.watering > strong { font-size:15px; }.controls { display:flex; align-items:center; gap:7px; margin:7px 0 10px; }.drop { display:grid; place-items:center; width:40px; height:40px; border-radius:50%; background:#4a8fd620; color:#4a8fd6; font-size:21px; }.controls > b { font-size:26px; line-height:1; }.controls > small { color:var(--muted); font-size:15px; }.pour { display:flex; gap:5px; align-items:center; justify-content:center; margin-left:auto; padding:9px 12px; border-radius:999px; background:var(--pink); color:white; opacity:.55; font-size:13px; font-weight:700; }.targets { display:flex; padding:4px; border-radius:999px; background:var(--fill); font-size:12px; font-weight:700; }.targets span { flex:1; padding:6px 2px; text-align:center; }.targets span:first-child { border-radius:999px; background:var(--bg); }.note { color:var(--muted); font-size:12px; margin:12px 0; }.note i { color:var(--ink); }.todo { padding:10px 12px; border:1px solid var(--rule); border-radius:16px; background:color-mix(in srgb,var(--bg) 50%,transparent); }.todo > strong { font-size:12px; }.todo > div { display:flex; align-items:center; gap:8px; padding-top:8px; margin-top:5px; border-top:1px solid var(--rule); font-size:12px; }.check { flex:none; color:var(--ink); }.reward { margin-left:auto; color:#4a8fd6; white-space:nowrap; }
.collection { display:grid; gap:18px; }.caption { margin:-6px 0 12px; color:var(--muted); font-size:12px; }.seasons { display:flex; gap:4px; margin-bottom:12px; padding:4px; border-radius:999px; background:var(--fill); }.seasons span { flex:1; padding:5px 2px; text-align:center; font-size:12px; font-weight:700; }.seasons .active { border-radius:999px; background:var(--pink); color:white; }.slots { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:7px; }.slot { display:grid; justify-items:center; align-content:start; text-align:center; gap:4px; border:1px solid var(--rule); border-radius:14px; padding:13px 4px; background:color-mix(in srgb,var(--bg) 50%,transparent); }.slot img { width:36px; height:36px; margin-bottom:5px; }.slot strong { font-size:12px; }.slot small { color:var(--muted); font-size:11px; }.seed { display:flex; align-items:center; gap:7px; padding-top:13px; color:var(--ink); font-size:11px; }.seed i { font-size:18px; }.seed b { margin-left:auto; white-space:nowrap; }.festivalTotal { display:flex; gap:7px; align-items:baseline; }.festivalTotal b { font-size:28px; }.festivalTotal span { font-size:12px; color:var(--muted); }.track { height:10px; overflow:hidden; border-radius:999px; background:var(--fill); margin:7px 0 12px; }.track span { display:block; width:72%; height:100%; border-radius:inherit; background:linear-gradient(90deg,#f2a04b,var(--pink)); }.people { display:flex; flex-wrap:wrap; gap:6px; }.people > span { display:flex; gap:5px; align-items:center; padding:4px 8px 4px 4px; background:var(--bg); border-radius:999px; font-size:12px; }.people b { width:22px; height:22px; display:grid; place-items:center; border-radius:50%; background:var(--pink); color:white; }.people > span:nth-child(2) b { background:#6b8fd6; }.festivalNote { margin:12px 0 0; font-size:12px; color:var(--muted); }.festivalNote i { color:var(--ink); }
.garden[data-motion='true'] .fallingDrop { animation:dropIn 850ms 200ms both ease-in; }.garden[data-motion='true'] .flower { animation:bloomIn 700ms 800ms both ease-out; }.garden[data-motion='true'] .collection > .card { animation:cardIn 600ms 1200ms both ease-out; }.garden[data-motion='true'] .collection > .card:nth-child(2) { animation-delay:1550ms; }
@keyframes dropIn { 0% { opacity:0; transform:translateY(-12px); } 25% { opacity:1; } 90% { opacity:1; } 100% { opacity:0; transform:translateY(40px) scale(.6); } } @keyframes bloomIn { from { opacity:.5; transform:scale(.7); } to { opacity:1; transform:scale(1); } } @keyframes cardIn { from { opacity:.5; transform:translateY(8px); } to { opacity:1; transform:none; } }
:global([data-mode='dark']) .garden { --pink:#ff7fa3; --ink:#ff7fa3; --bg:#150f1b; --surface:#302539; --fg:#f6ecf3; --muted:#c8b5c6; --fill:#f6ecf310; --rule:rgba(255,255,255,.18); color-scheme:dark; }
:global([data-mode='dark']) .harvest,:global([data-mode='dark']) .pour,:global([data-mode='dark']) .seasons .active { color:#26101c; }
@container release (max-width:620px) { .garden { padding:16px; }.intro { gap:10px; margin-bottom:16px; }.intro > img { width:70px; height:70px; }.intro strong { font-size:18px; }.intro small,.intro p { font-size:12px; }.layout { grid-template-columns:minmax(0,1fr); gap:14px; }.collection { gap:14px; }.card { padding:16px; }.masthead { gap:10px; }.masthead > .brand { font-size:23px; }.masthead small { flex-basis:100%; margin:0; }.growing { gap:12px; grid-template-columns:90px minmax(0,1fr); }.ring { width:90px; height:90px; }.flowerCopy strong { font-size:20px; }.intro { align-items:flex-start; }.pour { font-size:12px; padding-inline:9px; }.slot img { width:40px; height:40px; } }
@container release (max-width:380px) {
 .garden { padding:12px; }.card { padding:12px; }.intro { flex-direction:column; gap:8px; }.intro > img { width:72px; height:72px; align-self:center; }.intro > div { width:100%; }.intro strong { font-size:18px; }
 .growing { grid-template-columns:64px minmax(0,1fr); gap:8px; }.ring { width:64px; height:64px; }.flower { width:36px; height:36px; }.flowerCopy strong { font-size:18px; }.flowerCopy p { font-size:11px; }.fallingDrop { left:25px; }
 .controls { flex-wrap:wrap; justify-content:flex-start; }.controls > b,.controls > small { white-space:nowrap; flex:none; }.pour { flex-basis:100%; margin:3px 0 0; white-space:nowrap; }.targets { flex-direction:column; border-radius:14px; }.targets span:first-child { border-radius:10px; }
 .seasons { gap:0; }.seasons span { font-size:11px; white-space:nowrap; }.slots { grid-template-columns:minmax(0,1fr); }.slot { grid-template-columns:36px minmax(0,1fr); grid-template-rows:auto auto; column-gap:10px; row-gap:1px; justify-items:start; text-align:start; padding:9px 10px; }.slot img { width:36px; height:36px; grid-row:1 / 3; margin:0; align-self:center; }.slot strong { font-size:13px; }.slot small { font-size:12px; }.seed { flex-wrap:wrap; }.seed span { flex:1; min-width:0; }.harvest { padding-inline:9px; font-size:12px; }.todo > div { flex-wrap:wrap; }.people > span { font-size:11px; }
}
@media(prefers-reduced-motion:reduce) { .garden * { animation:none !important; } }
</style>
