<!-- SPDX-License-Identifier: AGPL-3.0-only -->
<template>
<div :class="$style.screen">
	<aside :class="$style.rail">
		<div :class="$style.instance">H</div>
		<div :class="$style.railItems">
			<span :class="$style.railActive"><House/></span><span><Search/></span><span><Bell/></span><span><MessageCircle/></span><span><Megaphone/></span><span><FolderOpen/></span><span><Star/></span>
		</div>
		<div :class="$style.railFoot"><span><PanelsTopLeft/></span><span><Moon/></span><span><Settings/></span><span><RectangleVertical/></span><span :class="$style.account">h</span></div>
	</aside>
		<main :class="$style.timeline">
			<div :class="$style.tabs"><span :class="$style.tabSpacer"></span><span :class="$style.tab"><i class="ti ti-home"></i></span><span :class="[$style.tab,$style.tabActive]"><i class="ti ti-planet"></i>ローカル</span><span :class="$style.tab"><i class="ti ti-universe"></i></span><span :class="$style.tab"><i class="ti ti-flame"></i></span><span :class="$style.tabEnd"><i><Ellipsis/></i></span></div>
			<div :class="$style.notes">
				<article :class="$style.note"><div :class="[$style.avatar,$style.avatarFlower]">小</div><div :class="$style.noteBody"><header><b>小花</b><small>@koharu</small><small>2分前</small></header><p>窓辺に小さな花が咲きました 🌼<br>朝の光がとてもきれいです。</p><div :class="$style.mobileActions"><Reply/><Repeat2/><Quote/><SmilePlus/><Ellipsis/></div></div><div :class="$style.reactions"><span :class="$style.reactionChip"><span>🌼</span><small>12</small></span><span :class="$style.reactionChip"><span>✨</span><small>4</small></span><span :class="[$style.reactionChip,$style.reactionAdd]"><SmilePlus/></span></div></article>
				<article :class="$style.note"><div :class="[$style.avatar,$style.avatarWalk]">歩</div><div :class="$style.noteBody"><header><b>日々の散歩</b><small>@hibi</small><small>15分前</small></header><p>今日は川沿いを、ゆっくり散歩。<br>風が涼しくなってきましたね。</p><div :class="$style.mobileActions"><Reply/><Repeat2/><Quote/><SmilePlus/><Ellipsis/></div></div><div :class="$style.reactions"><span :class="$style.reactionChip"><span>🍃</span><small>8</small></span><span :class="[$style.reactionChip,$style.reactionAdd]"><SmilePlus/></span></div></article>
			</div>
			<div :class="$style.composer"><div :class="$style.composeBox"><div :class="$style.placeholder">いま、なにしてる？</div><div :class="$style.composeRow"><span><LayoutGrid/></span><span><Paperclip/></span><span><EyeOff/></span><i :class="$style.shortcut"><Plus/></i><i :class="$style.shortcut"><Plus/></i><span><Smile/></span><div :class="$style.composeSpace"></div><span :class="$style.visibility"><Globe2/><b>パブリック</b></span><span :class="$style.visibility"><Rocket/><b>連合</b></span><span :class="$style.count">3000</span><span :class="$style.send"><Send/></span></div></div></div>
		</main>
		<aside :class="$style.right">
			<div :class="$style.rightTabs"><span><LayoutGrid/>ウィジェット</span><span :class="$style.rightTabActive"><CalendarCheck/><b>Hatask</b></span></div>
			<div :class="$style.rightScroll"><div :class="$style.day"><b>9.25</b><span>金</span><em>Hatask <ChevronRight/></em></div>
				<div :class="$style.stats"><span><small><ListChecks/>ToDo</small><b>1<em>/3</em></b></span><span><small><Calendar/>予定</small><b>1</b></span><span><small><Soup/>食事</small><b>2<em>/3</em></b></span></div>
				<section :class="$style.section"><strong><Calendar/>きょうの予定 <small>1</small></strong><div :class="$style.event"><time>14:00</time><span><b>散歩</b><small>まもなく始まります</small></span></div></section>
				<section :class="$style.section"><strong><ListChecks/>ToDo <small>1/3</small></strong><div :class="$style.progress"><i></i></div><div :class="$style.todo">□ 買い物 <small>16:00</small></div></section>
				<section :class="$style.section"><strong><Soup/>食事の記録 <small>2/3</small></strong><div :class="$style.meals"><span><small>朝</small>パン</span><span><small>昼</small>スープ</span><span><small>夜</small>未記録</span></div></section>
				<section :class="$style.section"><strong><Smile/>きょうの気分 <small>おだやか</small></strong><div :class="$style.moods">😢 🙁 😐 <span>🙂</span> 🥰</div></section>
				<section :class="$style.section"><strong><Flower2/>育てているお花 <small>60%</small></strong><div :class="$style.flower">🌱 小さな花 <span>▰▰▱▱</span></div></section>
			</div>
		</aside>
		<div :class="$style.bottomNav"><span><Menu/></span><span><Search/></span><span :class="$style.bottomActive"><House/><b>ホーム</b></span><span><Bell/></span></div>
</div>
</template>
<script setup lang="ts">
import { Bell, Calendar, CalendarCheck, ChevronRight, Ellipsis, EyeOff, Flower2, FolderOpen, Globe2, House, LayoutGrid, ListChecks, Megaphone, Menu, MessageCircle, Moon, PanelsTopLeft, Paperclip, Plus, Quote, RectangleVertical, Repeat2, Reply, Rocket, Search, Send, Settings, Smile, SmilePlus, Soup, Star } from '@lucide/vue';
</script>
<style module>
.screen { --bg:#f7f4f1; --surface:#eeeae6; --text:#221d19; --line:color-mix(in srgb,var(--text) 36%,transparent); --accent:#e56b0a; --accentSoft:#fff3e8; --muted:#635e59; display:grid; grid-template-columns:43px minmax(0,1fr) 212px; width:100%; height:100%; overflow:hidden; background:var(--bg); color:var(--text); font-family:'LINE Seed JP',system-ui,sans-serif; font-size:10px; line-height:1.4; }
:global([data-mode='dark']) .screen { --bg:#1c1a18; --surface:#242220; --text:#e6e1db; --line:color-mix(in srgb,var(--text) 26%,transparent); --accent:#d98f56; --accentSoft:#2c2520; --muted:#a49e98; }
.screen * { box-sizing:border-box; }.screen svg { width:13px; height:13px; stroke-width:2; flex:none; }
.rail { min-height:0; display:flex; flex-direction:column; align-items:center; border-right:2px solid var(--line); background:var(--bg); }
.instance { display:grid; place-items:center; width:27px; height:27px; margin:8px 0 12px; border:1px solid var(--line); background:var(--surface); color:var(--accent); font:400 20px/1 Righteous,sans-serif; }
.railItems,.railFoot { display:grid; justify-items:center; width:100%; gap:2px; }.railItems span,.railFoot span { display:grid; place-items:center; width:30px; height:26px; color:var(--muted); }.railItems svg,.railFoot svg { width:15px; height:15px; }.railItems .railActive { background:var(--accentSoft); color:var(--accent); box-shadow:inset 2px 0 var(--accent); }.railFoot { margin-top:auto; border-top:1px solid var(--line); }.railFoot .account { width:22px; height:22px; margin:2px 0 4px; border-radius:50%; background:var(--surface); color:var(--accent); font-weight:800; }
.timeline { display:flex; flex-direction:column; min-width:0; min-height:0; }.tabs { display:flex; height:39px; flex:none; border-bottom:2px solid var(--line); }.tabSpacer { flex:1; border-right:1px solid var(--line); }.tab,.tabEnd { display:flex; align-items:center; justify-content:center; gap:4px; min-width:37px; padding:0 8px; border-right:1px solid var(--line); font-weight:800; white-space:nowrap; }.tab :global(.ti) { font-size:15px; }.tabActive { background:var(--accentSoft); color:var(--accent); box-shadow:inset 0 -2px var(--accent); }.tabEnd { flex:1 1 0; min-width:0; justify-content:flex-end; padding:0; border-right:0; }.tabEnd i { display:grid; place-items:center; width:38px; height:100%; border-left:1px solid var(--line); font-style:normal; }.tabEnd svg { width:16px; }
.notes { flex:1; min-height:0; overflow:hidden; }.note { display:grid; grid-template-columns:28px minmax(0,1fr) 84px; gap:8px; min-height:100px; padding:13px 12px 10px; border-bottom:1px solid var(--line); }.avatar { display:grid; place-items:center; width:26px; height:26px; border-radius:50%; font-weight:800; }.avatarFlower { background:#ead5b3; color:#765335; }.avatarWalk { background:#ccdfd1; color:#365b4b; }.noteBody { min-width:0; }.noteBody header { display:flex; align-items:baseline; gap:5px; white-space:nowrap; }.noteBody header b { font-size:11px; }.noteBody header small { color:var(--muted); font-size:9px; }.noteBody header small:last-child { margin-left:auto; }.noteBody p { margin:7px 0 0; font-size:11px; line-height:1.6; }.reactions { display:grid; grid-template-columns:repeat(2,34px); grid-auto-rows:33px; align-content:start; gap:3px; padding-left:7px; border-left:1px solid var(--line); }.reactionChip { display:flex; flex-direction:column; align-items:center; justify-content:center; border:1px solid var(--line); background:var(--surface); line-height:1.05; }.reactionChip > span { font-size:13px; }.reactionChip small { font-size:8px; color:var(--muted); }.reactionAdd { border-style:dashed; color:var(--muted); }.reactionAdd svg { width:14px; height:14px; }.mobileActions { display:none; }
.composer { flex:none; padding:8px 9px; border-top:2px solid var(--line); background:var(--surface); }.composeBox { border:1px solid var(--line); background:var(--bg); }.placeholder { height:34px; padding:9px 10px; color:var(--muted); font-size:11px; }.composeRow { display:flex; align-items:center; gap:3px; min-width:0; padding:3px 5px 5px; }.composeRow > span,.shortcut { display:grid; place-items:center; flex:none; min-width:20px; height:21px; }.shortcut { border:1px dashed var(--line); color:var(--accent); }.shortcut svg { width:11px; }.composeSpace { flex:1; min-width:0; }.visibility { display:flex!important; gap:2px; white-space:nowrap; font-size:8px; font-weight:700; }.visibility svg { width:11px; height:11px; }.count { color:var(--muted); font-size:8px; }.send { width:22px; background:var(--accent); color:var(--bg); }.send svg { width:12px; }
.right { display:flex; flex-direction:column; min-height:0; border-left:2px solid var(--line); }.rightTabs { display:grid; grid-template-columns:1fr 1fr; height:39px; flex:none; border-bottom:2px solid var(--line); }.rightTabs span { display:flex; align-items:center; justify-content:center; gap:3px; color:var(--muted); font-size:9px; font-weight:800; }.rightTabs span + span { border-left:1px solid var(--line); }.rightTabs .rightTabActive { background:var(--accentSoft); color:var(--accent); box-shadow:inset 0 -2px var(--accent); }.rightTabActive b { font:400 11px Righteous,sans-serif; }.rightScroll { overflow:hidden; }.day { display:flex; align-items:center; gap:4px; height:42px; padding:0 10px; border-bottom:2px solid var(--line); }.day > b { font-size:18px; }.day em { display:flex; align-items:center; margin-left:auto; color:var(--accent); font:400 10px Righteous,sans-serif; }.day em svg { width:11px; }.stats { display:grid; grid-template-columns:repeat(3,1fr); border-bottom:2px solid var(--line); }.stats > span { min-width:0; padding:6px 5px; }.stats > span + span { border-left:1px solid var(--line); }.stats small { display:flex; align-items:center; gap:2px; color:var(--muted); font-size:8px; font-weight:800; }.stats small svg { width:10px; height:10px; color:var(--accent); }.stats b { font-size:15px; }.stats em { font-size:8px; font-style:normal; color:var(--muted); }.section { border-bottom:2px solid var(--line); padding:5px 9px 6px; }.section > strong { display:flex; align-items:center; gap:5px; font-size:9px; }.section > strong svg { width:12px; height:12px; color:var(--accent); }.section > strong small { margin-left:auto; font-size:8px; }.event { display:flex; gap:7px; margin-top:5px; font-size:9px; }.event time { color:var(--accent); font-weight:800; }.event span { display:grid; }.event small,.todo small { color:var(--muted); font-size:8px; }.progress { height:3px; margin:5px 0; background:var(--surface); }.progress i { display:block; width:33%; height:100%; background:var(--accent); }.todo { display:flex; justify-content:space-between; font-size:9px; }.meals { display:grid; grid-template-columns:repeat(3,1fr); margin-top:5px; }.meals span { display:grid; gap:1px; padding-left:4px; border-left:1px solid var(--line); font-size:8px; white-space:nowrap; }.meals small { color:var(--muted); font-size:8px; }.moods { margin-top:5px; font-size:14px; letter-spacing:4px; white-space:nowrap; }.moods span { background:var(--accentSoft); outline:1px solid var(--accent); }.flower { margin-top:5px; font-size:9px; }.flower span { color:var(--accent); }.bottomNav { display:none; }
@container release (max-width:620px) { .screen { grid-template-columns:minmax(0,1fr); grid-template-rows:minmax(0,1fr) 39px; font-size:12px; }.rail,.right { display:none; }.timeline { grid-row:1; }.tabs { height:41px; }.tabSpacer { display:none; }.tab { flex:1; min-width:0; padding:0 5px; }.tabEnd { flex:none; width:38px; }.note { grid-template-columns:29px minmax(0,1fr); min-height:106px; padding:10px 11px 7px; }.noteBody header b { font-size:12px; }.noteBody header small { font-size:10px; }.noteBody p { margin:5px 0; font-size:12px; }.reactions { display:none; }.mobileActions { display:flex; justify-content:space-around; padding-top:3px; color:var(--muted); }.mobileActions svg { width:13px; height:13px; }.composer { margin-top:auto; }.placeholder { height:36px; font-size:12px; }.composeRow { justify-content:space-between; }.composeRow > span { min-width:22px; }.composeRow .shortcut { display:none; }.visibility b { display:none; }.visibility svg { width:13px; height:13px; }.count { font-size:9px; }.bottomNav { display:grid; grid-template-columns:repeat(4,1fr); border-top:2px solid var(--line); }.bottomNav span { display:flex; align-items:center; justify-content:center; gap:5px; border-right:1px solid var(--line); }.bottomNav .bottomActive { flex-direction:column; gap:0; background:var(--accentSoft); color:var(--accent); box-shadow:inset 0 -2px var(--accent); font-size:10px; }.bottomNav svg { width:17px; height:17px; } }
</style>
