<!-- SPDX-FileCopyrightText: Tolehata and hatasaba-project
SPDX-License-Identifier: AGPL-3.0-only -->
<template><span class="notice-icon" :class="kind" :data-motion="animations ? 'on' : 'off'" aria-hidden="true"><i :class="icon"></i><span v-if="kind === 'drop'" class="splash"></span><span v-for="(particle, index) in particles" :key="index" class="particle" :style="{ '--dx': `${particle.dx}px`, '--dy': `${particle.dy}px` }"></span></span></template>
<script setup lang="ts">
import { computed } from 'vue';
const props = withDefaults(defineProps<{ icon: string; animations?: boolean }>(), { animations: true });
const kind = computed(() => /droplet-filled/.test(props.icon) ? 'drop' : /gift|confetti|sparkles/.test(props.icon) ? 'gift' : /off|pause|hourglass/.test(props.icon) ? 'negative' : /clock-forward/.test(props.icon) ? 'clock' : 'ordinary');
const particles = computed(() => kind.value === 'drop' || kind.value === 'gift' ? Array.from({ length: 6 }, (_, index) => { const angle = index / 6 * Math.PI * 2 - Math.PI / 2; return { dx: Math.cos(angle) * 13, dy: Math.sin(angle) * 13 }; }) : []);
</script>
<style scoped>
.notice-icon{position:relative;display:inline-grid;place-items:center;flex:none;width:20px;height:20px;font-size:18px;line-height:1}.notice-icon>i{display:block;transform-origin:50% 50%;color:var(--accent-ink,var(--MI_THEME-accent));animation:notice-pop .5s cubic-bezier(.34,1.56,.64,1) both}.drop>i{color:#4a8fd6;transform-origin:50% 100%;animation:notice-drop .6s cubic-bezier(.3,1.4,.5,1) both}.gift>i{animation:notice-wobble .7s cubic-bezier(.3,1.3,.5,1) both}.negative>i{color:var(--fg-2,var(--MI_THEME-fgMuted));animation:notice-shake .45s .1s ease both}.clock>i{animation:notice-spin .5s cubic-bezier(.2,0,0,1) both}.splash{position:absolute;left:50%;bottom:-2px;width:16px;height:3px;border-radius:50%;background:#4a8fd6;opacity:0;animation:notice-splash .45s .22s ease-out both}.particle{position:absolute;left:50%;top:50%;width:3.5px;height:3.5px;border-radius:50%;background:var(--accent,var(--MI_THEME-accent));opacity:0;animation:notice-spark .5s .12s cubic-bezier(.2,.7,.3,1) both}.drop .particle{background:#4a8fd6;animation-delay:.24s}.particle:nth-of-type(odd){background:var(--accent-ink,var(--MI_THEME-accent))}.drop .particle:nth-of-type(odd){background:#8dbbea}@keyframes notice-pop{from{transform:scale(.5);opacity:0}to{transform:scale(1);opacity:1}}@keyframes notice-drop{0%{transform:translateY(-15px) scale(.65,1.3);opacity:0}52%{transform:translateY(0) scale(1.25,.65);opacity:1}76%{transform:translateY(-4px) scale(.9,1.12)}100%{transform:none;opacity:1}}@keyframes notice-wobble{0%{transform:rotate(-20deg) scale(.45);opacity:0}50%{transform:rotate(14deg) scale(1.18);opacity:1}75%{transform:rotate(-7deg)}100%{transform:none;opacity:1}}@keyframes notice-shake{0%,100%{transform:none}25%{transform:translateX(-3px)}50%{transform:translateX(3px)}75%{transform:translateX(-2px)}}@keyframes notice-spin{from{transform:rotate(-180deg) scale(.65);opacity:0}to{transform:none;opacity:1}}@keyframes notice-splash{0%{transform:translateX(-50%) scaleX(.3);opacity:0}35%{opacity:.7}100%{transform:translateX(-50%) scaleX(1.7);opacity:0}}@keyframes notice-spark{0%{transform:translate(-50%,-50%) scale(.4);opacity:0}25%{opacity:1}100%{transform:translate(calc(-50% + var(--dx)),calc(-50% + var(--dy))) scale(.5);opacity:0}}[data-motion=off] i,[data-motion=off] .splash,[data-motion=off] .particle{animation:none!important}[data-motion=off] .splash,[data-motion=off] .particle{display:none}@media(prefers-reduced-motion:reduce){i,.splash,.particle{animation:none!important}.splash,.particle{display:none}}
</style>
