/* SPDX-License-Identifier: AGPL-3.0-only */
import { versatileLang } from '@/utility/intl-const.js';

const ja = {
	rename: '作品名を変更', artworkName: '作品名', untitled: '無題のキャンバス', returnTool: '直前のツールに戻る', panels: '制作パネル', export: '書き出す', canvas: 'キャンバス', changeTool: 'ツールを変更', draw: '描く', shapes: '図形', edit: '編集', view: '表示',
	preview: '全体プレビュー', moveView: '表示範囲。ドラッグまたは矢印キーで視点を移動', zoomOut: '縮小', zoomIn: '拡大', fit: '全体を表示', smoothing: '手ぶれ補正', pressure: '筆圧で太さを変える', penOnly: 'ペンだけで描く', pressureWaiting: 'ペンの入力を待っています', pressureUnavailable: '筆圧値なし（一定の太さ）',
	lockColor: '色の平面と色相をロック', saturation: '彩度と明るさ。左右で彩度、上下で明るさを調整', hue: '色相', colorLocked: '直接操作をロック中。色コードとパレットは使えます。', colorDrag: '丸を動かして色を調整。矢印キーでも動かせます。', colorCode: '色コード', invalidColor: '#に続けて6桁の色コードを入力してください。', eyedropper: 'スポイト', transform: '変形',
	addLayer: 'レイヤーを追加', hideLayer: 'レイヤーを隠す', showLayer: 'レイヤーを表示', layerName: 'レイヤー名', blend: '合成モード', copyLayer: 'レイヤーを複製', white: '白', black: '黒', transparent: '透明', restoreDraft: '端末の下書きを復元', more: 'その他', value: '数値で指定', resizeImage: '画像の大きさを変更',
	saveDevice: '端末に保存', saveDrive: 'ドライブに保存', attachNote: '投稿に添付', fromDevice: '端末の画像', fromDrive: 'ドライブの画像', terms: '利用規約に違反するイラスト（イラストに追加した画像などを含む）を、投稿したりサーバーのドライブに保存したりすることはできません。', readTerms: 'サーバーの利用規約を確認', agree: '上記を確認し、利用規約を守って投稿・ドライブ保存することに同意します。', once: '同意確認は1アカウントにつき初回の1回だけです。ドライブ保存・投稿添付で共用し、同意日時をコンパネの同意管理に記録します。', working: '処理中…', agreeContinue: '同意して進む', consentTitle: '保存・投稿の前に', consentFailed: '同意を確認・記録できませんでした。少し待ってもう一度お試しください。', loginRequired: 'ドライブ保存・投稿にはログインが必要です。', accountChanged: 'アカウントが切り替わりました。元のアカウントで開き直してください。',
	help: 'PC・タブレットでは左右の制作パネル、スマホでは下部のボタンから設定します。2本指で拡大・移動できます。閉じる際に保存を選ぶと、このブラウザ内にアカウント別の下書きを保存します。キャンバス設定から復元できます。', draftTitle: '下書きを保存しますか？', draftLocalOnly: '下書きはこの端末のブラウザ内に保存します。ドライブやサーバーには送信しません。', replaceDraft: '保存すると、このアカウントで以前保存した下書きを置き換えます。保存せず閉じる場合は、以前の下書きが残ります。', saveDraftAndClose: '端末に下書きを保存して閉じる', closeWithoutSaving: '保存せず閉じる', continueEditing: '編集に戻る', noDraft: 'このアカウントの下書きはありません。', restoreWarning: '端末に保存した下書きを開きます。現在の作品は「元に戻す」で戻せます。', draftFailed: '端末に下書きを保存できませんでした。編集に戻ってPNGを書き出すこともできます。', restoreFailed: '下書きを読み込めませんでした。現在の作品は保持しています。', draftSaved: '端末に下書き保存済み', unsaved: '未保存', savedDrive: 'ドライブに保存しました。', downloaded: 'PNGのダウンロードを開始しました。', hiddenLayer: '表示中のレイヤーを選んでください。', finishEdit: '選択範囲や画像の配置を確定・キャンセルしてから操作してください。', layerLimit: 'レイヤーは32枚までです。', tooLarge: '画像は20MB以下のPNG・JPEG・WebPを選んでください。', pen: 'ペン', pencil: '鉛筆', marker: 'マーカー', airbrush: 'エアブラシ',
};
const en: typeof ja = {
	rename: 'Rename artwork', artworkName: 'Artwork name', untitled: 'Untitled canvas', returnTool: 'Return to previous tool', panels: 'Studio panels', export: 'Export', canvas: 'Canvas', changeTool: 'Change tool', draw: 'Draw', shapes: 'Shapes', edit: 'Edit', view: 'View',
	preview: 'Canvas preview', moveView: 'Viewport. Drag or use arrow keys to pan', zoomOut: 'Zoom out', zoomIn: 'Zoom in', fit: 'Fit canvas', smoothing: 'Stabilization', pressure: 'Use pen pressure for width', penOnly: 'Draw with pen only', pressureWaiting: 'Waiting for pen input', pressureUnavailable: 'No pressure value (constant width)',
	lockColor: 'Lock color plane and hue', saturation: 'Saturation and brightness. Adjust with arrow keys', hue: 'Hue', colorLocked: 'Direct adjustment locked. HEX and palette remain available.', colorDrag: 'Drag the circle or use arrow keys to adjust color.', colorCode: 'HEX color', invalidColor: 'Enter # followed by six hexadecimal digits.', eyedropper: 'Eyedropper', transform: 'Transform',
	addLayer: 'Add layer', hideLayer: 'Hide layer', showLayer: 'Show layer', layerName: 'Layer name', blend: 'Blend mode', copyLayer: 'Duplicate layer', white: 'White', black: 'Black', transparent: 'Transparent', restoreDraft: 'Restore local draft', more: 'More', value: 'Numeric value', resizeImage: 'Resize image',
	saveDevice: 'Save to device', saveDrive: 'Save to Drive', attachNote: 'Attach to post', fromDevice: 'Image from device', fromDrive: 'Image from Drive', terms: 'Illustrations that violate the server terms of service, including images added to the artwork, must not be posted or saved to the server Drive.', readTerms: 'Read server terms of service', agree: 'I have read this notice and agree to follow the terms when posting or saving to Drive.', once: 'Consent is requested once per account and shared by Drive saves and post attachments. Its date is recorded in the control panel consent manager.', working: 'Working…', agreeContinue: 'Agree and continue', consentTitle: 'Before saving or posting', consentFailed: 'Could not verify or record consent. Please try again shortly.', loginRequired: 'Sign in to save to Drive or attach to a post.', accountChanged: 'The account has changed. Reopen with the original account.',
	help: 'Use the side panels on desktop and tablet, or the bottom dock on a phone. Pinch with two fingers to zoom and pan. Choose to save when closing to keep a draft in this browser for your account. Restore it from canvas settings.', draftTitle: 'Save a draft?', draftLocalOnly: 'The draft is stored in this browser on this device. It is never sent to Drive or a server.', replaceDraft: 'Saving replaces this account’s previous draft. Closing without saving keeps the previous draft.', saveDraftAndClose: 'Save draft on device and close', closeWithoutSaving: 'Close without saving', continueEditing: 'Keep editing', noDraft: 'No draft is saved for this account.', restoreWarning: 'Open the local draft? Undo restores your current artwork.', draftFailed: 'Could not save the draft on this device. You can return to editing and export a PNG.', restoreFailed: 'Could not restore the draft. Your current artwork is unchanged.', draftSaved: 'Draft saved on this device', unsaved: 'Unsaved', savedDrive: 'Saved to Drive.', downloaded: 'PNG download started.', hiddenLayer: 'Choose a visible layer.', finishEdit: 'Apply or cancel the selection or image placement first.', layerLimit: 'Up to 32 layers are supported.', tooLarge: 'Choose a PNG, JPEG, or WebP image under 20 MB.', pen: 'Pen', pencil: 'Pencil', marker: 'Marker', airbrush: 'Airbrush',
};
export const hatadintCopy = versatileLang.startsWith('ja') ? ja : en;
